export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'pick_up_view',
  deviewId: '00369e1afa941008086fb56392b401cc',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ACTIVITIY',
  },
  caption: '活动',
  codeName: 'activity_pick_up_view',
  appDataEntityId: 'plmweb.activity',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'plmweb.activity_pick_up_grid_view',
      codeName: 'pick_up_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'plmweb.activity',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pick_up_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ACTIVITIY',
      },
      caption: '活动',
      codeName: 'pick_up_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.activity',
      controlParam: {},
      name: 'captionbar',
      id: 'pick_up_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.activity',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '活动数据选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.ACTIVITIY.PICKUPVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ae41f4656d652850c90fa71675fd5108',
  modelType: 'PSAPPDEVIEW',
  name: 'activitypick_up_view',
  id: 'plmweb.activity_pick_up_view',
};
