export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'baseline_mpick_up_grid_view',
  deviewId: 'EA4217C4-5792-4D2F-962B-53E7A9911ED5',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '页面',
  codeName: 'article_page_baseline_mpick_up_grid_view',
  appDataEntityId: 'plmweb.article_page',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'baseline',
      value: 'baseline',
      id: 'baseline',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IDEA.IDENTIFIER',
          },
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '页面名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '页面名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'choose_version_name',
          excelCaption: '版本',
          appDEFieldId: 'choose_version_name',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '版本',
          codeName: 'choose_version_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          sysPFPluginId: 'jscode_grid_column',
          width: 100,
          widthUnit: 'PX',
          id: 'choose_version_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type',
          excelCaption: '类型',
          appCodeListId: 'plmweb.wiki__page_type',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'choose_version_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'choose_version_name',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'choose_version_id',
          scriptCode: 'data.cur_version_id',
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 25,
          id: 'choose_version_id',
        },
        {
          appDEFieldId: 'cur_version_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'cur_version_name',
        },
        {
          appDEFieldId: 'cur_version_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'cur_version_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'space_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'space_id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '版本',
          codeName: 'choose_version_name',
          enableCond: 3,
          appDEFieldId: 'choose_version_name',
          editor: {
            enablePickupView: true,
            singleSelect: true,
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'plmweb.version',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'choose_version_id',
            editorParams: {
              INITSCRIPTCODE:
                'data.choose_version_id = data.cur_version_id;data.choose_version_name = data.cur_version_name',
              'SRFNAVPARAM.n_owner_id_eq': '%id%',
              AC: 'TRUE',
              PICKUPVIEW: 'TRUE',
              ENABLESAVE: 'false',
            },
            editorType: 'PICKER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_owner_id_eq',
                value: 'id',
                id: 'n_owner_id_eq',
              },
            ],
            id: 'choose_version_name',
          },
          allowEmpty: true,
          id: 'choose_version_name',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'choose_version_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'choose_version_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_baseline_plan_page',
        appDataEntityId: 'plmweb.article_page',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.article_page',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'baseline_mpick_up_view_pickup_grid_view_grid',
      controlType: 'GRID',
      logicName: '基线规划页面多项选择视图_选择数据视图_表格',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'grid',
      },
      modelId: '9AA4E5D7-B2E4-4817-A2E5-7CBEE83959BC',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.article_page.baseline_mpick_up_view_pickup_grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入页面主题名称',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.PAGE.N_NAME_LIKE',
              },
              caption: '页面名称',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_name_like',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'choose_search_form',
      controlType: 'SEARCHFORM',
      logicName: '页面数据统计表格_搜索表单',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'searchform',
      },
      modelId: '0e1ac8b39dd90e1851c4111e37156ed6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.article_page.choose_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAGE',
      },
      caption: '页面',
      codeName: 'baseline_mpick_up_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {},
      name: 'captionbar',
      id: 'baseline_mpick_up_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '基线规划空间多项选择视图_选择数据视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '140776cfb3d4a9364d1bf05c7c570bf9',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pagebaseline_mpick_up_grid_view',
  id: 'plmweb.article_page_baseline_mpick_up_grid_view',
};
