export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'tree_exp_view',
  deviewId: '62efeb23d7d9309b8e582b766941d310',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '空间页面',
  codeName: 'article_pagetree_exp_view',
  appDataEntityId: 'plmweb.article_page',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.article_pagecreate_view_document',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.article_pagecreate_view_document',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_space_id_eq',
      value: 'space',
      id: 'n_space_id_eq',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '页面快速新建视图',
      refAppViewId: 'plmweb.article_pagecreate_view_document',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      title: '全部页面',
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '页面',
          refAppViewId: 'plmweb.article_pageshow_view',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
        {
          parentDataJO: {
            srfparentdename: 'SPACE',
            srfparentmode: 'DER1N_PAGE_SPACE_SPACE_ID',
            srfparentdefname: 'SPACE_ID',
          },
          realTitle: '页面',
          refAppViewId: 'plmweb.article_pageshow_view',
          name: 'EXPITEM:node_1',
          id: 'expitem:node_1',
        },
        {
          realTitle: '页面',
          refAppViewId: 'plmweb.article_pageshow_view',
          name: 'EXPITEM:node_2',
          id: 'expitem:node_2',
        },
        {
          realTitle: '页面',
          refAppViewId: 'plmweb.article_pageshow_view',
          name: 'EXPITEM:node_5',
          id: 'expitem:node_5',
        },
        {
          realTitle: '页面',
          refAppViewId: 'plmweb.article_pageshow_view',
          name: 'EXPITEM:node_6',
          id: 'expitem:node_6',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 2,
              id: '默认根节点 - 主页',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_5',
              parentValueLevel: 1,
              searchMode: 3,
              id: '有搜索时启用(页面) - 次级分组',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_6',
              parentValueLevel: 1,
              searchMode: 3,
              id: '有搜索时启用(分组) - 次级分组',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '首级页面 - 次级分组',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '次级页面 - 次级分组',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '首级分组 - 次级分组',
            },
            {
              childDETreeNodeId: 'node_4',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_4',
              parentValueLevel: 1,
              searchMode: 3,
              id: '次级分组 - 次级分组',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '次级页面 - 次级页面',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '首级页面 - 次级页面',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '首级分组 - 次级页面',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_4',
              parentValueLevel: 1,
              searchMode: 3,
              id: '次级分组 - 次级页面',
            },
            {
              childDETreeNodeId: 'node_3',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '2',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'space_id',
              parentDER1N: {
                masterRS: 4,
                pickupDEFName: 'SPACE_ID',
                codeName: 'Space',
                dertype: 'DER1N',
                logicName: '空间-页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Space',
                name: 'DER1N_PAGE_SPACE_SPACE_ID',
                id: 'wiki.article_page.der1n_page_space_space_id',
              },
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 2,
              id: '默认根节点 - 首级分组',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_5',
              parentValueLevel: 1,
              searchMode: 3,
              id: '有搜索时启用(页面) - 次级页面',
            },
            {
              childDETreeNodeId: 'node_2',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PARENT_ID',
                removeActionType: 2,
                recursiveRS: true,
                codeName: 'Page',
                dertype: 'DER1N',
                logicName: '嵌套页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Page',
                name: 'DER1N_PAGE_PAGE_PARENT_ID',
                id: 'wiki.article_page.der1n_page_page_parent_id',
              },
              parentDETreeNodeId: 'node_6',
              parentValueLevel: 1,
              searchMode: 3,
              id: '有搜索时启用(分组) - 次级页面',
            },
            {
              childDETreeNodeId: 'node_1',
              navigateParams: [
                {
                  key: 'n_type_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_type_eq',
                },
              ],
              parentAppDEFieldId: 'space_id',
              parentDER1N: {
                masterRS: 4,
                pickupDEFName: 'SPACE_ID',
                codeName: 'Space',
                dertype: 'DER1N',
                logicName: '空间-页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Space',
                name: 'DER1N_PAGE_SPACE_SPACE_ID',
                id: 'wiki.article_page.der1n_page_space_space_id',
              },
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 2,
              id: '默认根节点 - 首级页面',
            },
            {
              childDETreeNodeId: 'node_6',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 1,
              id: '默认根节点 - 有搜索时启用(分组)',
            },
          ],
          detreeNodes: [
            {
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              enableQuickSearch: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchhome_page',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.article_pageshow_view',
              nodeType: 'node',
              appDataEntityId: 'plmweb.article_page',
              sysImage: {
                rawContent:
                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="design-iconfont" width="18" height="18">\n  <path d="M14.7890625,7.890625 L8.7515625,1.85625 L8.346875,1.4515625 C8.1546875,1.2609375 7.8453125,1.2609375 7.653125,1.4515625 L1.2109375,7.890625 C1.01875,8.0828125 0.915625,8.3375 0.917170003,8.609375 C0.9234375,9.159375 1.38125,9.5984375 1.93125,9.5984375 L2.5953125,9.5984375 L2.5953125,14.6875 L13.4046875,14.6875 L13.4046875,9.5984375 L14.0828125,9.5984375 C14.35,9.5984375 14.6015625,9.49375 14.790625,9.3046875 C14.9796875,9.115625 15.0828125,8.8640625 15.0828125,8.596875 C15.0828125,8.33125 14.978125,8.0796875 14.7890625,7.890625 Z M8.875,13.5625 L7.125,13.5625 L7.125,10.375 L8.875,10.375 L8.875,13.5625 Z M12.2796875,8.4734375 L12.2796875,13.5625 L9.875,13.5625 L9.875,10 C9.875,9.6546875 9.5953125,9.375 9.25,9.375 L6.75,9.375 C6.4046875,9.375 6.125,9.6546875 6.125,10 L6.125,13.5625 L3.7203125,13.5625 L3.7203125,8.4734375 L2.2203125,8.4734375 L8.0015625,2.696875 L8.3625,3.0578125 L13.78125,8.4734375 L12.2796875,8.4734375 Z" fill="#56AAFC" fill-rule="nonzero"></path>\n</svg>',
              },
              treeNodeType: 'DE',
              allowEditText: true,
              enableQuickSearch: true,
              name: '主页',
              id: 'node',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchno_parent_page',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.article_pageshow_view',
              navDER: {
                masterRS: 4,
                pickupDEFName: 'SPACE_ID',
                codeName: 'Space',
                dertype: 'DER1N',
                logicName: '空间-页面',
                minorCodeName: 'pages',
                minorServiceCodeName: 'pages',
                orderValue: 100,
                serviceCodeName: 'Space',
                name: 'DER1N_PAGE_SPACE_SPACE_ID',
                id: 'wiki.article_page.der1n_page_space_space_id',
              },
              nodeType: 'node_1',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_1_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_1_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_1_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_1_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_1_cm',
                id: 'tree_exp_viewnode_1_cm',
              },
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowDrag: true,
              allowDrop: true,
              allowEditText: true,
              allowOrder: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              name: '首级页面',
              id: 'node_1',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchnormal',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.article_pageshow_view',
              nodeType: 'node_2',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_2_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_2_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_2_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_2_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_2_cm',
                id: 'tree_exp_viewnode_2_cm',
              },
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowDrag: true,
              allowDrop: true,
              allowEditText: true,
              allowOrder: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              name: '次级页面',
              id: 'node_2',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchno_parent_page',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              nodeType: 'node_3',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_3_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_3_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_3_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_3_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_3_cm',
                id: 'tree_exp_viewnode_3_cm',
              },
              sysImage: {
                cssClass: 'fa fa-folder-o',
                glyph: 'xf114@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowDrag: true,
              allowDrop: true,
              allowEditText: true,
              allowOrder: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              name: '首级分组',
              id: 'node_3',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchnormal',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              nodeType: 'node_4',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_4_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_4_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_4_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_4_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_4_cm',
                id: 'tree_exp_viewnode_4_cm',
              },
              sysImage: {
                cssClass: 'fa fa-folder-o',
                glyph: 'xf114@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowDrag: true,
              allowDrop: true,
              allowEditText: true,
              allowOrder: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              name: '次级分组',
              id: 'node_4',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchno_parent_page',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.article_pageshow_view',
              nodeType: 'node_5',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_5_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_5_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_5_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_5_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_5_cm',
                id: 'tree_exp_viewnode_5_cm',
              },
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowEditText: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              expanded: true,
              name: '有搜索时启用(页面)',
              id: 'node_5',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchnormal',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.article_pageshow_view',
              nodeType: 'node_6',
              appDataEntityId: 'plmweb.article_page',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_6_cm_deuiaction2_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '重命名',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '重命名',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_viewnode_6_cm_deuiaction1_click@article_page',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                codeName: 'tree_exp_viewnode_6_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点工具栏',
                appDataEntityId: 'plmweb.article_page',
                controlParam: {
                  id: 'node_6_cm',
                },
                modelId: '17f2339e97932380cf7a7053df2d0ff5',
                modelType: 'PSDETOOLBAR',
                name: 'node_6_cm',
                id: 'tree_exp_viewnode_6_cm',
              },
              sysImage: {
                cssClass: 'fa fa-folder-o',
                glyph: 'xf114@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              allowEditText: true,
              enableQuickSearch: true,
              enableRowEdit: true,
              expanded: true,
              name: '有搜索时启用(分组)',
              id: 'node_6',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.article_page',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.article_page',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.article_page',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.article_page',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.article_page',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          controls: [
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_1_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_1_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_1_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_1_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_1_cm',
              id: 'tree_exp_viewnode_1_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_6_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_6_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_6_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_6_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_6_cm',
              id: 'tree_exp_viewnode_6_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_3_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_3_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_3_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_3_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_3_cm',
              id: 'tree_exp_viewnode_3_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_5_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_5_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_5_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_5_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_5_cm',
              id: 'tree_exp_viewnode_5_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_2_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_2_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_2_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_2_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_2_cm',
              id: 'tree_exp_viewnode_2_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_4_cm_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '重命名',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  tooltip: '重命名',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewnode_4_cm_deuiaction1_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              codeName: 'tree_exp_viewnode_4_cm',
              controlType: 'CONTEXTMENU',
              logicName: '树节点工具栏',
              appDataEntityId: 'plmweb.article_page',
              controlParam: {
                id: 'node_4_cm',
              },
              modelId: '17f2339e97932380cf7a7053df2d0ff5',
              modelType: 'PSDETOOLBAR',
              name: 'node_4_cm',
              id: 'tree_exp_viewnode_4_cm',
            },
          ],
          codeName: 'Tree_exp_view_TreeView',
          controlStyle: 'GROUP_TREE',
          controlType: 'TREEVIEW',
          logicName: '页面树导航视图_树视图',
          appDataEntityId: 'plmweb.article_page',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'group_tree',
          modelId: '87bee24ee95b4a2ad1acb9d185641055',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.article_page.tree_exp_view_treeview',
        },
        {
          detoolbarItems: [
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'quick_create_page_document@article_page',
                  uiactionTarget: 'NONE',
                  valid: true,
                  caption: '新建文档',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-file-text-o',
                    glyph: 'xf0f6@FontAwesome',
                  },
                  tooltip: '新建文档',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction1',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewtreeexpbar_toolbar_deuiaction2_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '新建分组',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-folder-o',
                    glyph: 'xf114@FontAwesome',
                  },
                  tooltip: '新建分组',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_tree_exp_viewtreeexpbar_toolbar_deuiaction4_click@article_page',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '从模板新建',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-lightbulb-o',
                    glyph: 'xf0eb@FontAwesome',
                  },
                  tooltip: '从模板新建',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
              ],
              valid: true,
              caption: '新建',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-plus',
                glyph: 'xf067@FontAwesome',
              },
              tooltip: '新建',
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'refreshall',
              valid: true,
              caption: '刷新',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-refresh',
                glyph: 'xf021@FontAwesome',
              },
              tooltip: '刷新',
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          toolbarStyle: 'CONTEXTMENU',
          codeName: 'tree_exp_viewtreeexpbar_toolbar',
          controlType: 'TOOLBAR',
          logicName: '树工具栏',
          appDataEntityId: 'plmweb.article_page',
          controlParam: {
            id: 'treeexpbar_toolbar',
          },
          modelId: '7c66bcb92a07179dd9b413a96be2fc0d',
          modelType: 'PSDETOOLBAR',
          name: 'treeexpbar_toolbar',
          id: 'tree_exp_viewtreeexpbar_toolbar',
        },
      ],
      codeName: 'tree_exp_viewtreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: 'b8d24d3cb5ecf0e811009950b4559679_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_exp_viewtreeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAGE',
      },
      caption: '空间页面',
      codeName: 'tree_exp_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_exp_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '空间页面',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b8d24d3cb5ecf0e811009950b4559679',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pagetree_exp_view',
  id: 'plmweb.article_pagetree_exp_view',
};
