export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'INDEXVIEWTAB_POPUPMODAL',
  deviewCodeName: 'with_version_view',
  deviewId: '092ad5e34d2781b752aa4119d4a2b0ff',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '页面',
  codeName: 'article_page_with_version_view',
  height: 90,
  appDataEntityId: 'plmweb.article_page',
  appViewMsgGroupId: 'usrvmgroup0529043941',
  appViewNavContexts: [
    {
      key: 'PRINCIPAL_ID',
      value: 'article_page',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'PAGE',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      key: 'SPACE',
      value: 'space_id',
      name: 'SPACE',
      id: 'space',
    },
  ],
  sysCss: {
    cssName: 'space-page-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              rawItemParams: [
                {
                  key: 'POSITION',
                  value: 'TOP',
                },
              ],
              predefinedType: 'VIEWMSG_POS',
              id: 'viewmsg_pos',
            },
            caption: '视图消息占位',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            controlLogics: [
              {
                itemName: 'VIEWMSG_POS',
                logicTag: 'layoutpanel',
                logicType: 'SCRIPT',
                scriptCode: 'context.is_deleted == 0',
                triggerType: 'ITEMVISIBLE',
                id: 'logic1',
              },
            ],
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'viewmsg_pos',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              widthMode: 'FULL',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
          widthMode: 'FULL',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'VIEWEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'deleted_visible',
        appDataEntityId: 'plmweb.article_page',
        builtinLogic: true,
        name: 'LOGIC_POSITION',
        id: 'logic_position',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.article_page',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'plmweb.article_page',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'plmweb.article_page',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.article_page',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.article_page',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.article_page',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
              valign: 'flex-start',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'icon',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'icon',
                        },
                        allowEmpty: true,
                        caption: '图标',
                        codeName: 'icon',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['icon'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'ISNOTNULL',
                                defdname: 'icon',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'icon',
                      },
                      {
                        dataType: 25,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_name',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'title',
                        },
                        allowEmpty: true,
                        emptyCaption: true,
                        codeName: 'title',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        labelCssStyle:
                          '    font-weight: 600;\r\n    font-size: var(--ibiz-font-size-header-2);\r\n    color: var(--ibiz-color-black);',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'wiki-page-title',
                        },
                        id: 'title',
                      },
                    ],
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 21,
                        enableCond: 3,
                        ignoreInput: 12,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_content',
                        editor: {
                          contentType: 'HTML',
                          cssStyle: 'min-height: 500px;',
                          editorParams: {
                            contenttype: 'HTML',
                            LINKVIEWID: 'plmweb.recent_custom_redirect_view',
                            TITLE: 'name',
                            PARSESCRIPT:
                              'value?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g,(x, value, icon) => { const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                          },
                          editorStyle: 'ANCHO_HTML',
                          editorType: 'RAW',
                          sysPFPluginId: 'ancho_html',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'content',
                        },
                        allowEmpty: true,
                        emptyCaption: true,
                        enableAnchor: true,
                        codeName: 'content',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'HTML',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                          {
                            logicCat: 'ITEMENABLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'HTML',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'content',
                      },
                      {
                        dataType: 21,
                        ignoreInput: 12,
                        itemHeight: 1,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_content',
                        editor: {
                          mode: 'EDIT',
                          maxLength: 16777215,
                          showMaxLength: true,
                          editorHeight: 1,
                          editorType: 'MARKDOWN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'formitem1',
                        },
                        allowEmpty: true,
                        emptyCaption: true,
                        codeName: 'formitem1',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'MD',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                          {
                            logicCat: 'ITEMENABLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'MD',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'formitem1',
                      },
                      {
                        dataType: 21,
                        ignoreInput: 12,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_content',
                        editor: {
                          maxLength: 16777215,
                          showMaxLength: true,
                          editorStyle: 'LUCKYSHEET',
                          editorType: 'TEXTAREA',
                          sysPFPluginId: 'luckysheet',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'formitem',
                        },
                        allowEmpty: true,
                        emptyCaption: true,
                        codeName: 'formitem',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'EXCEL',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                          {
                            logicCat: 'ITEMENABLE',
                            relatedDetailNames: ['format_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'format_type',
                                value: 'EXCEL',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'formitem',
                      },
                    ],
                    caption: '正文',
                    codeName: 'description_container',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'description_container',
                  },
                  {
                    rawItem: {
                      contentType: 'DIVIDER',
                      rawContent: '{"contentPosition":"center","html":""}',
                      id: 'rawitem2',
                    },
                    codeName: 'rawitem2',
                    detailStyle: 'DEFAULT',
                    detailType: 'RAWITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'rawitem2',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        contentControl: {
                          aggMode: 'NONE',
                          columnEnableFilter: 2,
                          columnEnableLink: 2,
                          groupMode: 'NONE',
                          groupStyle: 'DEFAULT',
                          degridColumns: [
                            {
                              clconvertMode: 'NONE',
                              dataItemName: 'name',
                              excelCaption: '名称',
                              appDEFieldId: 'name',
                              deuiactionId: 'attachment_preview@attachment',
                              valueType: 'SIMPLE',
                              aggMode: 'NONE',
                              align: 'LEFT',
                              capLanguageRes: {
                                lanResTag: 'DEF.LNAME.NAME',
                              },
                              caption: '名称',
                              codeName: 'name',
                              columnType: 'DEFGRIDCOLUMN',
                              noPrivDisplayMode: 1,
                              width: 250,
                              widthUnit: 'STAR',
                              enableSort: true,
                              id: 'name',
                            },
                            {
                              clconvertMode: 'NONE',
                              dataItemName: 'create_time',
                              excelCaption: '上传时间',
                              appDEFieldId: 'create_time',
                              valueFormat: 'YYYY-MM-DD HH:mm:ss',
                              valueType: 'SIMPLE',
                              aggMode: 'NONE',
                              align: 'LEFT',
                              capLanguageRes: {
                                lanResTag: 'DEF.LNAME.CREATE_TIME',
                              },
                              caption: '上传时间',
                              codeName: 'create_time',
                              columnType: 'DEFGRIDCOLUMN',
                              noPrivDisplayMode: 1,
                              width: 200,
                              widthUnit: 'PX',
                              enableSort: true,
                              id: 'create_time',
                            },
                            {
                              clconvertMode: 'NONE',
                              dataItemName: 'owner_id',
                              excelCaption: '所属数据标识',
                              appDEFieldId: 'owner_id',
                              valueType: 'SIMPLE',
                              enableRowEdit: true,
                              aggMode: 'NONE',
                              align: 'LEFT',
                              caption: '所属数据标识',
                              codeName: 'owner_id',
                              columnType: 'DEFGRIDCOLUMN',
                              hideMode: 1,
                              noPrivDisplayMode: 1,
                              width: 100,
                              widthUnit: 'PX',
                              enableSort: true,
                              hideDefault: true,
                              id: 'owner_id',
                            },
                            {
                              deuiactionGroup: {
                                uiactionGroupDetails: [
                                  {
                                    actionLevel: 200,
                                    afterItemType: 'NONE',
                                    beforeItemType: 'NONE',
                                    caption: '下载',
                                    detailType: 'DEUIACTION',
                                    uiactionId: 'download@attachment',
                                    tooltip: '下载当前附件',
                                    showCaption: true,
                                    showIcon: true,
                                    sysImage: {
                                      cssClass: 'fa fa-download',
                                      glyph: 'xf019@FontAwesome',
                                    },
                                    id: 'u5832788',
                                  },
                                ],
                                appDataEntityId: 'plmweb.attachment',
                                uniqueTag: 'attachment__Usr0229502203',
                                name: '附件表格操作列（仅下载）',
                                id: 'usr0229502203',
                              },
                              aggMode: 'NONE',
                              align: 'RIGHT',
                              caption: '操作',
                              codeName: 'uagridcolumn1',
                              columnType: 'UAGRIDCOLUMN',
                              noPrivDisplayMode: 1,
                              width: 100,
                              widthUnit: 'PX',
                              id: 'uagridcolumn1',
                            },
                          ],
                          degridDataItems: [
                            {
                              appDEFieldId: 'name',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'name',
                            },
                            {
                              format: 'YYYY-MM-DD HH:mm:ss',
                              appDEFieldId: 'create_time',
                              valueType: 'SIMPLE',
                              dataType: 5,
                              id: 'create_time',
                            },
                            {
                              appDEFieldId: 'owner_id',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'owner_id',
                            },
                            {
                              appDEFieldId: 'file_id',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'file_id',
                            },
                            {
                              appDEFieldId: 'id',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'srfkey',
                            },
                            {
                              appDEFieldId: 'id',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'srfdataaccaction',
                            },
                            {
                              appDEFieldId: 'name',
                              valueType: 'SIMPLE',
                              dataType: 25,
                              id: 'srfmajortext',
                            },
                          ],
                          degridEditItems: [
                            {
                              caption: '所属数据标识',
                              codeName: 'owner_id',
                              createDV: 'srfowner_id',
                              createDVT: 'APPDATA',
                              enableCond: 3,
                              appDEFieldId: 'owner_id',
                              editor: {
                                maxLength: 100,
                                editorType: 'TEXTBOX',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'owner_id',
                              },
                              allowEmpty: true,
                              id: 'owner_id',
                            },
                            {
                              caption: '标识',
                              codeName: 'srfkey',
                              enableCond: 3,
                              appDEFieldId: 'id',
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'srfkey',
                              },
                              allowEmpty: true,
                              id: 'srfkey',
                            },
                          ],
                          pagingSize: 20,
                          sortMode: 'REMOTE',
                          enableRowEdit: true,
                          enableRowNew: true,
                          singleSelect: true,
                          navViewPos: 'NONE',
                          createControlAction: {
                            appDEMethodId: 'create',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'create',
                          },
                          fetchControlAction: {
                            appDEMethodId: 'fetchdefault',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'fetch',
                          },
                          getDraftControlAction: {
                            appDEMethodId: 'getdraft',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'loaddraft',
                          },
                          getControlAction: {
                            appDEMethodId: 'get',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'load',
                          },
                          removeControlAction: {
                            appDEMethodId: 'remove',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'remove',
                          },
                          updateControlAction: {
                            appDEMethodId: 'update',
                            appDataEntityId: 'plmweb.attachment',
                            id: 'update',
                          },
                          autoLoad: true,
                          showBusyIndicator: true,
                          codeName: 'attach_show',
                          controlType: 'GRID',
                          logicName: '附件表格（展示）',
                          appDataEntityId: 'plmweb.attachment',
                          controlLogics: [
                            {
                              eventNames: 'onLoadSuccess',
                              logicTag: 'attachments_grid',
                              logicType: 'APPDEUILOGIC',
                              appDEUILogicId: 'calc_attachment_hidden',
                              appDataEntityId: 'plmweb.attachment',
                              triggerType: 'CTRLEVENT',
                              id: 'logic2',
                            },
                          ],
                          controlParam: {},
                          modelId: '06c1227d27078b1bb52ad0319ed3be4a',
                          modelType: 'PSDEGRID',
                          name: 'attachments_grid',
                          id: 'plmweb.attachment.attach_show',
                        },
                        contentType: 'GRID',
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        codeName: 'attachments',
                        detailStyle: 'DEFAULT',
                        detailType: 'MDCTRL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'attachments',
                      },
                    ],
                    caption: '附件',
                    codeName: 'grouppanel_attachments_grid',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['attachments'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'ISNOTNULL',
                            defdname: 'attachments',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel_attachments_grid',
                  },
                  {
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'flex-start',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_man',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'plmweb.sysoperator',
                          editorStyle: 'PERSONNEL_INFO',
                          editorType: 'SPAN',
                          sysPFPluginId: 'personnel_info',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'publish_man',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        emptyCaption: true,
                        codeName: 'publish_man',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'publish_man',
                      },
                      {
                        rawItem: {
                          caption: '发布于',
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          id: 'rawitem1',
                        },
                        codeName: 'rawitem1',
                        detailStyle: 'DEFAULT',
                        detailType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'rawitem1',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'publish_time',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'publish_time',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        allowEmpty: true,
                        emptyCaption: true,
                        codeName: 'publish_time',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'publish_time',
                      },
                    ],
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel2',
                  },
                ],
                codeName: 'left_grouppanel',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'left_grouppanel',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'format_type',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'format_type',
                },
                allowEmpty: true,
                hidden: true,
                caption: '正文格式',
                codeName: 'format_type',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'format_type',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'is_lock',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'is_lock',
                },
                allowEmpty: true,
                hidden: true,
                caption: '是否锁定',
                codeName: 'is_lock',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'is_lock',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'show_edit_view_form',
        controlType: 'FORM',
        logicName: '页面实体编辑视图（展示）_表单',
        appDataEntityId: 'plmweb.article_page',
        controlParam: {
          id: 'form',
        },
        modelId: '4e0904462538e4af00965741988ded54',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'plmweb.article_page.show_edit_view_form',
      },
      {
        codeName: 'with_version_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'plmweb.article_page',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'with_version_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PAGE',
        },
        caption: '页面',
        codeName: 'with_version_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.article_page',
        controlParam: {},
        name: 'captionbar',
        id: 'with_version_view_captionbar',
      },
    ],
    codeName: 'usr0226644542',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '页面历史版本展示视图布局面板',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    modelId: 'ebf6813b0e803feab34f77ef411c5736',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0226644542',
  },
  title: '页面',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: '26b92440771902908f4357c8775c3f2e',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pagewith_version_view',
  id: 'plmweb.article_page_with_version_view',
};
