export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'advanced_search_grid_view',
  deviewId: 'A64FB991-9FF9-410B-950B-BB62BCED1280',
  accUserMode: 2,
  caption: '附件',
  codeName: 'attachmentadvanced_search_grid_view',
  appDataEntityId: 'plmweb.attachment',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.attachmenteditview',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.attachmenteditview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.attachmentredirectview',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.attachmentredirectview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '附件编辑视图',
      refAppViewId: 'plmweb.attachmenteditview',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '附件数据重定向视图',
      refAppViewId: 'plmweb.attachmentredirectview',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '附件名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '附件名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'create_man',
          excelCaption: '上传人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '上传人',
          codeName: 'create_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '上传时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '上传时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'create_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enablePagingBar: true,
      singleSelect: true,
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'plmweb.attachment',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.attachment',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Advanced_search_grid',
      controlType: 'GRID',
      logicName: '高级搜索_表格',
      appDataEntityId: 'plmweb.attachment',
      controlParam: {
        id: 'grid',
      },
      modelId: '8A773CB2-39C5-41B1-A483-AF04F92ADFE1',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.attachment.advanced_search_grid',
    },
    {
      searchButtonStyle: 'NONE',
      enableAutoSearch: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              rawItem: {
                caption: '所属模块',
                halign: 'LEFT',
                valign: 'MIDDLE',
                wrapMode: 'NOWRAP',
                contentType: 'RAW',
                id: 'rawitem1',
              },
              codeName: 'rawitem1',
              detailStyle: 'DEFAULT',
              detailType: 'RAWITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'rawitem1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.ftr__search_menu',
                editorType: 'DROPDOWNLIST',
                placeHolder: '选择所属模块',
                valueType: 'SIMPLE',
                editable: true,
                id: 'search_module',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '所属模块',
              codeName: 'search_module',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'search_module',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.prodmgmt__product_list',
                editorType: 'DROPDOWNLIST',
                placeHolder: '选择产品',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_product_id_eq',
              },
              resetItemNames: ['search_module'],
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '产品名称',
              codeName: 'n_product_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['search_module'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'search_module',
                      value: '1',
                      logicType: 'SINGLE',
                    },
                  ],
                  logicType: 'GROUP',
                  id: '表单成员[n_product_id_eq][面板显示]逻辑',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_product_id_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.projmgmt__usrcodelist0122047845',
                editorType: 'DROPDOWNLIST',
                placeHolder: '选择项目',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_project_id_eq',
              },
              resetItemNames: ['search_module'],
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '项目名称',
              codeName: 'n_project_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['search_module'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'search_module',
                      value: '2',
                      logicType: 'SINGLE',
                    },
                  ],
                  logicType: 'GROUP',
                  id: '表单成员[n_project_id_eq][面板显示]逻辑',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_project_id_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.testmgmt__library_list',
                editorType: 'DROPDOWNLIST',
                placeHolder: '选择测试库',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_library_id_eq',
              },
              resetItemNames: ['search_module'],
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '测试库名称',
              codeName: 'n_library_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['search_module'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'search_module',
                      value: '3',
                      logicType: 'SINGLE',
                    },
                  ],
                  logicType: 'GROUP',
                  id: '表单成员[n_library_id_eq][面板显示]逻辑',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_library_id_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appDEACModeId: 'default',
                appDEDataSetId: 'fetchnormal',
                appDataEntityId: 'plmweb.space',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                editorParams: {
                  AC: 'TRUE',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'FALSE',
                },
                editorType: 'PICKEREX_TRIGGER',
                placeHolder: '选择空间',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_space_id_eq',
              },
              resetItemNames: ['search_module'],
              allowEmpty: true,
              caption: '空间名称',
              codeName: 'n_space_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['search_module'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'search_module',
                      value: '4',
                      logicType: 'SINGLE',
                    },
                  ],
                  logicType: 'GROUP',
                  id: '表单成员[n_space_id_eq][面板显示]逻辑',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_space_id_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'create_man',
              editor: {
                singleSelect: true,
                handlerType: 'PickupText',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                editorParams: {
                  URL: '/users/fetchdefault',
                  ISSHOWTAB: 'false',
                  USERMAP: '{"id":"id","name":"display_name"}',
                  AC: 'TRUE',
                  USERMETHOD: 'get',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'FALSE',
                },
                editorStyle: 'PERSONEL_SELECT_ALL',
                editorType: 'PICKEREX_TRIGGER',
                sysPFPluginId: 'person_select',
                placeHolder: '选择上传人',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_create_man_eq',
              },
              allowEmpty: true,
              caption: '上传人',
              codeName: 'n_create_man_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_create_man_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATERANGE_NOTIME',
                editorItems: [
                  {
                    id: 'n_create_time_gtandeq',
                  },
                  {
                    id: 'n_create_time_ltandeq',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'create_time',
              },
              allowEmpty: true,
              caption: '上传时间',
              codeName: 'create_time',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'create_time',
            },
            {
              dataType: 5,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'create_time',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_create_time_ltandeq',
              },
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              allowEmpty: true,
              hidden: true,
              caption: '建立时间',
              codeName: 'n_create_time_ltandeq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_create_time_ltandeq',
            },
            {
              dataType: 5,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'create_time',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_create_time_gtandeq',
              },
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              allowEmpty: true,
              hidden: true,
              caption: '建立时间',
              codeName: 'n_create_time_gtandeq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_create_time_gtandeq',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Advanced_search_form',
      controlType: 'SEARCHFORM',
      logicName: '高级搜索_搜索表单',
      appDataEntityId: 'plmweb.attachment',
      controlParam: {
        id: 'searchform',
      },
      modelId: '711EA605-668C-45E7-8B4A-F494DAC157D7',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.attachment.advanced_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.attachment',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '附件',
      codeName: 'advanced_search_grid_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.attachment',
      controlParam: {},
      name: 'captionbar',
      id: 'advanced_search_grid_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.attachment',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '附件高级搜索表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4328a5ce90ede10a4d6455c46b87ef72',
  modelType: 'PSAPPDEVIEW',
  name: 'attachmentadvanced_search_grid_view',
  id: 'plmweb.attachmentadvanced_search_grid_view',
};
