export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'relation_version_list_view',
  deviewId: 'A272B198-E820-431C-88A4-01B5C7C92519',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.BASELINE_IDEA',
  },
  caption: '基线需求',
  codeName: 'baseline_idea_relation_version_list_view',
  appDataEntityId: 'plmweb.baseline_idea',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.baseline_idea_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.baseline_idea_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.baseline_idea_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.baseline_idea_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      key: 'idea',
      value: 'idea',
      id: 'idea',
    },
  ],
  appViewRefs: [
    {
      realTitle: '基线工需求编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.BASELINE_IDEA.EDITVIEW',
      },
      refAppViewId: 'plmweb.baseline_idea_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '基线工需求编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.BASELINE_IDEA.EDITVIEW',
      },
      refAppViewId: 'plmweb.baseline_idea_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'back@baseline_test_case',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '返回',
          itemType: 'DEUIACTION',
          tooltip: '返回',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'list',
      codeName: 'relation_version_list_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '返回',
      appDataEntityId: 'plmweb.baseline_idea',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '2BD40003-AF0E-4423-8FE7-9CA6DFA9A98D',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'relation_version_list_view_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.BASELINE_IDEA.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.baseline_idea',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'fd122cd5ef963ce45b46dc09bea6472b',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.baseline_idea.default',
    },
    {
      groupMode: 'NONE',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorParams: {
                        OBJECTNAMEFIELD: 'name',
                        VALUETYPE: 'OBJECT',
                      },
                      editorType: 'SPAN',
                      objectNameField: 'name',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'field_text_dynamic',
                    },
                    viewFieldName: 'BASELINE',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_text_dynamic',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'STYLE2',
                    buttonType: 'PANELBUTTON',
                    uiactionId: 'version_comparison@baseline_idea',
                    renderMode: 'BUTTON',
                    tooltip: '版本对比',
                    uiactionTarget: 'SINGLEDATA',
                    caption: '版本对比',
                    itemStyle: 'STYLE2',
                    itemType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysImage: {
                      cssClass: 'fa fa-exchange',
                      glyph: 'xf0ec@FontAwesome',
                    },
                    id: 'button_calluilogic',
                  },
                ],
                layout: {
                  align: 'space-between',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'plmweb.base__baseline_status',
                      editorParams: {
                        OBJECTNAMEFIELD: 'status',
                        VALUETYPE: 'OBJECT',
                      },
                      editorType: 'SPAN',
                      objectNameField: 'status',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'field_text_dynamic1',
                    },
                    viewFieldName: 'BASELINE',
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_text_dynamic1',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorParams: {
                        OBJECTNAMEFIELD: 'name',
                        VALUETYPE: 'OBJECT',
                      },
                      editorType: 'SPAN',
                      objectNameField: 'name',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'field_text_dynamic2',
                    },
                    viewFieldName: 'TARGET_VERSION',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingRight: 'INNERSMALL',
                    },
                    id: 'field_text_dynamic2',
                  },
                ],
                layout: {
                  align: 'space-between',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container1',
              },
              {
                editor: {
                  editorType: 'HIDDEN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'compare_version',
                },
                viewFieldName: 'TARGET_VERSION',
                allowEmpty: true,
                hidden: true,
                caption: '文本(动态)',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'compare_version',
              },
              {
                rawItem: {
                  contentType: 'DIVIDER',
                  predefinedType: 'STATIC_LABEL',
                  rawContent: '标签',
                  rawItemWidth: 100,
                  id: 'static_label',
                },
                contentWidth: 100,
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  width: 100,
                  widthMode: 'FULL',
                },
                width: 100,
                id: 'static_label',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0507349357',
        controlType: 'PANEL',
        logicName: 'baseline_relation_version_列表项面板',
        appDataEntityId: 'plmweb.baseline_idea',
        controlParam: {},
        modelId: '92EF1B11-A294-4F8B-951E-B5163454D8A1',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'plmweb.baseline_idea.usr0507349357',
      },
      delistDataItems: [
        {
          appDEFieldId: 'baseline',
          dataType: 21,
          id: 'baseline',
        },
        {
          appDEFieldId: 'target_version',
          dataType: 21,
          id: 'target_version',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.baseline_idea',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_baseline_relation_version',
        appDataEntityId: 'plmweb.baseline_idea',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.baseline_idea',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.baseline_idea',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.baseline_idea',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'baseline_relation_version',
      controlType: 'LIST',
      logicName: 'baseline_relation_version',
      appDataEntityId: 'plmweb.baseline_idea',
      controlParam: {
        id: 'list',
      },
      modelId: '1683DD48-D150-4B6B-A250-9D0305A6F3FB',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'plmweb.baseline_idea.baseline_relation_version',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.baseline_idea',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.BASELINE_IDEA',
      },
      caption: '基线需求',
      codeName: 'relation_version_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.baseline_idea',
      controlParam: {},
      name: 'captionbar',
      id: 'relation_version_list_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.baseline_idea',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '基线关联需求版本列表视图',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5d1bbb4fd6ad8c2d43662fed9bde7d5b',
  modelType: 'PSAPPDEVIEW',
  name: 'baseline_idearelation_version_list_view',
  id: 'plmweb.baseline_idea_relation_version_list_view',
};
