export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'product_main_view',
  deviewId: 'C1CAFFC4-5126-4872-9914-3F691C42D51D',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.BASELINE',
  },
  caption: '基线',
  codeName: 'baseline_product_main_view',
  appDataEntityId: 'plmweb.baseline',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基线需求',
          appViewId: 'plmweb.baseline_idea_relation_grid_view',
          id: 'idea',
        },
        {
          caption: '基线对比',
          appViewId: 'plmweb.baseline_idea_comparison_grid_view',
          id: 'comparison',
        },
      ],
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.BASELINE',
      },
      editItemCaption: '基线',
      uniqueTag: 'baseline_product_main_view__tabexppanel',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'product_tab_exp_view_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'plmweb.baseline',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '05275AC5-2DB6-43BD-9BE1-51A2B03DCDDC',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'product_tab_exp_view_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.BASELINE',
      },
      caption: '基线',
      codeName: 'product_main_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.baseline',
      controlParam: {},
      name: 'captionbar',
      id: 'product_main_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.baseline',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '产品基线分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '80a8ed75ee788ece55da1eba9b6522f5',
  modelType: 'PSAPPDEVIEW',
  name: 'baselineproduct_main_view',
  id: 'plmweb.baseline_product_main_view',
};
