export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'pick_up_grid_view',
  deviewId: '82137eff18e8e76dc51457e63af9d84f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.CUSTOMER',
  },
  caption: '客户',
  codeName: 'customer_pick_up_grid_view',
  appDataEntityId: 'plmweb.customer',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '客户名称',
          appDEFieldId: 'name',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '设置类别',
                detailType: 'DEUIACTION',
                uiactionId: 'add_categories@customer',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'u3b2b1f1',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'delete_customer@customer',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'u40c2174',
              },
            ],
            appDataEntityId: 'plmweb.customer',
            uniqueTag: 'customer__Usr1220480172',
            name: '主表格操作列',
            id: 'usr1220480172',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '客户名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'scale',
          excelCaption: '规模',
          appDEFieldId: 'scale',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '规模',
          codeName: 'scale',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'scale',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'grade_id',
          excelCaption: '等级',
          appCodeListId: 'plmweb.prodmgmt__customer_level',
          appDEFieldId: 'grade_id',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '等级',
          codeName: 'grade_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'grade_id',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'industry_id',
          excelCaption: '行业',
          appCodeListId: 'plmweb.prodmgmt__customer_sector',
          appDEFieldId: 'industry_id',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '行业',
          codeName: 'industry_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'industry_id',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'categories',
          excelCaption: '类别',
          appCodeListId: 'plmweb.prodmgmt__category',
          appDEFieldId: 'categories',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类别',
          codeName: 'categorys',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'categorys',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'assignee_name',
          excelCaption: '负责人',
          linkAppViewId: 'plmweb.user_redirect_view',
          linkValueItem: 'assignee_id',
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '负责人',
          codeName: 'assignee_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'assignee_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'ticket_finish',
          excelCaption: '已完成工单数',
          appDEFieldId: 'ticket_finish',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '已完成工单数',
          codeName: 'ticket_finish',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'ticket_finish',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'ticket_total',
          excelCaption: '工单总数',
          appDEFieldId: 'ticket_total',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '工单总数',
          codeName: 'ticket_total',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'ticket_total',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'create_man',
          excelCaption: '建立人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeName: 'create_man',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '建立时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'scale',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'scale',
        },
        {
          appDEFieldId: 'grade_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'grade_id',
        },
        {
          appDEFieldId: 'industry_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'industry_id',
        },
        {
          appDEFieldId: 'categories',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'categories',
        },
        {
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_name',
        },
        {
          appDEFieldId: 'ticket_finish',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'ticket_finish',
        },
        {
          appDEFieldId: 'ticket_total',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'ticket_total',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'create_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'assignee_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'product_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'product_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '规模',
          codeName: 'scale',
          enableCond: 3,
          appDEFieldId: 'scale',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'scale',
          },
          allowEmpty: true,
          id: 'scale',
        },
        {
          caption: '等级',
          codeName: 'grade_id',
          enableCond: 3,
          appDEFieldId: 'grade_id',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__customer_level',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'grade_id',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'grade_id',
        },
        {
          caption: '行业',
          codeName: 'industry_id',
          enableCond: 3,
          appDEFieldId: 'industry_id',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__customer_sector',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'industry_id',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'industry_id',
        },
        {
          caption: '类别',
          codeName: 'categorys',
          enableCond: 3,
          appDEFieldId: 'categories',
          editor: {
            appCodeListId: 'plmweb.prodmgmt__category',
            editorParams: {
              readonly: 'true',
            },
            editorType: 'MDROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            readOnly: true,
            id: 'categorys',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'categorys',
        },
        {
          caption: '负责人',
          codeName: 'assignee_name',
          enableCond: 3,
          appDEFieldId: 'assignee_name',
          editor: {
            singleSelect: true,
            appDEACModeId: 'member_select',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'plmweb.product_member',
            uiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '跳转至成员设置',
                  detailType: 'DEUIACTION',
                  uiactionId: 'jump_to_member_set@product_member',
                  tooltip: '跳转至成员设置',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-user-md',
                    glyph: 'xf0f0@FontAwesome',
                  },
                  id: 'u4befff7',
                },
              ],
              appDataEntityId: 'plmweb.product_member',
              uniqueTag: 'product_member__Usr0311005787',
              name: '跳转至成员设置',
              id: 'usr0311005787',
            },
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'assignee_id',
            editorParams: {
              'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
              AC: 'TRUE',
              TRIGGER: 'TRUE',
              URL: 'products/${context.product}/product_members/fetch_default',
              PICKUPVIEW: 'FALSE',
              USERMETHOD: 'post',
              USERMAP: '{"id":"user_id","name":"name"}',
              DEPTMAP: '{"id":"id","name":"display_name"}',
              DEPTMETHOD: 'get',
              DEPTURL: '/users/fetch_default',
            },
            editorStyle: 'PERSONEL_SELECT_PRODUCT',
            editorType: 'PICKEREX_TRIGGER',
            editorItems: [{}],
            sysPFPluginId: 'person_select',
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_department_id_eq',
                value: 'srforgsectorid',
                id: 'n_department_id_eq',
              },
            ],
            id: 'assignee_name',
          },
          allowEmpty: true,
          id: 'assignee_name',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'assignee_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'assignee_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.customer',
        id: 'fetch',
      },
      dedataImportId: 'import_customer',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.customer',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'add_categories@customer',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '设置类别',
              itemType: 'DEUIACTION',
              controlLogics: [
                {
                  itemName: 'deuiaction1',
                  logicTag: 'grid_batchtoolbar',
                  logicType: 'SCRIPT',
                  scriptCode: 'context.srfreadonly != true',
                  triggerType: 'ITEMENABLE',
                  id: 'deuiaction1',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-edit',
                glyph: 'xf044@FontAwesome',
              },
              tooltip: '设置类别',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          codeName: 'pick_up_grid_view_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '客户批操作工具栏',
          appDataEntityId: 'plmweb.customer',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: 'e36afab8d7a6fa9a3baac0dd6536bfb0',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'pick_up_grid_view_grid_batchtoolbar',
        },
      ],
      codeName: 'main',
      controlStyle: 'NUMBER_GRID',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'plmweb.customer',
      controlParam: {
        id: 'grid',
      },
      sysPFPluginId: 'number_grid',
      modelId: '8a84394a0fc65c70fdebb64e06e707ab',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.customer.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入客户名称',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.CUSTOMER.N_NAME_LIKE',
              },
              caption: '客户名称',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_name_like',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.CUSTOMER.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.customer',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'bdabe4f6b9237485d0f81f73f46df124',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.customer.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.customer',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.CUSTOMER',
      },
      caption: '客户',
      codeName: 'pick_up_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.customer',
      controlParam: {},
      name: 'captionbar',
      id: 'pick_up_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.customer',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '客户选择表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.CUSTOMER.PICKUPGRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '202ebafdea3f796a95c9ec84b7172d3c',
  modelType: 'PSAPPDEVIEW',
  name: 'customerPickupGridView',
  id: 'plmweb.customer_pick_up_grid_view',
};
