export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'target_grid_view',
  deviewId: '213f022b31069a6380a8dc8ee5b983ae',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DELIVERABLE',
  },
  caption: '交付物',
  codeName: 'deliverabletarget_grid_view',
  appDataEntityId: 'plmweb.deliverable',
  appViewNavParams: [
    {
      key: 'principal_id',
      value: 'principal_id',
      id: 'principal_id',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'total',
                    },
                    viewFieldName: 'total',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'INNERMEDIUM',
                    },
                    id: 'total',
                  },
                  {
                    rawItem: {
                      caption: '个交付目标',
                      halign: 'LEFT',
                      renderMode: 'TEXT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_text',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            editor: {
              editorType: 'TEXTBOX',
              placeHolder: '添加交付目标，按回车键（Enter）保存',
              predefinedType: 'FIELD_TEXT_DYNAMIC',
              valueType: 'SIMPLE',
              editable: true,
              id: 'input_data',
            },
            allowEmpty: true,
            caption: '文本(动态)',
            itemStyle: 'DEFAULT',
            itemType: 'FIELD',
            layoutPos: {
              grow: 10,
              shrink: 1,
              layout: 'FLEX',
              spacingBottom: 'INNERMEDIUM',
              spacingLeft: 'INNERMEDIUM',
              spacingRight: 'INNERMEDIUM',
              spacingTop: 'INNERMEDIUM',
            },
            id: 'input_data',
          },
          {
            actionType: 'UIACTION',
            buttonStyle: 'DEFAULT',
            buttonType: 'PANELBUTTON',
            uiactionId:
              'panel_usr0118680010_button_calluilogic_click@deliverable',
            renderMode: 'BUTTON',
            tooltip: '取消',
            uiactionTarget: 'SINGLEDATA',
            caption: '取消',
            itemStyle: 'DEFAULT',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingBottom: 'INNERMEDIUM',
              spacingTop: 'INNERMEDIUM',
            },
            showCaption: true,
            id: 'button_calluilogic',
          },
          {
            actionType: 'UIACTION',
            buttonStyle: 'DEFAULT',
            buttonType: 'PANELBUTTON',
            uiactionId:
              'panel_usr0118680010_button_calluilogic1_click@deliverable',
            renderMode: 'BUTTON',
            tooltip: '确定',
            uiactionTarget: 'SINGLEDATA',
            caption: '确定',
            itemStyle: 'DEFAULT',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingBottom: 'INNERMEDIUM',
              spacingTop: 'INNERMEDIUM',
            },
            showCaption: true,
            id: 'button_calluilogic1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container1',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          'view.layoutPanel.panelItems.container1.state.visible = false;\r\n\r\n// 初始化默认隐藏表格\r\nview.layoutPanel.panelItems.grid.state.keepAlive = true;\r\nview.layoutPanel.panelItems.grid.state.visible = false;\r\n\r\n',
        builtinLogic: true,
        name: 'VIEWMOUNTED',
        id: 'viewmounted',
      },
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'CTRLEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'get_deliverable_total',
        appDataEntityId: 'plmweb.deliverable',
        ctrlName: 'grid',
        builtinLogic: true,
        name: 'LOADSUCCESS',
        id: 'loadsuccess',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.deliverableeditview',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.deliverableeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.deliverableredirectview',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'plmweb.deliverableredirectview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        openMode: 'POPUPMODAL',
        realOpenMode: 'POPUPMODAL',
        realTitle: '交付物数据重定向视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.DELIVERABLE.REDIRECTVIEW',
        },
        refAppViewId: 'plmweb.deliverableredirectview',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '交付物编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.DELIVERABLE.EDITVIEW',
        },
        refAppViewId: 'plmweb.deliverableeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'show_add_input@deliverable',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '添加交付目标',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '添加交付目标',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'target_grid_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '添加交付目标',
        appDataEntityId: 'plmweb.deliverable',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '20b3c31d5983d8b35b095cc75cc2fee8',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'target_grid_viewtoolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'title',
            excelCaption: '交付目标',
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '交付目标',
            codeName: 'title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'title',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '交付物',
            appDEFieldId: 'name',
            deuiactionId: 'download@deliverable',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.NAME',
            },
            caption: '交付物',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'create_man',
            excelCaption: '提交人',
            appCodeListId: 'plmweb.sysoperator',
            appDEFieldId: 'create_man',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.CREATE_MAN',
            },
            caption: '提交人',
            codeName: 'create_man',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_man',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '提交时间',
            appDEFieldId: 'create_time',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '提交',
                  detailType: 'DEUIACTION',
                  uiactionId: 'submit_form@deliverable',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-upload',
                    glyph: 'xf093@FontAwesome',
                  },
                  id: 'ud9ceb13',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '删除',
                  detailType: 'DEUIACTION',
                  uiactionId: 'del_form@deliverable',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  id: 'u0d3e2ae',
                },
              ],
              appDataEntityId: 'plmweb.deliverable',
              uniqueTag: 'Deliverable__Usr0122603791',
              name: '交付目标_操作列',
              id: 'usr0122603791',
            },
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.CREATE_TIME',
            },
            caption: '提交时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'create_man',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'create_man',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'file_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'file_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'plmweb.deliverable',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.deliverable',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Target_grid',
        controlType: 'GRID',
        logicName: '交付目标_表格',
        appDataEntityId: 'plmweb.deliverable',
        controlParam: {
          id: 'grid',
        },
        modelId: '3adcc07c7cf0855022be8416ac7347eb',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.deliverable.target_grid',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.deliverable',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.DELIVERABLE',
        },
        caption: '交付物',
        codeName: 'target_grid_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.deliverable',
        controlParam: {},
        name: 'captionbar',
        id: 'target_grid_viewcaptionbar',
      },
    ],
    codeName: 'Usr0118680010',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'deliver_target_grid_view表格视图布局',
    appDataEntityId: 'plmweb.deliverable',
    controlLogics: [
      {
        eventNames: 'onEnter',
        itemName: 'INPUT_DATA',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'create_deliverable',
        appDataEntityId: 'plmweb.deliverable',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: 'ef002a9ba11322a3cea826bef037e38c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0118680010',
  },
  title: '交付目标表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e4cd9c05bb92870e4682686246905745',
  modelType: 'PSAPPDEVIEW',
  name: 'deliverabletarget_grid_view',
  id: 'plmweb.deliverabletarget_grid_view',
};
