export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'topic_grid_view',
  deviewId: '79295243f7e787052e1bbf7f3ef68eb5',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_TOPIC',
  },
  caption: '话题列表',
  codeName: 'discuss_topic_topic_grid_view',
  appDataEntityId: 'plmweb.discuss_topic',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      content: '<p><span style="color: #ced4d9;">共</span></p>',
                      contentType: 'HTML',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text1',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERSMALL',
                    },
                    showCaption: true,
                    id: 'static_text1',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'total',
                    },
                    viewFieldName: 'total',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERSMALL',
                      spacingRight: 'OUTERSMALL',
                    },
                    id: 'total',
                  },
                  {
                    rawItem: {
                      content:
                        '<p><span style="color: #ced4d9;">个话题</span></p>',
                      contentType: 'HTML',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_text',
                  },
                ],
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingBottom: 'OUTERSMALL',
                  spacingLeft: 'OUTERLARGE',
                },
                sysCss: {
                  cssName: 'dashboard_repair_style',
                },
                id: 'container',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'VIEWEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'get_table_size',
        appDataEntityId: 'plmweb.product',
        builtinLogic: true,
        name: 'LOGIC',
        id: 'logic',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.discuss_topic_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.discuss_topic_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'plmweb.discuss_topic_index_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.discuss_topic_index_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '话题首页视图',
        refAppViewId: 'plmweb.discuss_topic_index_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '话题编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.DISCUSS_TOPIC.EDITVIEW',
        },
        refAppViewId: 'plmweb.discuss_topic_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            buttonStyle: 'STYLE2',
            noPrivDisplayMode: 2,
            uiactionId: 'open_topic@discuss_topic',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '更多',
            itemType: 'DEUIACTION',
            sysCss: {
              cssName: 'swap_icon_text',
            },
            sysImage: {
              rawContent:
                '<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1732774437860" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="11278" width="12" height="12" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M767.369846 526.099692a47.261538 47.261538 0 0 0-13.705846-29.538461L328.940308 71.837538a47.419077 47.419077 0 1 0-67.032616 67.032616l391.640616 391.640615-391.640616 391.719385a47.419077 47.419077 0 1 0 66.953846 67.032615l424.802462-424.723692a47.261538 47.261538 0 0 0 13.705846-29.459692z" fill="#999999" p-id="11279"></path></svg>',
            },
            tooltip: '查看更多话题',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction3',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'topic_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '话题表格视图（仪表盘部件）_工具栏',
        appDataEntityId: 'plmweb.discuss_topic',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '3d388e4e99ad8a8f657638e852f037ea',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'topic_grid_view_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '话题名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.NAME',
            },
            caption: '话题名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 250,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'update_man',
            excelCaption: '更新人',
            appCodeListId: 'plmweb.sysoperator',
            appDEFieldId: 'update_man',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_MAN',
            },
            caption: '更新人',
            codeName: 'update_man',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'update_man',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'update_time',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            scriptCode:
              'var svgIcon = `<span title="话题" style="display: flex;align-items: center;"><?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="design-iconfont" width="24" height="24"><g fill="none" fill-rule="evenodd"><path d="M9.38014822,3 C9.67907467,2.99916693 9.96590669,3.12026973 10.1767119,3.33631994 L12.4843108,5.68866329 C12.5264166,5.73192912 12.5837821,5.75617853 12.6435672,5.75598382 L21.6007905,5.75598382 C22.22264,5.75669576 22.7265743,6.27040148 22.7272727,6.90430863 L22.7272727,19.3062164 C22.7265743,19.9401235 22.2226399,20.4538292 21.6007905,20.4545412 L3.12648221,20.4545412 C2.50463278,20.4538292 2.0006984,19.9401235 2,19.3062164 L2,4.14832912 C2.00069839,3.51442198 2.50463277,3.00071626 3.12648221,3 L9.38014822,3 Z M12.3,9.156 L11.28,9.156 L10.98,11.46 L9.744,11.46 L9.744,12.612 L10.836,12.612 L10.632,14.256 L9.468,14.256 L9.468,15.396 L10.5,15.396 L10.188,18 L11.232,18 L11.556,15.396 L13.056,15.396 L12.744,18 L13.8,18 L14.112,15.396 L15.384,15.396 L15.384,14.256 L14.244,14.256 L14.448,12.612 L15.66,12.612 L15.66,11.46 L14.592,11.46 L14.856,9.156 L13.836,9.156 L13.536,11.46 L12.024,11.46 L12.3,9.156 Z M13.392,12.612 L13.188,14.256 L11.676,14.256 L11.88,12.612 L13.392,12.612 Z" fill="#56AAFC" fill-rule="nonzero"></path></g></svg></span>`;\r\nreturn `<span style="display: flex; align-items: center;">` + svgIcon + `&nbsp;` + data.name + `</span>`;',
            valueType: 'SIMPLE',
            customCode: true,
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'update_man',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'update_man',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        forceFit: true,
        hideHeader: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_main',
          appDataEntityId: 'plmweb.discuss_topic',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.discuss_topic',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'topic_grid_view_grid',
        controlType: 'GRID',
        logicName: '话题表格视图（仪表盘部件）_表格',
        appDataEntityId: 'plmweb.discuss_topic',
        controlParam: {
          id: 'grid',
        },
        modelId: 'f2c60ee3de3cb09880879ca472713d4d',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.discuss_topic.topic_grid_view_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'topic_grid_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '话题表格视图（仪表盘部件）_搜索表单',
        appDataEntityId: 'plmweb.discuss_topic',
        controlParam: {
          id: 'searchform',
        },
        modelId: '25e5c1fcc88dc4e0103edaba75d33119',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'plmweb.discuss_topic.topic_grid_view_search_form',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.discuss_topic',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.DISCUSS_TOPIC',
        },
        caption: '话题列表',
        codeName: 'topic_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.discuss_topic',
        controlParam: {},
        name: 'captionbar',
        id: 'topic_grid_view_captionbar',
      },
    ],
    codeName: 'usr1112819648',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'topic_grid_view表格视图布局',
    appDataEntityId: 'plmweb.discuss_topic',
    controlParam: {},
    modelId: 'ce25eb7f2cb66545fff989aae89653eb',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1112819648',
  },
  title: '话题表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c310d4b227190c01d1d504d730f3c642',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_topictopic_grid_view',
  id: 'plmweb.discuss_topic_topic_grid_view',
};
