export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'bind_grid_view',
  deviewId: 'ABBBC861-2632-4837-BBDF-10559CABC0FD',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_MEMBER',
  },
  caption: '协作成员',
  codeName: 'discuss_member_bind_grid_view',
  appDataEntityId: 'plmweb.discuss_member',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onCreated',
      logicTrigger: 'VIEWEVENT',
      logicType: 'APPDEUILOGIC',
      appDEUILogicId: 'create_default_temp_members',
      appDataEntityId: 'plmweb.discuss_member',
      builtinLogic: true,
      name: 'LOGIC',
      id: 'logic',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        batchAddAppViews: [
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.discuss_member_edit_view',
        },
        enableBatchAdd: true,
        appDataEntityId: 'plmweb.discuss_member',
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.discuss_member_edit_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.discuss_member_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.discuss_member_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewParams: [
    {
      key: 'PROPERTYMAP',
      value: 'display_name:name',
      name: 'PROPERTYMAP',
      id: 'propertymap',
    },
  ],
  appViewRefs: [
    {
      realTitle: '协作成员数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.DISCUSS_MEMBER.REDIRECTVIEW',
      },
      refAppViewId: 'plmweb.discuss_member_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '协作成员编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.DISCUSS_MEMBER.EDITVIEW',
      },
      refAppViewId: 'plmweb.discuss_member_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      name: 'MPICKUPVIEW:DISCUSS_TOPIC',
      id: 'mpickupview:discuss_topic',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '选择成员',
      refAppViewId: 'plmweb.user_choose_mpick_up_view',
      name: 'MPICKUPVIEW:USER',
      id: 'mpickupview:user',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'add_discuss_topic_member',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '添加成员',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '添加成员',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      toolbarStyle: 'USER',
      xdataControlName: 'grid',
      codeName: 'bind_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '添加成员',
      appDataEntityId: 'plmweb.discuss_member',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'FA031A65-BBB8-4A07-B32E-DAC7432AC029',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'bind_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '姓名',
          linkAppViewId: 'plmweb.user_redirect_view',
          linkValueItem: 'user_id',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '姓名',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                detailType: 'DEUIACTION',
                uiactionId: 'remove_member@discuss_member',
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'uac12646',
              },
            ],
            appDataEntityId: 'plmweb.discuss_member',
            uniqueTag: 'discuss_member__Usr0514283014',
            name: '协作成员配置',
            id: 'usr0514283014',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'owner_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'owner_id',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.discuss_member',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.discuss_member',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'binding',
      controlType: 'GRID',
      logicName: '协作成员绑定表格',
      appDataEntityId: 'plmweb.discuss_member',
      controlParam: {
        id: 'grid',
      },
      modelId: '0284850b992c53bc9ff48a1f19e15043',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.discuss_member.binding',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.DISCUSS_MEMBER.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.discuss_member',
      controlParam: {
        id: 'searchform',
      },
      modelId: '624a23395c3f0be60961c8dd482be3fb',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.discuss_member.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.discuss_member',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_MEMBER',
      },
      caption: '协作成员',
      codeName: 'bind_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.discuss_member',
      controlParam: {},
      name: 'captionbar',
      id: 'bind_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.discuss_member',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '协作成员绑定表格视图（嵌入）',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'cb5549520a0c11013331bbddb1098e59',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_memberbind_grid_view',
  id: 'plmweb.discuss_member_bind_grid_view',
};
