export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'show_edit_view',
  deviewId: '0018E87A-DFD1-44FB-85F2-C76347AD78E6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DYNADASHBOARD',
  },
  caption: '仪表盘',
  codeName: 'dyna_dashboard_show_edit_view',
  appDataEntityId: 'plmweb.dyna_dashboard',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'show_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '仪表盘展示页_工具栏',
      appDataEntityId: 'plmweb.dyna_dashboard',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '61FAFA4B-D7CF-4B0C-BE2D-FD4E147C6E31',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'show_edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.dyna_dashboard',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 21,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'example_chart',
              editor: {
                editorParams: {
                  readonly: 'true',
                  RAWCONTENT: 'TRUE',
                  autoPreview: 'true',
                  MAXCOUNT: '1',
                },
                editorType: 'PICTURE_ONE_RAW',
                valueType: 'SIMPLE',
                editable: true,
                readOnly: true,
                id: 'example_chart',
              },
              allowEmpty: true,
              caption: '示例图',
              codeName: 'example_chart',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'example_chart',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'dyna_dashboard_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'dynadashboardid',
              },
              allowEmpty: true,
              hidden: true,
              caption: '动态数据看板标识',
              codeName: 'dynadashboardid',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'dynadashboardid',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'show_edit_view_form',
      controlType: 'FORM',
      logicName: '仪表盘展示页_表单',
      appDataEntityId: 'plmweb.dyna_dashboard',
      controlParam: {
        id: 'form',
      },
      modelId: 'CDF5A539-5A18-4BE7-B6C9-F4032767CE6C',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.dyna_dashboard.show_edit_view_form',
    },
    {
      codeName: 'show_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.dyna_dashboard',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'show_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DYNADASHBOARD',
      },
      caption: '仪表盘',
      codeName: 'show_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.dyna_dashboard',
      controlParam: {},
      name: 'captionbar',
      id: 'show_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.dyna_dashboard',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '仪表盘展示页',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7842b3e708b6390b72adac00e47b6a1b',
  modelType: 'PSAPPDEVIEW',
  name: 'dyna_dashboardshow_edit_view',
  id: 'plmweb.dyna_dashboard_show_edit_view',
};
