export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'list_exp_view',
  deviewId: '3DEDD759-12A3-4BD2-8E4E-3EAF9E151E9A',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DYNADASHBOARD',
  },
  caption: '仪表盘模板列表',
  codeName: 'dyna_dashboard_list_exp_view',
  height: 90,
  appDataEntityId: 'plmweb.dyna_dashboard',
  appViewNavContexts: [
    {
      key: 'INSIGHT_VIEW_ID',
      value: 'insight_view',
      name: 'INSIGHT_VIEW_ID',
      id: 'insight_view_id',
    },
    {
      rawValue: true,
      key: 'INSIGHT_VIEW',
      name: 'INSIGHT_VIEW',
      id: 'insight_view',
    },
    {
      rawValue: true,
      key: 'DYNA_DASHBOARD',
      name: 'DYNA_DASHBOARD',
      id: 'dyna_dashboard',
    },
  ],
  appViewParams: [
    {
      key: 'MODALOPTION',
      value:
        '{"showClose":false,"closeOnClickModal":false,"closeOnPressEscape":false}',
      name: 'MODALOPTION',
      id: 'modaloption',
    },
  ],
  sysCss: {
    cssName: 'stencil-center-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  editorParams: {
                    editMode: 'hover',
                  },
                  editorType: 'TEXTBOX',
                  placeHolder: '输入新标题',
                  predefinedType: 'FIELD_TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'board_title',
                },
                viewFieldName: 'board_name',
                allowEmpty: true,
                caption: '文本框',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysCss: {
                  cssName: 'board_title_style',
                },
                id: 'board_title',
              },
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 78,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              width: 78,
              widthMode: 'PERCENTAGE',
            },
            width: 78,
            id: 'view_exp',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  caption: '仪表盘模板',
                  halign: 'LEFT',
                  renderMode: 'PARAGRAPH',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'page_title',
                },
                caption: '仪表盘模板',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'page_title',
              },
              {
                caption: '列表导航',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'listexpbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId:
                  'panel_usr0702065870_button_calluilogic_click@dyna_dashboard',
                renderMode: 'BUTTON',
                tooltip: '使用此模板',
                uiactionTarget: 'SINGLEDATA',
                caption: '使用此模板',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'button_calluilogic',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content',
          },
        ],
        predefinedType: 'CONTAINER_H_SPLIT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'ListExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        xdataControlName: 'listexpbar_list',
        enableCounter: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '仪表盘展示页',
            refAppViewId: 'plmweb.dyna_dashboard_show_edit_view',
            name: 'EXPITEM:DEFAULT',
            id: 'expitem:default',
          },
        ],
        controls: [
          {
            groupMode: 'NONE',
            itemLayoutPanel: {
              layoutMode: 'TABLE_24COL',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              rootPanelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            sysImage: {
                              cssClass: 'fa fa-dashboard',
                              glyph: 'xf0e4@FontAwesome',
                            },
                            contentType: 'IMAGE',
                            predefinedType: 'STATIC_IMAGE',
                            id: 'static_image',
                          },
                          caption: '图片',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysImage: {
                            cssClass: 'fa fa-dashboard',
                            glyph: 'xf0e4@FontAwesome',
                          },
                          showCaption: true,
                          id: 'static_image',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'dyna_dashboard_name',
                          },
                          viewFieldName: 'dyna_dashboard_name',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingLeft: 'OUTERMEDIUM',
                          },
                          id: 'dyna_dashboard_name',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container',
                    },
                  ],
                  layout: {
                    dir: 'column',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'page_container',
                },
              ],
              codeName: 'usr0702974395',
              controlType: 'PANEL',
              logicName: 'List_列表项面板',
              appDataEntityId: 'plmweb.dyna_dashboard',
              controlLogics: [
                {
                  eventNames: 'onClick',
                  itemName: 'page_container',
                  logicTag: 'listexpbar_list_itempanel',
                  logicType: 'APPDEUILOGIC',
                  appDEUILogicId: 'fill_choosed_board_name',
                  appDataEntityId: 'plmweb.dyna_dashboard',
                  triggerType: 'CTRLEVENT',
                  id: 'logic',
                },
              ],
              controlParam: {},
              modelId: '5C03C783-8B91-4485-8F28-C4B11AE681F5',
              modelType: 'PSSYSVIEWPANEL',
              name: 'listexpbar_list_itempanel',
              id: 'plmweb.dyna_dashboard.usr0702974395',
            },
            delistDataItems: [
              {
                appDEFieldId: 'dyna_dashboard_id',
                dataType: 25,
                id: 'srfkey',
              },
              {
                appDEFieldId: 'dyna_dashboard_name',
                dataType: 25,
                id: 'srfmajortext',
              },
            ],
            pagingSize: 1000,
            showHeader: true,
            navAppViewId: 'plmweb.dyna_dashboard_show_edit_view',
            navigateParams: [
              {
                key: 'board_name',
                value: 'dyna_dashboard_name',
                id: 'board_name',
              },
            ],
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'plmweb.dyna_dashboard',
              id: 'create',
            },
            fetchControlAction: {
              appDEMethodId: 'fetch_example_chart',
              appDataEntityId: 'plmweb.dyna_dashboard',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'plmweb.dyna_dashboard',
              id: 'load',
            },
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'plmweb.dyna_dashboard',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'plmweb.dyna_dashboard',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'list_exp_view_list',
            controlType: 'LIST',
            logicName: 'List',
            appDataEntityId: 'plmweb.dyna_dashboard',
            controlLogics: [
              {
                eventNames: 'onLoadSuccess',
                logicTag: 'listexpbar_list',
                logicType: 'APPDEUIACTION',
                appDEUIActionId: 'load_success@dyna_dashboard',
                triggerType: 'CTRLEVENT',
                id: 'logic',
              },
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'listexpbar_list',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'listexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'listexpbar_list',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'listexpbar_load',
              },
            ],
            controlParam: {
              id: 'listexpbar_list',
            },
            modelId: 'CC44D2EE-0A89-4DEA-93C5-A9E15D499B0F',
            modelType: 'PSDELIST',
            name: 'listexpbar_list',
            id: 'plmweb.dyna_dashboard.list_exp_view_list',
          },
        ],
        codeName: 'list_exp_view_listexpbar',
        controlType: 'LISTEXPBAR',
        appDataEntityId: 'plmweb.dyna_dashboard',
        controlParam: {
          id: 'listexpbar',
        },
        modelId: 'c61de9a99519acce032404fb60530911_listexpbar',
        modelType: 'PSEXPBAR',
        name: 'listexpbar',
        id: 'list_exp_view_listexpbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.dyna_dashboard',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.DYNADASHBOARD',
        },
        caption: '仪表盘模板列表',
        codeName: 'list_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.dyna_dashboard',
        controlParam: {},
        name: 'captionbar',
        id: 'list_exp_view_captionbar',
      },
    ],
    codeName: 'usr0702065870',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'list_exp_view 实体列表导航视图布局面板',
    appDataEntityId: 'plmweb.dyna_dashboard',
    controlParam: {},
    modelId: '6329A6E3-7CFE-4738-8684-8806BB2975F4',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0702065870',
  },
  title: '仪表盘模板列表导航',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTEXPVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c61de9a99519acce032404fb60530911',
  modelType: 'PSAPPDEVIEW',
  name: 'dyna_dashboardlist_exp_view',
  id: 'plmweb.dyna_dashboard_list_exp_view',
};
