export default {
  gridRowActiveMode: 1,
  enableRowEdit: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_all',
  deviewId: '6ccac8917e3a0ae65682108795cf7197',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.IDEA.GRID_VIEW_ALL',
  },
  caption: '全部需求',
  codeName: 'ideagrid_view_all',
  appDataEntityId: 'plmweb.idea',
  appViewNavContexts: [
    {
      key: 'TEST_CASE',
      value: 'case_id',
      name: 'TEST_CASE',
      id: 'test_case',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              align: 'center',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.ideaquick_create_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'plmweb.ideaquick_create_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'plmweb.ideamain_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'INDEXVIEWTAB_POPUPMODAL',
              refAppViewId: 'plmweb.ideamain_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        openMode: 'INDEXVIEWTAB_POPUPMODAL',
        realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
        realTitle: '需求',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.IDEA.MAIN_VIEW',
        },
        refAppViewId: 'plmweb.ideamain_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '新建需求',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.IDEA.QUICK_CREATE_VIEW',
        },
        refAppViewId: 'plmweb.ideaquick_create_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'new',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建需求',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '新建需求',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'import',
                valid: true,
                caption: '导入需求',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-upload',
                  glyph: 'xf093@FontAwesome',
                },
                tooltip: '导入需求',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'exportexcel',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.EXPORT',
                },
                caption: '导出需求',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-file-excel-o',
                  glyph: 'xf1c3@FontAwesome',
                },
                tooltip: '导出需求',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.EXPORT',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction3',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-list-ul',
              glyph: 'xf0ca@FontAwesome',
            },
            showCaption: true,
            showIcon: true,
            id: 'items1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_alltoolbar',
        controlType: 'TOOLBAR',
        logicName: '新建需求',
        appDataEntityId: 'plmweb.idea',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '233eddea4e3f3333716c8a20112244f3',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_alltoolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'identifier',
            excelCaption: '编号',
            appDEFieldId: 'identifier',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.IDEA.IDENTIFIER',
            },
            caption: '编号',
            codeName: 'identifier',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 80,
            widthUnit: 'PX',
            enableSort: true,
            id: 'identifier',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'title',
            excelCaption: '标题',
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.TITLE',
            },
            caption: '标题',
            codeName: 'title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            sysPFPluginId: 'column_action_edit',
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            userParam: {
              SAVEMODE: 'BLUR',
            },
            id: 'title',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'state',
            excelCaption: '状态',
            appCodeListId: 'plmweb.prodmgmt__idea_state',
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.STATE',
            },
            caption: '状态',
            codeName: 'state',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'state',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'assignee_name',
            excelCaption: '负责人',
            linkAppViewId: 'plmweb.userredirectview',
            linkValueItem: 'assignee_id',
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            enableLinkView: true,
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ASSIGNEE_NAME',
            },
            caption: '负责人',
            codeName: 'assignee_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'assignee_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '建立时间',
            appDEFieldId: 'create_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.CREATE_TIME',
            },
            caption: '建立时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'identifier',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'identifier',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'state',
          },
          {
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_name',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'assignee_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'product_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'product_id',
          },
          {
            appDEFieldId: 'category_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'category_id',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        degridEditItems: [
          {
            caption: '标题',
            codeName: 'title',
            enableCond: 3,
            appDEFieldId: 'title',
            editor: {
              maxLength: 500,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'title',
            },
            allowEmpty: true,
            userParam: {
              SAVEMODE: 'BLUR',
            },
            id: 'title',
          },
          {
            caption: '状态',
            codeName: 'state',
            enableCond: 3,
            appDEFieldId: 'state',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.prodmgmt__idea_state',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'state',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            id: 'state',
          },
          {
            caption: '负责人',
            codeName: 'assignee_name',
            enableCond: 3,
            appDEFieldId: 'assignee_name',
            editor: {
              singleSelect: true,
              handlerType: 'PickupText',
              appDEACModeId: 'member_select',
              appDEDataSetId: 'fetchdefault',
              appDataEntityId: 'plmweb.product_member',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    caption: '跳转至成员设置',
                    detailType: 'DEUIACTION',
                    uiactionId: 'jump_to_member_set@product_member',
                    tooltip: '跳转至成员设置',
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-user-md',
                      glyph: 'xf0f0@FontAwesome',
                    },
                    id: 'u653ff49',
                  },
                ],
                uniqueTag: 'Product_member__Usr0311005787',
                name: '跳转至成员设置',
                id: 'usr0311005787',
              },
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'assignee_id',
              editorParams: {
                'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                AC: 'TRUE',
                TRIGGER: 'TRUE',
                URL: 'products/${context.product}/product_members/fetchdefault',
                PICKUPVIEW: 'FALSE',
                USERMETHOD: 'post',
                USERMAP: '{"id":"user_id","name":"name"}',
                DEPTMAP: '{"id":"id","name":"display_name"}',
                DEPTMETHOD: 'get',
                DEPTURL: '/users/fetchdefault',
              },
              editorStyle: 'PERSONEL_SELECT_PRODUCT',
              editorType: 'PICKEREX_TRIGGER',
              editorItems: [{}],
              sysPFPluginId: 'person_select',
              valueType: 'SIMPLE',
              editable: true,
              navigateParams: [
                {
                  key: 'n_department_id_eq',
                  value: 'srforgsectorid',
                  id: 'n_department_id_eq',
                },
              ],
              id: 'assignee_name',
            },
            allowEmpty: true,
            id: 'assignee_name',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
          {
            enableCond: 3,
            appDEFieldId: 'assignee_id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
            },
            allowEmpty: true,
            id: 'assignee_id',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enablePagingBar: true,
        enableRowEdit: true,
        enableRowNew: true,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.idea',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetchcommon',
          appDataEntityId: 'plmweb.idea',
          id: 'fetch',
        },
        getDraftControlAction: {
          appDEMethodId: 'getdraft',
          appDataEntityId: 'plmweb.idea',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.idea',
          id: 'load',
        },
        dedataImportId: 'import_idea',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.idea',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.idea',
          id: 'update',
        },
        autoLoad: true,
        enableItemPrivilege: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'change_idea_state@idea',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '变更状态',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-exchange',
                  glyph: 'xf0ec@FontAwesome',
                },
                tooltip: '变更状态',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'idea_re_plan@idea',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '需求排期',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-calendar',
                  glyph: 'xf073@FontAwesome',
                },
                tooltip: '需求排期',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction3',
              },
              {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'idea_copy@idea',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '复制',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-copy',
                      glyph: 'xf0c5@FontAwesome',
                    },
                    tooltip: '复制',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'idea_move@idea',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '移动',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-sign-in',
                      glyph: 'xf090@FontAwesome',
                    },
                    tooltip: '移动',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction5',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 1,
                    uiactionId: 'idea_archive@idea',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '归档',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-folder',
                      glyph: 'xf07b@FontAwesome',
                    },
                    tooltip: '归档',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction6',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 1,
                    uiactionId: 'activate@idea',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '激活',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'key',
                    },
                    tooltip: '激活',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete@idea',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction7',
                  },
                ],
                valid: true,
                caption: '更多',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-list-ul',
                  glyph: 'xf0ca@FontAwesome',
                },
                tooltip: '更多',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
            ],
            codeName: 'grid_view_allgrid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作工具栏（需求表格）',
            appDataEntityId: 'plmweb.idea',
            controlParam: {
              id: 'grid_batchtoolbar',
            },
            modelId: '1E0B4CCC-EC5C-4279-9D8E-BB048825A19E',
            modelType: 'PSDETOOLBAR',
            name: 'grid_batchtoolbar',
            id: 'grid_view_allgrid_batchtoolbar',
          },
        ],
        codeName: 'Main',
        controlStyle: 'NUMBER_GRID',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'plmweb.idea',
        controlParam: {
          id: 'grid',
        },
        sysPFPluginId: 'number_grid',
        modelId: '8fd529dadc8e3e13ca01355231d57bea',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.idea.main',
      },
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.prodmgmt__idea_state',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'state',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'state',
            id: 'state',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.prodmgmt__idea_priority',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'priority',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'priority',
            id: 'priority',
          },
          {
            dataType: 9,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.yesno',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'is_archived',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'is_archived',
            id: 'is_archived',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'assignee_id',
              editorParams: {
                ISADDSYMBOL: 'true',
                MULTIPLE: 'true',
                'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                AC: 'TRUE',
                TRIGGER: 'TRUE',
                URL: 'products/${context.product}/product_members/fetchdefault',
                PICKUPVIEW: 'FALSE',
                USERMETHOD: 'post',
                USERMAP: '{"id":"user_id","name":"name"}',
                DEPTMAP: '{"id":"id","name":"display_name"}',
                DEPTMETHOD: 'get',
                DEPTURL: '/users/fetchdefault',
              },
              editorStyle: 'PERSONEL_SELECT_PRODUCT',
              editorType: 'PICKEREX_TRIGGER',
              sysPFPluginId: 'person_select',
              valueType: 'SIMPLE',
              editable: true,
              navigateParams: [
                {
                  key: 'n_department_id_eq',
                  value: 'srforgsectorid',
                  id: 'n_department_id_eq',
                },
              ],
              id: 'assignee_id',
            },
            allowEmpty: true,
            caption: '负责人',
            itemType: 'FILTER',
            appDEFieldId: 'assignee_id',
            id: 'assignee_id',
          },
        ],
        searchBarGroups: [
          {
            defaultGroup: true,
            caption: '全部需求',
            data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'all',
          },
          {
            caption: '已归档的需求',
            data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"1"}]}]}}\n',
            itemType: 'GROUP',
            id: 'archive',
          },
          {
            caption: '我创建的需求',
            data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"create_man","condop":"EQ","value":"${context.srfpersonid}"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'my_create',
          },
          {
            caption: '我负责的需求',
            data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"assignee_id","condop":"EQ","value":"${context.srfpersonid}"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'my_assignee',
          },
        ],
        quickGroupCount: 2,
        quickSearchMode: 1,
        searchBarStyle: 'SEARCHBAR2',
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'product_idea',
        controlType: 'SEARCHBAR',
        logicName: '产品需求搜索栏',
        appDataEntityId: 'plmweb.idea',
        controlParam: {
          id: 'searchbar',
        },
        modelId: 'B5E7378B-0086-4265-AEA8-3FD96A51D011',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'plmweb.idea.product_idea',
      },
      {
        capLanguageRes: {
          lanResTag: 'PAGE.CAPTION.IDEA.GRID_VIEW_ALL',
        },
        caption: '全部需求',
        codeName: 'grid_view_allcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.idea',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_allcaptionbar',
      },
    ],
    codeName: 'Usr0119787094',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'grid_view_all表格视图布局',
    appDataEntityId: 'plmweb.idea',
    controlParam: {},
    modelId: '2919F240-0AE8-44BD-A53E-CB6E36F6FDED',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0119787094',
  },
  title: '全部需求',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.IDEA.GRID_VIEW_ALL',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b71524158993c50b39497712556cd9db',
  modelType: 'PSAPPDEVIEW',
  name: 'ideagrid_view_all',
  id: 'plmweb.ideagrid_view_all',
};
