export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'others_re_idea_view',
  deviewId: '4765134B-F7DD-4544-AC33-42F6661ACA1E',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.IDEA.OTHERS_RELATION_IDEA_VIEW',
  },
  caption: '选择需求',
  codeName: 'ideaothers_re_idea_view',
  appDataEntityId: 'plmweb.idea',
  appViewNavParams: [
    {
      key: 'target_type',
      value: 'target_type',
      id: 'target_type',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'plmweb.ideaothers_re_view_pickupgridview',
      codeName: 'others_re_idea_viewpickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'others_re_idea_viewpickupviewpanel',
    },
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '其他实体关联需求多项数据选择视图_选择数据视图',
          refAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
        {
          parentDataJO: {
            srfparentdefname: 'section',
          },
          realTitle: '其他实体关联需求多项数据选择视图_选择数据视图',
          refAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
          name: 'EXPITEM:node_1',
          id: 'expitem:node_1',
        },
        {
          parentDataJO: {
            srfparentdefname: 'category_id',
          },
          realTitle: '其他实体关联需求多项数据选择视图_选择数据视图',
          refAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
          name: 'EXPITEM:node_2',
          id: 'expitem:node_2',
        },
        {
          parentDataJO: {
            srfparentdefname: 'category_id',
          },
          realTitle: '其他实体关联需求多项数据选择视图_选择数据视图',
          refAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
          name: 'EXPITEM:node_3',
          id: 'expitem:node_3',
        },
        {
          parentDataJO: {
            srfparentdefname: 'category_id',
          },
          realTitle: '其他实体关联需求多项数据选择视图_选择数据视图',
          refAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
          name: 'EXPITEM:node_4',
          id: 'expitem:node_4',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node_1',
              navigateParams: [
                {
                  key: 'n_owner_id_eq',
                  value: 'product',
                  id: 'n_owner_id_eq',
                },
                {
                  key: 'n_owner_subtype_eq',
                  value: 'idea',
                  rawValue: true,
                  id: 'n_owner_subtype_eq',
                },
              ],
              parentFilter: 'OWNER_ID',
              parentDETreeNodeId: 'node',
              parentValueLevel: 1,
              searchMode: 3,
              id: '产品 - 子产品',
            },
            {
              childDETreeNodeId: 'node_4',
              parentAppDEFieldId: 'pid',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PID',
                removeActionType: 1,
                recursiveRS: true,
                codeName: 'Category',
                dertype: 'DER1N',
                logicName: '父类别',
                minorCodeName: 'parent_categories',
                minorServiceCodeName: 'parent_categories',
                orderValue: 100,
                serviceCodeName: 'Category',
                name: 'DER1N_CATEGORY_CATEGORY_PID',
                id: 'base.category.der1n_category_category_pid',
              },
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '模块 - 子模块',
            },
            {
              childDETreeNodeId: 'node_4',
              parentAppDEFieldId: 'pid',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PID',
                removeActionType: 1,
                recursiveRS: true,
                codeName: 'Category',
                dertype: 'DER1N',
                logicName: '父类别',
                minorCodeName: 'parent_categories',
                minorServiceCodeName: 'parent_categories',
                orderValue: 100,
                serviceCodeName: 'Category',
                name: 'DER1N_CATEGORY_CATEGORY_PID',
                id: 'base.category.der1n_category_category_pid',
              },
              parentDETreeNodeId: 'node_4',
              parentValueLevel: 1,
              searchMode: 3,
              id: '子模块 - 子模块',
            },
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 产品',
            },
            {
              childDETreeNodeId: 'node_2',
              parentAppDEFieldId: 'section_id',
              parentDER1N: {
                masterRS: 32,
                pickupDEFName: 'SECTION_ID',
                codeName: 'Section',
                dertype: 'DER1N',
                logicName: '分组-类别',
                minorCodeName: 'section_categories',
                minorServiceCodeName: 'section_categories',
                orderValue: 100,
                serviceCodeName: 'Section',
                name: 'DER1N_CATEGORY_SECTION_SECTION_ID',
                id: 'base.category.der1n_category_section_section_id',
              },
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '子产品 - 模块',
            },
            {
              childDETreeNodeId: 'node_3',
              parentFilter: 'owner_id',
              parentDETreeNodeId: 'node',
              parentValueLevel: 1,
              searchMode: 3,
              id: '产品 - 无分组模块',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              idAppDEFieldId: 'id',
              appDEDataSetId: 'fetchdefault',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
              nodeType: 'node',
              appDataEntityId: 'plmweb.product',
              navigateParams: [
                {
                  key: 'target_type',
                  value: 'target_type',
                  id: 'target_type',
                },
                {
                  key: 'principal_type',
                  value: 'principal_type',
                  id: 'principal_type',
                },
                {
                  key: 'n_product_id_eq',
                  value: 'id',
                  id: 'n_product_id_eq',
                },
                {
                  key: 'principal_id',
                  value: 'principal_id',
                  id: 'principal_id',
                },
              ],
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '产品',
              id: 'node',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchdefault',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'section',
              navAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
              nodeType: 'node_1',
              appDataEntityId: 'plmweb.section',
              navigateParams: [
                {
                  key: 'n_section_id_eq',
                  value: 'section',
                  id: 'n_section_id_eq',
                },
              ],
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '子产品',
              id: 'node_1',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchproduct_idea_category',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'category_id',
              navAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
              nodeType: 'node_2',
              appDataEntityId: 'plmweb.category',
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '模块',
              id: 'node_2',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchno_section',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'category_id',
              navAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
              nodeType: 'node_3',
              appDataEntityId: 'plmweb.category',
              treeNodeType: 'DE',
              name: '无分组模块',
              id: 'node_3',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchdefault',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'category_id',
              navAppViewId: 'plmweb.ideaothers_re_view_pickupgridview',
              nodeType: 'node_4',
              appDataEntityId: 'plmweb.category',
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '子模块',
              id: 'node_4',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.idea',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.idea',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.idea',
            id: 'load',
          },
          dedataImportId: 'import_idea',
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.idea',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.idea',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'Others_relation_view_TreeView',
          controlStyle: 'GROUP_TREE',
          controlType: 'TREEVIEW',
          logicName: '其他实体关联需求多项数据选择视图_树视图',
          appDataEntityId: 'plmweb.idea',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'group_tree',
          modelId: 'CBB12631-7B29-46F3-8F57-C0582F2D9808',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.idea.others_relation_view_treeview',
        },
      ],
      codeName: 'others_re_idea_viewtreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '03a7982cfcb28e7c869593a4cccabd0a_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'others_re_idea_viewtreeexpbar',
    },
    {
      groupMode: 'NONE',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'field_text_dynamic',
                },
                viewFieldName: 'ID',
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'field_text_dynamic',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'Usr1225429007',
        controlType: 'PANEL',
        logicName: 'simplelist_列表项面板',
        appDataEntityId: 'plmweb.idea',
        controlParam: {},
        modelId: '8DE88201-738E-4C85-AA90-D64465DB6EE4',
        modelType: 'PSSYSVIEWPANEL',
        name: 'simplelist_itempanel',
        id: 'plmweb.idea.usr1225429007',
      },
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'title',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'assignee_id',
          dataType: 25,
          id: 'assignee_id',
        },
        {
          appDEFieldId: 'product_id',
          dataType: 25,
          id: 'product_id',
        },
        {
          appDEFieldId: 'category_id',
          dataType: 25,
          id: 'category_id',
        },
        {
          dataType: 25,
          id: 'srfmstag',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.idea',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'plmweb.idea',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.idea',
        id: 'load',
      },
      dedataImportId: 'import_idea',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.idea',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.idea',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Simplelist',
      controlStyle: 'SAMPLE_LIST',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'simplelist',
      },
      sysPFPluginId: 'sample_list',
      modelId: '93CEB4D6-E5B0-42EC-A076-5D9E2E0FD1AB',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'plmweb.idea.simplelist',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.IDEA.OTHERS_RELATION_IDEA_VIEW',
      },
      caption: '选择需求',
      codeName: 'others_re_idea_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.idea',
      controlParam: {},
      name: 'captionbar',
      id: 'others_re_idea_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutMode: 'Flex',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '树导航栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'treeexpbar',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'container6',
              },
              {
                panelItems: [
                  {
                    caption: '控件占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'pickupviewpanel',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container7',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container3',
          },
          {
            panelItems: [
              {
                rawItem: {
                  caption: '已选择：',
                  halign: 'LEFT',
                  renderMode: 'PARAGRAPH',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_LABEL',
                  id: 'static_label',
                },
                caption: '标签',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                  spacingRight: 'OUTERSMALL',
                },
                showCaption: true,
                id: 'static_label',
              },
              {
                caption: '列表',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'simplelist',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              width: 300,
              widthMode: 'FULL',
            },
            width: 300,
            id: 'container5',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        panelItems: [
          {
            actionType: 'UIACTION',
            buttonStyle: 'PRIMARY',
            buttonType: 'PANELBUTTON',
            uiactionId: 'ok',
            renderMode: 'BUTTON',
            tooltip: '确定',
            caption: '确定',
            itemStyle: 'PRIMARY',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_okaction',
          },
          {
            actionType: 'UIACTION',
            buttonStyle: 'INFO',
            buttonType: 'PANELBUTTON',
            uiactionId: 'cancel',
            renderMode: 'BUTTON',
            tooltip: '取消',
            caption: '取消',
            itemStyle: 'INFO',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_cancelaction',
          },
        ],
        layout: {
          dir: 'row-reverse',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_footer',
      },
    ],
    layoutPanel: true,
    codeName: 'ExMPickupView2Layout',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '多项数据选择视图(左右关系)布局面板(扩展)',
    appDataEntityId: 'plmweb.idea',
    controlParam: {},
    modelId: '0056d69f3ffb26d730f120a7916c169d',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'exmpickupview2layout',
  },
  title: '其他实体关联需求多项数据选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.IDEA.OTHERS_RELATION_IDEA_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '03a7982cfcb28e7c869593a4cccabd0a',
  modelType: 'PSAPPDEVIEW',
  name: 'ideaothers_re_idea_view',
  id: 'plmweb.ideaothers_re_idea_view',
};
