export default {
  mdctrlActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'pick_up_tree_view',
  deviewId: '319c93fce4e1404d102170d337d221b8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.IDEA.PICKUPTREEVIEW',
  },
  caption: '需求选择树视图',
  codeName: 'idea_pick_up_tree_view',
  appDataEntityId: 'plmweb.idea',
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'product',
      id: 'n_owner_id_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_subtype_eq',
      value: 'idea',
      id: 'n_owner_subtype_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_type_eq',
      value: 'product',
      id: 'n_owner_type_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        caption: '树',
        itemStyle: 'DEFAULT',
        itemType: 'CTRLPOS',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'tree',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'PickupTreeView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'section_id',
            parentDER1N: {
              masterRS: 32,
              pickupDEFName: 'SECTION_ID',
              removeActionType: 2,
              codeName: 'section',
              dertype: 'DER1N',
              logicName: '分组-类别',
              minorCodeName: 'section_categories',
              minorServiceCodeName: 'section_categories',
              orderValue: 100,
              serviceCodeName: 'section',
              name: 'DER1N_CATEGORY_SECTION_SECTION_ID',
              id: 'base.category.der1n_category_section_section_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '子产品 - 模块',
          },
          {
            childDETreeNodeId: 'node_4',
            parentAppDEFieldId: 'pid',
            parentDER1N: {
              masterRS: 48,
              pickupDEFName: 'PID',
              removeActionType: 2,
              recursiveRS: true,
              codeName: 'category',
              dertype: 'DER1N',
              logicName: '父类别',
              minorCodeName: 'parent_categories',
              minorServiceCodeName: 'parent_categories',
              orderValue: 100,
              serviceCodeName: 'category',
              name: 'DER1N_CATEGORY_CATEGORY_PID',
              id: 'base.category.der1n_category_category_pid',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '模块 - 子模块',
          },
          {
            childDETreeNodeId: 'node_4',
            parentAppDEFieldId: 'pid',
            parentDER1N: {
              masterRS: 48,
              pickupDEFName: 'PID',
              removeActionType: 2,
              recursiveRS: true,
              codeName: 'category',
              dertype: 'DER1N',
              logicName: '父类别',
              minorCodeName: 'parent_categories',
              minorServiceCodeName: 'parent_categories',
              orderValue: 100,
              serviceCodeName: 'category',
              name: 'DER1N_CATEGORY_CATEGORY_PID',
              id: 'base.category.der1n_category_category_pid',
            },
            parentDETreeNodeId: 'node_4',
            parentValueLevel: 1,
            searchMode: 3,
            id: '子模块 - 子模块',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            id: '默认根节点 - 子产品',
          },
          {
            childDETreeNodeId: 'node_3',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            id: '默认根节点 - 无分组',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'is_leaf',
            appDEDataSetId: 'fetch_default',
            sortDir: 'ASC',
            sortAppDEFieldId: 'sequence',
            textAppDEFieldId: 'name',
            nodeType: 'node_1',
            appDataEntityId: 'plmweb.section',
            sysImage: {
              cssClass: 'fa fa-cube',
              glyph: 'xf1b2@FontAwesome',
            },
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            disableSelect: true,
            expanded: true,
            name: '子产品',
            id: 'node_1',
          },
          {
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'is_leaf',
            appDEDataSetId: 'fetch_product_idea_category',
            sortDir: 'ASC',
            sortAppDEFieldId: 'sequence',
            textAppDEFieldId: 'name',
            nodeType: 'node_2',
            appDataEntityId: 'plmweb.category',
            sysImage: {
              cssClass: 'fa fa-reorder',
              glyph: 'xf0c9@FontAwesome',
            },
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            expanded: true,
            name: '模块',
            id: 'node_2',
          },
          {
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'is_leaf',
            appDEDataSetId: 'fetch_no_section',
            sortDir: 'ASC',
            sortAppDEFieldId: 'sequence',
            textAppDEFieldId: 'name',
            nodeType: 'node_3',
            appDataEntityId: 'plmweb.category',
            sysImage: {
              cssClass: 'fa fa-reorder',
              glyph: 'xf0c9@FontAwesome',
            },
            treeNodeType: 'DE',
            name: '无分组',
            id: 'node_3',
          },
          {
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'is_leaf',
            appDEDataSetId: 'fetch_default',
            sortDir: 'ASC',
            sortAppDEFieldId: 'sequence',
            textAppDEFieldId: 'name',
            nodeType: 'node_4',
            appDataEntityId: 'plmweb.category',
            sysImage: {
              cssClass: 'fa fa-reorder',
              glyph: 'xf0c9@FontAwesome',
            },
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            expanded: true,
            name: '子模块',
            id: 'node_4',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.idea',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'plmweb.idea',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.idea',
          id: 'load',
        },
        dedataImportId: 'import_idea',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.idea',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.idea',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'pickup_tree',
        controlType: 'TREEVIEW',
        logicName: '需求选择树',
        appDataEntityId: 'plmweb.idea',
        controlParam: {
          id: 'tree',
        },
        modelId: '9c73f5ff769b05085c498bb8cbec5ed6',
        modelType: 'PSDETREEVIEW',
        name: 'tree',
        id: 'plmweb.idea.pickup_tree',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.idea',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'PAGE.CAPTION.IDEA.PICKUPTREEVIEW',
        },
        caption: '需求选择树视图',
        codeName: 'pick_up_tree_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.idea',
        controlParam: {},
        name: 'captionbar',
        id: 'pick_up_tree_view_captionbar',
      },
    ],
    codeName: 'pickup_tree_view',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '需求选择树视图布局面板',
    appDataEntityId: 'plmweb.idea',
    controlParam: {},
    modelId: '822c2805aede9da11dd124d281e63cad',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'pickup_tree_view',
  },
  title: '需求选择树视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.IDEA.PICKUPTREEVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPTREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '3d03b4ef864a70dec42ad2e0cd090bde',
  modelType: 'PSAPPDEVIEW',
  name: 'ideapick_up_tree_view',
  id: 'plmweb.idea_pick_up_tree_view',
};
