export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'system_report_grid_view',
  deviewId: '17a44cbc9d5567a31747167711c8454b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.INSIGHT_REPORT',
  },
  caption: '系统预置报表',
  codeName: 'insight_report_system_report_grid_view',
  appDataEntityId: 'plmweb.insight_report',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.insight_report_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.insight_report_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.insight_report_bi_report_content_panel_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.insight_report_bi_report_content_panel_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: 'BI报表呈现态面板视图',
      refAppViewId: 'plmweb.insight_report_bi_report_content_panel_view',
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      realTitle: 'BI报表呈现态面板视图',
      refAppViewId: 'plmweb.insight_report_bi_report_content_panel_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '效能报表编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.INSIGHT_REPORT.EDITVIEW',
      },
      refAppViewId: 'plmweb.insight_report_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'FRONT',
          dataItemName: 'chart_type',
          excelCaption: '图表类型',
          appCodeListId: 'plmweb.insight__bi_chart_type',
          appDEFieldId: 'chart_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '图表类型',
          codeName: 'chart_type',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'chart_type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '报表名称',
          appDEFieldId: 'name',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '设计',
                detailType: 'DEUIACTION',
                uiactionId: 'open_report_design_view@insight_report',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-wrench',
                  glyph: 'xf0ad@FontAwesome',
                },
                id: 'u9d57385',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'delete_report@insight_report',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                id: 'uefea2ee',
              },
            ],
            appDataEntityId: 'plmweb.insight_report',
            uniqueTag: 'insight_report__Usr0710881256',
            name: '全局报表行为组',
            id: 'usr0710881256',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '报表名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'group',
          excelCaption: '数据集',
          appCodeListId: 'plmweb.insight__report_group_bi',
          appDEFieldId: 'group',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '数据集',
          codeName: 'group',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'group',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'categories',
          excelCaption: '类别',
          appCodeListId: 'plmweb.prodmgmt__category',
          appDEFieldId: 'categories',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类别',
          codeName: 'categories_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'categories_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'desc',
          excelCaption: '描述',
          appDEFieldId: 'desc',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '描述',
          codeName: 'desc',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          hideDefault: true,
          id: 'desc',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'chart_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'chart_type',
        },
        {
          appDEFieldId: 'name',
          scriptCode:
            'data.is_system === 1 ? data.name + \'<span style="border-radius: 18px;background-color: #f5f5f5;color: #666;height: 24px;line-height: 24px;padding-left: 12px;padding-right: 12px;font-size: .75rem;font-weight: 400;display: inline-flex;align-items: center;border: 1px solid transparent;margin-left: .5rem !important;">系统</span>\':data.name',
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'group',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'group',
        },
        {
          appDEFieldId: 'categories',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'categories',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'desc',
          valueType: 'SIMPLE',
          dataType: 21,
          id: 'desc',
        },
        {
          appDEFieldId: 'is_system',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'is_system',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'view_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'view_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_is_system',
        appDataEntityId: 'plmweb.insight_report',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.insight_report',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'all_grid',
      controlType: 'GRID',
      logicName: '全局报表表格',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {
        id: 'grid',
      },
      modelId: 'F0E6E318-FA00-4C61-B532-E9CD6AF85699',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.insight_report.all_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr05200683_search_form',
      controlType: 'SEARCHFORM',
      logicName: '全部报表表格视图_搜索表单',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {
        id: 'searchform',
      },
      modelId: '5466781D-9298-4D2F-A6D8-C543C32815F3',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.insight_report.usr05200683_search_form',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'sync_model@insight_report',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          caption: '同步模型',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-retweet',
            glyph: 'xf079@FontAwesome',
          },
          tooltip: '同步模型',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'system_report_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '系统报表表格工具栏',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'A858FE20-5FF3-464E-A8D3-30B3D0EBA57A',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'system_report_grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.INSIGHT_REPORT',
      },
      caption: '系统预置报表',
      codeName: 'system_report_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {},
      name: 'captionbar',
      id: 'system_report_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.insight_report',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '系统预置报表表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '9fd56843d48b79ecedc15f66599a895b',
  modelType: 'PSAPPDEVIEW',
  name: 'insight_reportsystem_report_grid_view',
  id: 'plmweb.insight_report_system_report_grid_view',
};
