export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'scrum_tree_exp_view',
  deviewId: 'cbb48c522efc65b7d12e7cbf1aad3902',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.INSIGHT',
  },
  caption: 'Scrum报表',
  codeName: 'insightscrum_tree_exp_view',
  appDataEntityId: 'plmweb.insight',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      title: '统计报表',
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '全部报表',
          refAppViewId: 'plmweb.insightscrum_grid_view',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
        {
          realTitle: '全部报表',
          refAppViewId: 'plmweb.insightscrum_grid_view',
          name: 'EXPITEM:node_1',
          id: 'expitem:node_1',
        },
        {
          realTitle: '全部报表',
          refAppViewId: 'plmweb.insightscrum_grid_view',
          name: 'EXPITEM:node_2',
          id: 'expitem:node_2',
        },
        {
          realTitle: '全部报表',
          refAppViewId: 'plmweb.insightscrum_grid_view',
          name: 'EXPITEM:node_3',
          id: 'expitem:node_3',
        },
        {
          realTitle: '全部报表',
          refAppViewId: 'plmweb.insightscrum_grid_view',
          name: 'EXPITEM:node_4',
          id: 'expitem:node_4',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 全部报表',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 项目报表',
            },
            {
              childDETreeNodeId: 'node_2',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 迭代报表',
            },
            {
              childDETreeNodeId: 'node_3',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 需求报表',
            },
            {
              childDETreeNodeId: 'node_4',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 缺陷报表',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '全部报表',
              navAppViewId: 'plmweb.insightscrum_grid_view',
              nodeType: 'node',
              sysImage: {
                cssClass: 'fa fa-th-large',
                glyph: 'xf009@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '全部报表',
              id: 'node',
            },
            {
              text: '项目报表',
              navAppViewId: 'plmweb.insightscrum_grid_view',
              nodeType: 'node_1',
              navigateParams: [
                {
                  key: 'n_group_eq',
                  value: 'project',
                  rawValue: true,
                  id: 'n_group_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-cube',
                glyph: 'xf1b2@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '项目报表',
              id: 'node_1',
            },
            {
              text: '迭代报表',
              navAppViewId: 'plmweb.insightscrum_grid_view',
              nodeType: 'node_2',
              navigateParams: [
                {
                  key: 'n_group_eq',
                  value: 'sprint',
                  rawValue: true,
                  id: 'n_group_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-life-saver',
                glyph: 'xf1cd@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '迭代报表',
              id: 'node_2',
            },
            {
              text: '需求报表',
              navAppViewId: 'plmweb.insightscrum_grid_view',
              nodeType: 'node_3',
              navigateParams: [
                {
                  key: 'n_group_eq',
                  value: 'backlog',
                  rawValue: true,
                  id: 'n_group_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-puzzle-piece',
                glyph: 'xf12e@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '需求报表',
              id: 'node_3',
            },
            {
              text: '缺陷报表',
              navAppViewId: 'plmweb.insightscrum_grid_view',
              nodeType: 'node_4',
              navigateParams: [
                {
                  key: 'n_group_eq',
                  value: 'defect',
                  rawValue: true,
                  id: 'n_group_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-bug',
                glyph: 'xf188@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '缺陷报表',
              id: 'node_4',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.insight',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.insight',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.insight',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.insight',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.insight',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'Scrum_tree_exp_view_TreeView',
          controlStyle: 'GROUP_TREE',
          controlType: 'TREEVIEW',
          logicName: 'Scrum报表树导航视图_树视图',
          appDataEntityId: 'plmweb.insight',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'group_tree',
          modelId: 'b9eb9d6ccd91caf73aed1ee5f1eb8a89',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.insight.scrum_tree_exp_view_treeview',
        },
      ],
      codeName: 'scrum_tree_exp_viewtreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.insight',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '68d97b8183c11e25ab715f2aebc57315_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'scrum_tree_exp_viewtreeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.insight',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.INSIGHT',
      },
      caption: 'Scrum报表',
      codeName: 'scrum_tree_exp_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.insight',
      controlParam: {},
      name: 'captionbar',
      id: 'scrum_tree_exp_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.insight',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: 'Scrum报表树导航',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '68d97b8183c11e25ab715f2aebc57315',
  modelType: 'PSAPPDEVIEW',
  name: 'insightscrum_tree_exp_view',
  id: 'plmweb.insightscrum_tree_exp_view',
};
