export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'assigned_grid_view',
  deviewId: 'ab83e54b8626ee8c7c6b09409cd236b8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.INSIGHT_MEMBER.ASSIGNED_GRID_VIEW',
  },
  caption: '视图成员',
  codeName: 'insight_member_assigned_grid_view',
  appDataEntityId: 'plmweb.insight_member',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onCreated',
      logicTrigger: 'VIEWEVENT',
      logicType: 'APPDEUILOGIC',
      appDEUILogicId: 'create_default_temp_members',
      appDataEntityId: 'plmweb.insight_member',
      builtinLogic: true,
      name: 'LOGIC',
      id: 'logic',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        batchAddAppViews: [
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.insight_member_edit_view',
        },
        enableBatchAdd: true,
        appDataEntityId: 'plmweb.insight_member',
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.insight_member_edit_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.insight_member_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.insight_member_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewParams: [
    {
      key: 'PROPERTYMAP',
      value: 'display_name:name',
      name: 'PROPERTYMAP',
      id: 'propertymap',
    },
  ],
  appViewRefs: [
    {
      realTitle: '效能成员数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.INSIGHT_MEMBER.REDIRECTVIEW',
      },
      refAppViewId: 'plmweb.insight_member_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '效能成员编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.INSIGHT_MEMBER.EDITVIEW',
      },
      refAppViewId: 'plmweb.insight_member_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      name: 'MPICKUPVIEW:INSIGHT_VIEW',
      id: 'mpickupview:insight_view',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '选择成员',
      refAppViewId: 'plmweb.user_choose_mpick_up_view',
      name: 'MPICKUPVIEW:USER',
      id: 'mpickupview:user',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '添加成员',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '添加成员',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      toolbarStyle: 'USER',
      xdataControlName: 'grid',
      codeName: 'assigned_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '效能成员绑定_工具栏',
      appDataEntityId: 'plmweb.insight_member',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c29986c16af737419f2b2dedd82355d9',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'assigned_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '姓名',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEGRID.INSIGHT_MEMBER.ASSIGNED_GRID_VIEW_GRID.DEFGRIDCOLUMN.NAME',
          },
          caption: '姓名',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                detailType: 'DEUIACTION',
                uiactionId: 'remove_member@insight_member',
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'u806005d',
              },
            ],
            appDataEntityId: 'plmweb.insight_member',
            uniqueTag: 'insight_member__Usr0702314164',
            name: '效能成员配置',
            id: 'usr0702314164',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'owner_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'owner_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.insight_member',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.insight_member',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'assigned_grid_view_grid',
      controlType: 'GRID',
      logicName: '效能成员绑定_表格',
      appDataEntityId: 'plmweb.insight_member',
      controlParam: {
        id: 'grid',
      },
      modelId: 'd21f6ab8ebbbcff6b27dfe1d3ef90a49',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.insight_member.assigned_grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.INSIGHT_MEMBER.ASSIGNED_GRID_VIEW_SEARCHFORM.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'assigned_grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '效能成员绑定_搜索表单',
      appDataEntityId: 'plmweb.insight_member',
      controlParam: {
        id: 'searchform',
      },
      modelId: '0db62d50970a4ba8361707d04c298759',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.insight_member.assigned_grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.insight_member',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.INSIGHT_MEMBER.ASSIGNED_GRID_VIEW',
      },
      caption: '视图成员',
      codeName: 'assigned_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.insight_member',
      controlParam: {},
      name: 'captionbar',
      id: 'assigned_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.insight_member',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '视图成员',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.INSIGHT_MEMBER.ASSIGNED_GRID_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7ec11f5f26557d343a410f77a9c99b94',
  modelType: 'PSAPPDEVIEW',
  name: 'insight_memberassigned_grid_view',
  id: 'plmweb.insight_member_assigned_grid_view',
};
