export default {
  deviewCodeName: 'BIReportContentPanelView',
  deviewId: '2DC1C2F3-B7AA-4C96-8EC2-701E4DB5C3CA',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.INSIGHT_REPORT',
  },
  caption: 'BI报表呈现态面板视图',
  codeName: 'insight_report_bi_report_content_panel_view',
  appDataEntityId: 'plmweb.insight_report',
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'open_bi_report_panel_view@insight_report',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '编辑',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'deuiaction1',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'context.srfreadonly != true',
              triggerType: 'ITEMVISIBLE',
              id: 'deuiaction1',
            },
          ],
          tooltip: '编辑',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          groupExtractMode: 'ITEM',
          uiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '导出表格',
                detailType: 'DEUIACTION',
                uiactionId: 'export_table@insight_report',
                showCaption: true,
                showIcon: true,
                id: 'uf7b1940',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '导出为PDF',
                detailType: 'DEUIACTION',
                uiactionId: 'export_pdf@insight_report',
                showCaption: true,
                showIcon: true,
                id: 'ue60ea90',
              },
            ],
            appDataEntityId: 'plmweb.insight_report',
            uniqueTag: 'insight_report__Usr1121549416',
            name: '导出界面行为组',
            id: 'usr1121549416',
          },
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-list-ul',
            glyph: 'xf0ca@FontAwesome',
          },
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      codeName: 'bi_report_content_panel_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: 'BI报表呈现态工具栏',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '31666C3C-3F1D-46BC-819E-070116F8E3E1',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'bi_report_content_panel_view_toolbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.INSIGHT_REPORT',
      },
      caption: 'BI报表呈现态面板视图',
      codeName: 'bi_report_content_panel_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.insight_report',
      controlParam: {},
      name: 'captionbar',
      id: 'bi_report_content_panel_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'export-canvas-style',
  },
  viewLayoutPanel: {
    layoutMode: 'Flex',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'captionbar',
                      },
                    ],
                    layout: {
                      align: 'center',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                    },
                    id: 'view_captionbar',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingLeft: 'INNERSMALL',
                },
                id: 'view_header_left',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingRight: 'INNERSMALL',
                },
                id: 'view_toolbar',
              },
            ],
            predefinedType: 'VIEWHEADER',
            layout: {
              align: 'space-between',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_header',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'field_text_dynamic',
                },
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'bi_report_panel_content',
                id: 'field_text_dynamic',
              },
            ],
            predefinedType: 'VIEWCONTENT',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    codeName: 'usr0705249058',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'BI报表呈现态',
    appDataEntityId: 'plmweb.insight_report',
    controlParam: {},
    modelId: '9AB75D4B-7BF1-4F9B-919B-898F6C95525B',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0705249058',
  },
  title: 'BI报表呈现态面板视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPANELVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4efb5f2e71bd2c603764f86e04e8c69b',
  modelType: 'PSAPPDEVIEW',
  name: 'insight_reportBIReportContentPanelView',
  id: 'plmweb.insight_report_bi_report_content_panel_view',
};
