export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'show_edit_view',
  deviewId: 'ff98504f841ee9583d4a501ff00c3e05',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.INSIGHT_VIEW',
  },
  caption: '视图信息',
  codeName: 'insight_view_show_edit_view',
  height: 600,
  appDataEntityId: 'plmweb.insight_view',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'show_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '效能度量信息展示视图_工具栏',
      appDataEntityId: 'plmweb.insight_view',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'baafb83a82d3927438d35325a65eb68a',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'show_edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.insight_view',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.insight_view',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.insight_view',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.insight_view',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.insight_view',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.insight_view',
        id: 'update',
      },
      infoFormMode: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'scope_type',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'plmweb.group',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'scope_id',
                    editorParams: {
                      AC: 'TRUE',
                      fillMap:
                        '{"user":"user","user_group":"user_group","organization":"organization"}',
                      enablePerson: 'false',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorStyle: 'TEAM_PICKER',
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'scope_id',
                      },
                    ],
                    sysPFPluginId: 'team_picker',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'scope_type',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.SCOPE_TYPE',
                  },
                  caption: '所属',
                  codeName: 'scope_type',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'scope_type',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.NAME',
                  },
                  caption: '视图名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'identifier',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'identifier',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.INSIGHT_VIEW.IDENTIFIER',
                  },
                  caption: '视图标识',
                  codeName: 'identifier',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'identifier',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'visibility',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'plmweb.visibility',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'visibility',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.VISIBILITY',
                  },
                  caption: '可见范围',
                  codeName: 'visibility',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'visibility',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.DESCRIPTION',
                  },
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
              ],
              caption: '基本信息',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'scope_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'scope_id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.SCOPE_ID',
              },
              caption: '所属对象',
              codeName: 'scope_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'scope_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'show_edit_view_form',
      controlType: 'FORM',
      logicName: '效能度量信息展示视图_表单',
      appDataEntityId: 'plmweb.insight_view',
      controlParam: {
        id: 'form',
      },
      modelId: 'e15ac867aefe687e9992bedf0dfcc18a',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.insight_view.show_edit_view_form',
    },
    {
      codeName: 'show_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.insight_view',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'show_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.INSIGHT_VIEW',
      },
      caption: '视图信息',
      codeName: 'show_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.insight_view',
      controlParam: {},
      name: 'captionbar',
      id: 'show_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.insight_view',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '效能度量信息展示视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 800,
  enableDP: true,
  showCaptionBar: true,
  modelId: '5845bacc457c0f9ec0c3499c4ac26f79',
  modelType: 'PSAPPDEVIEW',
  name: 'insight_viewshow_edit_view',
  id: 'plmweb.insight_view_show_edit_view',
};
