export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'tree_exp_view_config',
  deviewId: 'a431c7d3ee1e9656164fc255c27b21df',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.LIBRARY',
  },
  caption: '测试库配置',
  codeName: 'librarytree_exp_view_config',
  appDataEntityId: 'plmweb.library',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '测试库管理',
          refAppViewId: 'plmweb.librarytab_exp_view_config',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '通用 - 测试库管理',
            },
            {
              childDETreeNodeId: 'node_4',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '配置 - 测试用例配置',
            },
            {
              childDETreeNodeId: 'node_6',
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '权限 - 权限配置',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 通用',
            },
            {
              childDETreeNodeId: 'node_5',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '配置 - 测试库配置',
            },
            {
              childDETreeNodeId: 'node_2',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 配置',
            },
            {
              childDETreeNodeId: 'node_3',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 权限',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '测试库管理',
              navAppViewId: 'plmweb.librarytab_exp_view_config',
              nodeType: 'node',
              treeNodeType: 'STATIC',
              name: '测试库管理',
              id: 'node',
            },
            {
              text: '通用',
              nodeType: 'node_1',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '通用',
              id: 'node_1',
            },
            {
              text: '配置',
              nodeType: 'node_2',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '配置',
              id: 'node_2',
            },
            {
              text: '权限',
              nodeType: 'node_3',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '权限',
              id: 'node_3',
            },
            {
              text: '测试用例配置',
              nodeType: 'node_4',
              treeNodeType: 'STATIC',
              disableSelect: true,
              name: '测试用例配置',
              id: 'node_4',
            },
            {
              text: '测试库配置',
              nodeType: 'node_5',
              treeNodeType: 'STATIC',
              disableSelect: true,
              name: '测试库配置',
              id: 'node_5',
            },
            {
              text: '权限配置',
              nodeType: 'node_6',
              treeNodeType: 'STATIC',
              disableSelect: true,
              name: '权限配置',
              id: 'node_6',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.library',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.library',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.library',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.library',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.library',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'Tree_exp_view_config_TreeView',
          controlStyle: 'LIST_TREE',
          controlType: 'TREEVIEW',
          logicName: '测试库配置中心视图_树视图',
          appDataEntityId: 'plmweb.library',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'list_tree',
          modelId: '76ed6ac985c38b506b3bcd563493bae4',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.library.tree_exp_view_config_treeview',
        },
      ],
      codeName: 'tree_exp_view_configtreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '17099fe42d3b6d835864bdabb88c9937_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_exp_view_configtreeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.LIBRARY',
      },
      caption: '测试库配置',
      codeName: 'tree_exp_view_configcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_exp_view_configcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.library',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试库配置',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '17099fe42d3b6d835864bdabb88c9937',
  modelType: 'PSAPPDEVIEW',
  name: 'librarytree_exp_view_config',
  id: 'plmweb.librarytree_exp_view_config',
};
