export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'config_tab_exp_view',
  deviewId: '0059c280c6bd1613683c2eb6aa63bdd8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.LIBRARY',
  },
  caption: '测试库管理',
  codeName: 'library_config_tab_exp_view',
  appDataEntityId: 'plmweb.library',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      tabExpPageIds: ['in_progress', 'archived', 'deleted'],
      tabLayout: 'TOP',
      uniqueTag: 'library_config_tab_exp_view__tabexppanel',
      appViewRefs: [
        {
          realTitle: '测试库管理',
          refAppViewId: 'plmweb.library_in_progress_grid_view',
          name: 'EXPITEM:in_progress',
          id: 'expitem:in_progress',
        },
        {
          realTitle: '测试库管理',
          refAppViewId: 'plmweb.library_archived_grid_view',
          name: 'EXPITEM:archived',
          id: 'expitem:archived',
        },
        {
          realTitle: '测试库管理',
          refAppViewId: 'plmweb.library_deleted_grid_view',
          name: 'EXPITEM:deleted',
          id: 'expitem:deleted',
        },
      ],
      controls: [
        {
          caption: '进行中',
          embeddedAppDEViewId: 'plmweb.library_in_progress_grid_view',
          codeName: 'config_tab_exp_view_in_progress',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'plmweb.library',
          controlParam: {
            id: 'in_progress',
          },
          modelId: '4222cea9219c3327e6244ed257697dee_in_progress',
          modelType: 'PSVIEWPANEL',
          name: 'in_progress',
          id: 'config_tab_exp_view_in_progress',
        },
        {
          caption: '已归档',
          embeddedAppDEViewId: 'plmweb.library_archived_grid_view',
          codeName: 'config_tab_exp_view_archived',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'plmweb.library',
          controlParam: {
            id: 'archived',
          },
          modelId: '4222cea9219c3327e6244ed257697dee_archived',
          modelType: 'PSVIEWPANEL',
          name: 'archived',
          id: 'config_tab_exp_view_archived',
        },
        {
          caption: '已删除',
          embeddedAppDEViewId: 'plmweb.library_deleted_grid_view',
          codeName: 'config_tab_exp_view_deleted',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'plmweb.library',
          controlParam: {
            id: 'deleted',
          },
          modelId: '4222cea9219c3327e6244ed257697dee_deleted',
          modelType: 'PSVIEWPANEL',
          name: 'deleted',
          id: 'config_tab_exp_view_deleted',
        },
      ],
      codeName: 'config_tab_exp_view_tabexppanel',
      controlType: 'TABEXPPANEL',
      appDataEntityId: 'plmweb.library',
      controlParam: {},
      modelId: '4222cea9219c3327e6244ed257697dee_tabexppanel',
      modelType: 'PSTABEXPPANEL',
      name: 'tabexppanel',
      id: 'config_tab_exp_view_tabexppanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.LIBRARY',
      },
      caption: '测试库管理',
      codeName: 'config_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {},
      name: 'captionbar',
      id: 'config_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.library',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试库管理',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4222cea9219c3327e6244ed257697dee',
  modelType: 'PSAPPDEVIEW',
  name: 'libraryconfig_tab_exp_view',
  id: 'plmweb.library_config_tab_exp_view',
};
