export default {
  funcViewMode: 'MPICKUPVIEW',
  openMode: 'POPUPMODAL',
  deviewCodeName: 'mpick_up_view',
  deviewId: '1d6d4775ce5906329ad327f206cc5c96',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PORTFOLIO',
  },
  caption: '文件夹',
  codeName: 'portfolio_mpick_up_view',
  appDataEntityId: 'plmweb.portfolio',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'plmweb.portfolio_pick_up_grid_view',
      codeName: 'mpick_up_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'mpick_up_view_pickupviewpanel',
    },
    {
      groupMode: 'NONE',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'field_text_dynamic',
                },
                viewFieldName: 'NAME',
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'field_text_dynamic',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0301834728',
        controlType: 'PANEL',
        logicName: 'simplelist_列表项面板',
        appDataEntityId: 'plmweb.portfolio',
        controlParam: {},
        modelId: '9196918658559f4732254f42da8bd57d',
        modelType: 'PSSYSVIEWPANEL',
        name: 'simplelist_itempanel',
        id: 'plmweb.portfolio.usr0301834728',
      },
      delistDataItems: [
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.portfolio',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.portfolio',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.portfolio',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.portfolio',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.portfolio',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {
        id: 'simplelist',
      },
      modelId: 'cae998a97dcb7f3701c7e4b1b5fee314',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'plmweb.portfolio.simplelist',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PORTFOLIO',
      },
      caption: '文件夹',
      codeName: 'mpick_up_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {},
      name: 'captionbar',
      id: 'mpick_up_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.portfolio',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '文件夹数据多项选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PORTFOLIO.MPICKUPVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c2f4b208dd819171bc41d2bacc432995',
  modelType: 'PSAPPDEVIEW',
  name: 'portfolioMPickupView',
  id: 'plmweb.portfolio_mpick_up_view',
};
