export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'project_set_advanced_view',
  deviewId: 'c7d1885f6bc3a44806eea8170db236c0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PORTFOLIO',
  },
  caption: '高级设置',
  codeName: 'portfolio_project_set_advanced_view',
  appDataEntityId: 'plmweb.portfolio',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.portfolio',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.portfolio',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.portfolio',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.portfolio',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.portfolio',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.portfolio',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  rawItem: {
                    caption:
                      '如果此项目集已经不再需要了，你可以删除它。删除后如果想找回该项目集，可以通过配置中心由管理员进行恢复。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
                {
                  actionType: 'UIACTION',
                  uiactionId: 'delete_project_set@portfolio',
                  tooltip: '删除项目集',
                  uiactionTarget: 'SINGLEKEY',
                  caption: '删除项目集',
                  codeName: 'button1',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    colLG: 2,
                    colMD: 2,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'button1',
                },
              ],
              caption: '删除项目集',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'project_set_advanced_form',
      controlType: 'FORM',
      logicName: '项目集高级设置_表单',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {
        id: 'form',
      },
      modelId: '153ab81f1b9fc431b0747d52957e63d9',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.portfolio.project_set_advanced_form',
    },
    {
      codeName: 'project_set_advanced_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'project_set_advanced_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PORTFOLIO',
      },
      caption: '高级设置',
      codeName: 'project_set_advanced_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.portfolio',
      controlParam: {},
      name: 'captionbar',
      id: 'project_set_advanced_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.portfolio',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '项目集高级设置编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'fdabd1b707400a8d16cacef7006e4c5f',
  modelType: 'PSAPPDEVIEW',
  name: 'portfolioproject_set_advanced_view',
  id: 'plmweb.portfolio_project_set_advanced_view',
};
