export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'recover_tab_exp_view',
  deviewId: '880A35D1-303E-43F7-BF4A-6339E100CBAB',
  accUserMode: 2,
  caption: '产品',
  codeName: 'productrecover_tab_exp_view',
  appDataEntityId: 'plmweb.product',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '需求',
          appViewId: 'plmweb.idearecycle_bin_grid_view',
          id: 'idea',
        },
        {
          caption: '工单',
          appViewId: 'plmweb.ticketrecover_grid_view',
          id: 'ticket',
        },
      ],
      editItemCaption: '产品',
      uniqueTag: 'productrecover_tab_exp_view__tabexppanel',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'DataRelation',
      controlType: 'DRTAB',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'AB21F39D-E1D0-4C19-B0AB-654B58B70ECE',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'datarelation',
    },
    {
      caption: '产品',
      codeName: 'recover_tab_exp_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {},
      name: 'captionbar',
      id: 'recover_tab_exp_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.product',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '产品回收站',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2d5e5936637aaafe025f11a19106506b',
  modelType: 'PSAPPDEVIEW',
  name: 'productrecover_tab_exp_view',
  id: 'plmweb.productrecover_tab_exp_view',
};
