export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'base_information_edit_view',
  deviewId: 'a7f79f00c06747e532a9d3ee8de1dba2',
  accUserMode: 2,
  caption: '基本信息',
  codeName: 'product_base_information_edit_view',
  appDataEntityId: 'plmweb.product',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.product',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.product',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.product',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.product',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.product',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.product',
        id: 'update',
      },
      deformItemVRs: [
        {
          checkMode: 1,
          deformItemName: 'identifier',
          sysValueRule: {
            codeName: 'UsrValueRule0312488358',
            regExCode: '^[A-Z0-9]{1,15}$',
            ruleInfo: '请填写大写字母和数字',
            ruleType: 'REGEX',
            name: '大写字母和数字',
            id: 'usrvaluerule0312488358',
          },
          valueRuleType: 'SYSVALUERULE',
          id: '表单项值规则',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'scope_type',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'plmweb.group',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'scope_id',
                    editorParams: {
                      AC: 'TRUE',
                      fillMap:
                        '{"user":"user","user_group":"user_group","organization":"organization"}',
                      enablePerson: 'false',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorStyle: 'TEAM_PICKER',
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'scope_id',
                      },
                    ],
                    sysPFPluginId: 'team_picker',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'scope_type',
                  },
                  allowEmpty: true,
                  caption: '所属',
                  codeName: 'scope_type',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'scope_type',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'scope_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'scope_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '所属对象',
                  codeName: 'scope_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'scope_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.NAME',
                  },
                  caption: '产品名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'identifier',
                  editor: {
                    maxLength: 15,
                    sysValueRule: {
                      codeName: 'UsrValueRule0312488358',
                      regExCode: '^[A-Z0-9]{1,15}$',
                      ruleInfo: '请填写大写字母和数字',
                      ruleType: 'REGEX',
                      name: '大写字母和数字',
                      id: 'plmweb.usrvaluerule0312488358',
                    },
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'identifier',
                  },
                  caption: '产品标识',
                  codeName: 'identifier',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'identifier',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'visibility',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'plmweb.visibility',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'visibility',
                  },
                  needCodeListConfig: true,
                  caption: '可见范围',
                  codeName: 'visibility',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'visibility',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  itemHeight: 220,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    maxLength: 2000,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
                {
                  actionType: 'UIACTION',
                  uiactionId: 'save',
                  tooltip: '确定',
                  capLanguageRes: {
                    lanResTag: 'TBB.TEXT.*.SAVE',
                  },
                  caption: '确定',
                  codeName: 'button1',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  sysImage: {
                    cssClass: 'fa fa-save',
                    glyph: 'xf0c7@FontAwesome',
                  },
                  showCaption: true,
                  id: 'button1',
                },
              ],
              caption: '基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 12,
                colMD: 12,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      enableItemPrivilege: true,
      showBusyIndicator: true,
      codeName: 'base_information',
      controlType: 'FORM',
      logicName: '基本信息',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        id: 'form',
      },
      modelId: 'cf477a34db04c9886708130ab5e7c736',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.product.base_information',
    },
    {
      codeName: 'base_information_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'base_information_edit_view_datainfobar',
    },
    {
      caption: '基本信息',
      codeName: 'base_information_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {},
      name: 'captionbar',
      id: 'base_information_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.product',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '基本信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '67f5a45686b6bd31172241a3994187ac',
  modelType: 'PSAPPDEVIEW',
  name: 'productbase_information_edit_view',
  id: 'plmweb.product_base_information_edit_view',
};
