export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'setting_view',
  deviewId: '86caa8872505d8ea22f547253952908d',
  accUserMode: 2,
  caption: '产品配置',
  codeName: 'product_setting_view',
  appDataEntityId: 'plmweb.product',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView2',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.product',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.product',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.product',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.product',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.product',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.product',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      enableItemPrivilege: true,
      showBusyIndicator: true,
      codeName: 'index_view_form',
      controlType: 'FORM',
      logicName: '产品首页视图_表单',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        id: 'form',
      },
      modelId: 'fafc79267d14df97f63d7cd394ed33c3',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.product.index_view_form',
    },
    {
      dedrbarGroups: [
        {
          caption: '通用',
          name: '通用',
          id: 'usrdrgroup0314526198',
        },
        {
          caption: '设置',
          name: '设置',
          id: 'usrdrgroup0314383150',
        },
      ],
      showTitle: true,
      editItemCaption: '产品',
      dedrctrlItems: [
        {
          dedrbarGroupId: 'usrdrgroup0314526198',
          caption: '产品成员',
          appViewId: 'plmweb.product_member_config_grid_view',
          id: 'member',
        },
        {
          dedrbarGroupId: 'usrdrgroup0314526198',
          caption: '标签管理',
          appViewId: 'plmweb.product_tag_tag_grid_view',
          id: 'tag',
        },
        {
          dedrbarGroupId: 'usrdrgroup0314526198',
          caption: '回收站',
          dataAccessAction: 'UPDATE',
          enableMode: 'DEOPPRIV',
          appViewId: 'plmweb.product_recover_tab_exp_view',
          id: 'recycle',
        },
        {
          dedrbarGroupId: 'usrdrgroup0314383150',
          caption: '基本信息',
          dataAccessAction: 'UPDATE',
          enableMode: 'DEOPPRIV',
          appViewId: 'plmweb.product_base_information_edit_view',
          id: 'base',
        },
        {
          dedrbarGroupId: 'usrdrgroup0314383150',
          caption: '高级设置',
          dataAccessAction: 'UPDATE',
          enableMode: 'DEOPPRIV',
          appViewId: 'plmweb.product_advanced_setting_edit_view',
          id: 'adv',
        },
      ],
      uniqueTag: 'product_setting_view__drbar',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'setting_view_dr',
      controlType: 'DRBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        ctrlParams: {
          SINGLEITEMGROUP: 'true',
        },
        id: 'drbar',
      },
      modelId: 'f5c5559c0a8599867693ff957a4e8305',
      modelType: 'PSDEDRBAR',
      name: 'drbar',
      id: 'setting_view_dr',
    },
    {
      codeName: 'setting_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'setting_view_datainfobar',
    },
    {
      caption: '产品配置',
      codeName: 'setting_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.product',
      controlParam: {},
      name: 'captionbar',
      id: 'setting_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'editview2-menu',
  },
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.product',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '产品配置',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e76ce60277d6667a76bc13d90dd22249',
  modelType: 'PSAPPDEVIEW',
  name: 'product_setting_view',
  id: 'plmweb.product_setting_view',
};
