export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'test_list_view',
  deviewId: '204cc63954453a54eb9ad6b999a4a984',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT_MEMBER',
  },
  caption: '项目成员',
  codeName: 'project_member_test_list_view',
  appDataEntityId: 'plmweb.project_member',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        batchAddAppViews: [
          {
            openMode: 'POPUPMODAL',
            refMode: 'PROJECT',
            refAppViewId: 'plmweb.project_mpick_up_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.project_member_edit_view',
        },
        enableBatchAdd: true,
        appDataEntityId: 'plmweb.project_member',
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.project_member_edit_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'PROJECT',
            refAppViewId: 'plmweb.project_mpick_up_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'USER',
            refAppViewId: 'plmweb.user_choose_mpick_up_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.project_member_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.project_member_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '项目成员编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PROJECT_MEMBER.EDITVIEW',
      },
      refAppViewId: 'plmweb.project_member_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '项目成员编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PROJECT_MEMBER.EDITVIEW',
      },
      refAppViewId: 'plmweb.project_member_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '项目数据多项选择视图',
      refAppViewId: 'plmweb.project_mpick_up_view',
      name: 'MPICKUPVIEW:PROJECT',
      id: 'mpickupview:project',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '选择成员',
      refAppViewId: 'plmweb.user_choose_mpick_up_view',
      name: 'MPICKUPVIEW:USER',
      id: 'mpickupview:user',
    },
  ],
  controls: [
    {
      xdataControlName: 'list',
      codeName: 'test_list_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '测试项布局面板_工具栏',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '094f541f4fcbd7af8cddd271fa709715',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'test_list_view_toolbar',
    },
    {
      groupMode: 'NONE',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      caption: '这是直接内容',
                      halign: 'LEFT',
                      renderMode: 'PARAGRAPH',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_LABEL',
                      id: 'static_label',
                    },
                    caption: '标签',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_label',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'field_text_dynamic',
                    },
                    viewFieldName: 'NAME',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_text_dynamic',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            contentHeight: 150,
            contentWidth: 300,
            height: 150,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              height: 150,
              heightMode: 'PX',
              layout: 'TABLE_24COL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'page_container',
          },
        ],
        codeName: 'usr0105222325',
        controlType: 'PANEL',
        logicName: 'List_列表项面板',
        appDataEntityId: 'plmweb.project_member',
        controlParam: {},
        modelId: '96e93aa05223cacfc310c469236d0a07',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'plmweb.project_member.usr0105222325',
      },
      delistDataItems: [
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'user_id',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'project_id',
          dataType: 25,
          id: 'project_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.project_member',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.project_member',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.project_member',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.project_member',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.project_member',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr01051713_list_view_list',
      controlType: 'LIST',
      logicName: 'List',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {
        id: 'list',
      },
      modelId: '28643eebc43993f9ff6a7f8965fe87fc',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'plmweb.project_member.usr01051713_list_view_list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PROJECT_MEMBER',
      },
      caption: '项目成员',
      codeName: 'test_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {},
      name: 'captionbar',
      id: 'test_list_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.project_member',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试项布局面板',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6f0fe5ebb44061dbde64cf10738253b2',
  modelType: 'PSAPPDEVIEW',
  name: 'project_membertest_list_view',
  id: 'plmweb.project_member_test_list_view',
};
