export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'choose_position_option_view',
  deviewId: '662C2B31-6AC1-407B-83B1-5FB6C873AF23',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT_MEMBER',
  },
  caption: '选择职位',
  codeName: 'project_member_choose_position_option_view',
  height: 220,
  appDataEntityId: 'plmweb.project_member',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.project_member',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.project_member',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.project_member',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.project_member',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.project_member',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.project_member',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              fieldName: 'target_title',
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.base__position',
                editorType: 'DROPDOWNLIST',
                placeHolder: '请选择职位',
                valueType: 'SIMPLE',
                editable: true,
                id: 'target_title',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '职位',
              codeName: 'target_title',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'target_title',
            },
            {
              dataType: 25,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr12128076_form',
      controlType: 'FORM',
      logicName: '项目成员选择职位选项操作视图_表单',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {
        id: 'form',
      },
      modelId: 'DD909C61-71F1-4EE2-B6CB-8203D8D8AB29',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.project_member.usr12128076_form',
    },
    {
      codeName: 'choose_position_option_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'choose_position_option_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PROJECT_MEMBER',
      },
      caption: '选择职位',
      codeName: 'choose_position_option_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.project_member',
      controlParam: {},
      name: 'captionbar',
      id: 'choose_position_option_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.project_member',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择职位',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 400,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f3b699471c3488af983626ed7756d678',
  modelType: 'PSAPPDEVIEW',
  name: 'project_memberchoose_position_option_view',
  id: 'plmweb.project_member_choose_position_option_view',
};
