export default {
  htmlUrl: 'https://plm.ibizlab.cn/doc#/',
  loadDefault: true,
  deviewCodeName: 'data_model_html_view',
  deviewId: 'a330cf46f90157761ab3bc48deb4716c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PSCOREPRDFUNC',
  },
  caption: '核心产品功能',
  codeName: 'ps_core_prd_func_data_model_html_view',
  appDataEntityId: 'plmweb.pscoreprdfunc',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'HtmlView',
      id: 'engine',
    },
  ],
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PSCOREPRDFUNC',
      },
      caption: '核心产品功能',
      codeName: 'data_model_html_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.pscoreprdfunc',
      controlParam: {},
      name: 'captionbar',
      id: 'data_model_html_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEHTMLVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.pscoreprdfunc',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据模型HTML',
  viewStyle: 'DEFAULT',
  viewType: 'DEHTMLVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b14a50bc0b623d2dd7934d00849958be',
  modelType: 'PSAPPDEVIEW',
  name: 'PSCorePrdFuncdata_model_html_view',
  id: 'plmweb.ps_core_prd_func_data_model_html_view',
};
