export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_view_setting',
  deviewId: 'bb70b948a12e0567cec481a8aee34662',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PSDENOTIFY',
  },
  caption: '通知列表',
  codeName: 'psde_notify_list_view_setting',
  appDataEntityId: 'plmweb.psdenotify',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.psde_notify_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.psde_notify_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.psde_notify_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.psde_notify_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '实体通知编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PSDENOTIFY.EDITVIEW',
      },
      refAppViewId: 'plmweb.psde_notify_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '实体通知编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PSDENOTIFY.EDITVIEW',
      },
      refAppViewId: 'plmweb.psde_notify_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'list',
      codeName: 'list_view_setting_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认表格界面）',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'ec6fbb681f5e3e6783c2af57e5eefaaa',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'list_view_setting_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.PSDENOTIFY.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'searchform',
      },
      modelId: '87ec72bb7382fc4f3a62883a5461b9f8',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.psdenotify.default',
    },
    {
      groupMode: 'NONE',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'psdenotifyname',
                    },
                    viewFieldName: 'PSDENOTIFYNAME',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'psdenotifyname',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'codename',
                    },
                    viewFieldName: 'CODENAME',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'codename',
                  },
                ],
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0314107798',
        controlType: 'PANEL',
        logicName: 'notify_list_列表项面板',
        appDataEntityId: 'plmweb.psdenotify',
        controlParam: {},
        modelId: '59008e46996961e95a3f45520d8f8eac',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'plmweb.psdenotify.usr0314107798',
      },
      delistDataItems: [
        {
          dataType: 25,
          id: 'codename',
        },
        {
          dataType: 25,
          id: 'psdenotifyname',
        },
        {
          appDEFieldId: 'psdenotifyid',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'psdenotifyname',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'notify_list',
      controlType: 'LIST',
      logicName: 'notify_list',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'list',
      },
      modelId: 'b5e25ab068a458e3f4f14e29f0282af2',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'plmweb.psdenotify.notify_list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PSDENOTIFY',
      },
      caption: '通知列表',
      codeName: 'list_view_setting_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {},
      name: 'captionbar',
      id: 'list_view_setting_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.psdenotify',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '通知列表',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b3eb2faf1169b9596cc662dabea7ff47',
  modelType: 'PSAPPDEVIEW',
  name: 'PSDENotifylist_view_setting',
  id: 'plmweb.psde_notify_list_view_setting',
};
