export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'template_info_view',
  deviewId: '7c298ad33408e1b6ae5e3c571dc06bba',
  accUserMode: 2,
  caption: '自动规则模板信息',
  codeName: 'psdelogictemplate_info_view',
  appDataEntityId: 'plmweb.psdelogic',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '关系分页部件',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drtab',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container2',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    buttonType: 'PANELBUTTON',
                    uiactionId: 'create_by_template@psdelogic',
                    renderMode: 'BUTTON',
                    tooltip: '使用此模板建立规则',
                    uiactionTarget: 'NONE',
                    caption: '使用此模板建立规则',
                    itemStyle: 'DEFAULT',
                    itemType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'button_okaction',
                  },
                ],
                layout: {
                  dir: 'row-reverse',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_right',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        dedrtabPages: [
          {
            caption: '规则模板',
            appViewId: 'plmweb.psdelogiclogicdesign_readonly',
            id: 'template',
          },
        ],
        dataRelationTag: 'flow_preview',
        editItemCaption: '实体处理逻辑',
        uniqueTag: 'psdelogictemplate_info_view__drtab',
        hideEditItem: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'flow_preview',
        controlType: 'DRTAB',
        appDataEntityId: 'plmweb.psdelogic',
        controlParam: {
          id: 'drtab',
        },
        modelId: 'a9232b8b86e289f0b72f366fdc413cff',
        modelType: 'PSDEDRTAB',
        name: 'drtab',
        id: 'flow_preview',
      },
      {
        caption: '自动规则模板信息',
        codeName: 'template_info_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.psdelogic',
        controlParam: {},
        name: 'captionbar',
        id: 'template_info_view_captionbar',
      },
    ],
    codeName: 'usr0328073006',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'template_info_view分页导航视图布局面板',
    appDataEntityId: 'plmweb.psdelogic',
    controlParam: {},
    modelId: '5ea70115b3dfb074582ae7e09313a3a7',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0328073006',
  },
  title: '自动规则模板信息',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '00eacc5d4b957f6a3a67ea10749e7d1a',
  modelType: 'PSAPPDEVIEW',
  name: 'psdelogictemplate_info_view',
  id: 'plmweb.psdelogictemplate_info_view',
};
