export default {
  deviewCodeName: 'LogicDesign',
  deviewId: '5B64656B-5CC2-4526-A507-144F15E2A9EE',
  accUserMode: 2,
  caption: '实体处理逻辑',
  codeName: 'PSDELogicLogicDesign',
  appDataEntityId: 'plmweb.psdelogic',
  controls: [
    {
      caption: '实体处理逻辑',
      codeName: 'LogicDesigncaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.psdelogic',
      controlParam: {},
      name: 'captionbar',
      id: 'logicdesigncaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDESUBAPPREFVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.psdelogic',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '设计',
  viewStyle: 'DEFAULT',
  viewType: 'DESUBAPPREFVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2c53d6822f5d130fcb16a2ed4491494f',
  modelType: 'PSAPPDEVIEW',
  name: 'PSDELogicLogicDesign',
  id: 'plmweb.psdelogiclogicdesign',
};
