export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'DesignView_MSNode2',
  deviewId: 'b6d092c2974fb09bbf1d2cb799c3f3ce',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PSDELOGICNODE',
  },
  caption: '主状态逻辑节点(设计)',
  codeName: 'psdelogicnodedesignview_msnode2',
  appDataEntityId: 'plmweb.psdelogicnode',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      autoSaveMode: 1,
      createControlAction: {
        appDEMethodId: 'createtemp',
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'getdrafttemp',
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'gettemp',
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'removetemp',
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'updatetemp',
        appDataEntityId: 'plmweb.psdelogicnode',
        id: 'update',
      },
      enableAutoSave: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: 'psdelogicid',
                  createDVT: 'CONTEXT',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'psdelogicid',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'psdelogicid',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.PSDELOGICID',
                  },
                  caption: '实体处理逻辑',
                  codeName: 'psdelogicid',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'psdelogicid',
                },
                {
                  createDV: 'MAINSTATE',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'logicnodetype',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'logicnodetype',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '逻辑节点类型',
                  codeName: 'logicnodetype',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'logicnodetype',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'psdelogicnodename',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'psdelogicnodename',
                  },
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.PSDELOGICNODENAME',
                  },
                  caption: '状态名称',
                  codeName: 'psdelogicnodename',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'psdelogicnodename',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'param1',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'plmweb.projmgmt__work_item_state2',
                    editorParams: {
                      forceSelection: 'false',
                    },
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'param1',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '状态值',
                  codeName: 'param1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'param1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'codename',
                  editor: {
                    maxLength: 60,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'codename',
                  },
                  caption: '代码名称',
                  codeName: 'codename',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'codename',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'ordervalue',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'ordervalue',
                  },
                  updateDV: '100',
                  allowEmpty: true,
                  caption: '排序属性',
                  codeName: 'ordervalue',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'ordervalue',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 85,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'param9',
                  editor: {
                    editorType: 'SWITCH',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'param9',
                  },
                  allowEmpty: true,
                  caption: '初始状态',
                  codeName: 'param9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'param9',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 85,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'param12',
                      editor: {
                        editorType: 'COLORPICKER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'param12',
                      },
                      allowEmpty: true,
                      caption: '前景颜色',
                      codeName: 'param12',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'param12',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 85,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'param13',
                      editor: {
                        editorType: 'COLORPICKER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'param13',
                      },
                      allowEmpty: true,
                      caption: '背景颜色',
                      codeName: 'param13',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'param13',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 85,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'param11',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'param11',
                      },
                      allowEmpty: true,
                      caption: '样式表名称',
                      codeName: 'param11',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'param11',
                    },
                  ],
                  caption: '样式',
                  codeName: 'grouppanel5',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel5',
                },
                {
                  createDV: '0',
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 100,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'param7',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'param7',
                  },
                  updateDV: '0',
                  allowEmpty: true,
                  hidden: true,
                  caption: '行为允许模式',
                  codeName: 'param7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'param7',
                },
                {
                  createDV: '0',
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 120,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'param8',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'param8',
                  },
                  updateDV: '0',
                  allowEmpty: true,
                  hidden: true,
                  caption: '操作标识允许模式',
                  codeName: 'param8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'param8',
                },
                {
                  createDV: '0',
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 120,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'param10',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'param10',
                  },
                  updateDV: '0',
                  allowEmpty: true,
                  hidden: true,
                  caption: '属性变更允许模式',
                  codeName: 'param10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'param10',
                },
              ],
              caption: '主状态',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              labelPos: 'LEFT',
              labelWidth: 85,
              noPrivDisplayMode: 1,
              appDEFieldId: 'psdelogicnodeid',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'psdelogicnodeid',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.PSDELOGICNODEID',
              },
              caption: '实体处理逻辑节点标识',
              codeName: 'psdelogicnodeid',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'psdelogicnodeid',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'ms_node',
      controlType: 'FORM',
      logicName: '主状态逻辑节点',
      appDataEntityId: 'plmweb.psdelogicnode',
      controlParam: {
        id: 'form',
      },
      modelId: 'b54f55ec192f749394279580c0437ce9',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.psdelogicnode.ms_node',
    },
    {
      codeName: 'design_view_ms_node2_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.psdelogicnode',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'design_view_ms_node2_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PSDELOGICNODE',
      },
      caption: '主状态逻辑节点(设计)',
      codeName: 'design_view_ms_node2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.psdelogicnode',
      controlParam: {},
      name: 'captionbar',
      id: 'design_view_ms_node2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.psdelogicnode',
    controlParam: {},
    id: 'layoutpanel',
  },
  priority: 20,
  title: '主状态逻辑节点(设计)',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a75ac51bb869bcadaa218ede3e4f7135',
  modelType: 'PSAPPDEVIEW',
  name: 'psdelogicnodedesignview_msnode2',
  id: 'plmweb.psdelogicnodedesignview_msnode2',
};
