export default {
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'EditView',
  deviewId: 'e49f9646060185ada8315bc3a140ee6d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PSDENOTIFY',
  },
  caption: '实体通知',
  codeName: 'PSDENotifyEditView',
  appDataEntityId: 'plmweb.psdenotify',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'save',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.SAVE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.SAVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem3',
        },
      ],
      xdataControlName: 'form',
      codeName: 'EditViewtoolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认编辑界面）',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '48c8f789be8a5522d3003293c1cf2ffb',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editviewtoolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.psdenotify',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'getdraft',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.psdenotify',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              actionGroupExtractMode: 'ITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.PSDENOTIFY.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '实体通知基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'psdenotifyid',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'psdenotifyid',
              },
              allowEmpty: true,
              hidden: true,
              caption: '实体通知标识',
              codeName: 'psdenotifyid',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'psdenotifyid',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.PSDENOTIFY.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              actionGroupExtractMode: 'ITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.PSDENOTIFY.MAIN.GROUPPANEL.GROUP2',
              },
              caption: '操作信息',
              codeName: 'group2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group2',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.PSDENOTIFY.MAIN.FORMPAGE.FORMPAGE2',
          },
          caption: '其它',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Main',
      controlType: 'FORM',
      logicName: '主编辑表单',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'form',
      },
      modelId: 'cbf4f33b2be6ed5e6ea81ac07a666173',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.psdenotify.main',
    },
    {
      codeName: 'EditViewdatainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editviewdatainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PSDENOTIFY',
      },
      caption: '实体通知',
      codeName: 'EditViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.psdenotify',
      controlParam: {},
      name: 'captionbar',
      id: 'editviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.psdenotify',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '实体通知编辑视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PSDENOTIFY.EDITVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '136d7d6af6e50705ca982ced7ecf765d',
  modelType: 'PSAPPDEVIEW',
  name: 'PSDENotifyEditView',
  id: 'plmweb.psdenotifyeditview',
};
