export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'my_created_tab_exp_view',
  deviewId: 'E90694AF-C5C9-46B5-956F-050292EAB3AC',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RECENT',
  },
  caption: '最近访问',
  codeName: 'recentmy_created_tab_exp_view',
  appDataEntityId: 'plmweb.recent',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '工作项',
          appViewId: 'plmweb.work_itemmy_created_grid_view',
          id: 'work_item',
        },
        {
          caption: '产品需求',
          appViewId: 'plmweb.ideamy_created_grid_view',
          id: 'idea',
        },
        {
          caption: '工单',
          appViewId: 'plmweb.ticketmy_created_grid_view',
          id: 'ticket',
        },
        {
          caption: '测试用例',
          appViewId: 'plmweb.test_casemy_craeted_grid_view',
          id: 'test_case',
        },
      ],
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.RECENT',
      },
      editItemCaption: '最近访问',
      appCounterRefId: '2af91be5a63e7a40d7425715f44596d5',
      uniqueTag: 'recentmy_created_tab_exp_view__tabexppanel',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'my_created_entry',
            counterType: 'DEDR',
            getAppDEActionId: 'my_created_entry',
            appDataEntityId: 'plmweb.recent',
            timer: 60000,
            name: '我创建的事项',
            id: 'plmweb.my_created_entry',
          },
          refMode: {
            srfdeid: 'RECENT',
          },
          tag: '2af91be5a63e7a40d7425715f44596d5',
          id: '2af91be5a63e7a40d7425715f44596d5',
        },
      ],
      codeName: 'my_create_item',
      controlType: 'DRTAB',
      appDataEntityId: 'plmweb.recent',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '7D2E3219-453C-4559-9A2A-8D8986D07F7D',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'my_create_item',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RECENT',
      },
      caption: '最近访问',
      codeName: 'my_created_tab_exp_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.recent',
      controlParam: {},
      name: 'captionbar',
      id: 'my_created_tab_exp_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.recent',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '我创建的事项',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '24b1581a0587c7344c1b2d06326757b8',
  modelType: 'PSAPPDEVIEW',
  name: 'recentmy_created_tab_exp_view',
  id: 'plmweb.recentmy_created_tab_exp_view',
};
