export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'data_test_view',
  deviewId: '9934c78cf7ef6897baf4615798e6c780',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RECENT',
  },
  caption: '最近使用',
  codeName: 'recent_data_test_view',
  appDataEntityId: 'plmweb.recent',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_dataview',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '数据视图',
            contentHeight: 200,
            height: 200,
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              height: 200,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dataview',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '最近使用',
        contentHeight: 300,
        height: 300,
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          height: 300,
          heightMode: 'PX',
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group1',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '最近访问',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'DataView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            navigateContexts: [
              {
                key: 'PROJECT',
                value: 'owner_id',
                name: 'PROJECT',
                id: 'project',
              },
              {
                key: 'LIBRARY',
                value: 'owner_id',
                name: 'LIBRARY',
                id: 'library',
              },
              {
                key: 'PRODUCT',
                value: 'owner_id',
                name: 'PRODUCT',
                id: 'product',
              },
            ],
            refAppViewId: 'plmweb.recent_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              navigateContexts: [
                {
                  key: 'PROJECT',
                  value: 'owner_id',
                  name: 'PROJECT',
                  id: 'project',
                },
                {
                  key: 'LIBRARY',
                  value: 'owner_id',
                  name: 'LIBRARY',
                  id: 'library',
                },
                {
                  key: 'PRODUCT',
                  value: 'owner_id',
                  name: 'PRODUCT',
                  id: 'product',
                },
              ],
              refAppViewId: 'plmweb.recent_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        navigateContexts: [
          {
            key: 'PROJECT',
            value: 'owner_id',
            name: 'PROJECT',
            id: 'project',
          },
          {
            key: 'LIBRARY',
            value: 'owner_id',
            name: 'LIBRARY',
            id: 'library',
          },
          {
            key: 'PRODUCT',
            value: 'owner_id',
            name: 'PRODUCT',
            id: 'product',
          },
        ],
        realTitle: '最近访问数据重定向视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.RECENT.REDIRECTVIEW',
        },
        refAppViewId: 'plmweb.recent_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        cardHeight: 120,
        cardWidth: 150,
        groupMode: 'NONE',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'plmweb.base__recent_use',
                    editorHeight: 20,
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_IMAGE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'owner_subtype',
                  },
                  viewFieldName: 'owner_subtype',
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  caption: '图片(动态)',
                  contentHeight: 20,
                  height: 20,
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    height: 20,
                    heightMode: 'PX',
                    layout: 'FLEX',
                  },
                  id: 'owner_subtype',
                },
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  controlRenders: [
                    {
                      layoutPanelModel:
                        "`<div class='ibiz-span' title='${data?.name}'>${data?.name}</div>`",
                      renderType: 'LAYOUTPANEL_MODEL',
                      id: 'logic',
                    },
                  ],
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'plmweb.base__recent_type',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'owner_type',
                  },
                  viewFieldName: 'owner_type',
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'owner_type',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container1',
            },
          ],
          layoutPanel: true,
          codeName: 'usr0103233849',
          controlType: 'PANEL',
          logicName: 'data_view_card卡片视图',
          appDataEntityId: 'plmweb.recent',
          controlParam: {},
          modelId: '6d73f3e6ea69e7999c4fc03af95a49b5',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'plmweb.recent.usr0103233849',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.recent',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_recent_use',
          appDataEntityId: 'plmweb.recent',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.recent',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.recent',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.recent',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'data_view_card',
        controlType: 'DATAVIEW',
        logicName: '最近使用',
        appDataEntityId: 'plmweb.recent',
        controlParam: {
          id: 'dataview',
        },
        sysCss: {
          cssName: 'index-recentdata-custom',
        },
        modelId: 'd59f398379dc14c0c0758de4c7186e4a',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'plmweb.recent.data_view_card',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'update_time',
        degridColumns: [
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner_subtype',
            excelCaption: '所属对象子类型',
            appCodeListId: 'plmweb.base__recent_visite',
            appDEFieldId: 'owner_subtype',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所属对象子类型',
            codeName: 'owner_subtype',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            sysPFPluginId: 'icon_gridcolumn',
            width: 40,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner_subtype',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'show_identifier',
            excelCaption: '编号',
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编号',
            cellSysCss: {
              cssName: 'recent_identified_style',
            },
            codeName: 'identifier',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'identifier',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.NAME',
            },
            caption: '名称',
            cellSysCss: {
              cssName: 'td_a_link',
            },
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 600,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'recent_parent_name',
            excelCaption: '所属访问父类名称',
            appDEFieldId: 'recent_parent_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '所属访问父类名称',
            cellSysCss: {
              cssName: 'td_right',
            },
            codeName: 'recent_parent_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 230,
            widthUnit: 'PX',
            enableSort: true,
            id: 'recent_parent_name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'owner_subtype',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner_subtype',
          },
          {
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'show_identifier',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'recent_parent_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'recent_parent_name',
          },
          {
            appDEFieldId: 'owner_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner_id',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        forceFit: true,
        hideHeader: true,
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'plmweb.recent',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.recent',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'plmweb.recent',
        controlParam: {
          id: 'grid',
        },
        modelId: '9fd8e9a7cee034fb7f66feae3e0a5433',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.recent.main',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.recent',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RECENT',
        },
        caption: '最近使用',
        codeName: 'data_test_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.recent',
        controlParam: {},
        name: 'captionbar',
        id: 'data_test_view_captionbar',
      },
    ],
    codeName: 'usr0103947151',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'data_view卡片视图布局面',
    appDataEntityId: 'plmweb.recent',
    controlParam: {},
    modelId: '391df7a1b1fcabaa1077c92a260dbcf2',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0103947151',
  },
  title: '概览',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd5efc3bd496cb0c5699a5b91167a3d0a',
  modelType: 'PSAPPDEVIEW',
  name: 'recentdata_test_view',
  id: 'plmweb.recent_data_test_view',
};
