export default {
  redirectAppViewRefs: [
    {
      realTitle: '工作项关联编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.RELATION.EDITVIEW',
      },
      refAppViewId: 'plmweb.relation_edit_view',
      name: 'RELATION:EDITVIEW',
      id: 'relation:editview',
    },
    {
      realTitle: '工作项关联编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.RELATION.EDITVIEW',
      },
      refAppViewId: 'plmweb.relation_edit_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '8f04e30967a61cc99f0b4014b8cd8c8e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RELATION',
  },
  caption: '关联',
  codeName: 'relation_redirect_view',
  appDataEntityId: 'plmweb.relation',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RELATION',
      },
      caption: '关联',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.relation',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.relation',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作项关联数据重定向视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.RELATION.REDIRECTVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: '96eebf8d8626e01bd8d712d7fc9bc3f8',
  modelType: 'PSAPPDEVIEW',
  name: 'relationRedirectView',
  id: 'plmweb.relation_redirect_view',
};
