export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'ticket_re_idea_grid_view',
  deviewId: 'F6326F2B-7EB5-4202-8AB4-BEC8772E8B19',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RELATION',
  },
  caption: '关联',
  codeName: 'relation_ticket_re_idea_grid_view',
  appDataEntityId: 'plmweb.relation',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'total',
                    },
                    viewFieldName: 'total',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'INNERMEDIUM',
                    },
                    id: 'total',
                  },
                  {
                    rawItem: {
                      caption: '个需求',
                      halign: 'LEFT',
                      renderMode: 'TEXT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_text',
                  },
                ],
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              align: 'center',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  enablePickupView: true,
                  singleSelect: true,
                  pickupAppViewId: 'plmweb.idea_product_plan_re_idea_view',
                  appDEACModeId: 'create_idea',
                  appDEDataSetId: 'fetch_recent_idea',
                  appDataEntityId: 'plmweb.recent',
                  uiactionGroup: {
                    uiactionGroupDetails: [
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        caption: '新建',
                        detailType: 'DEUIACTION',
                        uiactionId: 'create_new_idea@recent',
                        showCaption: true,
                        showIcon: true,
                        sysImage: {
                          cssClass: 'fa fa-plus',
                          glyph: 'xf067@FontAwesome',
                        },
                        id: 'uc95d0ba',
                      },
                    ],
                    appDataEntityId: 'plmweb.recent',
                    uniqueTag: 'recent__Usr0122481934',
                    name: '新建需求',
                    id: 'usr0122481934',
                  },
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    'srfnavparam.principal_id': '%principal_id%',
                    'srfnavparam.size': '20',
                    lastlabel: '更多需求',
                    AC: 'TRUE',
                    'srfnavparam.N_RECENT_PARENT_EQ': '%product%',
                    toplabel: '最近浏览',
                    PICKUPVIEW: 'TRUE',
                  },
                  editorStyle: 'MANAGE',
                  editorType: 'PICKER',
                  editorWidth: 90,
                  sysPFPluginId: 'manage',
                  placeHolder: '添加关联需求，点击确定按钮保存',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  navigateParams: [
                    {
                      key: 'principal_id',
                      value: 'principal_id',
                      id: 'principal_id',
                    },
                    {
                      key: 'size',
                      value: '20',
                      rawValue: true,
                      id: 'size',
                    },
                    {
                      key: 'n_recent_parent_eq',
                      value: 'product',
                      id: 'n_recent_parent_eq',
                    },
                  ],
                  id: 'choose_relation_data',
                },
                allowEmpty: true,
                caption: '文本(动态)',
                contentWidth: 90,
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingBottom: 'INNERMEDIUM',
                  spacingLeft: 'INNERMEDIUM',
                  spacingRight: 'INNERMEDIUM',
                  spacingTop: 'INNERMEDIUM',
                  width: 90,
                  widthMode: 'PERCENTAGE',
                },
                width: 90,
                id: 'choose_relation_data',
              },
              {
                editor: {
                  singleSelect: true,
                  appCodeListId: 'plmweb.prodmgmt__common_level',
                  editorParams: {
                    type: 'round',
                    value: '10',
                  },
                  editorType: 'DROPDOWNLIST',
                  editorWidth: 10,
                  predefinedType: 'FIELD_DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'choose_level',
                },
                allowEmpty: true,
                caption: '下拉列表框',
                contentWidth: 10,
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingBottom: 'INNERMEDIUM',
                  spacingLeft: 'INNERMEDIUM',
                  spacingRight: 'INNERMEDIUM',
                  spacingTop: 'INNERMEDIUM',
                  width: 10,
                  widthMode: 'PERCENTAGE',
                },
                sysCss: {
                  cssName: 'common-level-dropdown',
                },
                width: 10,
                id: 'choose_level',
              },
            ],
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'choose_data',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onViewMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.layoutPanel.panelItems.choose_level.setDataValue('50');",
        builtinLogic: true,
        name: 'CHOOSE_LEVEL',
        id: 'choose_level',
      },
      {
        eventNames: 'onMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.layoutPanel.panelItems.choose_data.state.visible = view.context.srfshowchoose || false;\n\n// 初始化默认隐藏表格\nview.layoutPanel.panelItems.grid.state.keepAlive = true;\nview.layoutPanel.panelItems.grid.state.visible = false;\nconst form = view.getController('form');\nif (form) {\n    form.evt.on('onFormDetailEvent', event =>{\n        const panelItems = view.layoutPanel.panelItems;\n        if (!panelItems.comment) {\n            return;\n        }\n        if (event.formDetailName === 'tabpage1') {\n            panelItems.comment.state.visible = true;\n        } else {\n            panelItems.comment.state.visible = false;\n        }\n    });\n}\n\n// 初始化隐藏发送和清空按钮\nview.layoutPanel.panelItems.button_calluilogic1.state.visible = false\nview.layoutPanel.panelItems.button_calluilogic.state.visible = false",
        builtinLogic: true,
        id: 'viewmounted',
      },
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'VIEWEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'get_grid_total',
        appDataEntityId: 'plmweb.idea',
        builtinLogic: true,
        id: 'onloadsuccess',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.relation_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.relation_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            navigateContexts: [
              {
                key: 'PRODUCT',
                value: 'target_parent_id.product_id',
                name: 'PRODUCT',
                id: 'product',
              },
              {
                key: 'IDEA',
                value: 'target_id',
                name: 'IDEA',
                id: 'idea',
              },
            ],
            refAppViewId: 'plmweb.idea_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              navigateContexts: [
                {
                  key: 'PRODUCT',
                  value: 'target_parent_id.product_id',
                  name: 'PRODUCT',
                  id: 'product',
                },
                {
                  key: 'IDEA',
                  value: 'target_id',
                  name: 'IDEA',
                  id: 'idea',
                },
              ],
              refAppViewId: 'plmweb.idea_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        openMode: 'POPUPMODAL',
        navigateContexts: [
          {
            key: 'PRODUCT',
            value: 'target_parent_id.product_id',
            name: 'PRODUCT',
            id: 'product',
          },
          {
            key: 'IDEA',
            value: 'target_id',
            name: 'IDEA',
            id: 'idea',
          },
        ],
        realOpenMode: 'POPUPMODAL',
        realTitle: '需求',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.IDEA.MAIN_VIEW',
        },
        refAppViewId: 'plmweb.idea_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '工作项关联编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.RELATION.EDITVIEW',
        },
        refAppViewId: 'plmweb.relation_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'add_relation@relation',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '添加需求',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'deuiaction1',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode: 'context.srfreadonly != true',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '添加需求',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        toolbarStyle: 'USER',
        xdataControlName: 'grid',
        codeName: 'ticket_re_idea_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '添加关联需求',
        appDataEntityId: 'plmweb.relation',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'A4A92B30-9A2A-4B9D-9D51-00121585DEE9',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'ticket_re_idea_grid_view_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'idea',
            excelCaption: '编号',
            objectNameField: 'show_identifier',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编号',
            codeName: 'target_identifier',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'target_identifier',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'idea',
            excelCaption: '标题',
            objectNameField: 'title',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '标题',
            codeName: 'target_title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'STAR',
            id: 'target_title',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'idea',
            excelCaption: '状态',
            objectNameField: 'state',
            appCodeListId: 'plmweb.prodmgmt__idea_state',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'target_state',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'target_state',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'idea',
            excelCaption: '负责人',
            objectNameField: 'assignee_name',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '负责人',
            codeName: 'target_assignee',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'target_assignee',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'level',
            excelCaption: '重要程度',
            appCodeListId: 'plmweb.prodmgmt__common_level',
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '重要程度',
            cellSysCss: {
              cssName: 'common-level-dropdown',
            },
            codeName: 'level',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'level',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'idea',
            excelCaption: '优先级',
            objectNameField: 'priority',
            appCodeListId: 'plmweb.prodmgmt__idea_priority',
            appDEFieldId: 'idea',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '取消关联',
                  detailType: 'DEUIACTION',
                  uiactionId: 'del_relation@relation',
                  tooltip: '取消关联',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-unlink',
                    glyph: 'xf127@FontAwesome',
                  },
                  id: 'ue009d6d',
                },
              ],
              appDataEntityId: 'plmweb.relation',
              uniqueTag: 'relation__Usr0417741727',
              name: '取消关联',
              id: 'usr0417741727',
            },
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '优先级',
            codeName: 'target_priority',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'target_priority',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'idea',
            excelCaption: '产品需求',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '产品需求',
            codeName: 'idea',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            hideDefault: true,
            id: 'idea',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'target_id',
            excelCaption: '关联目标标识',
            appDEFieldId: 'target_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '关联目标标识',
            codeName: 'target_id',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'target_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'idea',
            excelCaption: '产品需求',
            objectNameField: 'product_id',
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '产品需求',
            codeName: 'target_parent_id',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            hideDefault: true,
            id: 'target_parent_id',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'idea',
            valueType: 'OBJECT',
            dataType: 21,
            id: 'idea',
          },
          {
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'level',
          },
          {
            appDEFieldId: 'target_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'target_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '重要程度',
            codeName: 'level',
            enableCond: 3,
            appDEFieldId: 'level',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.prodmgmt__common_level',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'level',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            id: 'level',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 1000,
        sortMode: 'REMOTE',
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetch_ticket_re_idea',
          appDataEntityId: 'plmweb.relation',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.relation',
          id: 'remove',
        },
        autoLoad: true,
        enableItemPrivilege: true,
        showBusyIndicator: true,
        codeName: 'relation_idea_grid',
        controlType: 'GRID',
        logicName: '关联产品需求_表格',
        appDataEntityId: 'plmweb.relation',
        controlLogics: [
          {
            eventNames: 'onLoadSuccess',
            logicTag: 'grid',
            logicType: 'APPDEUILOGIC',
            appDEUILogicId: 'del_relation_disabled',
            appDataEntityId: 'plmweb.relation',
            triggerType: 'CTRLEVENT',
            id: 'logic',
          },
        ],
        controlParam: {
          ctrlParams: {
            LOCATERECORDKEY: 'target_id',
          },
          id: 'grid',
        },
        modelId: '71330C8D-D4A4-4287-B1C2-84F962E76EDD',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.relation.relation_idea_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.RELATION.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'plmweb.relation',
        controlParam: {
          id: 'searchform',
        },
        modelId: '6b1f689780dac040c5a069cb68887d39',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'plmweb.relation.default',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.relation',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RELATION',
        },
        caption: '关联',
        codeName: 'ticket_re_idea_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.relation',
        controlParam: {},
        name: 'captionbar',
        id: 'ticket_re_idea_grid_view_captionbar',
      },
    ],
    codeName: 'ticket_re_idea',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '工单关联需求表格视图布局',
    appDataEntityId: 'plmweb.relation',
    controlLogics: [
      {
        eventNames: 'onChange',
        itemName: 'CHOOSE_RELATION_DATA',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'ticket_relation_idea',
        appDataEntityId: 'plmweb.idea',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: '1f4bc0e2822230d4cfec1eaa88686a70',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'ticket_re_idea',
  },
  title: '工单关联产品需求表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'badc9c3d9d4d525d224f1406cd74bacd',
  modelType: 'PSAPPDEVIEW',
  name: 'relationticket_re_idea_grid_view',
  id: 'plmweb.relation_ticket_re_idea_grid_view',
};
