export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'work_item_re_test_case_list_view',
  deviewId: 'A1A411A4-E4B3-4D83-928D-906709BF0FF3',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RELATION',
  },
  caption: '关联',
  codeName: 'relation_work_item_re_test_case_list_view',
  appDataEntityId: 'plmweb.relation',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.relation_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.relation_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          navigateContexts: [
            {
              key: 'TEST_CASE',
              value: 'test_case.id',
              name: 'TEST_CASE',
              id: 'test_case',
            },
            {
              key: 'LIBRARY',
              value: 'test_case.test_library_id',
              name: 'LIBRARY',
              id: 'library',
            },
          ],
          refAppViewId: 'plmweb.test_case_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            navigateContexts: [
              {
                key: 'TEST_CASE',
                value: 'test_case.id',
                name: 'TEST_CASE',
                id: 'test_case',
              },
              {
                key: 'LIBRARY',
                value: 'test_case.test_library_id',
                name: 'LIBRARY',
                id: 'library',
              },
            ],
            refAppViewId: 'plmweb.test_case_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      openMode: 'POPUPMODAL',
      navigateContexts: [
        {
          key: 'TEST_CASE',
          value: 'test_case.id',
          name: 'TEST_CASE',
          id: 'test_case',
        },
        {
          key: 'LIBRARY',
          value: 'test_case.test_library_id',
          name: 'LIBRARY',
          id: 'library',
        },
      ],
      realOpenMode: 'POPUPMODAL',
      realTitle: '用例',
      refAppViewId: 'plmweb.test_case_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '工作项关联编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.RELATION.EDITVIEW',
      },
      refAppViewId: 'plmweb.relation_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.RELATION.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.relation',
      controlParam: {
        id: 'searchform',
      },
      modelId: '6b1f689780dac040c5a069cb68887d39',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.relation.default',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorParams: {
                        OBJECTNAMEFIELD: 'show_identifier',
                        VALUETYPE: 'OBJECT',
                      },
                      editorType: 'SPAN',
                      objectNameField: 'show_identifier',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'test_case',
                    },
                    viewFieldName: 'TEST_CASE',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingRight: 'OUTERMEDIUM',
                    },
                    id: 'test_case',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorParams: {
                        OBJECTNAMEFIELD: 'title',
                        VALUETYPE: 'OBJECT',
                      },
                      editorType: 'SPAN',
                      objectNameField: 'title',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'field_text_dynamic1',
                    },
                    viewFieldName: 'TEST_CASE',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_text_dynamic1',
                  },
                ],
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0430775554',
        controlType: 'PANEL',
        logicName: 'relation_test_case_list_列表项面板',
        appDataEntityId: 'plmweb.relation',
        controlParam: {},
        modelId: 'A2FFE384-C69B-4CA1-B0E4-DFFDBA024A85',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'plmweb.relation.usr0430775554',
      },
      delistDataItems: [
        {
          appDEFieldId: 'test_case',
          dataType: 21,
          id: 'test_case',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.relation',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_work_item_relation_test_case',
        appDataEntityId: 'plmweb.relation',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.relation',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.relation',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.relation',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'relation_test_case_list',
      controlType: 'LIST',
      logicName: 'relation_test_case_list',
      appDataEntityId: 'plmweb.relation',
      controlParam: {
        id: 'list',
      },
      modelId: '35BE443F-B442-47FD-959E-D9005FD9F499',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'plmweb.relation.relation_test_case_list',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.relation',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RELATION',
      },
      caption: '关联',
      codeName: 'work_item_re_test_case_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.relation',
      controlParam: {},
      name: 'captionbar',
      id: 'work_item_re_test_case_list_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.relation',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作项关联测试用例列表视图',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'aadb8f70248c24ccc16f7acd8cd06dde',
  modelType: 'PSAPPDEVIEW',
  name: 'relationwork_item_re_test_case_list_view',
  id: 'plmweb.relation_work_item_re_test_case_list_view',
};
