export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'overview_base_view',
  deviewId: '10B09D14-B247-4529-85C5-6C749DB43004',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RELEASE',
  },
  caption: '项目发布',
  codeName: 'release_overview_base_view',
  appDataEntityId: 'plmweb.release',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.release',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.release',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.release',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.release',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.release',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.release',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'remaining_days',
                  },
                  allowEmpty: true,
                  caption: '距离发布还有',
                  codeName: 'remaining_days',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'remaining_days',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'assignee_id',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'plmweb.sysoperator',
                    editorStyle: 'PERSONNEL_INFO',
                    editorType: 'SPAN',
                    sysPFPluginId: 'personnel_info',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'assignee_id',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  caption: '负责人',
                  codeName: 'assignee_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'assignee_id',
                },
                {
                  dataType: 21,
                  enableCond: 1,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'stage_transitions',
                  editor: {
                    halign: 'LEFT',
                    linkAppViewId: 'plmweb.release_change_stage_view',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    enableLinkView: true,
                    editorParams: {
                      CLICKSTAGEIDFIELD: 'target_stage',
                      RELEASESTAGEIDFIELD: 'current_stage',
                      SHOWCONFIG:
                        '{"sort": "p_sequence","typeName":"pname","color":"p_color"}',
                      LINKVIEW: 'TRUE',
                      'srfnavparam.release': '%release%',
                    },
                    editorStyle: 'STAGE_PROGRESS_BAR',
                    editorType: 'SPAN_LINK',
                    objectIdField: 'id',
                    objectNameField: 'name',
                    sysPFPluginId: 'stage_progress_bar',
                    valueType: 'OBJECTS',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'release',
                        value: 'release',
                        id: 'release',
                      },
                    ],
                    id: 'stage_transitions',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'stage_transitions',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 16,
                    colMD: 16,
                    colSM: 16,
                    colXS: 16,
                    layout: 'TABLE_24COL',
                  },
                  id: 'stage_transitions',
                },
              ],
              caption: '项目发布基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 5,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'end_at',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'end_at',
              },
              valueFormat: 'YYYY-MM-DD',
              allowEmpty: true,
              hidden: true,
              caption: '发布时间',
              codeName: 'end_at',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'end_at',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'overview_base_form',
      controlType: 'FORM',
      logicName: '发布概览基本信息_表单',
      appDataEntityId: 'plmweb.release',
      controlLogics: [
        {
          eventNames: 'onLoadSuccess',
          logicTag: 'form',
          logicType: 'SCRIPT',
          scriptCode:
            "var end_at = view.layoutPanel.panelItems.form.control.details.end_at;\r\nvar remaining_days = view.layoutPanel.panelItems.form.control.details.remaining_days;\r\nvar end_at_date = end_at.value;\r\nvar daysDifference = 0;\r\nif(end_at_date){\r\n    // 今天的日期\r\n    var today = new Date();\r\n\r\n    // 指定日期的日期对象\r\n    var specifiedDate = new Date(end_at_date);\r\n\r\n    // 将两个日期转换为毫秒数\r\n    var todayTime = today.getTime();\r\n    var specifiedDateTime = specifiedDate.getTime();\r\n\r\n    // 计算剩余天数\r\n    var timeDiff = specifiedDateTime - todayTime;\r\n    daysDifference = Math.ceil(timeDiff / (1000 * 3600 * 24));\r\n    if(daysDifference < 0){\r\n        daysDifference = 0;\r\n    }\r\n}\r\nremaining_days.setDataValue(daysDifference + '天');\r\n",
          triggerType: 'CTRLEVENT',
          id: 'cal_remaining_days',
        },
      ],
      controlParam: {
        id: 'form',
      },
      modelId: '80A35691-509D-4E69-8343-E6A432B093A8',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.release.overview_base_form',
    },
    {
      codeName: 'overview_base_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.release',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'overview_base_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RELEASE',
      },
      caption: '项目发布',
      codeName: 'overview_base_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.release',
      controlParam: {},
      name: 'captionbar',
      id: 'overview_base_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'sprint-base-info-view',
  },
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.release',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '发布概览基本信息视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b28eb271f4bd898c2e8afc12ad45ec40',
  modelType: 'PSAPPDEVIEW',
  name: 'releaseoverview_base_view',
  id: 'plmweb.release_overview_base_view',
};
