export default {
  mdctrlActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'pick_up_tree_view',
  deviewId: '5B8F4ED4-2F34-4E3A-AE81-A7BEAFD3126C',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.REVIEW.PICK_UP_TREE_VIEW',
  },
  caption: '评审选择',
  codeName: 'review_pick_up_tree_view',
  appDataEntityId: 'plmweb.review',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupTreeView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'library',
      id: 'n_owner_id_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_subtype_eq',
      value: 'library_review',
      id: 'n_owner_subtype_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_type_eq',
      value: 'library',
      id: 'n_owner_type_eq',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 分组',
        },
        {
          childDETreeNodeId: 'node_1',
          parentAppDEFieldId: 'section_id',
          parentDER1N: {
            masterRS: 32,
            pickupDEFName: 'SECTION_ID',
            removeActionType: 2,
            codeName: 'section',
            dertype: 'DER1N',
            logicName: '分组-类别',
            minorCodeName: 'section_categories',
            minorServiceCodeName: 'section_categories',
            orderValue: 100,
            serviceCodeName: 'section',
            name: 'DER1N_CATEGORY_SECTION_SECTION_ID',
            id: 'base.category.der1n_category_section_section_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '分组 - 类别',
        },
        {
          childDETreeNodeId: 'node_2',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 无分组类别',
        },
      ],
      detreeNodes: [
        {
          nodeValue: 'root',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetch_default',
          sortDir: 'ASC',
          sortAppDEFieldId: 'sequence',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'plmweb.section',
          sysImage: {
            cssClass: 'fa fa-table',
            glyph: 'xf0ce@FontAwesome',
          },
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          enableCheck: true,
          expanded: true,
          name: '分组',
          id: 'node',
        },
        {
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetch_default',
          sortDir: 'ASC',
          sortAppDEFieldId: 'sequence',
          textAppDEFieldId: 'name',
          nodeType: 'node_1',
          appDataEntityId: 'plmweb.category',
          sysImage: {
            cssClass: 'fa fa-reorder',
            glyph: 'xf0c9@FontAwesome',
          },
          treeNodeType: 'DE',
          name: '类别',
          id: 'node_1',
        },
        {
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetch_no_section',
          sortDir: 'ASC',
          sortAppDEFieldId: 'sequence',
          textAppDEFieldId: 'name',
          nodeType: 'node_2',
          appDataEntityId: 'plmweb.category',
          sysImage: {
            cssClass: 'fa fa-table',
            glyph: 'xf0ce@FontAwesome',
          },
          treeNodeType: 'DE',
          name: '无分组类别',
          id: 'node_2',
        },
      ],
      outputIconDefault: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.review',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'plmweb.review',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.review',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.review',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.review',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'pick_up_tree_view_tree_view',
      controlType: 'TREEVIEW',
      logicName: '评审选择树视图_树视图',
      appDataEntityId: 'plmweb.review',
      controlParam: {
        id: 'tree',
      },
      modelId: 'F52BEFF3-793A-4B10-8B56-5C03021B629E',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'plmweb.review.pick_up_tree_view_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.review',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.REVIEW.PICK_UP_TREE_VIEW',
      },
      caption: '评审选择',
      codeName: 'pick_up_tree_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.review',
      controlParam: {},
      name: 'captionbar',
      id: 'pick_up_tree_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPTREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.review',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '评审选择',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.REVIEW.PICK_UP_TREE_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPTREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6c74022a32abd22d68d265bbd1cccea7',
  modelType: 'PSAPPDEVIEW',
  name: 'reviewpick_up_tree_view',
  id: 'plmweb.review_pick_up_tree_view',
};
