export default {
  showDataInfoBar: true,
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'tree_exp_view',
  deviewId: 'badaa2908e919e581be28306aff0e341',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RUN',
  },
  caption: '执行用例导航',
  codeName: 'runtree_exp_view',
  appDataEntityId: 'plmweb.run',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        enableBatchAdd: true,
        appDataEntityId: 'plmweb.run',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '全部用例',
          refAppViewId: 'plmweb.rungrid_view_all',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
        {
          parentDataJO: {
            srfparentdefname: 'suite_id',
          },
          realTitle: '全部用例',
          refAppViewId: 'plmweb.rungrid_view_all',
          name: 'EXPITEM:node_2',
          id: 'expitem:node_2',
        },
        {
          parentDataJO: {
            srfparentdefname: 'suite_id',
          },
          realTitle: '全部用例',
          refAppViewId: 'plmweb.rungrid_view_all',
          name: 'EXPITEM:node_3',
          id: 'expitem:node_3',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 全部用例',
            },
            {
              childDETreeNodeId: 'node_3',
              parentAppDEFieldId: 'pid',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PID',
                recursiveRS: true,
                codeName: 'Test_suite',
                dertype: 'DER1N',
                logicName: '模块',
                minorCodeName: 'test_suites',
                minorServiceCodeName: 'test_suites',
                orderValue: 100,
                serviceCodeName: 'Test_suite',
                name: 'DER1N_TEST_SUITE_TEST_SUITE_PID',
                id: 'testmgmt.test_suite.der1n_test_suite_test_suite_pid',
              },
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '子模块 - 子模块',
            },
            {
              childDETreeNodeId: 'node_2',
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '用例模块 - 模块',
            },
            {
              childDETreeNodeId: 'node_3',
              parentAppDEFieldId: 'pid',
              parentDER1N: {
                masterRS: 48,
                pickupDEFName: 'PID',
                recursiveRS: true,
                codeName: 'Test_suite',
                dertype: 'DER1N',
                logicName: '模块',
                minorCodeName: 'test_suites',
                minorServiceCodeName: 'test_suites',
                orderValue: 100,
                serviceCodeName: 'Test_suite',
                name: 'DER1N_TEST_SUITE_TEST_SUITE_PID',
                id: 'testmgmt.test_suite.der1n_test_suite_test_suite_pid',
              },
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '模块 - 子模块',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 用例模块',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '全部用例',
              navAppViewId: 'plmweb.rungrid_view_all',
              nodeType: 'node',
              treeNodeType: 'STATIC',
              name: '全部用例',
              id: 'node',
            },
            {
              text: '用例模块',
              nodeType: 'node_1',
              sysImage: {
                cssClass: 'fa fa-th',
                glyph: 'xf00a@FontAwesome',
              },
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '用例模块',
              id: 'node_1',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchroot',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'suite_id',
              navAppViewId: 'plmweb.rungrid_view_all',
              nodeType: 'node_2',
              appDataEntityId: 'plmweb.test_suite',
              sysImage: {
                cssClass: 'fa fa-table',
                glyph: 'xf0ce@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '模块',
              id: 'node_2',
            },
            {
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'is_leaf',
              appDEDataSetId: 'fetchdefault',
              sortDir: 'ASC',
              sortAppDEFieldId: 'sequence',
              textAppDEFieldId: 'name',
              navFilter: 'suite_id',
              navAppViewId: 'plmweb.rungrid_view_all',
              nodeType: 'node_3',
              appDataEntityId: 'plmweb.test_suite',
              sysImage: {
                cssClass: 'fa fa-navicon',
                glyph: 'xf0c9@FontAwesome',
              },
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              name: '子模块',
              id: 'node_3',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.run',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.run',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.run',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.run',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.run',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'Tree_exp_view_TreeView',
          controlStyle: 'GROUP_TREE',
          controlType: 'TREEVIEW',
          logicName: '执行用例导航视图_树视图',
          appDataEntityId: 'plmweb.run',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'group_tree',
          modelId: 'ea83f171a52efbd975cd769f4322636d',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.run.tree_exp_view_treeview',
        },
      ],
      codeName: 'tree_exp_viewtreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.run',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '68f85392d8f76ec2f02f7797e7eec2cb_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_exp_viewtreeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.run',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RUN',
      },
      caption: '执行用例导航',
      codeName: 'tree_exp_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.run',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_exp_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.run',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '执行用例导航',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '68f85392d8f76ec2f02f7797e7eec2cb',
  modelType: 'PSAPPDEVIEW',
  name: 'runtree_exp_view',
  id: 'plmweb.runtree_exp_view',
};
