export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'tab_search_view',
  deviewId: '871826B8-7D8F-4AFD-90A5-A99B3EDCF3AE',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SEARCH_HUB',
  },
  caption: '高级搜索',
  codeName: 'search_hub_tab_search_view',
  appDataEntityId: 'plmweb.search_hub',
  sysCss: {
    cssName: 'advancedSearch',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '页面标题',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'captionbar',
                          },
                        ],
                        layout: {
                          align: 'center',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        id: 'view_captionbar',
                      },
                    ],
                    predefinedType: 'VIEWHEADER',
                    layout: {
                      align: 'center',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 64,
                    height: 64,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      height: 64,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    id: 'view_header',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '搜索栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'searchbar',
                      },
                    ],
                    layout: {
                      align: 'center',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 46,
                    height: 46,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      height: 46,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    id: 'view_tab_searchbar',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '关系分页部件',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'tabexppanel',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 66,
                    height: 66,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      height: 66,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    id: 'view_tabexppanel',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          predefinedType: 'NAV_POS',
                          id: 'nav_pos',
                        },
                        caption: '导航区占位',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_pos',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'view_nav_pos',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container1',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container3',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  contentType: 'IMAGE',
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabsearchform',
                },
                caption: '占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabsearchform',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 360,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
              width: 360,
              widthMode: 'PX',
            },
            width: 360,
            id: 'container2',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        eventNames: 'onViewMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'searchbar',
        scriptCode:
          "const searchBar = view.getController('searchbar');\r\nif (searchBar) {\r\nsearchBar.state.query = view.params.srfquery ? view.params.srfquery : '';\r\n}",
        builtinLogic: true,
        name: 'VIEWSEARCHBAR',
        id: 'viewsearchbar',
      },
      {
        eventNames: 'onCreated',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, c) => {\r\n    if(name==='tabexppanel'){\r\n        c.state.expViewParams={query: viewParam.srfquery}\r\n    }\r\n});",
        builtinLogic: true,
        name: 'VIEW_CREATED',
        id: 'view_created',
      },
    ],
    controls: [
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        codeName: 'advanced_search_bar',
        controlType: 'SEARCHBAR',
        logicName: '高级搜索栏',
        appDataEntityId: 'plmweb.search_hub',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '2ED65E8E-A88A-42B0-869B-A8FAC66E9D15',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'plmweb.search_hub.advanced_search_bar',
      },
      {
        tabExpPageIds: [
          'work_item',
          'idea',
          'ticket',
          'page',
          'test_case',
          'attachment',
          'comment',
        ],
        tabLayout: 'TOP',
        uniqueTag: 'search_hub_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '工作项高级搜索表格视图',
            refAppViewId: 'plmweb.work_item_advanced_search_grid_view',
            name: 'EXPITEM:work_item',
            id: 'expitem:work_item',
          },
          {
            realTitle: '需求高级搜索表格视图',
            realTitleLanguageRes: {
              lanResTag: 'PAGE.TITLE.IDEA.ADVANCED_SEARCH_GRID_VIEW',
            },
            refAppViewId: 'plmweb.idea_advanced_search_grid_view',
            name: 'EXPITEM:idea',
            id: 'expitem:idea',
          },
          {
            realTitle: '工单高级搜索表格视图',
            refAppViewId: 'plmweb.ticket_advanced_search_grid_view',
            name: 'EXPITEM:ticket',
            id: 'expitem:ticket',
          },
          {
            realTitle: '页面高级搜索表格视图',
            refAppViewId: 'plmweb.article_page_advanced_search_grid_view',
            name: 'EXPITEM:page',
            id: 'expitem:page',
          },
          {
            realTitle: '测试用例高级搜索表格视图',
            refAppViewId: 'plmweb.test_case_advanced_search_grid_view',
            name: 'EXPITEM:test_case',
            id: 'expitem:test_case',
          },
          {
            realTitle: '附件高级搜索表格视图',
            refAppViewId: 'plmweb.search_attachment_advanced_search_grid_view',
            name: 'EXPITEM:attachment',
            id: 'expitem:attachment',
          },
          {
            realTitle: '评论高级搜索表格视图',
            refAppViewId: 'plmweb.search_comment_advanced_search_grid_view',
            name: 'EXPITEM:comment',
            id: 'expitem:comment',
          },
        ],
        controls: [
          {
            caption: '工作项',
            embeddedAppDEViewId: 'plmweb.work_item_advanced_search_grid_view',
            codeName: 'tab_search_view_work_item',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'work_item',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_work_item',
            modelType: 'PSVIEWPANEL',
            name: 'work_item',
            id: 'tab_search_view_work_item',
          },
          {
            caption: '产品需求',
            embeddedAppDEViewId: 'plmweb.idea_advanced_search_grid_view',
            codeName: 'tab_search_view_idea',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'idea',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_idea',
            modelType: 'PSVIEWPANEL',
            name: 'idea',
            id: 'tab_search_view_idea',
          },
          {
            caption: '工单',
            embeddedAppDEViewId: 'plmweb.ticket_advanced_search_grid_view',
            codeName: 'tab_search_view_ticket',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'ticket',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_ticket',
            modelType: 'PSVIEWPANEL',
            name: 'ticket',
            id: 'tab_search_view_ticket',
          },
          {
            caption: '页面',
            embeddedAppDEViewId:
              'plmweb.article_page_advanced_search_grid_view',
            codeName: 'tab_search_view_page',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'page',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_page',
            modelType: 'PSVIEWPANEL',
            name: 'page',
            id: 'tab_search_view_page',
          },
          {
            caption: '测试用例',
            embeddedAppDEViewId: 'plmweb.test_case_advanced_search_grid_view',
            codeName: 'tab_search_view_test_case',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'test_case',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_test_case',
            modelType: 'PSVIEWPANEL',
            name: 'test_case',
            id: 'tab_search_view_test_case',
          },
          {
            caption: '附件',
            embeddedAppDEViewId:
              'plmweb.search_attachment_advanced_search_grid_view',
            codeName: 'tab_search_view_attachment',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'attachment',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_attachment',
            modelType: 'PSVIEWPANEL',
            name: 'attachment',
            id: 'tab_search_view_attachment',
          },
          {
            caption: '评论',
            embeddedAppDEViewId:
              'plmweb.search_comment_advanced_search_grid_view',
            codeName: 'tab_search_view_comment',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.search_hub',
            controlParam: {
              id: 'comment',
            },
            modelId: '556c4c6a79fdaa933dfbde38cf9b7973_comment',
            modelType: 'PSVIEWPANEL',
            name: 'comment',
            id: 'tab_search_view_comment',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'plmweb.search_hub',
        controlParam: {},
        modelId: '556c4c6a79fdaa933dfbde38cf9b7973_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.SEARCH_HUB',
        },
        caption: '高级搜索',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.search_hub',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0329722414',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'search_hub_advanced_search_view布局',
    appDataEntityId: 'plmweb.search_hub',
    controlParam: {},
    modelId: '84FAC10C-55A9-498F-B9B3-C758F7593EB9',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0329722414',
  },
  title: '高级搜索分页视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '556c4c6a79fdaa933dfbde38cf9b7973',
  modelType: 'PSAPPDEVIEW',
  name: 'search_hubtab_search_view',
  id: 'plmweb.search_hub_tab_search_view',
};
