export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'log_grid_view',
  deviewId: 'B65E8A57-6478-4197-A958-9EC9C3702E66',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SPRINT_ALTERATION',
  },
  caption: '变更记录',
  codeName: 'sprint_alteration_log_grid_view',
  appDataEntityId: 'plmweb.sprint_alteration',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'PROJECT',
      value: '42e3898e-d43b-3f3c-611b-87b5e6ed2233',
      name: 'PROJECT',
      id: 'project',
    },
    {
      rawValue: true,
      key: 'SPRINT',
      value: '912e7c4c50122f8edebe1b0c4cd2892b',
      name: 'SPRINT',
      id: 'sprint',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_sprint_id_eq',
      value: 'sprint',
      id: 'n_sprint_id_eq',
    },
    {
      rawValue: true,
      key: 'sort',
      value: 'create_time,desc',
      id: 'sort',
    },
    {
      key: 'sprint',
      value: 'sprint',
      id: 'sprint',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '起始',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text',
                        },
                        caption: '起始',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'static_text',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic',
                        },
                        viewFieldName: 'first_count',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        id: 'field_text_dynamic',
                      },
                    ],
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '面板容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      grow: 4,
                      shrink: 1,
                      layout: 'SIMPLEFLEX',
                    },
                    id: 'container',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '新增',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text1',
                        },
                        caption: '新增',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'static_text1',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic1',
                        },
                        viewFieldName: 'shift_in_count',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        id: 'field_text_dynamic1',
                      },
                    ],
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '面板容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      grow: 4,
                      shrink: 1,
                      layout: 'SIMPLEFLEX',
                    },
                    id: 'container1',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '移出',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text2',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'static_text2',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic2',
                        },
                        viewFieldName: 'shift_out_count',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          colMD: 24,
                          halignSelf: 'CENTER',
                          layout: 'TABLE_24COL',
                        },
                        id: 'field_text_dynamic2',
                      },
                    ],
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '面板容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      grow: 4,
                      shrink: 1,
                      layout: 'SIMPLEFLEX',
                    },
                    id: 'container2',
                  },
                ],
                predefinedType: 'CONTAINER_GRID',
                layout: {
                  layout: 'SIMPLEFLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '栅格容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingBottom: 'OUTERLARGE',
                  spacingTop: 'OUTERLARGE',
                },
                id: 'container_grid',
              },
            ],
            predefinedType: 'CONTAINER_SINGLEDATA',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'SINGLEDATA',
            dataSourceType: 'DEACTION',
            appDEMethodId: 'rep_change',
            appDataEntityId: 'plmweb.sprint_alteration',
            navigateParams: [
              {
                key: 'sprint',
                value: 'sprint',
                id: 'sprint',
              },
            ],
            caption: '单项数据容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_singledata',
          },
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.sprint_alteration_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.sprint_alteration_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'plmweb.sprint_alteration_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.sprint_alteration_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '迭代变更编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.SPRINT_ALTERATION.EDITVIEW',
        },
        refAppViewId: 'plmweb.sprint_alteration_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '迭代变更数据重定向视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.SPRINT_ALTERATION.REDIRECTVIEW',
        },
        refAppViewId: 'plmweb.sprint_alteration_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'work_item_title',
            excelCaption: '标题',
            linkAppViewId: 'plmweb.work_item_redirect_view',
            linkValueItem: 'work_item_id',
            appDEFieldId: 'work_item_title',
            valueType: 'SIMPLE',
            enableLinkView: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '标题',
            codeName: 'work_item_title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'work_item_title',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'work_item_priority',
            excelCaption: '工作项优先级',
            appCodeListId: 'plmweb.projmgmt__work_item_priority',
            appDEFieldId: 'work_item_priority',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '工作项优先级',
            codeName: 'work_item_priority',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'work_item_priority',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'type',
            excelCaption: '操作',
            appCodeListId: 'plmweb.projmgmt__sprint_alteration_type',
            appDEFieldId: 'type',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '操作',
            codeName: 'type',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'type',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'create_man',
            excelCaption: '操作人',
            appCodeListId: 'plmweb.sysoperator',
            appDEFieldId: 'create_man',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.CREATE_MAN',
            },
            caption: '操作人',
            codeName: 'create_man',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_man',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '操作时间',
            appDEFieldId: 'create_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.CREATE_TIME',
            },
            caption: '操作时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'work_item_title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'work_item_title',
          },
          {
            appDEFieldId: 'work_item_priority',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'work_item_priority',
          },
          {
            appDEFieldId: 'type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'type',
          },
          {
            appDEFieldId: 'create_man',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'create_man',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'work_item_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'work_item_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'sprint_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'sprint_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 1000,
        sortMode: 'REMOTE',
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'plmweb.sprint_alteration',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.sprint_alteration',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'plmweb.sprint_alteration',
        controlParam: {
          id: 'grid',
        },
        modelId: '9c1568b09fdc41a6a7637184a7ea3bf6',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.sprint_alteration.main',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.sprint_alteration',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.SPRINT_ALTERATION',
        },
        caption: '变更记录',
        codeName: 'log_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.sprint_alteration',
        controlParam: {},
        name: 'captionbar',
        id: 'log_grid_view_captionbar',
      },
    ],
    codeName: 'usr0618184952',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'log_grid_view表格视图布局',
    appDataEntityId: 'plmweb.sprint_alteration',
    controlParam: {},
    modelId: '473C86BE-9049-404E-8435-C15B57414505',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0618184952',
  },
  title: '迭代变更记录表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '22073805923167076a785de8adca1587',
  modelType: 'PSAPPDEVIEW',
  name: 'sprint_alterationlog_grid_view',
  id: 'plmweb.sprint_alteration_log_grid_view',
};
