export default {
  deviewCodeName: 'base_info_custom_view',
  deviewId: '34ACB6D7-B1AE-4D59-A47B-3DC8EC008648',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SPRINT',
  },
  caption: '基本信息',
  codeName: 'sprint_base_info_custom_view',
  appDataEntityId: 'plmweb.sprint',
  sysCss: {
    cssName: 'sprint-base-info-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'page_container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.sprint',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'plmweb.sprint',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'plmweb.sprint',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'overview',
          appDataEntityId: 'plmweb.sprint',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.sprint',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.sprint',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 6,
                        enableCond: 3,
                        inputTip: '距迭代结束还有',
                        itemHeight: 96,
                        itemWidth: 206,
                        labelPos: 'TOP',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'past_days',
                        editor: {
                          stepValue: 1,
                          editorHeight: 76,
                          editorParams: {
                            showText: 'true',
                            type: 'circle',
                            format: '0天',
                            textItem: 'remaining_days',
                          },
                          editorType: 'SLIDER',
                          editorWidth: 76,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'past_days',
                        },
                        valueFormat: '0天',
                        allowEmpty: true,
                        enableInputTip: true,
                        caption: '日期',
                        codeName: 'past_days',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        controlAttributes: [
                          {
                            attrName: 'width',
                            attrValue: '76',
                            id: 'logic',
                          },
                        ],
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'past_days',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        itemHeight: 96,
                        itemWidth: 206,
                        labelPos: 'TOP',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        editor: {
                          stepValue: 1,
                          editorHeight: 76,
                          editorParams: {
                            showText: 'true',
                            type: 'circle',
                            textItem: 'work_item_counts',
                          },
                          editorType: 'SLIDER',
                          editorWidth: 76,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'work_item_complete_percent',
                        },
                        allowEmpty: true,
                        caption: '工作项',
                        codeName: 'work_item_complete_percent',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        labelCssStyle: 'text-align: center;',
                        controlAttributes: [
                          {
                            attrName: 'width',
                            attrValue: '76',
                            id: 'logic2',
                          },
                        ],
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'work_item_complete_percent',
                      },
                    ],
                    caption: '标签居中分组',
                    codeName: 'group_label_center',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'group_label_center',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'status',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'plmweb.projmgmt__sprint_status',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'status',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    caption: '状态',
                    codeName: 'status',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'status',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'assignee_id',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'plmweb.sysoperator',
                      editorStyle: 'PERSONNEL_INFO',
                      editorType: 'SPAN',
                      sysPFPluginId: 'personnel_info',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'assignee_id',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    caption: '负责人',
                    codeName: 'assignee_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'assignee_id',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'start_at',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'start_at',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '开始时间',
                    codeName: 'start_at',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'start_at',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'end_at',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'end_at',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '结束时间',
                    codeName: 'end_at',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'end_at',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'description',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'description',
                    },
                    allowEmpty: true,
                    caption: '迭代目标',
                    codeName: 'description',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'description',
                  },
                ],
                caption: '迭代基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'overview_baseinfo_form',
        controlType: 'FORM',
        logicName: '迭代概览基本信息_表单',
        appDataEntityId: 'plmweb.sprint',
        controlParam: {
          id: 'form',
        },
        sysCss: {
          cssName: 'base-info-form',
        },
        modelId: 'F558829C-575F-42D6-8543-F792FB803F92',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'plmweb.sprint.overview_baseinfo_form',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.SPRINT',
        },
        caption: '基本信息',
        codeName: 'base_info_custom_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.sprint',
        controlParam: {},
        name: 'captionbar',
        id: 'base_info_custom_view_captionbar',
      },
    ],
    codeName: 'usr0528298628',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '迭代概览基本信息自定义视图布局面板',
    appDataEntityId: 'plmweb.sprint',
    controlParam: {},
    modelId: 'A62019FF-3F6C-454D-B0DC-C08ECB0E36C5',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0528298628',
  },
  title: '迭代概览基本信息自定义视图',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6b820b9d30e488b6068420ba0bb12afe',
  modelType: 'PSAPPDEVIEW',
  name: 'sprintbase_info_custom_view',
  id: 'plmweb.sprint_base_info_custom_view',
};
