export default {
  sideBarLayout: 'TOP',
  showDataInfoBar: true,
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'list_exp_view',
  deviewId: '518fb6c4c19b8c1ce513a956502c4ab1',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.STENCIL',
  },
  caption: '模板中心',
  codeName: 'stencil_list_exp_view',
  height: 90,
  appDataEntityId: 'plmweb.stencil',
  appViewNavContexts: [
    {
      key: 'STENCIL_SPACE',
      value: 'space',
      name: 'STENCIL_SPACE',
      id: 'stencil_space',
    },
    {
      rawValue: true,
      key: 'SPACE',
      name: 'SPACE',
      id: 'space',
    },
  ],
  sysCss: {
    cssName: 'stencil-center-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 78,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              width: 78,
              widthMode: 'PERCENTAGE',
            },
            width: 78,
            id: 'view_exp',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  caption: '模板中心',
                  halign: 'LEFT',
                  renderMode: 'PARAGRAPH',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_LABEL',
                  id: 'page_title',
                },
                caption: '模板中心',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'page_title',
              },
              {
                caption: '列表导航',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'listexpbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId:
                  'panel_usr0312103524_button_calluilogic_click@stencil',
                renderMode: 'BUTTON',
                tooltip: '使用此模板',
                uiactionTarget: 'SINGLEDATA',
                caption: '使用此模板',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'button_calluilogic',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content',
          },
        ],
        predefinedType: 'CONTAINER_H_SPLIT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'ListExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        xdataControlName: 'listexpbar_list',
        enableCounter: true,
        enableSearch: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realOpenMode: 'POPUPMODAL',
            realTitle: '页面模板编辑视图_展示',
            refAppViewId: 'plmweb.stencil_show_edit_view',
            name: 'EXPITEM:DEFAULT',
            id: 'expitem:default',
          },
        ],
        controls: [
          {
            groupMode: 'NONE',
            itemLayoutPanel: {
              layoutMode: 'TABLE_24COL',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              rootPanelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            sysImage: {
                              rawContent:
                                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="design-iconfont" width="32" height="32">\n  <path d="M13.02375,4.213125 C13.13625,4.325625 13.2,4.4775 13.2,4.636875 L13.2,16.2 C13.2,16.531875 12.931875,16.8 12.6,16.8 L0.6,16.8 C0.268125,16.8 0,16.531875 0,16.2 L0,0.6 C0,0.268125 0.268125,0 0.6,0 L8.563125,0 C8.7225,0 8.87625,0.06375 8.98875,0.17625 L13.02375,4.213125 Z M11.81625,4.9125 L8.2875,1.38375 L8.2875,4.9125 L11.81625,4.9125 Z M3,7.8375 C2.91715729,7.8375 2.85,7.90465729 2.85,7.9875 L2.85,8.8875 C2.85,8.97034271 2.91715729,9.0375 3,9.0375 L10.2,9.0375 C10.2828427,9.0375 10.35,8.97034271 10.35,8.8875 L10.35,7.9875 C10.35,7.90465729 10.2828427,7.8375 10.2,7.8375 L3,7.8375 Z M3,10.3875 C2.91715729,10.3875 2.85,10.4546573 2.85,10.5375 L2.85,11.4375 C2.85,11.5203427 2.91715729,11.5875 3,11.5875 L6.45,11.5875 C6.53284271,11.5875 6.6,11.5203427 6.6,11.4375 L6.6,10.5375 C6.6,10.4546573 6.53284271,10.3875 6.45,10.3875 L3,10.3875 Z" transform="translate(3.4 1.6)" fill="#9A7EF4" fill-rule="nonzero"></path>\n</svg>',
                            },
                            contentType: 'IMAGE',
                            predefinedType: 'STATIC_IMAGE',
                            id: 'static_image',
                          },
                          caption: '图片',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysImage: {
                            rawContent:
                              '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="design-iconfont" width="32" height="32">\n  <path d="M13.02375,4.213125 C13.13625,4.325625 13.2,4.4775 13.2,4.636875 L13.2,16.2 C13.2,16.531875 12.931875,16.8 12.6,16.8 L0.6,16.8 C0.268125,16.8 0,16.531875 0,16.2 L0,0.6 C0,0.268125 0.268125,0 0.6,0 L8.563125,0 C8.7225,0 8.87625,0.06375 8.98875,0.17625 L13.02375,4.213125 Z M11.81625,4.9125 L8.2875,1.38375 L8.2875,4.9125 L11.81625,4.9125 Z M3,7.8375 C2.91715729,7.8375 2.85,7.90465729 2.85,7.9875 L2.85,8.8875 C2.85,8.97034271 2.91715729,9.0375 3,9.0375 L10.2,9.0375 C10.2828427,9.0375 10.35,8.97034271 10.35,8.8875 L10.35,7.9875 C10.35,7.90465729 10.2828427,7.8375 10.2,7.8375 L3,7.8375 Z M3,10.3875 C2.91715729,10.3875 2.85,10.4546573 2.85,10.5375 L2.85,11.4375 C2.85,11.5203427 2.91715729,11.5875 3,11.5875 L6.45,11.5875 C6.53284271,11.5875 6.6,11.5203427 6.6,11.4375 L6.6,10.5375 C6.6,10.4546573 6.53284271,10.3875 6.45,10.3875 L3,10.3875 Z" transform="translate(3.4 1.6)" fill="#9A7EF4" fill-rule="nonzero"></path>\n</svg>',
                          },
                          showCaption: true,
                          id: 'static_image',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'name',
                          },
                          viewFieldName: 'name',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'name',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container',
                    },
                  ],
                  layout: {
                    dir: 'column',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'page_container',
                },
              ],
              codeName: 'usr0312321457',
              controlType: 'PANEL',
              logicName: 'List_列表项面板',
              appDataEntityId: 'plmweb.stencil',
              controlParam: {},
              modelId: 'fff4145a98b4c0930a46f8fb8913da7e',
              modelType: 'PSSYSVIEWPANEL',
              name: 'listexpbar_list_itempanel',
              id: 'plmweb.stencil.usr0312321457',
            },
            delistDataItems: [
              {
                appDEFieldId: 'id',
                dataType: 25,
                id: 'srfkey',
              },
              {
                appDEFieldId: 'name',
                dataType: 25,
                id: 'srfmajortext',
              },
              {
                appDEFieldId: 'space_id',
                dataType: 25,
                id: 'space_id',
              },
            ],
            pagingSize: 1000,
            showHeader: true,
            navAppViewId: 'plmweb.stencil_show_edit_view',
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'plmweb.stencil',
              id: 'create',
            },
            fetchControlAction: {
              appDEMethodId: 'fetch_default',
              appDataEntityId: 'plmweb.stencil',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'plmweb.stencil',
              id: 'load',
            },
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'plmweb.stencil',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'plmweb.stencil',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'list_exp_view_list',
            controlType: 'LIST',
            logicName: 'List',
            appDataEntityId: 'plmweb.stencil',
            controlLogics: [
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'listexpbar_list',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'listexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'listexpbar_list',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'listexpbar_load',
              },
            ],
            controlParam: {
              id: 'listexpbar_list',
            },
            modelId: 'a0652e476036b42191e11bb07e4e6d76',
            modelType: 'PSDELIST',
            name: 'listexpbar_list',
            id: 'plmweb.stencil.list_exp_view_list',
          },
        ],
        codeName: 'list_exp_view_listexpbar',
        controlType: 'LISTEXPBAR',
        appDataEntityId: 'plmweb.stencil',
        controlParam: {
          id: 'listexpbar',
        },
        modelId: '5f4904abc83ef3bca749a0a1ee97a287_listexpbar',
        modelType: 'PSEXPBAR',
        name: 'listexpbar',
        id: 'list_exp_view_listexpbar',
      },
      {
        groupMode: 'SINGLE',
        searchBarGroups: [
          {
            caption: '空间',
            data: '{"n_space_id_eq":"%stencil_space%"}',
            itemType: 'GROUP',
            id: 'space_stencil',
          },
          {
            caption: '组织',
            data: '{"n_space_id_isnull":true}',
            itemType: 'GROUP',
            id: 'org_stencil',
          },
        ],
        quickGroupCount: 2,
        quickSearchMode: 1,
        enableGroup: true,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.stencil',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.STENCIL',
        },
        caption: '模板中心',
        codeName: 'list_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.stencil',
        controlParam: {},
        name: 'captionbar',
        id: 'list_exp_view_captionbar',
      },
    ],
    codeName: 'usr0312103524',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'list_exp_view 实体列表导航视图布局面板',
    appDataEntityId: 'plmweb.stencil',
    controlParam: {},
    modelId: '7f8b19caa41cd5f3e29cd1598a77e709',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0312103524',
  },
  title: '页面模板实体列表导航',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTEXPVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: '5f4904abc83ef3bca749a0a1ee97a287',
  modelType: 'PSAPPDEVIEW',
  name: 'stencillist_exp_view',
  id: 'plmweb.stencil_list_exp_view',
};
