export default {
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'copy_test_case_option_view',
  deviewId: 'ac0b46e0370ede09a5de70bbf15e9442',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_CASE',
  },
  caption: '复制用例',
  codeName: 'test_case_copy_test_case_option_view',
  height: 320,
  appDataEntityId: 'plmweb.test_case',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.test_case',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.test_case',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.test_case',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.test_case',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.test_case',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.test_case',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'test_library_name',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'plmweb.testmgmt__library_list',
                    editorType: 'DROPDOWNLIST',
                    editorItems: [
                      {
                        id: 'target_library_id',
                      },
                    ],
                    placeHolder: '请选择测试库',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'test_library_name',
                  },
                  needCodeListConfig: true,
                  caption: '所属测试库',
                  codeName: 'test_library_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'test_library_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'suite_name',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'plmweb.test_suite_pick_up_view',
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'plmweb.test_suite',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'suite_id',
                    editorParams: {
                      PVALUE: 'pid',
                      FILTERMAP: '{"label":"name","value":"id"}',
                      'SRFNAVCTX.library': '%target_library_id%',
                      AC: 'TRUE',
                      'srfnavcxt.test_library': '%target_library_id%',
                      URL: '`/libraries/${data.target_library_id}/test_suites/fetch_default`',
                      PICKUPVIEW: 'TRUE',
                      'srfnavparam.n_test_library_id_eq': '%target_library_id%',
                      METHOD: 'post',
                    },
                    editorStyle: 'MODEL_SELECT',
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'suite_id',
                      },
                    ],
                    sysPFPluginId: 'model_select',
                    placeHolder: '请选择所属模块',
                    valueType: 'SIMPLE',
                    editable: true,
                    navigateContexts: [
                      {
                        key: 'LIBRARY',
                        value: 'target_library_id',
                        name: 'LIBRARY',
                        id: 'library',
                      },
                    ],
                    navigateParams: [
                      {
                        key: 'n_test_library_id_eq',
                        value: 'target_library_id',
                        id: 'n_test_library_id_eq',
                      },
                    ],
                    id: 'suite_name',
                  },
                  resetItemNames: ['test_library_name'],
                  allowEmpty: true,
                  caption: '所属模块',
                  codeName: 'suite_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'suite_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'suite_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'suite_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '用例模块标识',
                  codeName: 'suite_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'suite_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'target_library_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'target_library_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '目标测试库',
                  codeName: 'target_library_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'target_library_id',
                },
              ],
              caption: '用例基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'copy_case_form',
      controlType: 'FORM',
      logicName: '复制用例表单',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'form',
      },
      ctrlMsg: {
        codeName: 'UsrCtrlMsg0228593610',
        ctrlMsgItems: [
          {
            name: 'BEFOREREMOVE_HIDDEN',
            id: 'beforeremove_hidden',
          },
          {
            name: 'CREATESUCCESS_HIDDEN',
            id: 'createsuccess_hidden',
          },
          {
            name: 'UPDATESUCCESS_HIDDEN',
            id: 'updatesuccess_hidden',
          },
        ],
        name: '编辑表单自定义消息(隐藏)',
        id: 'usrctrlmsg0228593610',
      },
      modelId: '1448852e6bf6fb3eb89ec41a158f3671',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.test_case.copy_case_form',
    },
    {
      codeName: 'copy_test_case_option_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'copy_test_case_option_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TEST_CASE',
      },
      caption: '复制用例',
      codeName: 'copy_test_case_option_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {},
      name: 'captionbar',
      id: 'copy_test_case_option_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.test_case',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '复制用例',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 600,
  enableDP: true,
  showCaptionBar: true,
  modelId: '0658d7d4c618b43b1686296aba9db3b3',
  modelType: 'PSAPPDEVIEW',
  name: 'test_casecopy_test_case_option_view',
  id: 'plmweb.test_case_copy_test_case_option_view',
};
