export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'tree_exp_view',
  deviewId: 'dbb8e5f86f3718003eb3eb7cc159b679',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_PLAN',
  },
  caption: '测试计划',
  codeName: 'test_plan_tree_exp_view',
  appDataEntityId: 'plmweb.test_plan',
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'library',
      id: 'n_owner_id_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_subtype_eq',
      value: 'test_plan',
      id: 'n_owner_subtype_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_type_eq',
      value: 'library',
      id: 'n_owner_type_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '树导航栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'treeexpbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_content_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content_right',
          },
        ],
        predefinedType: 'CONTAINER_H_SPLIT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'TreeExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        title: '计划',
        xdataControlName: 'treeexpbar_tree',
        enableCounter: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '全部计划',
            refAppViewId: 'plmweb.test_plan_all_grid_view',
            name: 'EXPITEM:node',
            id: 'expitem:node',
          },
          {
            realTitle: '全部计划',
            refAppViewId: 'plmweb.test_plan_all_grid_view',
            name: 'EXPITEM:node_2',
            id: 'expitem:node_2',
          },
          {
            realTitle: '全部计划',
            refAppViewId: 'plmweb.test_plan_all_grid_view',
            name: 'EXPITEM:node_3',
            id: 'expitem:node_3',
          },
          {
            parentDataJO: {
              srfparentdefname: 'TYPE',
            },
            realTitle: '全部计划',
            refAppViewId: 'plmweb.test_plan_all_grid_view',
            name: 'EXPITEM:node_6',
            id: 'expitem:node_6',
          },
        ],
        controls: [
          {
            detreeNodeRSs: [
              {
                childDETreeNodeId: 'node_2',
                parentAppDEFieldId: 'section_id',
                parentDER1N: {
                  masterRS: 32,
                  pickupDEFName: 'SECTION_ID',
                  removeActionType: 1,
                  codeName: 'section',
                  dertype: 'DER1N',
                  logicName: '分组-类别',
                  minorCodeName: 'section_categories',
                  minorServiceCodeName: 'section_categories',
                  orderValue: 100,
                  serviceCodeName: 'section',
                  name: 'DER1N_CATEGORY_SECTION_SECTION_ID',
                  id: 'base.category.der1n_category_section_section_id',
                },
                parentDETreeNodeId: 'node_1',
                parentValueLevel: 1,
                searchMode: 3,
                id: '计划分组 - 计划类型',
              },
              {
                childDETreeNodeId: 'node',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 全部计划',
              },
              {
                childDETreeNodeId: 'node_6',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 测试分类',
              },
              {
                childDETreeNodeId: 'node_1',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 计划分组',
              },
              {
                childDETreeNodeId: 'node_3',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 无分组',
              },
            ],
            detreeNodes: [
              {
                text: '默认根节点',
                nodeType: 'ROOT',
                treeNodeType: 'STATIC',
                hasDETreeNodeRSs: true,
                rootNode: true,
                name: '默认根节点',
                id: 'root',
              },
              {
                text: '全部计划',
                navAppViewId: 'plmweb.test_plan_all_grid_view',
                nodeType: 'node',
                sysImage: {
                  cssClass: 'fa fa-th-large',
                  glyph: 'xf009@FontAwesome',
                },
                treeNodeType: 'STATIC',
                name: '全部计划',
                id: 'node',
              },
              {
                idAppDEFieldId: 'id',
                leafFlagAppDEFieldId: 'is_leaf',
                appDEDataSetId: 'fetch_default',
                sortDir: 'ASC',
                sortAppDEFieldId: 'sequence',
                textAppDEFieldId: 'name',
                nodeType: 'node_1',
                appDataEntityId: 'plmweb.section',
                decontextMenu: {
                  detoolbarItems: [
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node1_cm_deuiaction1_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '编辑',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-edit',
                        glyph: 'xf044@FontAwesome',
                      },
                      tooltip: '编辑',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction1',
                    },
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node1_cm_deuiaction2_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '删除',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-trash-o',
                        glyph: 'xf014@FontAwesome',
                      },
                      tooltip: '删除',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction2',
                    },
                  ],
                  toolbarStyle: 'CONTEXTMENU',
                  codeName: 'tree_exp_view_node1_cm',
                  controlType: 'CONTEXTMENU',
                  logicName: '树节点上下文菜单',
                  appDataEntityId: 'plmweb.test_plan',
                  controlParam: {
                    id: 'node_1_cm',
                  },
                  modelId: '5fc332fd876eb8801c95133d9458183b',
                  modelType: 'PSDETOOLBAR',
                  name: 'node_1_cm',
                  id: 'tree_exp_view_node1_cm',
                },
                sysImage: {
                  cssClass: 'fa fa-table',
                  glyph: 'xf0ce@FontAwesome',
                },
                treeNodeType: 'DE',
                hasDETreeNodeRSs: true,
                allowDrag: true,
                allowDrop: true,
                allowEditText: true,
                allowOrder: true,
                expanded: true,
                name: '计划分组',
                id: 'node_1',
              },
              {
                idAppDEFieldId: 'id',
                leafFlagAppDEFieldId: 'is_leaf',
                appDEDataSetId: 'fetch_default',
                sortDir: 'ASC',
                sortAppDEFieldId: 'sequence',
                textAppDEFieldId: 'name',
                navAppViewId: 'plmweb.test_plan_all_grid_view',
                nodeType: 'node_2',
                appDataEntityId: 'plmweb.category',
                decontextMenu: {
                  detoolbarItems: [
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node2_cm_deuiaction1_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '编辑',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-edit',
                        glyph: 'xf044@FontAwesome',
                      },
                      tooltip: '编辑',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction1',
                    },
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node2_cm_deuiaction2_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '删除',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-trash-o',
                        glyph: 'xf014@FontAwesome',
                      },
                      tooltip: '删除',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction2',
                    },
                  ],
                  toolbarStyle: 'CONTEXTMENU',
                  codeName: 'tree_exp_view_node2_cm',
                  controlType: 'CONTEXTMENU',
                  logicName: '树节点上下文菜单',
                  appDataEntityId: 'plmweb.test_plan',
                  controlParam: {
                    id: 'node_2_cm',
                  },
                  modelId: '5fc332fd876eb8801c95133d9458183b',
                  modelType: 'PSDETOOLBAR',
                  name: 'node_2_cm',
                  id: 'tree_exp_view_node2_cm',
                },
                navigateParams: [
                  {
                    key: 'n_categories_like',
                    value: 'id',
                    id: 'n_categories_like',
                  },
                ],
                sysImage: {
                  cssClass: 'fa fa-navicon',
                  glyph: 'xf0c9@FontAwesome',
                },
                treeNodeType: 'DE',
                allowDrag: true,
                allowEditText: true,
                allowOrder: true,
                expanded: true,
                name: '计划类型',
                id: 'node_2',
              },
              {
                idAppDEFieldId: 'id',
                leafFlagAppDEFieldId: 'is_leaf',
                appDEDataSetId: 'fetch_no_section',
                sortDir: 'ASC',
                sortAppDEFieldId: 'sequence',
                textAppDEFieldId: 'name',
                navAppViewId: 'plmweb.test_plan_all_grid_view',
                nodeType: 'node_3',
                appDataEntityId: 'plmweb.category',
                decontextMenu: {
                  detoolbarItems: [
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node3_cm_deuiaction1_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '编辑',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-edit',
                        glyph: 'xf044@FontAwesome',
                      },
                      tooltip: '编辑',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction1',
                    },
                    {
                      actionLevel: 100,
                      noPrivDisplayMode: 2,
                      uiactionId:
                        'toolbar_tree_exp_view_node3_cm_deuiaction2_click@test_plan',
                      uiactionTarget: 'SINGLEDATA',
                      valid: true,
                      caption: '删除',
                      itemType: 'DEUIACTION',
                      sysImage: {
                        cssClass: 'fa fa-trash-o',
                        glyph: 'xf014@FontAwesome',
                      },
                      tooltip: '删除',
                      showCaption: true,
                      showIcon: true,
                      id: 'deuiaction2',
                    },
                  ],
                  toolbarStyle: 'CONTEXTMENU',
                  codeName: 'tree_exp_view_node3_cm',
                  controlType: 'CONTEXTMENU',
                  logicName: '树节点上下文菜单',
                  appDataEntityId: 'plmweb.test_plan',
                  controlParam: {
                    id: 'node_3_cm',
                  },
                  modelId: '5fc332fd876eb8801c95133d9458183b',
                  modelType: 'PSDETOOLBAR',
                  name: 'node_3_cm',
                  id: 'tree_exp_view_node3_cm',
                },
                navigateParams: [
                  {
                    key: 'n_categoryies_like',
                    value: 'id',
                    id: 'n_categoryies_like',
                  },
                ],
                sysImage: {
                  cssClass: 'fa fa-navicon',
                  glyph: 'xf0c9@FontAwesome',
                },
                treeNodeType: 'DE',
                allowDrag: true,
                allowEditText: true,
                allowOrder: true,
                name: '无分组',
                id: 'node_3',
              },
              {
                codeListId: 'plmweb.testmgmt__test_plan_type',
                navFilter: 'TYPE',
                navAppViewId: 'plmweb.test_plan_all_grid_view',
                nodeType: 'node_6',
                sysImage: {
                  cssClass: 'fa fa-bars',
                  glyph: 'xf0c9@FontAwesome',
                },
                treeNodeType: 'CODELIST',
                name: '测试分类',
                id: 'node_6',
              },
            ],
            outputIconDefault: true,
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'plmweb.test_plan',
              id: 'create',
            },
            fetchControlAction: {
              appDataEntityId: 'plmweb.test_plan',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'plmweb.test_plan',
              id: 'load',
            },
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'plmweb.test_plan',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'plmweb.test_plan',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            controls: [
              {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node1_cm_deuiaction1_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '编辑',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '编辑',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node1_cm_deuiaction2_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'tree_exp_view_node1_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点上下文菜单',
                appDataEntityId: 'plmweb.test_plan',
                controlParam: {
                  id: 'node_1_cm',
                },
                modelId: '5fc332fd876eb8801c95133d9458183b',
                modelType: 'PSDETOOLBAR',
                name: 'node_1_cm',
                id: 'tree_exp_view_node1_cm',
              },
              {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node3_cm_deuiaction1_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '编辑',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '编辑',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node3_cm_deuiaction2_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'tree_exp_view_node3_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点上下文菜单',
                appDataEntityId: 'plmweb.test_plan',
                controlParam: {
                  id: 'node_3_cm',
                },
                modelId: '5fc332fd876eb8801c95133d9458183b',
                modelType: 'PSDETOOLBAR',
                name: 'node_3_cm',
                id: 'tree_exp_view_node3_cm',
              },
              {
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node2_cm_deuiaction1_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '编辑',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-edit',
                      glyph: 'xf044@FontAwesome',
                    },
                    tooltip: '编辑',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_node2_cm_deuiaction2_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-trash-o',
                      glyph: 'xf014@FontAwesome',
                    },
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'tree_exp_view_node2_cm',
                controlType: 'CONTEXTMENU',
                logicName: '树节点上下文菜单',
                appDataEntityId: 'plmweb.test_plan',
                controlParam: {
                  id: 'node_2_cm',
                },
                modelId: '5fc332fd876eb8801c95133d9458183b',
                modelType: 'PSDETOOLBAR',
                name: 'node_2_cm',
                id: 'tree_exp_view_node2_cm',
              },
            ],
            codeName: 'tree_exp_view_tree_view',
            controlStyle: 'GROUP_TREE',
            controlType: 'TREEVIEW',
            logicName: '测试计划导航视图_树视图',
            appDataEntityId: 'plmweb.test_plan',
            controlLogics: [
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_load',
              },
            ],
            controlParam: {
              id: 'treeexpbar_tree',
            },
            sysPFPluginId: 'group_tree',
            modelId: 'b8a3676843669cc6507a4225a17817e2',
            modelType: 'PSDETREEVIEW',
            name: 'treeexpbar_tree',
            id: 'plmweb.test_plan.tree_exp_view_tree_view',
          },
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_treeexpbar_toolbar_deuiaction1_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '新建分组',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-navicon',
                      glyph: 'xf0c9@FontAwesome',
                    },
                    tooltip: '新建分组',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_tree_exp_view_treeexpbar_toolbar_deuiaction2_click@test_plan',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '新建类别',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-navicon',
                      glyph: 'xf0c9@FontAwesome',
                    },
                    tooltip: '新建类别',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                ],
                valid: true,
                caption: '新建',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-plus',
                  glyph: 'xf067@FontAwesome',
                },
                tooltip: '新建',
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'refreshall',
                valid: true,
                caption: '刷新',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-refresh',
                  glyph: 'xf021@FontAwesome',
                },
                tooltip: '刷新',
                showIcon: true,
                id: 'deuiaction3',
              },
            ],
            toolbarStyle: 'USER',
            codeName: 'tree_exp_view_treeexpbar_toolbar',
            controlType: 'TOOLBAR',
            logicName: '新建类别或分组',
            appDataEntityId: 'plmweb.test_plan',
            controlParam: {
              id: 'treeexpbar_toolbar',
            },
            modelId: 'aa36066fa7f401983dc5452878401b0d',
            modelType: 'PSDETOOLBAR',
            name: 'treeexpbar_toolbar',
            id: 'tree_exp_view_treeexpbar_toolbar',
          },
        ],
        codeName: 'tree_exp_view_treeexpbar',
        controlType: 'TREEEXPBAR',
        appDataEntityId: 'plmweb.test_plan',
        controlParam: {
          id: 'treeexpbar',
        },
        modelId: '0f1808c6283a4de765cff91d9c7cb29b_treeexpbar',
        modelType: 'PSEXPBAR',
        name: 'treeexpbar',
        id: 'tree_exp_view_treeexpbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.test_plan',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.TEST_PLAN',
        },
        caption: '测试计划',
        codeName: 'tree_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.test_plan',
        controlParam: {},
        name: 'captionbar',
        id: 'tree_exp_view_captionbar',
      },
    ],
    codeName: 'usr0220977732',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'tree_exp_view实体树导航视图布局面板',
    appDataEntityId: 'plmweb.test_plan',
    controlParam: {},
    modelId: '1419959da4aa916a2f971dda48520b79',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0220977732',
  },
  title: '测试计划',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '0f1808c6283a4de765cff91d9c7cb29b',
  modelType: 'PSAPPDEVIEW',
  name: 'test_plantree_exp_view',
  id: 'plmweb.test_plan_tree_exp_view',
};
