export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'test_all_grid_view',
  deviewId: '0ac1652affce44be3ad56d6af76615d7',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_CASE',
  },
  caption: '用例',
  codeName: 'test_case_test_all_grid_view',
  appDataEntityId: 'plmweb.test_case',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.test_case_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.test_case_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.test_case_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.test_case_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '用例编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TEST_CASE.EDITVIEW',
      },
      refAppViewId: 'plmweb.test_case_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '用例数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TEST_CASE.REDIRECTVIEW',
      },
      refAppViewId: 'plmweb.test_case_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'grid',
      codeName: 'test_all_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '测试用例表格视图_工具栏',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fa07f1140343b4c93372358c7ee8931f',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'test_all_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '移入计划',
                detailType: 'DEUIACTION',
                uiactionId: 'case_move_plan@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-send-o',
                  glyph: 'xf1d9@FontAwesome',
                },
                id: 'uf6b66e1',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '复制用例',
                detailType: 'DEUIACTION',
                uiactionId: 'copy_test_case@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-copy',
                  glyph: 'xf0c5@FontAwesome',
                },
                id: 'uc5b9282',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '移动',
                detailType: 'DEUIACTION',
                uiactionId: 'move@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-arrows',
                  glyph: 'xf047@FontAwesome',
                },
                id: 'ue6692cd',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'delete@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'u87a0321',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '界面行为支持获取编辑列',
                detailType: 'DEUIACTION',
                uiactionId: 'get_editor_column',
                showCaption: true,
                showIcon: true,
                id: 'u06706db',
              },
            ],
            appDataEntityId: 'plmweb.test_case',
            uniqueTag: 'test_case__Usr1220537977',
            name: '主表格操作列',
            id: 'usr1220537977',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'title',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'maintenance_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'maintenance_id',
        },
        {
          appDEFieldId: 'test_library_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'test_library_id',
        },
        {
          appDEFieldId: 'suite_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'suite_id',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.test_case',
        id: 'fetch',
      },
      dedataImportId: 'import_test_case',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.test_case',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'test_grid_view_all_grid',
      controlType: 'GRID',
      logicName: '测试用例表格视图_表格',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'grid',
      },
      modelId: '3ab215a2914e1827d5ca385d9cc38f09',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.test_case.test_grid_view_all_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'test_grid_view_all_search_form',
      controlType: 'SEARCHFORM',
      logicName: '测试用例表格视图_搜索表单',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'searchform',
      },
      modelId: '098e29cd8df63c511d2b512f348fe437',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.test_case.test_grid_view_all_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TEST_CASE',
      },
      caption: '用例',
      codeName: 'test_all_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {},
      name: 'captionbar',
      id: 'test_all_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.test_case',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试用例表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '9e19bb3dd20d20134ab595b447b19ba6',
  modelType: 'PSAPPDEVIEW',
  name: 'test_casetest_all_grid_view',
  id: 'plmweb.test_case_test_all_grid_view',
};
