export default {
  redirectAppViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '测试计划编辑视图',
      refAppViewId: 'plmweb.test_plan_update_option_view',
      name: 'TEST_PLAN:EDITVIEW',
      id: 'test_plan:editview',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '测试计划编辑视图',
      refAppViewId: 'plmweb.test_plan_update_option_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '6f6434d849d5ba1db938d5d643b9f560',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_PLAN',
  },
  caption: '测试计划',
  codeName: 'test_plan_redirect_view',
  appDataEntityId: 'plmweb.test_plan',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TEST_PLAN',
      },
      caption: '测试计划',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.test_plan',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.test_plan',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试计划数据重定向视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.TEST_PLAN.REDIRECTVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: '2f728a41143a2a2b97e5b66cc4ab1d1c',
  modelType: 'PSAPPDEVIEW',
  name: 'test_planRedirectView',
  id: 'plmweb.test_plan_redirect_view',
};
