export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'nosuite_test_case_grid_view',
  deviewId: 'b94d7b59cb3d34711ef0a53a375e0545',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_CASE',
  },
  caption: '用例',
  codeName: 'test_casenosuite_test_case_grid_view',
  appDataEntityId: 'plmweb.test_case',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.test_caseeditview',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.test_caseeditview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'plmweb.test_caseredirectview',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.test_caseredirectview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '用例数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TEST_CASE.REDIRECTVIEW',
      },
      refAppViewId: 'plmweb.test_caseredirectview',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '用例编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TEST_CASE.EDITVIEW',
      },
      refAppViewId: 'plmweb.test_caseeditview',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'new',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建用例',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建用例',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import',
              valid: true,
              caption: '导入用例',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-upload',
                glyph: 'xf093@FontAwesome',
              },
              tooltip: '导入用例',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'exportexcel',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.EXPORT',
              },
              caption: '导出用例',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-excel-o',
                glyph: 'xf1c3@FontAwesome',
              },
              tooltip: '导出用例',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.EXPORT',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-list-ul',
            glyph: 'xf0ca@FontAwesome',
          },
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'nosuite_test_case_grid_viewtoolbar',
      controlType: 'TOOLBAR',
      logicName: '新建用例',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'f93a13fe4519e5faee8a76c35e4867ab',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'nosuite_test_case_grid_viewtoolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      frozenFirstColumn: 2,
      groupMode: 'NONE',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 80,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '移入计划',
                detailType: 'DEUIACTION',
                uiactionId: 'case_move_plan@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-send-o',
                  glyph: 'xf1d9@FontAwesome',
                },
                id: 'uf6b66e1',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.COPY',
                },
                caption: '复制',
                detailType: 'DEUIACTION',
                uiactionId: 'copy',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.COPY',
                },
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-copy',
                  glyph: 'xf0c5@FontAwesome',
                },
                id: 'u86cee9d',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '移动',
                detailType: 'DEUIACTION',
                uiactionId: 'move@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-arrows',
                  glyph: 'xf047@FontAwesome',
                },
                id: 'ue6692cd',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'delete@test_case',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'u87a0321',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '界面行为支持获取编辑列',
                detailType: 'DEUIACTION',
                uiactionId: 'get_editor_column',
                showCaption: true,
                showIcon: true,
                id: 'u06706db',
              },
            ],
            uniqueTag: 'Test_case__Usr1220537977',
            name: '主表格操作列',
            id: 'usr1220537977',
          },
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          sysPFPluginId: 'column_action_edit',
          width: 300,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'title',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state',
          excelCaption: '评审状态',
          appCodeListId: 'plmweb.testmgmt__test_case_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '评审状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'maintenance_name',
          excelCaption: '维护人',
          linkAppViewId: 'plmweb.userredirectview',
          linkValueItem: 'maintenance_id',
          appDEFieldId: 'maintenance_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '维护人',
          codeName: 'maintenance_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'maintenance_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'level',
          excelCaption: '重要程度',
          appCodeListId: 'plmweb.testmgmt__test_case_level',
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '重要程度',
          codeName: 'level',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'level',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type',
          excelCaption: '用例类型',
          appCodeListId: 'plmweb.testmgmt__test_case_type',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '用例类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'suite_name',
          excelCaption: '所属模块',
          appDEFieldId: 'suite_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '所属模块',
          codeName: 'suite_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'suite_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'create_man',
          excelCaption: '建立人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeName: 'create_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '建立时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'maintenance_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'maintenance_name',
        },
        {
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'level',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'suite_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'suite_name',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'create_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'maintenance_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'maintenance_id_text',
        },
        {
          appDEFieldId: 'maintenance_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'maintenance_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'test_library_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'test_library_id',
        },
        {
          appDEFieldId: 'suite_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'suite_id',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标题',
          codeName: 'title',
          enableCond: 3,
          appDEFieldId: 'title',
          editor: {
            maxLength: 500,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'title',
          },
          allowEmpty: true,
          id: 'title',
        },
        {
          caption: '评审状态',
          codeName: 'state',
          enableCond: 3,
          appDEFieldId: 'state',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.testmgmt__test_case_state',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'state',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'state',
        },
        {
          caption: '维护人',
          codeName: 'maintenance_name',
          enableCond: 3,
          appDEFieldId: 'maintenance_name',
          editor: {
            singleSelect: true,
            appDEACModeId: 'member_select',
            appDEDataSetId: 'fetchdefault',
            appDataEntityId: 'plmweb.library_member',
            uiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '跳转至成员设置',
                  detailType: 'DEUIACTION',
                  uiactionId: 'jump_to_member_set@library_member',
                  tooltip: '跳转至成员设置',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-user-md',
                    glyph: 'xf0f0@FontAwesome',
                  },
                  id: 'u23c0102',
                },
              ],
              uniqueTag: 'Library_member__Usr0311619181',
              name: '跳转至成员设置',
              id: 'usr0311619181',
            },
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'maintenance_id',
            editorParams: {
              'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
              AC: 'TRUE',
              TRIGGER: 'TRUE',
              URL: 'libraries/${context.library}/library_members/fetchdefault',
              PICKUPVIEW: 'FALSE',
              USERMETHOD: 'post',
              USERMAP: '{"id":"user_id","name":"name"}',
              DEPTMAP: '{"id":"id","name":"display_name"}',
              DEPTMETHOD: 'get',
              DEPTURL: '/users/fetchdefault',
            },
            editorStyle: 'PERSONEL_SELECT_LIBRARY',
            editorType: 'PICKEREX_TRIGGER',
            editorItems: [
              {
                id: 'maintenance_id',
              },
            ],
            sysPFPluginId: 'person_select',
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_department_id_eq',
                value: 'srforgsectorid',
                id: 'n_department_id_eq',
              },
            ],
            id: 'maintenance_name',
          },
          allowEmpty: true,
          id: 'maintenance_name',
        },
        {
          caption: '重要程度',
          codeName: 'level',
          enableCond: 3,
          appDEFieldId: 'level',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.testmgmt__test_case_level',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'level',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'level',
        },
        {
          caption: '用例类型',
          codeName: 'type',
          enableCond: 3,
          appDEFieldId: 'type',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.testmgmt__test_case_type',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'type',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'type',
        },
        {
          caption: '维护人',
          codeName: 'maintenance_id',
          enableCond: 3,
          appDEFieldId: 'maintenance_id',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.testmgmt__library_member',
            editorType: 'DROPDOWNLIST',
            editorItems: [
              {
                appDEACModeId: 'default',
                appDEDataSetId: 'fetchdefault',
                appDataEntityId: 'plmweb.user',
                id: 'maintenance_id',
              },
            ],
            valueType: 'SIMPLE',
            editable: true,
            id: 'maintenance_id',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'maintenance_id',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      fetchControlAction: {
        appDEMethodId: 'fetchnosuite_test_case',
        appDataEntityId: 'plmweb.test_case',
        id: 'fetch',
      },
      dedataImportId: 'import_test_case',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.test_case',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'set_maintenance@test_case',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '设置维护人',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-user-plus',
                glyph: 'xf234@FontAwesome',
              },
              tooltip: '设置维护人',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'set_state@test_case',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '设置评审状态',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-edit',
                glyph: 'xf044@FontAwesome',
              },
              tooltip: '设置评审状态',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'set_level@test_case',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '设置重要程度',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-flag-o',
                glyph: 'xf11d@FontAwesome',
              },
              tooltip: '设置重要程度',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'case_move_plan@test_case',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '移入计划',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-send-o',
                glyph: 'xf1d9@FontAwesome',
              },
              tooltip: '移入计划',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction4',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'copy_test_case@test_case',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '复制',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-copy',
                    glyph: 'xf0c5@FontAwesome',
                  },
                  tooltip: '复制',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction7',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'move_idea@test_case',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '移动',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-arrows-alt',
                    glyph: 'xf0b2@FontAwesome',
                  },
                  tooltip: '移动',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction8',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'delete@test_case',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction9',
                },
              ],
              valid: true,
              caption: '更多',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-list-ul',
                glyph: 'xf0ca@FontAwesome',
              },
              tooltip: '更多',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
          ],
          codeName: 'nosuite_test_case_grid_viewgrid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作工具栏',
          appDataEntityId: 'plmweb.test_case',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: '53c82b535f8b4f3e0767aad6c75cb2fe',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'nosuite_test_case_grid_viewgrid_batchtoolbar',
        },
      ],
      codeName: 'Main',
      controlStyle: 'NUMBER_GRID',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'grid',
      },
      sysPFPluginId: 'number_grid',
      modelId: '2f74aa1a36e38370175a007f08558639',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.test_case.main',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TEST_CASE',
      },
      caption: '用例',
      codeName: 'nosuite_test_case_grid_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.test_case',
      controlParam: {},
      name: 'captionbar',
      id: 'nosuite_test_case_grid_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.test_case',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '无模块用例表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1601cd27590dbd58f0e0c186c3f8cfc7',
  modelType: 'PSAPPDEVIEW',
  name: 'test_casenosuite_test_case_grid_view',
  id: 'plmweb.test_casenosuite_test_case_grid_view',
};
