export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'tree_exp_view_project',
  deviewId: 'FFFE5FC0-3C77-4EF3-85F5-8C552B437060',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TEST_PLAN',
  },
  caption: '测试计划',
  codeName: 'test_plantree_exp_view_project',
  appDataEntityId: 'plmweb.test_plan',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      key: 'project_id',
      value: 'project',
      id: 'project_id',
    },
  ],
  controls: [
    {
      title: '测试计划',
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '测试计划表格视图（项目）',
          refAppViewId: 'plmweb.test_plangrid_view_project',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
        {
          realTitle: '测试计划表格视图（项目）',
          refAppViewId: 'plmweb.test_plangrid_view_project',
          name: 'EXPITEM:node_1',
          id: 'expitem:node_1',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 全部计划',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 测试库',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '全部计划',
              navAppViewId: 'plmweb.test_plangrid_view_project',
              nodeType: 'node',
              navigateParams: [
                {
                  key: 'n_project_id_eq',
                  value: 'project',
                  id: 'n_project_id_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-th-large',
                glyph: 'xf009@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '全部计划',
              id: 'node',
            },
            {
              idAppDEFieldId: 'id',
              appDEDataSetId: 'fetchproject_relation_library',
              textAppDEFieldId: 'name',
              navAppViewId: 'plmweb.test_plangrid_view_project',
              nodeType: 'node_1',
              appDataEntityId: 'plmweb.library',
              navigateParams: [
                {
                  key: 'n_library_id_eq',
                  value: 'id',
                  id: 'n_library_id_eq',
                },
                {
                  key: 'n_project_id_eq',
                  value: 'project',
                  id: 'n_project_id_eq',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-cubes',
                glyph: 'xf1b3@FontAwesome',
              },
              treeNodeType: 'DE',
              name: '测试库',
              id: 'node_1',
            },
          ],
          outputIconDefault: true,
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.test_plan',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.test_plan',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.test_plan',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.test_plan',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.test_plan',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'Tree_exp_view_project_TreeView',
          controlStyle: 'GROUP_TREE',
          controlType: 'TREEVIEW',
          logicName: '测试计划树导航视图（项目）_树视图',
          appDataEntityId: 'plmweb.test_plan',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'group_tree',
          modelId: '4FEE5ED7-AA48-4C95-80ED-56693125ED10',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.test_plan.tree_exp_view_project_treeview',
        },
      ],
      codeName: 'tree_exp_view_projecttreeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.test_plan',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '94ebeccdf1ee1455652e15f0e23f242b_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_exp_view_projecttreeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.test_plan',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TEST_PLAN',
      },
      caption: '测试计划',
      codeName: 'tree_exp_view_projectcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.test_plan',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_exp_view_projectcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.test_plan',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '测试计划树导航视图（项目）',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '94ebeccdf1ee1455652e15f0e23f242b',
  modelType: 'PSAPPDEVIEW',
  name: 'test_plantree_exp_view_project',
  id: 'plmweb.test_plantree_exp_view_project',
};
