export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'customer_re_ticket_grid_view',
  deviewId: 'A7B44413-8414-4FD8-8E21-9D442A5C04D6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TICKET',
  },
  caption: '工单',
  codeName: 'ticketcustomer_re_ticket_grid_view',
  appDataEntityId: 'plmweb.ticket',
  appViewNavParams: [
    {
      key: 'n_customer_id_eq',
      value: 'customer',
      id: 'n_customer_id_eq',
    },
    {
      key: 'product_id',
      value: 'product',
      id: 'product_id',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'total',
                    },
                    viewFieldName: 'total',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'INNERMEDIUM',
                    },
                    id: 'total',
                  },
                  {
                    rawItem: {
                      caption: '个工单',
                      halign: 'LEFT',
                      renderMode: 'TEXT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_text',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        editor: {
          enablePickupView: true,
          singleSelect: true,
          pickupAppViewId: 'plmweb.ticketcustomer_re_ticket_pick_up_view',
          appDEACModeId: 'customer_create_ticket',
          appDEDataSetId: 'fetchrecent_curproduct_ticket',
          appDataEntityId: 'plmweb.recent',
          uiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '新建',
                detailType: 'DEUIACTION',
                uiactionId: 'customer_create_ticket@recent',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-plus',
                  glyph: 'xf067@FontAwesome',
                },
                id: 'u2d1c389',
              },
            ],
            uniqueTag: 'Recent__Usr0202267187',
            name: '新建工单（客户）',
            id: 'usr0202267187',
          },
          enableAC: true,
          forceSelection: true,
          showTrigger: true,
          editorParams: {
            'srfnavparam.principal_id': '%principal_id%',
            'srfnavparam.size': '20',
            lastlabel: '更多工单',
            AC: 'TRUE',
            'srfnavparam.N_RECENT_PARENT_EQ': '%product_id%',
            toplabel: '最近浏览',
            PICKUPVIEW: 'TRUE',
          },
          editorStyle: 'MANAGE',
          editorType: 'PICKER',
          sysPFPluginId: 'manage',
          placeHolder: '添加关联工单，点击确定按钮保存',
          predefinedType: 'FIELD_TEXT_DYNAMIC',
          valueType: 'SIMPLE',
          editable: true,
          navigateParams: [
            {
              key: 'principal_id',
              value: 'principal_id',
              id: 'principal_id',
            },
            {
              key: 'size',
              value: '20',
              rawValue: true,
              id: 'size',
            },
            {
              key: 'n_recent_parent_eq',
              value: 'product_id',
              id: 'n_recent_parent_eq',
            },
          ],
          id: 'choose_data',
        },
        allowEmpty: true,
        caption: '文本(动态)',
        itemStyle: 'DEFAULT',
        itemType: 'FIELD',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
          spacingBottom: 'INNERMEDIUM',
          spacingLeft: 'INNERMEDIUM',
          spacingRight: 'INNERMEDIUM',
          spacingTop: 'INNERMEDIUM',
        },
        id: 'choose_data',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.layoutPanel.panelItems.choose_data.state.visible = false;\n\n// 初始化默认隐藏表格\nview.layoutPanel.panelItems.grid.state.keepAlive = true;\nview.layoutPanel.panelItems.grid.state.visible = false;\nconst form = view.getController('form');\nconsole.log('项显示逻辑执行了')\nif (form) {\n    form.evt.on('onFormDetailEvent', event =>{\n        const panelItems = view.layoutPanel.panelItems;\n        if (!panelItems.comment) {\n            return;\n        }\n        if (event.formDetailName === 'tabpage1') {\n            panelItems.comment.state.visible = true;\n        } else {\n            panelItems.comment.state.visible = false;\n        }\n    });\n}\n\n// 初始化隐藏发送和清空按钮\nview.layoutPanel.panelItems.button_calluilogic1.state.visible = false\nview.layoutPanel.panelItems.button_calluilogic.state.visible = false",
        builtinLogic: true,
        id: 'viewmounted',
      },
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'VIEWEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'get_idea_total',
        appDataEntityId: 'plmweb.idea',
        builtinLogic: true,
        id: 'onloadsuccess',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.ticketeditview',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.ticketeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            navigateContexts: [
              {
                key: 'PRODUCT',
                value: 'product_id',
                name: 'PRODUCT',
                id: 'product',
              },
            ],
            refAppViewId: 'plmweb.ticketmain_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              navigateContexts: [
                {
                  key: 'PRODUCT',
                  value: 'product_id',
                  name: 'PRODUCT',
                  id: 'product',
                },
              ],
              refAppViewId: 'plmweb.ticketmain_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        openMode: 'POPUPMODAL',
        navigateContexts: [
          {
            key: 'PRODUCT',
            value: 'product_id',
            name: 'PRODUCT',
            id: 'product',
          },
        ],
        realOpenMode: 'POPUPMODAL',
        realTitle: '工单',
        refAppViewId: 'plmweb.ticketmain_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '工单编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.TICKET.EDITVIEW',
        },
        refAppViewId: 'plmweb.ticketeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'others_add_relation_ticket@ticket',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '添加工单',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'deuiaction2',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode: '!context.is_delete',
                triggerType: 'ITEMVISIBLE',
                id: 'action',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '添加工单',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'customer_re_ticket_grid_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '添加工单',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '13AC8B51-935C-40E2-A413-A65AAB8B60C5',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'customer_re_ticket_grid_viewtoolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'show_identifier',
            excelCaption: '编号',
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编号',
            codeName: 'show_identifier',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'show_identifier',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'title',
            excelCaption: '标题',
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '标题',
            codeName: 'title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'title',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'state',
            excelCaption: '状态',
            appCodeListId: 'plmweb.prodmgmt__ticket_state',
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'state',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'state',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'assignee_name',
            excelCaption: '负责人',
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '负责人',
            codeName: 'assignee_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'assignee_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'priority',
            excelCaption: '优先级',
            appCodeListId: 'plmweb.prodmgmt__ticket_priority',
            appDEFieldId: 'priority',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '取消关联',
                  detailType: 'DEUIACTION',
                  uiactionId: 'customer_del_ticket@ticket',
                  showCaption: true,
                  showIcon: true,
                  id: 'uc73d061',
                },
              ],
              uniqueTag: 'Ticket__Usr0204918890',
              name: '客户取消关联',
              id: 'usr0204918890',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '优先级',
            codeName: 'priority',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'priority',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'show_identifier',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'state',
          },
          {
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_name',
          },
          {
            appDEFieldId: 'priority',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'priority',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'assignee_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_id',
          },
          {
            appDEFieldId: 'product_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'product_id',
          },
          {
            appDEFieldId: 'customer_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'customer_id',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetchnormal',
          appDataEntityId: 'plmweb.ticket',
          id: 'fetch',
        },
        dedataImportId: 'import_ticket',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.ticket',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Customer_re_ticket_grid',
        controlType: 'GRID',
        logicName: '客户关联工单表格',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {
          id: 'grid',
        },
        modelId: '8C4CB5EA-3256-438C-A417-95279029C263',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.ticket.customer_re_ticket_grid',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.TICKET',
        },
        caption: '工单',
        codeName: 'customer_re_ticket_grid_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {},
        name: 'captionbar',
        id: 'customer_re_ticket_grid_viewcaptionbar',
      },
    ],
    codeName: 'Usr0112784663',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'customer_relation_ticket_grid_view表格视图布局',
    appDataEntityId: 'plmweb.ticket',
    controlLogics: [
      {
        eventNames: 'onChange',
        itemName: 'CHOOSE_DATA',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'customer_add_change',
        appDataEntityId: 'plmweb.ticket',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: '5A982B25-4402-45A2-B736-EE8A9E915110',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0112784663',
  },
  title: '客户关联工单表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e6bb1fa9b5d4fec5f2d7040f29d3a2c3',
  modelType: 'PSAPPDEVIEW',
  name: 'ticketcustomer_re_ticket_grid_view',
  id: 'plmweb.ticketcustomer_re_ticket_grid_view',
};
