export default {
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPOVER',
  deviewCodeName: 'allocate_person_view',
  deviewId: '3173b64c9b47cac8c79d4a5e72f5331d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TICKET',
  },
  caption: '工单',
  codeName: 'ticket_allocate_person_view',
  appDataEntityId: 'plmweb.ticket',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.ticket',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.ticket',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.ticket',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.ticket',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.ticket',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'plmweb.ticket',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'assignee_name',
                  editor: {
                    singleSelect: true,
                    handlerType: 'PickupText',
                    appDEACModeId: 'member_select',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'plmweb.product_member',
                    uiactionGroup: {
                      uiactionGroupDetails: [
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          caption: '跳转至成员设置',
                          detailType: 'DEUIACTION',
                          uiactionId: 'jump_to_member_set@product_member',
                          tooltip: '跳转至成员设置',
                          showCaption: true,
                          showIcon: true,
                          sysImage: {
                            cssClass: 'fa fa-user-md',
                            glyph: 'xf0f0@FontAwesome',
                          },
                          id: 'u4befff7',
                        },
                      ],
                      appDataEntityId: 'plmweb.product_member',
                      uniqueTag: 'product_member__Usr0311005787',
                      name: '跳转至成员设置',
                      id: 'usr0311005787',
                    },
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'assignee_id',
                    editorParams: {
                      'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                      AC: 'TRUE',
                      TRIGGER: 'TRUE',
                      URL: 'products/${context.product}/product_members/fetch_default',
                      PICKUPVIEW: 'FALSE',
                      USERMETHOD: 'post',
                      USERMAP: '{"id":"user_id","name":"name"}',
                      DEPTMAP: '{"id":"id","name":"display_name"}',
                      DEPTMETHOD: 'get',
                      DEPTURL: '/users/fetch_default',
                    },
                    editorStyle: 'PERSONEL_SELECT_PRODUCT',
                    editorType: 'PICKEREX_TRIGGER',
                    editorItems: [
                      {
                        id: 'assignee_id',
                      },
                    ],
                    sysPFPluginId: 'person_select',
                    valueType: 'SIMPLE',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'n_department_id_eq',
                        value: 'srforgsectorid',
                        id: 'n_department_id_eq',
                      },
                    ],
                    id: 'assignee_name',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'assignee_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'assignee_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'assignee_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'assignee_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '负责人标识',
                  codeName: 'assignee_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'assignee_id',
                },
              ],
              caption: '工单基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'allocate_person_form',
      controlType: 'FORM',
      logicName: '分配负责人表单',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {
        id: 'form',
      },
      ctrlMsg: {
        codeName: 'UsrCtrlMsg0228593610',
        ctrlMsgItems: [
          {
            name: 'CREATESUCCESS_HIDDEN',
            id: 'createsuccess_hidden',
          },
          {
            name: 'UPDATESUCCESS_HIDDEN',
            id: 'updatesuccess_hidden',
          },
        ],
        name: '编辑表单自定义消息(隐藏)',
        id: 'usrctrlmsg0228593610',
      },
      modelId: 'f87a96853bed74ef7d7847a42627170c',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.ticket.allocate_person_form',
    },
    {
      codeName: 'allocate_person_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'allocate_person_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TICKET',
      },
      caption: '工单',
      codeName: 'allocate_person_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {},
      name: 'captionbar',
      id: 'allocate_person_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.ticket',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '分配负责人',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b9debf81410c609a380fd6019b531173',
  modelType: 'PSAPPDEVIEW',
  name: 'ticketallocate_person_view',
  id: 'plmweb.ticket_allocate_person_view',
};
