export default {
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'INDEXVIEWTAB_POPUPMODAL',
  deviewCodeName: 'main_view',
  deviewId: 'f89b6354622475eecdd1a6b4dd9551b4',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TICKET',
  },
  caption: '工单',
  codeName: 'ticketmain_view',
  height: 90,
  appDataEntityId: 'plmweb.ticket',
  appViewNavContexts: [
    {
      key: 'PRINCIPAL_ID',
      value: 'ticket',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'TICKET',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    panelItems: [
                      {
                        panelItems: [
                          {
                            panelItems: [
                              {
                                editor: {
                                  editorParams: {
                                    USERINSCRIPT:
                                      'value.replaceAll(/\\@\\{\\"(user)?id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\"\\}/g,(x, user, id, name) => {return controller.getNodeInfo({ id, name })}).replaceAll(/\\@\\{userid=(.+?),name=(.+?)\\}/g,(x, id, name) => {return controller.getNodeInfo({ id, name })})',
                                    QUOTECODELISTMAP:
                                      '{"type":"plmweb.base__recent_visite"}',
                                    QUOTEFIELDMAP:
                                      '{"identifier":"show_identifier","name":"name","id":"id","type":"owner_subtype"}',
                                    QUOTEPARAMS:
                                      '{"page":0,"size":20,"sort":"update_time,desc"}',
                                    QUOTEINSCRIPT:
                                      'value.replaceAll(/\\#\\{\\"id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\",\\"identifier\\":\\"(.+?)\\",\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\"\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })}).replaceAll(/\\#\\{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })})',
                                    USERSCRIPT:
                                      '`@{"id":"${data.id}","name":"${data.name}"}`',
                                    QUOTESCRIPT:
                                      '`#{"id":"${data.id}","name":"${data.name}","identifier":"${data.identifier}","icon":"${data.icon}"}`',
                                    REPLYSCRIPT:
                                      'value?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/#{"id":"(.+?)","name":"(.+?)","identifier":"(.+?)","icon":"((.|[\\t\\r\\f\\n\\s])+?)"}/g, "<span class=\\\'comment-tag\\\'>$4 $3 $2</span>").replace(/#{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)}/g, "<span class=\\\'comment-tag\\\'>$4 $3 $2</span>")',
                                    USERFIELDMAP:
                                      '{"id":"user_id","name":"name"}',
                                    USERURL:
                                      '`products/${context.product}/product_members/fetchdefault`',
                                    QUOTEURL: '`recents/fetchrecent_access`',
                                  },
                                  editorStyle: 'COMMENT_PRODUCT',
                                  editorType: 'HTMLEDITOR',
                                  sysPFPluginId: 'comment',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'field_textbox',
                                },
                                allowEmpty: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  grow: 10,
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                id: 'field_textbox',
                              },
                              {
                                actionType: 'UIACTION',
                                buttonStyle: 'INFO',
                                buttonType: 'PANELBUTTON',
                                uiactionId: 'clear_comment@comment',
                                renderMode: 'BUTTON',
                                tooltip: '取消',
                                uiactionTarget: 'NONE',
                                caption: '取消',
                                dynaClass:
                                  "['ibiz-panel-button--comment__cancel']",
                                itemStyle: 'INFO',
                                itemType: 'BUTTON',
                                layoutPos: {
                                  shrink: 0,
                                  layout: 'FLEX',
                                },
                                panelItemGroupLogics: [
                                  {
                                    logicCat: 'PANELVISIBLE',
                                    relatedItemNames: ['field_textbox'],
                                    groupOP: 'AND',
                                    panelItemLogics: [
                                      {
                                        condOp: 'ISNOTNULL',
                                        dstModelField: 'FIELD_TEXTBOX',
                                        logicType: 'SINGLE',
                                        id: '逻辑项',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                    id: '面板成员[comment_cancel][面板显示]逻辑',
                                  },
                                ],
                                showCaption: true,
                                id: 'comment_cancel',
                              },
                              {
                                actionType: 'UIACTION',
                                buttonStyle: 'DEFAULT',
                                buttonType: 'PANELBUTTON',
                                uiactionId: 'send_comment@comment',
                                renderMode: 'BUTTON',
                                tooltip: '发送',
                                uiactionTarget: 'NONE',
                                caption: '发送',
                                dynaClass:
                                  "['ibiz-panel-button--comment__send']",
                                itemStyle: 'DEFAULT',
                                itemType: 'BUTTON',
                                layoutPos: {
                                  shrink: 0,
                                  layout: 'FLEX',
                                },
                                panelItemGroupLogics: [
                                  {
                                    logicCat: 'PANELVISIBLE',
                                    relatedItemNames: ['field_textbox'],
                                    groupOP: 'AND',
                                    panelItemLogics: [
                                      {
                                        condOp: 'ISNOTNULL',
                                        dstModelField: 'FIELD_TEXTBOX',
                                        logicType: 'SINGLE',
                                        id: '逻辑项',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                    id: '面板成员[comment_send][面板显示]逻辑',
                                  },
                                ],
                                showCaption: true,
                                id: 'comment_send',
                              },
                              {
                                rawItem: {
                                  sysImage: {
                                    cssClass: 'fa fa-arrow-circle-o-right',
                                    glyph: 'xf18e@FontAwesome',
                                  },
                                  contentType: 'IMAGE',
                                  dynaClass:
                                    "['ibiz-panel-button--comment__icon']",
                                  sysCss: {
                                    cssName: 'comment_icon',
                                  },
                                  predefinedType: 'STATIC_IMAGE',
                                  rawItemHeight: 48,
                                  id: 'comment_icon',
                                },
                                caption: '图片',
                                contentHeight: 48,
                                height: 48,
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 0,
                                  height: 48,
                                  heightMode: 'PX',
                                  layout: 'FLEX',
                                },
                                sysCss: {
                                  cssName: 'comment_icon',
                                },
                                sysImage: {
                                  cssClass: 'fa fa-arrow-circle-o-right',
                                  glyph: 'xf18e@FontAwesome',
                                },
                                showCaption: true,
                                id: 'comment_icon',
                              },
                            ],
                            layout: {
                              dir: 'row',
                              layout: 'FLEX',
                              valign: 'flex-start',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              widthMode: 'FULL',
                            },
                            id: 'container_comment',
                          },
                        ],
                        layout: {
                          dir: 'column',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          colMD: 24,
                          heightMode: 'FULL',
                          layout: 'TABLE_24COL',
                          widthMode: 'FULL',
                        },
                        id: 'page_container',
                      },
                    ],
                    predefinedType: 'PANELPART',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '引用布局面板',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'panelpart',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                  spacingLeft: 'INNERSMALL',
                  spacingRight: 'INNERSMALL',
                },
                id: 'container',
              },
              {
                panelItems: [
                  {
                    panelItems: [
                      {
                        editor: {
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          editorParams: {
                            DEFAULTATNVALUE: '40',
                            CODELISTID: 'Base__Attention_type',
                            'SRFNAVPARAM.n_department_id_eq':
                              '%srforgsectorid%',
                            AC: 'TRUE',
                            TRIGGER: 'TRUE',
                            SELFFILLMAP:
                              '{"user_id":"user_id","user_name":"name"}',
                            URL: 'products/${context.product}/product_members/fetchdefault',
                            PICKUPVIEW: 'FALSE',
                            USERMETHOD: 'post',
                            USERMAP: '{"id":"user_id","name":"name"}',
                            DEPTMAP: '{"id":"id","name":"display_name"}',
                            DEPTMETHOD: 'get',
                            DEPTURL: '/users/fetchdefault',
                            CODELISTMAP:
                              '{"FOLLOWED":[20,30,40],"NOTFOLLOWING":[10]}',
                          },
                          editorStyle: 'ATTENTION',
                          editorType: 'PICKEREX_TRIGGER',
                          sysPFPluginId: 'attention',
                          predefinedType: 'FIELD_PICKER',
                          valueType: 'SIMPLE',
                          editable: true,
                          navigateParams: [
                            {
                              key: 'n_department_id_eq',
                              value: 'srforgsectorid',
                              id: 'n_department_id_eq',
                            },
                          ],
                          id: 'attentions',
                        },
                        viewFieldName: 'ATTENTIONS',
                        allowEmpty: true,
                        caption: '数据选择',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'attentions',
                      },
                    ],
                    predefinedType: 'CONTAINER_SINGLEDATA',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'SINGLEDATA',
                    dataSourceType: 'DEACTION',
                    appDEMethodId: 'get_attention',
                    appDataEntityId: 'plmweb.ticket',
                    caption: '单项数据容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                      spacingLeft: 'INNERSMALL',
                      spacingRight: 'INNERSMALL',
                    },
                    id: 'container_attention',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container1',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 0,
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'container_view_bottom',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onViewMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "const form = view.getController('form');\r\nif (form) {\r\n    form.evt.on('onFormDetailEvent', event =>{\r\n        const panelItems = view.layoutPanel.panelItems;\r\n        if (!panelItems.container_comment) {\r\n            return;\r\n        }\r\n        if (form.details.tabpanel1) {\r\n            const activeTab = form.details.tabpanel1.state.activeTab;\r\n            panelItems.container_comment.state.visible = activeTab === 'tabpage1';\r\n        }\r\n    });\r\n}",
        builtinLogic: true,
        name: 'LOGIC',
        id: 'logic',
      },
    ],
    controls: [
      {
        autoSaveMode: 1,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.ticket',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'plmweb.ticket',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'getdraft',
          appDataEntityId: 'plmweb.ticket',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.ticket',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.ticket',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.ticket',
          id: 'update',
        },
        enableAutoSave: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'title',
                    editor: {
                      maxLength: 500,
                      showMaxLength: true,
                      editorParams: {
                        SHOWLIMIT: 'true',
                        ISAUTO: 'true',
                      },
                      editorType: 'TEXTAREA',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'title',
                    },
                    allowEmpty: true,
                    caption: '标题',
                    codeName: 'title',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'title',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'assignee_name',
                    editor: {
                      singleSelect: true,
                      handlerType: 'PickupText',
                      appDEACModeId: 'member_select',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'plmweb.product_member',
                      uiactionGroup: {
                        uiactionGroupDetails: [
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            caption: '跳转至成员设置',
                            detailType: 'DEUIACTION',
                            uiactionId: 'jump_to_member_set@product_member',
                            tooltip: '跳转至成员设置',
                            showCaption: true,
                            showIcon: true,
                            sysImage: {
                              cssClass: 'fa fa-user-md',
                              glyph: 'xf0f0@FontAwesome',
                            },
                            id: 'u653ff49',
                          },
                        ],
                        uniqueTag: 'Product_member__Usr0311005787',
                        name: '跳转至成员设置',
                        id: 'usr0311005787',
                      },
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'assignee_id',
                      editorParams: {
                        'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        URL: 'products/${context.product}/product_members/fetchdefault',
                        PICKUPVIEW: 'FALSE',
                        USERMETHOD: 'post',
                        USERMAP: '{"id":"user_id","name":"name"}',
                        DEPTMAP: '{"id":"id","name":"display_name"}',
                        DEPTMETHOD: 'get',
                        DEPTURL: '/users/fetchdefault',
                      },
                      editorStyle: 'PERSONEL_SELECT_PRODUCT',
                      editorType: 'PICKEREX_TRIGGER',
                      editorItems: [
                        {
                          id: 'assignee_id',
                        },
                      ],
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      navigateParams: [
                        {
                          key: 'n_department_id_eq',
                          value: 'srforgsectorid',
                          id: 'n_department_id_eq',
                        },
                      ],
                      id: 'assignee_name',
                    },
                    allowEmpty: true,
                    caption: '负责人',
                    codeName: 'assignee_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'assignee_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'state',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'plmweb.prodmgmt__ticket_state',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'state',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    caption: '状态',
                    codeName: 'state',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'state',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'solution',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'plmweb.prodmgmt__solutions',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'solution',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    caption: '解决方案',
                    codeName: 'solution',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'solution',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'priority',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'plmweb.prodmgmt__ticket_priority',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'priority',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    caption: '优先级',
                    codeName: 'priority',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'priority',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'assignee_id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'assignee_id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    caption: '负责人标识',
                    codeName: 'assignee_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'assignee_id',
                  },
                  {
                    deformTabPages: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'NONE',
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'description',
                                editor: {
                                  editorParams: {
                                    USERINSCRIPT:
                                      'value.replaceAll(/\\@\\{\\"(user)?id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\"\\}/g,(x, user, id, name) => {return controller.getNodeInfo({ id, name })}).replaceAll(/\\@\\{userid=(.+?),name=(.+?)\\}/g,(x, id, name) => {return controller.getNodeInfo({ id, name })})',
                                    MAXHEIGHT: '450',
                                    QUOTECODELISTMAP:
                                      '{"type":"plmweb.base__recent_visite"}',
                                    enableEdit: 'true',
                                    QUOTEFIELDMAP:
                                      '{"identifier":"show_identifier","name":"name","id":"id","type":"owner_subtype"}',
                                    QUOTEPARAMS:
                                      '{"page":0,"size":20,"sort":"update_time,desc"}',
                                    enableFullScreen: 'true',
                                    MODE: 'default',
                                    QUOTEINSCRIPT:
                                      'value.replaceAll(/\\#\\{\\"id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\",\\"identifier\\":\\"(.+?)\\",\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\"\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })}).replaceAll(/\\#\\{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })})',
                                    USERSCRIPT:
                                      '`@{"id":"${data.id}","name":"${data.name}"}`',
                                    QUOTESCRIPT:
                                      '`#{"id":"${data.id}","name":"${data.name}","identifier":"${data.identifier}","icon":"${data.icon}"}`',
                                    USERURL:
                                      "`${context.library ? `libraries/${context.library}/library_members/fetchdefault` : context.product ? `products/${context.product}/product_members/fetchdefault` : context.project ? `projects/${context.project}/project_members/fetchdefault` : ''}`",
                                    USERFIELDMAP:
                                      '{"id":"user_id","name":"name"}',
                                    INSERTKEYS:
                                      '[{"index":66,"keys":["marker"]}]',
                                    QUOTEURL: '`recents/fetchrecent_access`',
                                  },
                                  editorStyle: 'COLLAPSE',
                                  editorType: 'HTMLEDITOR',
                                  sysPFPluginId: 'comment',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'description',
                                },
                                allowEmpty: true,
                                caption: '描述',
                                codeName: 'description',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'description',
                              },
                            ],
                            caption: '描述',
                            codeName: 'description_container',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'description_container',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            uiactionGroup: {
                              uiactionGroupDetails: [
                                {
                                  actionLevel: 100,
                                  afterItemType: 'NONE',
                                  beforeItemType: 'NONE',
                                  caption: '添加附件',
                                  detailType: 'DEUIACTION',
                                  uiactionId: 'add_attachments@ticket',
                                  showCaption: true,
                                  showIcon: true,
                                  sysImage: {
                                    cssClass: 'fa fa-plus',
                                    glyph: 'xf067@FontAwesome',
                                  },
                                  id: 'uadd40ac',
                                },
                              ],
                              uniqueTag: 'Ticket__Usr0110243653',
                              name: '新建附件',
                              id: 'usr0110243653',
                            },
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                contentControl: {
                                  aggMode: 'NONE',
                                  columnEnableFilter: 2,
                                  columnEnableLink: 2,
                                  groupMode: 'NONE',
                                  degridColumns: [
                                    {
                                      clconvertMode: 'NONE',
                                      dataItemName: 'name',
                                      excelCaption: '名称',
                                      appDEFieldId: 'name',
                                      valueType: 'SIMPLE',
                                      enableRowEdit: true,
                                      aggMode: 'NONE',
                                      align: 'LEFT',
                                      capLanguageRes: {
                                        lanResTag: 'DEF.LNAME.NAME',
                                      },
                                      caption: '名称',
                                      codeName: 'name',
                                      columnType: 'DEFGRIDCOLUMN',
                                      noPrivDisplayMode: 1,
                                      width: 250,
                                      widthUnit: 'STAR',
                                      enableSort: true,
                                      id: 'name',
                                    },
                                    {
                                      clconvertMode: 'NONE',
                                      dataItemName: 'update_time',
                                      excelCaption: '上传时间',
                                      appDEFieldId: 'update_time',
                                      valueFormat: 'YYYY-MM-DD HH:mm:ss',
                                      valueType: 'SIMPLE',
                                      aggMode: 'NONE',
                                      align: 'LEFT',
                                      capLanguageRes: {
                                        lanResTag: 'DEF.LNAME.UPDATE_TIME',
                                      },
                                      caption: '上传时间',
                                      codeName: 'update_time',
                                      columnType: 'DEFGRIDCOLUMN',
                                      noPrivDisplayMode: 1,
                                      width: 200,
                                      widthUnit: 'PX',
                                      enableSort: true,
                                      id: 'update_time',
                                    },
                                    {
                                      clconvertMode: 'NONE',
                                      dataItemName: 'owner_id',
                                      excelCaption: '所属数据标识',
                                      appDEFieldId: 'owner_id',
                                      valueType: 'SIMPLE',
                                      enableRowEdit: true,
                                      aggMode: 'NONE',
                                      align: 'LEFT',
                                      caption: '所属数据标识',
                                      codeName: 'owner_id',
                                      columnType: 'DEFGRIDCOLUMN',
                                      noPrivDisplayMode: 1,
                                      width: 100,
                                      widthUnit: 'PX',
                                      enableSort: true,
                                      hideDefault: true,
                                      id: 'owner_id',
                                    },
                                    {
                                      deuiactionGroup: {
                                        uiactionGroupDetails: [
                                          {
                                            actionLevel: 250,
                                            afterItemType: 'NONE',
                                            beforeItemType: 'NONE',
                                            detailType: 'DEUIACTION',
                                            uiactionId: 'download@attachment',
                                            tooltip: '下载当前附件',
                                            showIcon: true,
                                            sysImage: {
                                              cssClass: 'fa fa-download',
                                              glyph: 'xf019@FontAwesome',
                                            },
                                            id: 'u0b42a77',
                                          },
                                          {
                                            actionLevel: 100,
                                            afterItemType: 'NONE',
                                            beforeItemType: 'NONE',
                                            caption: '删除',
                                            detailType: 'DEUIACTION',
                                            uiactionId: 'delete@attachment',
                                            tooltip: '删除',
                                            showCaption: true,
                                            showIcon: true,
                                            sysImage: {
                                              cssClass: 'fa fa-trash-o',
                                              glyph: 'xf014@FontAwesome',
                                            },
                                            id: 'u8aff03a',
                                          },
                                        ],
                                        uniqueTag: 'Attachment__Usr0103721999',
                                        name: '附件表格操作列',
                                        id: 'usr0103721999',
                                      },
                                      aggMode: 'NONE',
                                      align: 'RIGHT',
                                      caption: '操作',
                                      codeName: 'uagridcolumn1',
                                      columnType: 'UAGRIDCOLUMN',
                                      noPrivDisplayMode: 1,
                                      width: 100,
                                      widthUnit: 'PX',
                                      id: 'uagridcolumn1',
                                    },
                                  ],
                                  degridDataItems: [
                                    {
                                      appDEFieldId: 'name',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'name',
                                    },
                                    {
                                      format: 'YYYY-MM-DD HH:mm:ss',
                                      appDEFieldId: 'update_time',
                                      valueType: 'SIMPLE',
                                      dataType: 5,
                                      id: 'update_time',
                                    },
                                    {
                                      appDEFieldId: 'owner_id',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'owner_id',
                                    },
                                    {
                                      appDEFieldId: 'file_id',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'file_id',
                                    },
                                    {
                                      appDEFieldId: 'id',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'srfkey',
                                    },
                                    {
                                      appDEFieldId: 'id',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'srfdataaccaction',
                                    },
                                    {
                                      appDEFieldId: 'name',
                                      valueType: 'SIMPLE',
                                      dataType: 25,
                                      id: 'srfmajortext',
                                    },
                                  ],
                                  degridEditItems: [
                                    {
                                      caption: '名称',
                                      codeName: 'name',
                                      enableCond: 3,
                                      appDEFieldId: 'name',
                                      editor: {
                                        maxLength: 200,
                                        editorType: 'TEXTBOX',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'name',
                                      },
                                      allowEmpty: true,
                                      id: 'name',
                                    },
                                    {
                                      caption: '所属数据标识',
                                      codeName: 'owner_id',
                                      createDV: 'srfowner_id',
                                      createDVT: 'APPDATA',
                                      enableCond: 3,
                                      appDEFieldId: 'owner_id',
                                      editor: {
                                        maxLength: 100,
                                        editorType: 'TEXTBOX',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'owner_id',
                                      },
                                      allowEmpty: true,
                                      id: 'owner_id',
                                    },
                                    {
                                      caption: '标识',
                                      codeName: 'srfkey',
                                      enableCond: 3,
                                      appDEFieldId: 'id',
                                      editor: {
                                        editorType: 'HIDDEN',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'srfkey',
                                      },
                                      allowEmpty: true,
                                      id: 'srfkey',
                                    },
                                  ],
                                  pagingSize: 20,
                                  sortMode: 'REMOTE',
                                  enableRowEdit: true,
                                  enableRowNew: true,
                                  createControlAction: {
                                    appDEMethodId: 'create',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'create',
                                  },
                                  fetchControlAction: {
                                    appDEMethodId: 'fetchdefault',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'fetch',
                                  },
                                  getDraftControlAction: {
                                    appDEMethodId: 'getdraft',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'loaddraft',
                                  },
                                  getControlAction: {
                                    appDEMethodId: 'get',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'load',
                                  },
                                  removeControlAction: {
                                    appDEMethodId: 'remove',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'remove',
                                  },
                                  updateControlAction: {
                                    appDEMethodId: 'update',
                                    appDataEntityId: 'plmweb.attachment',
                                    id: 'update',
                                  },
                                  autoLoad: true,
                                  showBusyIndicator: true,
                                  codeName: 'Attach',
                                  controlStyle: 'ATTACHMENT_GRID',
                                  controlType: 'GRID',
                                  logicName: '附件表格',
                                  appDataEntityId: 'plmweb.attachment',
                                  controlLogics: [
                                    {
                                      eventNames: 'onLoadSuccess',
                                      logicTag: 'attachments_grid',
                                      logicType: 'APPDEUILOGIC',
                                      appDEUILogicId: 'calc_attachment_hidden',
                                      appDataEntityId: 'plmweb.attachment',
                                      triggerType: 'CTRLEVENT',
                                      id: 'logic2',
                                    },
                                  ],
                                  controlParam: {},
                                  sysPFPluginId: 'attachment_grid',
                                  modelId: '998d996121eae3cd01a2d8c20de49f02',
                                  modelType: 'PSDEGRID',
                                  name: 'attachments_grid',
                                  id: 'plmweb.attachment.attach',
                                },
                                contentType: 'GRID',
                                layout: {
                                  columnCount: 24,
                                  layout: 'TABLE_24COL',
                                },
                                codeName: 'attachments',
                                detailStyle: 'DEFAULT',
                                detailType: 'MDCTRL',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'attachments',
                              },
                            ],
                            caption: '附件',
                            codeName: 'grouppanel6',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'grouppanel6',
                          },
                          {
                            deformTabPages: [
                              {
                                layout: {
                                  columnCount: 24,
                                  layout: 'TABLE_24COL',
                                },
                                deformDetails: [
                                  {
                                    appViewId: 'plmweb.commentlist_view',
                                    parentDataJO: {
                                      srfparentdename: 'TICKET',
                                      SRFPARENTTYPE: 'CUSTOM',
                                    },
                                    codeName: 'druipart1',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'DRUIPART',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    showCaption: true,
                                    id: 'druipart1',
                                  },
                                ],
                                caption: '评论',
                                codeName: 'tabpage2',
                                detailStyle: 'DEFAULT',
                                detailType: 'TABPAGE',
                                showCaption: true,
                                id: 'tabpage2',
                              },
                              {
                                layout: {
                                  columnCount: 24,
                                  layout: 'TABLE_24COL',
                                },
                                deformDetails: [
                                  {
                                    appViewId:
                                      'plmweb.activitiyhistorylistview',
                                    parentDataJO: {
                                      srfparentdename: 'TICKET',
                                      SRFPARENTTYPE: 'CUSTOM',
                                    },
                                    codeName: 'druipart2',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'DRUIPART',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    showCaption: true,
                                    id: 'druipart2',
                                  },
                                ],
                                caption: '活动',
                                codeName: 'tabpage3',
                                detailStyle: 'DEFAULT',
                                detailType: 'TABPAGE',
                                showCaption: true,
                                id: 'tabpage3',
                              },
                              {
                                layout: {
                                  columnCount: 24,
                                  layout: 'TABLE_24COL',
                                },
                                deformDetails: [
                                  {
                                    appViewId:
                                      'plmweb.transition_historywork_item_calendar_view',
                                    parentDataJO: {
                                      srfparentdename: 'TICKET',
                                      SRFPARENTTYPE: 'CUSTOM',
                                    },
                                    codeName: 'druipart3',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'DRUIPART',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    showCaption: true,
                                    id: 'druipart3',
                                  },
                                ],
                                caption: '流转',
                                codeName: 'tabpage4',
                                detailStyle: 'DEFAULT',
                                detailType: 'TABPAGE',
                                showCaption: true,
                                id: 'tabpage4',
                              },
                            ],
                            codeName: 'tabpanel_tags',
                            detailStyle: 'DEFAULT',
                            detailType: 'TABPANEL',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'tabpanel_tags',
                          },
                        ],
                        caption: '基本信息',
                        codeName: 'tabpage1',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            appViewId: 'plmweb.ideaticket_re_idea_gridview',
                            navigateContexts: [
                              {
                                key: 'TARGET_TYPE',
                                value: 'idea',
                                rawValue: true,
                                name: 'TARGET_TYPE',
                                id: 'target_type',
                              },
                              {
                                key: 'PRINCIPAL_TYPE',
                                value: 'ticket',
                                rawValue: true,
                                name: 'PRINCIPAL_TYPE',
                                id: 'principal_type',
                              },
                            ],
                            navigateParams: [
                              {
                                key: 'principal_id',
                                value: 'ticket',
                                id: 'principal_id',
                              },
                            ],
                            parentDataJO: {
                              srfparentdename: 'TICKET',
                              SRFPARENTTYPE: 'CUSTOM',
                            },
                            codeName: 'tabpanel1_idea_druipart',
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'tabpanel1_idea_druipart',
                          },
                        ],
                        caption: '产品需求',
                        codeName: 'tabpanel1_idea',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpanel1_idea',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            appViewId:
                              'plmweb.work_itemticket_re_work_item_gridview',
                            navigateContexts: [
                              {
                                key: 'TARGET_TYPE',
                                value: 'work_item',
                                rawValue: true,
                                name: 'TARGET_TYPE',
                                id: 'target_type',
                              },
                              {
                                key: 'PRINCIPAL_TYPE',
                                value: 'ticket',
                                rawValue: true,
                                name: 'PRINCIPAL_TYPE',
                                id: 'principal_type',
                              },
                            ],
                            navigateParams: [
                              {
                                key: 'principal_id',
                                value: 'ticket',
                                id: 'principal_id',
                              },
                            ],
                            parentDataJO: {
                              srfparentdename: 'TICKET',
                              SRFPARENTTYPE: 'CUSTOM',
                            },
                            codeName: 'tabpanel1_work_item_druipart',
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'tabpanel1_work_item_druipart',
                          },
                        ],
                        caption: '工作项',
                        codeName: 'tabpanel1_work_item',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpanel1_work_item',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            appViewId: 'plmweb.ticketre_self_grid_view',
                            navigateContexts: [
                              {
                                key: 'PRODUCT',
                                rawValue: true,
                                name: 'PRODUCT',
                                id: 'product',
                              },
                              {
                                key: 'TARGET_TYPE',
                                value: 'ticket',
                                rawValue: true,
                                name: 'TARGET_TYPE',
                                id: 'target_type',
                              },
                              {
                                key: 'PRINCIPAL_TYPE',
                                value: 'ticket',
                                rawValue: true,
                                name: 'PRINCIPAL_TYPE',
                                id: 'principal_type',
                              },
                              {
                                key: 'CURPRODUCT',
                                value: 'product',
                                name: 'CURPRODUCT',
                                id: 'curproduct',
                              },
                            ],
                            navigateParams: [
                              {
                                key: 'principal_id',
                                value: 'ticket',
                                id: 'principal_id',
                              },
                            ],
                            parentDataJO: {
                              srfparentdename: 'TICKET',
                              SRFPARENTTYPE: 'CUSTOM',
                            },
                            codeName: 'tabpanel1_ticket_druipart',
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'tabpanel1_ticket_druipart',
                          },
                        ],
                        caption: '工单',
                        codeName: 'tabpanel1_ticket',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpanel1_ticket',
                      },
                    ],
                    codeName: 'tabpanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPANEL',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'tabpanel1',
                  },
                ],
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFORM.TICKET.MAIN.GROUPPANEL.GROUP1',
                },
                caption: '工单基本信息',
                codeName: 'left_grouppanel',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 16,
                  colMD: 16,
                  layout: 'TABLE_24COL',
                },
                id: 'left_grouppanel',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'estimated_at',
                        editor: {
                          editorParams: {
                            TIMEFMT: 'YYYY-MM-DD',
                          },
                          editorType: 'DATERANGE_NOTIME',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'estimated_at',
                        },
                        allowEmpty: true,
                        caption: '预计时间',
                        codeName: 'estimated_at',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'estimated_at',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'type',
                        editor: {
                          singleSelect: true,
                          appCodeListId: 'plmweb.prodmgmt__product_ticket_type',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'type',
                        },
                        allowEmpty: true,
                        needCodeListConfig: true,
                        caption: '类型',
                        codeName: 'type',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'type',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'tags',
                        editor: {
                          appCodeListId: 'plmweb.prodmgmt__product_tag',
                          editorParams: {
                            'srfnavparam.n_product_id_eq': '%product%',
                          },
                          editorType: 'MDROPDOWNLIST',
                          placeHolder: '添加标签',
                          valueType: 'SIMPLE',
                          editable: true,
                          navigateParams: [
                            {
                              key: 'n_product_id_eq',
                              value: 'product',
                              id: 'n_product_id_eq',
                            },
                          ],
                          id: 'tags',
                        },
                        allowEmpty: true,
                        needCodeListConfig: true,
                        caption: '标签',
                        codeName: 'tags',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'tags',
                      },
                    ],
                    caption: '属性',
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel2',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'channel',
                        editor: {
                          maxLength: 100,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'channel',
                        },
                        allowEmpty: true,
                        caption: '渠道',
                        codeName: 'channel',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'channel',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'customer_name',
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          contextJOString: '{"PRODUCT":"%product_id%"}',
                          itemParamJO: {
                            parentdata: {
                              srfparentkey: '%product_id%',
                              srfparentdename: 'PRODUCT',
                              srfparentmode:
                                'DER1N_CUSTOMER_PRODUCT_PRODUCT_ID',
                              srfparentdefname: 'PRODUCT_ID',
                            },
                            fetchcond: {
                              n_product_id_eq: 'product_id',
                            },
                          },
                          paramJOString: '{"n_product_id_eq":"%product_id%"}',
                          pickupAppViewId: 'plmweb.customerpickupview',
                          handlerType: 'PickupText',
                          appDEACModeId: 'default',
                          appDEDataSetId: 'fetchdefault',
                          appDataEntityId: 'plmweb.customer',
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'customer_id',
                          editorParams: {
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'customer_id',
                            },
                          ],
                          valueType: 'SIMPLE',
                          editable: true,
                          navigateContexts: [
                            {
                              key: 'PRODUCT',
                              value: 'product_id',
                              name: 'PRODUCT',
                              id: 'product',
                            },
                          ],
                          navigateParams: [
                            {
                              key: 'n_product_id_eq',
                              value: 'product_id',
                              id: 'n_product_id_eq',
                            },
                          ],
                          id: 'customer_name',
                        },
                        resetItemNames: ['product_id'],
                        allowEmpty: true,
                        caption: '客户',
                        codeName: 'customer_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'customer_name',
                      },
                      {
                        dataType: 25,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'submitter_name',
                        editor: {
                          singleSelect: true,
                          handlerType: 'PickupText',
                          appDEACModeId: 'member_select',
                          appDEDataSetId: 'fetchdefault',
                          appDataEntityId: 'plmweb.product_member',
                          uiactionGroup: {
                            uiactionGroupDetails: [
                              {
                                actionLevel: 100,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                caption: '跳转至成员设置',
                                detailType: 'DEUIACTION',
                                uiactionId: 'jump_to_member_set@product_member',
                                tooltip: '跳转至成员设置',
                                showCaption: true,
                                showIcon: true,
                                sysImage: {
                                  cssClass: 'fa fa-user-md',
                                  glyph: 'xf0f0@FontAwesome',
                                },
                                id: 'u653ff49',
                              },
                            ],
                            uniqueTag: 'Product_member__Usr0311005787',
                            name: '跳转至成员设置',
                            id: 'usr0311005787',
                          },
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'submitter_id',
                          editorParams: {
                            'SRFNAVPARAM.n_department_id_eq':
                              '%srforgsectorid%',
                            AC: 'TRUE',
                            TRIGGER: 'TRUE',
                            URL: 'products/${context.product}/product_members/fetchdefault',
                            PICKUPVIEW: 'FALSE',
                            USERMETHOD: 'post',
                            USERMAP: '{"id":"user_id","name":"name"}',
                            DEPTMAP: '{"id":"id","name":"display_name"}',
                            DEPTMETHOD: 'get',
                            DEPTURL: '/users/fetchdefault',
                          },
                          editorStyle: 'PERSONEL_SELECT_PRODUCT',
                          editorType: 'PICKEREX_TRIGGER',
                          editorItems: [
                            {
                              id: 'submitter_id',
                            },
                          ],
                          sysPFPluginId: 'person_select',
                          valueType: 'SIMPLE',
                          editable: true,
                          navigateParams: [
                            {
                              key: 'n_department_id_eq',
                              value: 'srforgsectorid',
                              id: 'n_department_id_eq',
                            },
                          ],
                          id: 'submitter_name',
                        },
                        allowEmpty: true,
                        caption: '提交人',
                        codeName: 'submitter_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'submitter_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'submitter_id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'submitter_id',
                        },
                        allowEmpty: true,
                        hidden: true,
                        caption: '提交人标识',
                        codeName: 'submitter_id',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'submitter_id',
                      },
                      {
                        dataType: 5,
                        itemWidth: 131,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'submitted_at',
                        editor: {
                          dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                          editorParams: {
                            TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                          },
                          editorType: 'DATEPICKER',
                          editorWidth: 1,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'submitted_at',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        allowEmpty: true,
                        caption: '提交时间',
                        codeName: 'submitted_at',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'submitted_at',
                      },
                    ],
                    caption: '来源',
                    codeName: 'grouppanel3',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel3',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'product_name',
                        editor: {
                          halign: 'LEFT',
                          linkAppViewId: 'plmweb.productindex_view',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'product_name',
                        },
                        allowEmpty: true,
                        caption: '所属产品',
                        codeName: 'product_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'product_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'create_man',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'plmweb.sysoperator',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'create_man',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.CREATE_MAN',
                        },
                        caption: '建立人',
                        codeName: 'create_man',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'create_man',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'create_time',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'create_time',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.CREATE_TIME',
                        },
                        caption: '建立时间',
                        codeName: 'create_time',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'create_time',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'update_man',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'plmweb.sysoperator',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'update_man',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.UPDATE_MAN',
                        },
                        caption: '更新人',
                        codeName: 'update_man',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'update_man',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'update_time',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'update_time',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.UPDATE_TIME',
                        },
                        caption: '更新时间',
                        codeName: 'update_time',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'update_time',
                      },
                    ],
                    caption: '基础信息',
                    codeName: 'grouppanel4',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel4',
                  },
                ],
                codeName: 'right_grouppanel',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                id: 'right_grouppanel',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'customer_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'customer_id',
                },
                resetItemNames: ['product_id'],
                allowEmpty: true,
                hidden: true,
                caption: '客户标识',
                codeName: 'customer_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'customer_id',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.TICKET.MAIN.FORMPAGE.FORMPAGE1',
            },
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'product_ticket_re_counters',
              counterType: 'DEDR',
              getAppDEActionId: 'product_ticket_re_counters',
              appDataEntityId: 'plmweb.ticket',
              timer: 60000,
              name: '产品工单关联分页计数器',
              id: 'plmweb.product_ticket_re_counters',
            },
            tag: '7f53f6259a2c319e8efc3afef14357d7',
            id: '7f53f6259a2c319e8efc3afef14357d7',
          },
        ],
        codeName: 'Main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '9db1aa2be35a58b18c1974ca7cb64cc1',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'plmweb.ticket.main',
      },
      {
        codeName: 'main_viewdatainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_viewdatainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.TICKET',
        },
        caption: '工单',
        codeName: 'main_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.ticket',
        controlParam: {},
        name: 'captionbar',
        id: 'main_viewcaptionbar',
      },
    ],
    codeName: 'Usr0116931148',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'main_view编辑视图布局面板',
    appDataEntityId: 'plmweb.ticket',
    controlLogics: [
      {
        eventNames: 'onChange',
        itemName: 'ATTENTIONS',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'attention_personnel_update',
        appDataEntityId: 'plmweb.work_item',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onBlur',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_hidden',
        appDataEntityId: 'plmweb.comment',
        triggerType: 'CTRLEVENT',
        name: 'onBlur',
        id: 'onblur',
      },
      {
        eventNames: 'onFocus',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_show',
        appDataEntityId: 'plmweb.comment',
        triggerType: 'CTRLEVENT',
        name: 'onFocus',
        id: 'onfocus',
      },
    ],
    controlParam: {},
    modelId: '59C6F36B-1B0E-4339-94AD-1C1FC86E3998',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0116931148',
  },
  title: '工单',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd671e0bef3f01b120d203fdaef04c926',
  modelType: 'PSAPPDEVIEW',
  name: 'ticketmain_view',
  id: 'plmweb.ticketmain_view',
};
