export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'test_all_grid_view',
  deviewId: 'c520d7bfa5f744eed998a8789bb18330',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.TICKET',
  },
  caption: '全部工单',
  codeName: 'ticket_test_all_grid_view',
  appDataEntityId: 'plmweb.ticket',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.ticket_quick_create_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.ticket_quick_create_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          navigateContexts: [
            {
              key: 'PRODUCT',
              value: 'product',
              name: 'PRODUCT',
              id: 'product',
            },
          ],
          refAppViewId: 'plmweb.ticket_test_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            navigateContexts: [
              {
                key: 'PRODUCT',
                value: 'product',
                name: 'PRODUCT',
                id: 'product',
              },
            ],
            refAppViewId: 'plmweb.ticket_test_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '新建工单',
      refAppViewId: 'plmweb.ticket_quick_create_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      openMode: 'INDEXVIEWTAB_POPUPMODAL',
      navigateContexts: [
        {
          key: 'PRODUCT',
          value: 'product',
          name: 'PRODUCT',
          id: 'product',
        },
      ],
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '工单',
      refAppViewId: 'plmweb.ticket_test_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'new',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建工单',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建工单',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import',
              valid: true,
              caption: '导入工单',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-upload',
                glyph: 'xf093@FontAwesome',
              },
              tooltip: '导入工单',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'exportexcel',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.EXPORT',
              },
              caption: '导出工单',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-excel-o',
                glyph: 'xf1c3@FontAwesome',
              },
              tooltip: '导出工单',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.EXPORT',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-list-ul',
            glyph: 'xf0ca@FontAwesome',
          },
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'test_all_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '新建工单',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'f62d94c21a5285db6d1b01be71854b68',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'test_all_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 80,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          sysPFPluginId: 'column_action_edit',
          width: 300,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'title',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state',
          excelCaption: '状态',
          appCodeListId: 'plmweb.prodmgmt__ticket_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type_text',
          excelCaption: '类型',
          appCodeListId: 'plmweb.prodmgmt__product_ticket_type',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'assignee_name',
          excelCaption: '负责人',
          linkAppViewId: 'plmweb.user_redirect_view',
          linkValueItem: 'assignee_id',
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '负责人',
          codeName: 'assignee_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'assignee_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'customer_name',
          excelCaption: '客户',
          linkAppViewId: 'plmweb.customer_redirect_view',
          linkValueItem: 'customer_id',
          appDEFieldId: 'customer_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '客户',
          codeName: 'customer_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'customer_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'submitter_name',
          excelCaption: '提交人',
          appDEFieldId: 'submitter_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '提交人',
          codeName: 'submitter_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'submitter_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'submitted_at',
          excelCaption: '提交时间',
          appDEFieldId: 'submitted_at',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '提交时间',
          codeName: 'submitted_at',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'submitted_at',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type_text',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_name',
        },
        {
          appDEFieldId: 'customer_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'customer_name',
        },
        {
          appDEFieldId: 'submitter_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'submitter_name',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'submitted_at',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'submitted_at',
        },
        {
          appDEFieldId: 'channel',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'channel',
        },
        {
          appDEFieldId: 'assignee_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_id',
        },
        {
          appDEFieldId: 'submitter_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'submitter_id',
        },
        {
          appDEFieldId: 'estimated_at',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'estimated_at',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'product_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'product_id',
        },
        {
          appDEFieldId: 'customer_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'customer_id',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmstag',
        },
      ],
      degridEditItems: [
        {
          caption: '标题',
          codeName: 'title',
          enableCond: 3,
          appDEFieldId: 'title',
          editor: {
            maxLength: 500,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'title',
          },
          allowEmpty: true,
          id: 'title',
        },
        {
          caption: '状态',
          codeName: 'state',
          enableCond: 3,
          appDEFieldId: 'state',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__ticket_state',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'state',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'state',
        },
        {
          caption: '类型',
          codeName: 'type',
          enableCond: 3,
          appDEFieldId: 'type',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__product_ticket_type',
            editorType: 'DROPDOWNLIST',
            editorItems: [
              {
                id: 'type',
              },
            ],
            valueType: 'SIMPLE',
            editable: true,
            id: 'type',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'type',
        },
        {
          caption: '负责人',
          codeName: 'assignee_name',
          enableCond: 3,
          appDEFieldId: 'assignee_name',
          editor: {
            singleSelect: true,
            appDEACModeId: 'member_select',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'plmweb.product_member',
            uiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '跳转至成员设置',
                  detailType: 'DEUIACTION',
                  uiactionId: 'jump_to_member_set@product_member',
                  tooltip: '跳转至成员设置',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-user-md',
                    glyph: 'xf0f0@FontAwesome',
                  },
                  id: 'u4befff7',
                },
              ],
              appDataEntityId: 'plmweb.product_member',
              uniqueTag: 'product_member__Usr0311005787',
              name: '跳转至成员设置',
              id: 'usr0311005787',
            },
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'assignee_id',
            editorParams: {
              'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
              AC: 'TRUE',
              TRIGGER: 'TRUE',
              URL: 'products/${context.product}/product_members/fetch_default',
              PICKUPVIEW: 'FALSE',
              USERMETHOD: 'post',
              USERMAP: '{"id":"user_id","name":"name"}',
              DEPTMAP: '{"id":"id","name":"display_name"}',
              DEPTMETHOD: 'get',
              DEPTURL: '/users/fetch_default',
            },
            editorStyle: 'PERSONEL_SELECT_PRODUCT',
            editorType: 'PICKEREX_TRIGGER',
            editorItems: [{}],
            sysPFPluginId: 'person_select',
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_department_id_eq',
                value: 'srforgsectorid',
                id: 'n_department_id_eq',
              },
            ],
            id: 'assignee_name',
          },
          allowEmpty: true,
          id: 'assignee_name',
        },
        {
          caption: '客户',
          codeName: 'customer_name',
          enableCond: 3,
          appDEFieldId: 'customer_name',
          editor: {
            singleSelect: true,
            itemParamJO: {
              fetchcond: {
                n_product_id_eq: 'product_id',
              },
            },
            paramJOString: '{"n_product_id_eq":"%product_id%"}',
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_normal',
            appDataEntityId: 'plmweb.customer',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'customer_id',
            editorParams: {
              AC: 'TRUE',
              TRIGGER: 'TRUE',
              PICKUPVIEW: 'FALSE',
            },
            editorType: 'PICKEREX_TRIGGER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_product_id_eq',
                value: 'product_id',
                id: 'n_product_id_eq',
              },
            ],
            id: 'customer_name',
          },
          resetItemNames: ['product_id'],
          allowEmpty: true,
          id: 'customer_name',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'assignee_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'assignee_id',
        },
        {
          enableCond: 3,
          appDEFieldId: 'customer_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          resetItemNames: ['product_id'],
          allowEmpty: true,
          id: 'customer_id',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEditChangedOnly: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_common',
        appDataEntityId: 'plmweb.ticket',
        id: 'fetch',
      },
      dedataExportId: 'dataexport',
      dedataImportId: 'import_ticket',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.ticket',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'allocate_person@ticket',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '分配负责人',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-user-plus',
                glyph: 'xf234@FontAwesome',
              },
              tooltip: '分配负责人',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'choose_tag@ticket',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '设置标签',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-tags',
                glyph: 'xf02c@FontAwesome',
              },
              tooltip: '设置标签',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'ticket_archive@ticket',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '归档',
                  itemType: 'DEUIACTION',
                  controlLogics: [
                    {
                      itemName: 'deuiaction3',
                      logicTag: 'grid_batchtoolbar',
                      logicType: 'SCRIPT',
                      scriptCode: '!data.is_archived',
                      triggerType: 'ITEMENABLE',
                      id: 'deuiaction3',
                    },
                  ],
                  sysImage: {
                    cssClass: 'fa fa-archive',
                    glyph: 'xf187@FontAwesome',
                  },
                  tooltip: '归档',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'activate@ticket',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '激活',
                  itemType: 'DEUIACTION',
                  controlLogics: [
                    {
                      itemName: 'deuiaction5',
                      logicTag: 'grid_batchtoolbar',
                      logicType: 'SCRIPT',
                      scriptCode: '!!data.is_archived',
                      triggerType: 'ITEMENABLE',
                      id: 'deuiaction5',
                    },
                  ],
                  sysImage: {
                    cssClass: 'key',
                  },
                  tooltip: '激活',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction5',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'ticket_delete@ticket',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
              ],
              valid: true,
              caption: '更多',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-list-ul',
                glyph: 'xf0ca@FontAwesome',
              },
              tooltip: '更多',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
          ],
          codeName: 'test_all_grid_view_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '需求工单批操作工具栏',
          appDataEntityId: 'plmweb.ticket',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: '6ac708f68c1ab990f6f12a92bad3d65f',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'test_all_grid_view_grid_batchtoolbar',
        },
      ],
      codeName: 'main',
      controlStyle: 'NUMBER_GRID',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {
        id: 'grid',
      },
      sysPFPluginId: 'number_grid',
      modelId: '9db1aa2be35a58b18c1974ca7cb64cc1',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.ticket.main',
    },
    {
      groupMode: 'SINGLE',
      groupMoreText: '更多',
      searchBarFilters: [
        {
          dataType: 25,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'assignee_id',
            editorParams: {
              ISADDSYMBOL: 'true',
              MULTIPLE: 'true',
              'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
              AC: 'TRUE',
              TRIGGER: 'TRUE',
              URL: 'products/${context.product}/product_members/fetch_default',
              PICKUPVIEW: 'FALSE',
              USERMETHOD: 'post',
              USERMAP: '{"id":"user_id","name":"name"}',
              DEPTMAP: '{"id":"id","name":"display_name"}',
              DEPTMETHOD: 'get',
              DEPTURL: '/users/fetch_default',
            },
            editorStyle: 'PERSONEL_SELECT_PRODUCT',
            editorType: 'PICKEREX_TRIGGER',
            sysPFPluginId: 'person_select',
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_department_id_eq',
                value: 'srforgsectorid',
                id: 'n_department_id_eq',
              },
            ],
            id: 'assignee_id',
          },
          allowEmpty: true,
          caption: '负责人',
          itemType: 'FILTER',
          appDEFieldId: 'assignee_id',
          id: 'assignee_id',
        },
        {
          dataType: 25,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__product_ticket_type',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'type',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          itemType: 'FILTER',
          appDEFieldId: 'type',
          id: 'type',
        },
        {
          dataType: 25,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__ticket_state',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'state',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          itemType: 'FILTER',
          appDEFieldId: 'state',
          id: 'state',
        },
        {
          dataType: 25,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.prodmgmt__ticket_priority',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'priority',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          itemType: 'FILTER',
          appDEFieldId: 'priority',
          id: 'priority',
        },
        {
          dataType: 9,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.yesno',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'is_archived',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          itemType: 'FILTER',
          appDEFieldId: 'is_archived',
          id: 'is_archived',
        },
      ],
      searchBarGroups: [
        {
          defaultGroup: true,
          caption: '全部工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          id: 'all',
        },
        {
          caption: '待计划的工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"state","condop":"EQ","value":"10"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          id: 'unplan',
        },
        {
          caption: '进行中的工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"state","condop":"EQ","value":"20"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          id: 'underway',
        },
        {
          caption: '我提交的工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"create_man","condop":"EQ","value":"${context.srfpersonid}"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          id: 'my_create',
        },
        {
          caption: '我负责的工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"assignee_id","condop":"EQ","value":"${context.srfpersonid}"},{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          id: 'my_assignee',
        },
        {
          caption: '已归档的工单',
          data: '{"theme_model": {"searchconds": [{"condtype":"GROUP", "condop":"AND", "bnotmode":false, "searchconds": [{"condtype":"DEFIELD","fieldname":"is_archived","condop":"EQ","value":"1"}]}]}}\n',
          itemType: 'GROUP',
          id: 'archive',
        },
      ],
      quickGroupCount: 4,
      quickSearchMode: 1,
      searchBarStyle: 'SEARCHBAR2',
      enableFilter: true,
      enableGroup: true,
      enableQuickSearch: true,
      codeName: 'ticket_searchbar',
      controlType: 'SEARCHBAR',
      logicName: '工单搜索栏',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {
        id: 'searchbar',
      },
      modelId: 'baf226cf8165dfb257dd6b2e757add9e',
      modelType: 'PSSYSSEARCHBAR',
      name: 'searchbar',
      id: 'plmweb.ticket.ticket_searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.TICKET',
      },
      caption: '全部工单',
      codeName: 'test_all_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.ticket',
      controlParam: {},
      name: 'captionbar',
      id: 'test_all_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.ticket',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '全部工单——测试',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '19f4465c4e9712f27e5348c8066d1840',
  modelType: 'PSAPPDEVIEW',
  name: 'tickettest_all_grid_view',
  id: 'plmweb.ticket_test_all_grid_view',
};
