export default {
  mdctrlActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'user_pick_up_tree_view',
  deviewId: '05A5E7AD-5BE1-483E-A3F3-7B2A1B43A92E',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  caption: '用户选择',
  codeName: 'user_user_pick_up_tree_view',
  appDataEntityId: 'plmweb.user',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupTreeView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'roles',
          parentDETreeNodeId: 'role',
          parentValueLevel: 1,
          searchMode: 3,
          id: '角色 - 角色(动态)',
        },
        {
          childDETreeNodeId: 'depts',
          parentDETreeNodeId: 'dept',
          parentValueLevel: 1,
          searchMode: 3,
          id: '部门 - 部门（动态）',
        },
        {
          childDETreeNodeId: 'role',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 角色',
        },
        {
          childDETreeNodeId: 'users',
          parentDETreeNodeId: 'user',
          parentValueLevel: 1,
          searchMode: 3,
          id: '成员 - 成员（动态）',
        },
        {
          childDETreeNodeId: 'groups',
          parentDETreeNodeId: 'group',
          parentValueLevel: 1,
          searchMode: 3,
          id: '团队 - 团队（动态）',
        },
        {
          childDETreeNodeId: 'group_member',
          parentFilter: 'owner_id',
          parentDETreeNodeId: 'groups',
          parentValueLevel: 1,
          searchMode: 3,
          id: '团队（动态） - 团队成员(动态)',
        },
        {
          childDETreeNodeId: 'sub_depts',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'department',
            dertype: 'DER1N',
            logicName: '父部门',
            minorCodeName: 'departments',
            minorServiceCodeName: 'departments',
            orderValue: 100,
            serviceCodeName: 'department',
            name: 'DER1N_DEPARTMENT_DEPARTMENT_PARENT_ID',
            id: 'base.department.der1n_department_department_parent_id',
          },
          parentDETreeNodeId: 'depts',
          parentValueLevel: 1,
          searchMode: 3,
          id: '部门（动态） - 子部门（动态）',
        },
        {
          childDETreeNodeId: 'sub_depts',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'department',
            dertype: 'DER1N',
            logicName: '父部门',
            minorCodeName: 'departments',
            minorServiceCodeName: 'departments',
            orderValue: 100,
            serviceCodeName: 'department',
            name: 'DER1N_DEPARTMENT_DEPARTMENT_PARENT_ID',
            id: 'base.department.der1n_department_department_parent_id',
          },
          parentDETreeNodeId: 'sub_depts',
          parentValueLevel: 1,
          searchMode: 3,
          id: '子部门（动态） - 子部门（动态）',
        },
        {
          childDETreeNodeId: 'user',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 成员',
        },
        {
          childDETreeNodeId: 'dept',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 部门',
        },
        {
          childDETreeNodeId: 'group',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 团队',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '部门',
          nodeType: 'dept',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          name: '部门',
          id: 'dept',
        },
        {
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_root',
          textAppDEFieldId: 'name',
          nodeType: 'depts',
          appDataEntityId: 'plmweb.department',
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '部门（动态）',
          id: 'depts',
        },
        {
          text: '团队',
          nodeType: 'group',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          name: '团队',
          id: 'group',
        },
        {
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'group_member',
          appDataEntityId: 'plmweb.member',
          treeNodeType: 'DE',
          name: '团队成员(动态)',
          id: 'group_member',
        },
        {
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'groups',
          appDataEntityId: 'plmweb.group',
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '团队（动态）',
          id: 'groups',
        },
        {
          text: '角色',
          nodeType: 'role',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          name: '角色',
          id: 'role',
        },
        {
          nodeType: 'roles',
          treeNodeType: 'DE',
          name: '角色(动态)',
          id: 'roles',
        },
        {
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'sub_depts',
          appDataEntityId: 'plmweb.department',
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '子部门（动态）',
          id: 'sub_depts',
        },
        {
          text: '成员',
          nodeType: 'user',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          name: '成员',
          id: 'user',
        },
        {
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'users',
          appDataEntityId: 'plmweb.user',
          treeNodeType: 'DE',
          name: '成员（动态）',
          id: 'users',
        },
      ],
      outputIconDefault: true,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.user',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'plmweb.user',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.user',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.user',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.user',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'pick_up_tree',
      controlType: 'TREEVIEW',
      logicName: '成员选择树',
      appDataEntityId: 'plmweb.user',
      controlParam: {
        id: 'tree',
      },
      modelId: 'FDFAB2E9-4832-4C1A-81BE-673DDAEEFAED',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'plmweb.user.pick_up_tree',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.user',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      caption: '用户选择',
      codeName: 'user_pick_up_tree_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.user',
      controlParam: {},
      name: 'captionbar',
      id: 'user_pick_up_tree_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPTREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.user',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '用户选择',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPTREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c2ea6d27a768afae8a5b1080f291a655',
  modelType: 'PSAPPDEVIEW',
  name: 'useruser_pick_up_tree_view',
  id: 'plmweb.user_user_pick_up_tree_view',
};
