export default {
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'management_work_type_grid_view',
  deviewId: '7b6a5ae8a48feb055c800359c21faab9',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORKLOAD',
  },
  caption: '工时',
  codeName: 'workload_management_work_type_grid_view',
  appDataEntityId: 'plmweb.workload',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_searchform',
              },
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onBeforeLoadDraft',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'searchform',
        scriptCode:
          "const time = new Date();\r\nconst preTime = new Date(time.getTime() - 604800000);\r\nconst n_register_date_gtandeq = preTime.getFullYear() +'-' +(preTime.getMonth() + 1 < 10 ? '0' + (preTime.getMonth() + 1): preTime.getMonth() + 1) +'-' +(preTime.getDate() < 10 ? '0' + preTime.getDate() : preTime.getDate()) \r\nconst n_register_date_ltandeq = time.getFullYear() +'-' +(time.getMonth() + 1 < 10 ? '0' + (time.getMonth() + 1): time.getMonth() + 1) +'-' +(time.getDate() < 10 ? '0' + time.getDate() : time.getDate())\r\nconst date_range = n_register_date_gtandeq + ',' + n_register_date_ltandeq;\r\nObject.assign(viewParam, { n_register_date_gtandeq, n_register_date_ltandeq, date_range });",
        builtinLogic: true,
        name: 'LOGICUPDATE',
        id: 'logicupdate',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.workload_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.workload_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'plmweb.workload_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.workload_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '工时数据重定向视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORKLOAD.REDIRECTVIEW',
        },
        refAppViewId: 'plmweb.workload_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '工时编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORKLOAD.EDITVIEW',
        },
        refAppViewId: 'plmweb.workload_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'AUTO',
        groupAppDEFieldId: 'type_id',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'type_name',
            excelCaption: '工作类别',
            appDEFieldId: 'type_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '工作类别',
            codeName: 'type_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'type_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'duration',
            excelCaption: '总登记工时',
            appDEFieldId: 'duration',
            deuiactionId: 'management_type_duration_link@workload',
            valueFormat: '#0.0',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '总登记工时',
            codeName: 'duration',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'duration',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'type_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'type_name',
          },
          {
            format: '#0.0',
            appDEFieldId: 'duration',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'duration',
          },
          {
            appDEFieldId: 'type_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'type_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableGroup: true,
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetch_type_of_management_dimension',
          appDataEntityId: 'plmweb.workload',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.workload',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'workload_type_management_grid',
        controlStyle: 'WORKLOAD_TABLE',
        controlType: 'GRID',
        logicName: '工时日历_工作类别（管理）_表格',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          ctrlParams: {
            DATERANGE: 'date_range',
          },
          id: 'grid',
        },
        sysPFPluginId: 'workload_table',
        modelId: '15e1e72e75c6b687f572fdf4ff7670ae',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.workload.workload_type_management_grid',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                editor: {
                  editorParams: {
                    TIMEFMT: 'YYYY-MM-DD',
                  },
                  editorType: 'DATERANGE_NOTIME',
                  editorItems: [
                    {
                      id: 'n_register_date_gtandeq',
                    },
                    {
                      id: 'n_register_date_ltandeq',
                    },
                  ],
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'date_range',
                },
                allowEmpty: true,
                caption: '工作日期',
                codeName: 'date_range',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                controlAttributes: [
                  {
                    attrName: 'disabledDate',
                    attrValue:
                      "(time) => {\r\n    const searchForm = view.ctx.controllersMap.get('searchform');\r\n    if (!searchForm) {\r\n        return false;\r\n    }\r\n\r\n    const formItem = searchForm.formItems.find((item) => item.model.codeName === 'date_range');\r\n    if(!formItem) {\r\n        return false;\r\n    }\r\n\r\n    // 获取日期弹框内选择日期的选中值t\r\n    const dateRange = formItem.editor.dateRange;\r\n    if (!dateRange || dateRange && dateRange.length === 0) {\r\n        return false;\r\n    }\r\n\r\n    const currentTime = dateRange[0];\r\n    currentTime.setHours(0, 0, 0, 0);\r\n    time.setHours(0, 0, 0, 0);\r\n\r\n    const beforeDays = new Date(\r\n        currentTime.getTime() - 31 * 24 * 60 * 60 * 1000,\r\n    );\r\n    const afterDays = new Date(\r\n        currentTime.getTime() + 31 * 24 * 60 * 60 * 1000,\r\n    );\r\n\r\n    return (\r\n        beforeDays.getTime() >= time.getTime() ||\r\n        afterDays.getTime() <= time.getTime()\r\n    );\r\n}",
                    name: 'logic_disabledDate',
                    id: 'logic_disableddate',
                  },
                  {
                    attrName: 'clearable',
                    attrValue: 'false',
                    id: 'logic_clearable',
                  },
                ],
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'date_range',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'register_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_register_date_gtandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '工作日期（大于）',
                codeName: 'n_register_date_gtandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_register_date_gtandeq',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'register_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_register_date_ltandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '工作日期（小于）',
                codeName: 'n_register_date_ltandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_register_date_ltandeq',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.WORKLOAD.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'register_date_search_form',
        controlType: 'SEARCHFORM',
        logicName: '登记日期_搜索表单',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'searchform',
        },
        modelId: '3318849a4312bd64804d404ac154bde9',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'plmweb.workload.register_date_search_form',
      },
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.base__workload_type',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'workload_type_id',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'type_id',
            id: 'workload_type_id',
          },
        ],
        searchBarGroups: [
          {
            defaultGroup: true,
            caption: '全部类别',
            itemType: 'GROUP',
            id: 'all',
          },
        ],
        quickGroupCount: 4,
        quickSearchMode: 1,
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'type_calendar_searchbar',
        controlType: 'SEARCHBAR',
        logicName: '工作类别工时日历_搜索栏',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '75d5b22971522d0071e11a7a417edcc9',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'plmweb.workload.type_calendar_searchbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'exportexcel',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.EXPORT',
            },
            caption: '导出',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-excel-o',
              glyph: 'xf1c3@FontAwesome',
            },
            tooltip: '导出',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.EXPORT',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'management_work_type_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工时日历_工具栏',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '1caa28e37cd29023f9d644f5b0378f0f',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'management_work_type_grid_view_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORKLOAD',
        },
        caption: '工时',
        codeName: 'management_work_type_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.workload',
        controlParam: {},
        name: 'captionbar',
        id: 'management_work_type_grid_view_captionbar',
      },
    ],
    codeName: 'usr0322579642',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'management_work_type_grid_view表格视图布局',
    appDataEntityId: 'plmweb.workload',
    controlParam: {},
    modelId: 'b80d7ed86b754e3b69492c9dbaa69eb2',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0322579642',
  },
  title: '工时日历工作类别维度表格视图（管理）',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3f15b26389fbcee597b3abbea1a36b0e',
  modelType: 'PSAPPDEVIEW',
  name: 'workloadmanagement_work_type_grid_view',
  id: 'plmweb.workload_management_work_type_grid_view',
};
