export default {
  openMode: 'INDEXVIEWTAB_POPUPMODAL',
  deviewCodeName: 'change_view',
  deviewId: 'd82f47e6a37722cd724e20a9ddcc0ce0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM_WIZARD',
  },
  caption: '变更工作项类型',
  codeName: 'work_item_wizard_change_view',
  appDataEntityId: 'plmweb.work_item_wizard',
  appViewNavParams: [
    {
      key: 'project_id',
      value: 'project',
      id: 'project_id',
    },
    {
      key: 'work_item',
      value: 'work_item',
      id: 'work_item',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '向导面板',
            contentHeight: 100,
            height: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              height: 100,
              heightMode: 'PERCENTAGE',
              layout: 'FLEX',
              spacingTop: 'OUTERLARGE',
            },
            showCaption: true,
            id: 'wizardpanel',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'WizardView',
        id: 'engine',
      },
    ],
    controls: [
      {
        finishControlAction: {
          appDEMethodId: 'change',
          appDataEntityId: 'plmweb.work_item_wizard',
          id: 'finish',
        },
        initControlAction: {
          appDEMethodId: 'createtemp',
          appDataEntityId: 'plmweb.work_item_wizard',
          id: 'init',
        },
        deeditForms: [
          {
            getControlAction: {
              appDEMethodId: 'gettemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'updatetemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'update',
            },
            dewizardForm: {
              formTag: 'choose_types',
              deformName: '选择目标类型',
              dewizardStepId: '选择目标类型',
              stepActions: ['NEXT'],
              stepTag: 'choose_types',
              firstForm: true,
              id: '选择目标类型',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        appViewId:
                          'plmweb.work_item_wizard_detail_target_type_grid_view',
                        parentDataJO: {
                          SRFPARENTTYPE: 'DER1N',
                          srfparentdename: 'WORK_ITEM_WIZARD',
                          srfparentmode:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                          srfparentdefname: 'WIZARD_ID',
                          SRFDER1NID:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                        },
                        codeName: 'druipart1',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'druipart1',
                      },
                    ],
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_TARGET_TYPES.GROUPPANEL.GROUP1',
                    },
                    caption: '工作项操作向导基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_TARGET_TYPES.FORMPAGE.FORMPAGE1',
                },
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step_target_types',
            controlType: 'FORM',
            logicName: '选择目标类型',
            appDataEntityId: 'plmweb.work_item_wizard',
            controlLogics: [
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_choose_types',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_choose_types',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_choose_types',
            },
            modelId: '19f1be308866c283d9326d56a696e811',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_choose_types',
            id: 'plmweb.work_item_wizard.step_target_types',
          },
          {
            getControlAction: {
              appDEMethodId: 'gettemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'updatetemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'update',
            },
            dewizardForm: {
              formTag: 'choose_states',
              deformName: '选择目标状态',
              dewizardStepId: '选择目标状态',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'choose_states',
              id: '选择目标状态',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        appViewId:
                          'plmweb.work_item_wizard_detail_target_state_grid_view',
                        parentDataJO: {
                          SRFPARENTTYPE: 'DER1N',
                          srfparentdename: 'WORK_ITEM_WIZARD',
                          srfparentmode:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                          srfparentdefname: 'WIZARD_ID',
                          SRFDER1NID:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                        },
                        codeName: 'druipart1',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'druipart1',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        fieldName: 'srfnextform',
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfnextform',
                        },
                        allowEmpty: true,
                        hidden: true,
                        codeName: 'srfnextform',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'srfnextform',
                      },
                    ],
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_TARGET_STATES.GROUPPANEL.GROUP1',
                    },
                    caption: '工作项操作向导基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_TARGET_STATES.FORMPAGE.FORMPAGE1',
                },
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step_target_states',
            controlType: 'FORM',
            logicName: '选择目标状态',
            appDataEntityId: 'plmweb.work_item_wizard',
            controlLogics: [
              {
                eventNames: 'onLoadSuccess',
                logicTag: 'wizardpanel_form_choose_states',
                logicType: 'SCRIPT',
                scriptCode:
                  "var detail = ctrl.data.details[0];\r\nif(detail.influence_childs == 0) {\r\n    ctrl.details.srfnextform.setDataValue('confirm');\r\n}\r\n",
                triggerType: 'CTRLEVENT',
                id: 'logic',
              },
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_choose_states',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_choose_states',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_choose_states',
            },
            modelId: 'df3014dc93d209d99ba66a635e2ee021',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_choose_states',
            id: 'plmweb.work_item_wizard.step_target_states',
          },
          {
            getControlAction: {
              appDEMethodId: 'gettemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'updatetemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'update',
            },
            dewizardForm: {
              formTag: 'choose_parent',
              deformName: '选择子工作项所属父级',
              dewizardStepId: '选择子工作项所属父级',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'choose_parent',
              id: '选择子工作项所属父级',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        rawItem: {
                          caption: '原工作项类型',
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          id: 'rawitem1',
                        },
                        codeName: 'rawitem1',
                        detailStyle: 'DEFAULT',
                        detailType: 'RAWITEM',
                        layoutPos: {
                          colLG: 4,
                          colMD: 4,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'rawitem1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            rawItem: {
                              caption: '子工作项类型',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem2',
                            },
                            codeName: 'rawitem2',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 4,
                              colMD: 4,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem2',
                          },
                          {
                            rawItem: {
                              caption: '原父工作项',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem3',
                            },
                            codeName: 'rawitem3',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 8,
                              colMD: 8,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem3',
                          },
                          {
                            rawItem: {
                              caption: '目标父工作项',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem4',
                            },
                            codeName: 'rawitem4',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 8,
                              colMD: 8,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem4',
                          },
                          {
                            rawItem: {
                              caption: '影响工作项',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem5',
                            },
                            codeName: 'rawitem5',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 3,
                              colLGOffset: 1,
                              colMD: 3,
                              colMDOffset: 1,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem5',
                          },
                        ],
                        codeName: 'grouppanel2',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 20,
                          colMD: 20,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel2',
                      },
                    ],
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    sysCss: {
                      cssName: 'form-group-to-grid-header',
                    },
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        buildInActions: 2,
                        contentType: 'REPEATER',
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            fieldName: 'id',
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'detail_id',
                            },
                            allowEmpty: true,
                            hidden: true,
                            codeName: 'detail_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            repeatContent: true,
                            id: 'detail_id',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'influence_childs',
                            },
                            allowEmpty: true,
                            hidden: true,
                            codeName: 'influence_childs',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            repeatContent: true,
                            id: 'influence_childs',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'target_type',
                            },
                            allowEmpty: true,
                            hidden: true,
                            codeName: 'target_type',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            repeatContent: true,
                            id: 'target_type',
                          },
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                ignoreInput: 3,
                                labelPos: 'NONE',
                                noPrivDisplayMode: 1,
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId:
                                    'plmweb.projmgmt__work_item_type',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'origin_type',
                                },
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                codeName: 'origin_type',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 4,
                                  colMD: 4,
                                  layout: 'TABLE_24COL',
                                },
                                repeatContent: true,
                                id: 'origin_type',
                              },
                              {
                                buildInActions: 2,
                                contentType: 'REPEATER',
                                fieldName: 'child_work_item_types',
                                layout: {
                                  columnCount: 24,
                                  layout: 'TABLE_24COL',
                                },
                                deformDetails: [
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    ignoreInput: 3,
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      halign: 'LEFT',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      appCodeListId:
                                        'plmweb.projmgmt__work_item_type',
                                      editorType: 'SPAN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'child_work_item_type',
                                    },
                                    allowEmpty: true,
                                    convertToCodeItemText: true,
                                    codeName: 'child_work_item_type',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colLG: 4,
                                      colMD: 4,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'child_work_item_type',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      halign: 'LEFT',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorParams: {
                                        overflowMode: 'ellipsis',
                                      },
                                      editorType: 'SPAN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'parent_title',
                                    },
                                    allowEmpty: true,
                                    codeName: 'parent_title',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colLG: 8,
                                      colMD: 8,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'parent_title',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    fieldName: 'target_parent_title',
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      enableLinkView: true,
                                      singleSelect: true,
                                      pickupAppViewId:
                                        'plmweb.work_item_change_parent_pick_up_view',
                                      appDEACModeId: 'default',
                                      appDEDataSetId: 'fetch_normal',
                                      appDataEntityId: 'plmweb.work_item',
                                      enableAC: true,
                                      forceSelection: true,
                                      showTrigger: true,
                                      valueItemName: 'target_parent',
                                      editorParams: {
                                        'srfnavparam.n_id_noteq': '%work_item%',
                                        overflowMode: 'ellipsis',
                                        'srfnavparam.n_work_item_type_id_eq':
                                          '%parent_origin_type%',
                                        LINKVIEW: 'TRUE',
                                        AC: 'TRUE',
                                        TRIGGER: 'TRUE',
                                        PICKUPVIEW: 'FALSE',
                                      },
                                      editorType: 'PICKEREX_TRIGGER_LINK',
                                      placeHolder: '搜索标题或编号',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      navigateParams: [
                                        {
                                          key: 'n_id_noteq',
                                          value: 'work_item',
                                          id: 'n_id_noteq',
                                        },
                                        {
                                          key: 'n_work_item_type_id_eq',
                                          value: 'parent_origin_type',
                                          id: 'n_work_item_type_id_eq',
                                        },
                                      ],
                                      id: 'target_parent_title',
                                    },
                                    allowEmpty: true,
                                    codeName: 'target_parent_title',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colLG: 8,
                                      colMD: 8,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'target_parent_title',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      halign: 'LEFT',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorType: 'SPAN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'influence',
                                    },
                                    allowEmpty: true,
                                    codeName: 'influence',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colLG: 2,
                                      colLGOffset: 2,
                                      colMD: 2,
                                      colMDOffset: 2,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'influence',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    fieldName: 'id',
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      editorType: 'HIDDEN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'child_id',
                                    },
                                    allowEmpty: true,
                                    hidden: true,
                                    codeName: 'child_id',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'child_id',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    fieldName: 'parent_origin_type',
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      editorType: 'HIDDEN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'parent_origin_type',
                                    },
                                    allowEmpty: true,
                                    hidden: true,
                                    codeName: 'parent_origin_type',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'parent_origin_type',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    fieldName: 'target_parent',
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      editorType: 'HIDDEN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'target_parent',
                                    },
                                    allowEmpty: true,
                                    hidden: true,
                                    codeName: 'target_parent',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'target_parent',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      editorType: 'HIDDEN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'target_state',
                                    },
                                    allowEmpty: true,
                                    hidden: true,
                                    codeName: 'target_state',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'target_state',
                                  },
                                  {
                                    dataType: 25,
                                    enableCond: 3,
                                    fieldName: 'influence_child_ids',
                                    labelPos: 'NONE',
                                    noPrivDisplayMode: 1,
                                    editor: {
                                      editorType: 'HIDDEN',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'influence_child_ids',
                                    },
                                    allowEmpty: true,
                                    hidden: true,
                                    codeName: 'influence_child_ids',
                                    detailStyle: 'DEFAULT',
                                    detailType: 'FORMITEM',
                                    layoutPos: {
                                      colMD: 24,
                                      layout: 'TABLE_24COL',
                                    },
                                    repeatContent: true,
                                    id: 'influence_child_ids',
                                  },
                                ],
                                codeName: 'child_work_item_types',
                                detailStyle: 'DEFAULT',
                                detailType: 'MDCTRL',
                                layoutPos: {
                                  colLG: 20,
                                  colMD: 20,
                                  layout: 'TABLE_24COL',
                                },
                                repeatContent: true,
                                showCaption: true,
                                id: 'child_work_item_types',
                              },
                            ],
                            codeName: 'grouppanel3',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['influence_childs'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'NOTEQ',
                                    defdname: 'influence_childs',
                                    value: '0',
                                    logicType: 'SINGLE',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            repeatContent: true,
                            id: 'grouppanel3',
                          },
                        ],
                        codeName: 'details',
                        detailStyle: 'DEFAULT',
                        detailType: 'MDCTRL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'details',
                      },
                    ],
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_CHILD_WORK_ITEM_PARENT.GROUPPANEL.GROUP1',
                    },
                    caption: '工作项操作向导基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'influence_ids',
                    },
                    allowEmpty: true,
                    hidden: true,
                    codeName: 'influence_ids',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'influence_ids',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_CHILD_WORK_ITEM_PARENT.FORMPAGE.FORMPAGE1',
                },
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step_child_work_item_parent',
            controlType: 'FORM',
            logicName: '选择子工作项所属父级',
            appDataEntityId: 'plmweb.work_item_wizard',
            controlLogics: [
              {
                eventNames: 'onLoadSuccess',
                logicTag: 'wizardpanel_form_choose_parent',
                logicType: 'SCRIPT',
                scriptCode: 'console.log("当前部件", ctrl)',
                triggerType: 'CTRLEVENT',
                id: 'logic',
              },
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_choose_parent',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_choose_parent',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_choose_parent',
            },
            modelId: '971f448995c12599b4103020cc22cd0c',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_choose_parent',
            id: 'plmweb.work_item_wizard.step_child_work_item_parent',
          },
          {
            getControlAction: {
              appDEMethodId: 'gettemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'updatetemp',
              appDataEntityId: 'plmweb.work_item_wizard',
              id: 'update',
            },
            dewizardForm: {
              formTag: 'confirm',
              deformName: '确认变更类型',
              dewizardStepId: '确认变更类型',
              stepActions: ['PREV', 'FINISH'],
              stepTag: 'confirm',
              id: '确认变更类型',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        appViewId:
                          'plmweb.work_item_wizard_detail_change_confirm_grid_view',
                        parentDataJO: {
                          SRFPARENTTYPE: 'DER1N',
                          srfparentdename: 'WORK_ITEM_WIZARD',
                          srfparentmode:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                          srfparentdefname: 'WIZARD_ID',
                          SRFDER1NID:
                            'DER1N_WORK_ITEM_WIZARD_DETAIL_WORK_ITEM_WIZARD_WIZARD_ID',
                        },
                        codeName: 'druipart1',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'druipart1',
                      },
                      {
                        dataType: 21,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'details',
                        editor: {
                          editorType: 'HIDDEN',
                          objectIdField: 'id',
                          objectNameField: 'name',
                          valueType: 'OBJECTS',
                          editable: true,
                          id: 'details',
                        },
                        allowEmpty: true,
                        hidden: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DETAILS',
                        },
                        caption: '向导明细',
                        codeName: 'details',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'details',
                      },
                    ],
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_CONFIRM.GROUPPANEL.GROUP1',
                    },
                    caption: '工作项操作向导基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.WORK_ITEM_WIZARD.STEP_CONFIRM.FORMPAGE.FORMPAGE1',
                },
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step_confirm',
            controlType: 'FORM',
            logicName: '确认变更类型',
            appDataEntityId: 'plmweb.work_item_wizard',
            controlLogics: [
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_confirm',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_confirm',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_confirm',
            },
            modelId: '02780d739d3a3d06601873e6073daeb4',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_confirm',
            id: 'plmweb.work_item_wizard.step_confirm',
          },
        ],
        dewizard: {
          codeName: 'change_wizard',
          firstDEWizardFormId: '选择目标类型',
          nextCaption: '下一步',
          dewizardForms: [
            {
              formTag: 'choose_types',
              deformName: '选择目标类型',
              dewizardStepId: '选择目标类型',
              stepActions: ['NEXT'],
              stepTag: 'choose_types',
              firstForm: true,
              id: '选择目标类型',
            },
            {
              formTag: 'choose_states',
              deformName: '选择目标状态',
              dewizardStepId: '选择目标状态',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'choose_states',
              id: '选择目标状态',
            },
            {
              formTag: 'choose_parent',
              deformName: '选择子工作项所属父级',
              dewizardStepId: '选择子工作项所属父级',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'choose_parent',
              id: '选择子工作项所属父级',
            },
            {
              formTag: 'confirm',
              deformName: '确认变更类型',
              dewizardStepId: '确认变更类型',
              stepActions: ['PREV', 'FINISH'],
              stepTag: 'confirm',
              id: '确认变更类型',
            },
          ],
          dewizardSteps: [
            {
              stepTag: 'choose_types',
              title: '选择目标类型',
              id: '选择目标类型',
            },
            {
              stepTag: 'choose_states',
              title: '选择目标状态',
              id: '选择目标状态',
            },
            {
              stepTag: 'choose_parent',
              title: '选择子工作项所属父级',
              id: '选择子工作项所属父级',
            },
            {
              stepTag: 'confirm',
              title: '确认变更类型',
              id: '确认变更类型',
            },
          ],
          prevCaption: '上一步',
          wizardStyle: 'DEFAULT',
          name: '变更工作项类型向导视图_向导',
          id: 'projmgmt.work_item_wizard.change_wizard',
        },
        wizardStyle: 'DEFAULT',
        showActionBar: true,
        showStepBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'change_wizard',
        controlType: 'WIZARDPANEL',
        logicName: '变更工作项类型向导视图_向导',
        appDataEntityId: 'plmweb.work_item_wizard',
        controlParam: {
          id: 'wizardpanel',
        },
        modelId: '69c4b43c0e884793c0b2bd600e273e5f',
        modelType: 'PSDEWIZARDPANEL',
        name: 'wizardpanel',
        id: 'plmweb.work_item_wizard.change_wizard',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORK_ITEM_WIZARD',
        },
        caption: '变更工作项类型',
        codeName: 'change_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.work_item_wizard',
        controlParam: {},
        name: 'captionbar',
        id: 'change_view_captionbar',
      },
    ],
    codeName: 'usr0717603071',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'change_view向导视图布局面板',
    appDataEntityId: 'plmweb.work_item_wizard',
    controlParam: {},
    modelId: 'f1b21c1c0714ab129c419885cc0dc55d',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0717603071',
  },
  title: '变更工作项类型',
  viewStyle: 'DEFAULT',
  viewType: 'DEWIZARDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f453458bc482b00a31140e9042f68b77',
  modelType: 'PSAPPDEVIEW',
  name: 'work_item_wizardchange_view',
  id: 'plmweb.work_item_wizard_change_view',
};
