export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'calendar_management_view',
  deviewId: '3f4ad1949c6a6f252a3a2e059e7c50ed',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORKLOAD',
  },
  caption: '工时',
  codeName: 'workload_calendar_management_view',
  appDataEntityId: 'plmweb.workload',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onActive',
      logicTrigger: 'CTRLEVENT',
      logicType: 'APPDEUILOGIC',
      appDEUILogicId: 'open_main_view',
      appDataEntityId: 'plmweb.workload',
      ctrlName: 'grid',
      builtinLogic: true,
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      eventNames: 'onBeforeLoadDraft',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'searchform',
      scriptCode:
        "const time = new Date();\r\nconst preTime = new Date(time.getTime() - 604800000);\r\nconst n_register_date_gtandeq = preTime.getFullYear() +'-' +(preTime.getMonth() + 1 < 10 ? '0' + (preTime.getMonth() + 1): preTime.getMonth() + 1) +'-' +(preTime.getDate() < 10 ? '0' + preTime.getDate() : preTime.getDate()) \r\nconst n_register_date_ltandeq = time.getFullYear() +'-' +(time.getMonth() + 1 < 10 ? '0' + (time.getMonth() + 1): time.getMonth() + 1) +'-' +(time.getDate() < 10 ? '0' + time.getDate() : time.getDate())\r\nconst date_range = n_register_date_gtandeq + ',' + n_register_date_ltandeq;\r\nObject.assign(viewParam, { n_register_date_gtandeq, n_register_date_ltandeq, date_range });",
      builtinLogic: true,
      name: 'LOGICUPDATE',
      id: 'logicupdate',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'plmweb.workload_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'plmweb.workload_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '工时编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.WORKLOAD.EDITVIEW',
      },
      refAppViewId: 'plmweb.workload_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '工时数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.WORKLOAD.REDIRECTVIEW',
      },
      refAppViewId: 'plmweb.workload_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'PAGE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'AUTO',
      groupAppDEFieldId: 'show_identifier',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'show_identifier',
          excelCaption: '编号',
          appDEFieldId: 'show_identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编号',
          codeName: 'show_identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'show_identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '事项',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '事项',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'duration',
          excelCaption: '总登记工时',
          appDEFieldId: 'duration',
          valueFormat: '#0.0',
          valueType: 'SIMPLE',
          aggMode: 'SUM',
          align: 'RIGHT',
          caption: '总登记工时',
          codeName: 'duration',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 130,
          widthUnit: 'PX',
          enableSort: true,
          id: 'duration',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'show_identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'show_identifier',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          format: '#0.0',
          appDEFieldId: 'duration',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'duration',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableGroup: true,
      singleSelect: true,
      fetchControlAction: {
        appDEMethodId: 'fetch_calendar',
        appDataEntityId: 'plmweb.workload',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.workload',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_grid',
      controlStyle: 'WORKLOAD_TABLE',
      controlType: 'GRID',
      logicName: '工时日历表格',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        ctrlParams: {
          DATERANGE: 'date_range',
        },
        id: 'grid',
      },
      sysPFPluginId: 'workload_table',
      modelId: '2d0860cea7f6c9d96431ca05e885d93f',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.workload.calendar_grid',
    },
    {
      searchButtonStyle: 'NONE',
      enableAutoSearch: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              editor: {
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATERANGE_NOTIME',
                editorItems: [
                  {
                    id: 'n_register_date_gtandeq',
                  },
                  {
                    id: 'n_register_date_ltandeq',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'date_range',
              },
              allowEmpty: true,
              caption: '工作日期',
              codeName: 'date_range',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              controlAttributes: [
                {
                  attrName: 'shortcuts',
                  attrValue:
                    "[\r\n    {\r\n    text: '最近7天',\r\n    value: () => {\r\n        const end_at = new Date();\r\n        const start_at = new Date();\r\n        start_at.setDate(end_at.getDate() - 6);\r\n        return [start_at, end_at];\r\n    },\r\n    },\r\n    {\r\n    text: '最近30天',\r\n    value: () => {\r\n        const end_at = new Date();\r\n        const start_at = new Date();\r\n        start_at.setDate(end_at.getDate() - 29);\r\n        return [start_at, end_at];\r\n    },\r\n    },\r\n    {\r\n    text: '本周',\r\n    value: () => {\r\n        const end_at = new Date();\r\n        const currentDay = end_at.getDay();\r\n        const start_at = new Date(end_at);\r\n\r\n        // 计算本周的开始日期 (周一)\r\n        start_at.setDate(\r\n        end_at.getDate() - currentDay + (currentDay === 0 ? -6 : 1),\r\n        );\r\n        return [start_at, end_at];\r\n    },\r\n    },\r\n    {\r\n    text: '本月',\r\n    value: () => {\r\n        const end_at = new Date();\r\n        const start_at = new Date(end_at);\r\n\r\n        // 将日期设置为本月第一天\r\n        start_at.setDate(1);\r\n        return [start_at, end_at];\r\n    },\r\n    },\r\n]",
                  id: 'date_range_shortcuts',
                },
              ],
              layoutPos: {
                colLG: 4,
                colMD: 4,
                colSM: 8,
                colXS: 8,
                layout: 'TABLE_24COL',
              },
              id: 'date_range',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'show_identifier',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '编号',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_show_identifier_like',
              },
              allowEmpty: true,
              caption: '编号',
              codeName: 'n_show_identifier_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 3,
                colMD: 3,
                colSM: 8,
                colXS: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_show_identifier_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '事项',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.WORKLOAD.N_NAME_LIKE',
              },
              caption: '事项',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 3,
                colMD: 3,
                colSM: 8,
                colXS: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_name_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              editor: {
                singleSelect: true,
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'n_create_man_eq',
                editorParams: {
                  URL: '/users/fetch_default',
                  ISSHOWTAB: 'false',
                  USERMAP: '{"id":"id","name":"display_name"}',
                  AC: 'TRUE',
                  USERMETHOD: 'get',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'FALSE',
                },
                editorStyle: 'PERSONEL_SELECT_ALL',
                editorType: 'PICKEREX_TRIGGER',
                editorItems: [
                  {
                    id: 'n_create_man_eq',
                  },
                ],
                sysPFPluginId: 'person_select',
                valueType: 'SIMPLE',
                editable: true,
                id: 'create_man',
              },
              allowEmpty: true,
              caption: '表单项',
              codeName: 'create_man',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 3,
                colMD: 3,
                colSM: 8,
                colXS: 8,
                layout: 'TABLE_24COL',
              },
              id: 'create_man',
            },
            {
              dataType: 5,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'register_date',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_register_date_gtandeq',
              },
              valueFormat: 'YYYY-MM-DD',
              allowEmpty: true,
              hidden: true,
              caption: '工作日期（大于）',
              codeName: 'n_register_date_gtandeq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              id: 'n_register_date_gtandeq',
            },
            {
              dataType: 5,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'register_date',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_register_date_ltandeq',
              },
              valueFormat: 'YYYY-MM-DD',
              allowEmpty: true,
              hidden: true,
              caption: '工作日期（小于）',
              codeName: 'n_register_date_ltandeq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              id: 'n_register_date_ltandeq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'create_man',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_create_man_eq',
              },
              allowEmpty: true,
              hidden: true,
              caption: '建立人',
              codeName: 'n_create_man_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              id: 'n_create_man_eq',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.WORKLOAD.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'ee349d5f6bb5b56ce9de024cda919ef1',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.workload.default',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'exportexcel',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EXPORT',
          },
          caption: '导出',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-excel-o',
            glyph: 'xf1c3@FontAwesome',
          },
          tooltip: '导出',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EXPORT',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'calendar_management_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工时日历_工具栏',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '1caa28e37cd29023f9d644f5b0378f0f',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'calendar_management_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WORKLOAD',
      },
      caption: '工时',
      codeName: 'calendar_management_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.workload',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_management_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.workload',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工时日历表格视图（管理）',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'af3c29d5b4e6114e4cb8d0d6c8e9b410',
  modelType: 'PSAPPDEVIEW',
  name: 'workloadcalendar_management_view',
  id: 'plmweb.workload_calendar_management_view',
};
