export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'kanban',
  loadDefault: true,
  deviewCodeName: 'kanban_view',
  deviewId: 'f493bbf6e187fbacbd92ec4e8ea258d9',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '工作项看板',
  codeName: 'work_itemkanban_view',
  appDataEntityId: 'plmweb.work_item',
  appViewNavParams: [
    {
      key: 'n_board_id_eq',
      value: 'BOARD',
      id: 'n_board_id_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      enablePickupView: true,
                      singleSelect: true,
                      appDEACModeId: 'create_board',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'plmweb.board',
                      uiactionGroup: {
                        uiactionGroupDetails: [
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            caption: '新建看板',
                            detailType: 'DEUIACTION',
                            uiactionId: 'new@board',
                            showCaption: true,
                            showIcon: true,
                            sysImage: {
                              cssClass: 'fa fa-plus',
                              glyph: 'xf067@FontAwesome',
                            },
                            id: 'u243d7d9',
                          },
                        ],
                        appDataEntityId: 'plmweb.board',
                        uniqueTag: 'Board__Usr1225361038',
                        name: '自填模式_界面行为组',
                        id: 'usr1225361038',
                      },
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        MODE: 'CONTEXTCHANGE',
                        ENABLESEARCH: 'FALSE',
                        AC: 'TRUE',
                        SUFFIX: 'chevron-down-outline',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorStyle: 'ROUTE',
                      editorType: 'PICKER',
                      sysPFPluginId: 'route',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'route_picker',
                    },
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'route_picker',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchbar',
                  },
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  halignSelf: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  valignSelf: 'MIDDLE',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '看板',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'kanban',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_kanban',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'KanBanView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.work_itemeditview',
          },
          wizardAppView: {
            refAppViewId: 'plmweb.work_itemeditview',
          },
          enableWizardAdd: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.work_itemeditview',
            },
            {
              refAppViewId: 'plmweb.work_itemeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'plmweb.work_itemmain_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'INDEXVIEWTAB_POPUPMODAL',
              refAppViewId: 'plmweb.work_itemmain_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        openMode: 'INDEXVIEWTAB_POPUPMODAL',
        realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
        realTitle: '工作项',
        refAppViewId: 'plmweb.work_itemmain_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '工作项编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORK_ITEM.EDITVIEW',
        },
        refAppViewId: 'plmweb.work_itemeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'new_kanban_story_toolbar@work_item',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '用户故事',
                itemType: 'DEUIACTION',
                tooltip: '用户故事',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'new_kanban_task_toolbar@work_item',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '任务',
                itemType: 'DEUIACTION',
                tooltip: '任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'new_kanban_bug_toolbar@work_item',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '缺陷',
                itemType: 'DEUIACTION',
                tooltip: '缺陷',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction3',
              },
            ],
            valid: true,
            caption: '新建',
            itemType: 'ITEMS',
            tooltip: '新建',
            showCaption: true,
            showIcon: true,
            id: 'items1',
          },
        ],
        xdataControlName: 'kanban',
        codeName: 'kanban_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工作项看板视图_工具栏',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'f5d5df041cf3892c38015e52e1c2b72f',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'kanban_viewtoolbar',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                appDEFieldId: 'show_identifier',
                editor: {
                  editorType: 'TEXTBOX',
                  placeHolder: '编号',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_show_identifier_like',
                },
                allowEmpty: true,
                caption: '编号',
                codeName: 'n_show_identifier_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 3,
                  colMD: 3,
                  layout: 'TABLE_24COL',
                },
                id: 'n_show_identifier_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                appDEFieldId: 'title',
                editor: {
                  editorType: 'TEXTBOX',
                  placeHolder: '标题',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_title_like',
                },
                allowEmpty: true,
                emptyCaption: true,
                codeName: 'n_title_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 3,
                  colMD: 3,
                  layout: 'TABLE_24COL',
                },
                id: 'n_title_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                appDEFieldId: 'state',
                editor: {
                  editorType: 'HIDDEN',
                  placeHolder: '选择状态',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_state_eq',
                },
                allowEmpty: true,
                emptyCaption: true,
                hidden: true,
                codeName: 'n_state_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 3,
                  colMD: 3,
                  layout: 'TABLE_24COL',
                },
                id: 'n_state_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                appDEFieldId: 'project_name',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  appDEACModeId: 'default',
                  appDEDataSetId: 'fetchnormal',
                  appDataEntityId: 'plmweb.project',
                  uiactionGroup: {
                    uiactionGroupDetails: [
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        caption: '项目配置',
                        detailType: 'DEUIACTION',
                        uiactionId: 'open_global_setting@project',
                        showCaption: true,
                        showIcon: true,
                        id: 'u3fee786',
                      },
                    ],
                    appDataEntityId: 'plmweb.project',
                    uniqueTag: 'Project__Usr1221520658',
                    name: '自填模式行为组',
                    id: 'usr1221520658',
                  },
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  valueItemName: 'n_project_id_eq',
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  editorItems: [
                    {
                      id: 'n_project_id_eq',
                    },
                  ],
                  placeHolder: '选择项目',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_project_name_eq',
                },
                allowEmpty: true,
                caption: '所属项目',
                codeName: 'n_project_name_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 3,
                  colMD: 3,
                  layout: 'TABLE_24COL',
                },
                id: 'n_project_name_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_project_id_eq',
                },
                allowEmpty: true,
                hidden: true,
                codeName: 'n_project_id_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 3,
                  colMD: 3,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_project_id_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Kanban_view_SearchForm',
        controlType: 'SEARCHFORM',
        logicName: '工作项看板视图_搜索表单',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'searchform',
        },
        modelId: '61ba43bf73f82539179e0f3a969efce9',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'plmweb.work_item.kanban_view_searchform',
      },
      {
        updateGroupControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.work_item',
          id: 'updategroup',
        },
        groupLayout: 'ROW',
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'entry_id',
        groupCodeListId: 'plmweb.projmgmt__kanban_bar',
        groupUIActionGroup: {
          uiactionGroupDetails: [
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建史诗',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_epic@work_item',
              showCaption: true,
              showIcon: true,
              id: 'u74fa84e',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建特性',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_feature@work_item',
              showCaption: true,
              showIcon: true,
              id: 'u75d4bef',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建用户故事',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_story@work_item',
              showCaption: true,
              showIcon: true,
              id: 'u598a13c',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建任务',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_task@work_item',
              showCaption: true,
              showIcon: true,
              id: 'u28a9d6a',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建缺陷',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_bug@work_item',
              showCaption: true,
              showIcon: true,
              id: 'u3069f4a',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              caption: '新建事务',
              detailType: 'DEUIACTION',
              uiactionId: 'new_kanban_issue@work_item',
              showCaption: true,
              showIcon: true,
              id: 'uc9efa9c',
            },
          ],
          appDataEntityId: 'plmweb.work_item',
          uniqueTag: 'Work_item__Usr1219683065',
          name: '工作项看板_分组界面行为组',
          id: 'usr1219683065',
        },
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId:
                                  'plmweb.projmgmt__work_item_type',
                                editorParams: {
                                  codeListId: 'ProjMgmt__Work_item_type',
                                  contenttype: 'IMAGE',
                                  editable: 'FALSE',
                                },
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_IMAGE',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'work_item_type_id',
                              },
                              viewFieldName: 'work_item_type_id',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '图片(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              sysCss: {
                                cssName: 'kanban-kind-icon',
                              },
                              id: 'work_item_type_id',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'identifier',
                              },
                              viewFieldName: 'IDENTIFIER',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              sysCss: {
                                cssName: 'kanban-identifier',
                              },
                              id: 'identifier',
                            },
                            {
                              actionType: 'NONE',
                              buttonStyle: 'INFO',
                              buttonType: 'PANELBUTTON',
                              renderMode: 'BUTTON',
                              tooltip: '快捷操作',
                              uiactionTarget: 'NONE',
                              caption: '快捷操作',
                              itemStyle: 'INFO',
                              itemType: 'BUTTON',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              sysCss: {
                                cssName: 'kanban-more-button',
                              },
                              sysImage: {
                                cssClass: 'fa fa-ellipsis-v',
                                glyph: 'xf142@FontAwesome',
                              },
                              sysPFPluginId: 'kanban_operate',
                              userTag: 'OPERATE',
                              id: 'more_button',
                            },
                          ],
                          layout: {
                            dir: 'row',
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          contentHeight: 40,
                          height: 40,
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            colMD: 24,
                            height: 40,
                            heightMode: 'PX',
                            layout: 'TABLE_24COL',
                          },
                          id: 'container2',
                        },
                      ],
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '面板容器',
                      contentHeight: 40,
                      height: 40,
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        grow: 6,
                        shrink: 1,
                        height: 40,
                        heightMode: 'PX',
                        layout: 'SIMPLEFLEX',
                      },
                      id: 'container1',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '面板容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        grow: 3,
                        shrink: 1,
                        layout: 'SIMPLEFLEX',
                      },
                      id: 'container3',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorStyle: 'PERSONNEL_INFO',
                            editorType: 'SPAN',
                            sysPFPluginId: 'personnel_info',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'assignee_name',
                          },
                          viewFieldName: 'ASSIGNEE_NAME',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['assignee_name'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'ASSIGNEE_NAME',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                              id: '面板成员[assignee_name][面板显示]逻辑',
                            },
                          ],
                          sysCss: {
                            cssName: 'kanban-assignee',
                          },
                          id: 'assignee_name',
                        },
                      ],
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '面板容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        grow: 3,
                        shrink: 1,
                        layout: 'SIMPLEFLEX',
                      },
                      id: 'container4',
                    },
                  ],
                  predefinedType: 'CONTAINER_GRID',
                  layout: {
                    layout: 'SIMPLEFLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '栅格容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container_grid',
                },
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'title',
                  },
                  viewFieldName: 'TITLE',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  dynaClass:
                    "// 已完成、挂起、被拒绝\n{'kanban-finished': data.state === '40' || data.state === '50' || data.state === '60'}",
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  sysCss: {
                    cssName: 'kanban-title',
                  },
                  id: 'title',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'plmweb.projmgmt__work_item_state2',
                            editorType: 'SPAN',
                            placeHolder: '状态',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'state',
                          },
                          viewFieldName: 'STATE',
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['state'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'STATE',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                              id: '面板成员[state][面板显示]逻辑',
                            },
                          ],
                          sysCss: {
                            cssName: 'kanban-state',
                          },
                          id: 'state',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              rawItem: {
                                sysImage: {
                                  cssClass: 'fa fa-calendar',
                                  glyph: 'xf073@FontAwesome',
                                },
                                contentType: 'IMAGE',
                                predefinedType: 'STATIC_IMAGE',
                                id: 'static_image1',
                              },
                              caption: '图片',
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingRight: 'OUTERSMALL',
                              },
                              sysImage: {
                                cssClass: 'fa fa-calendar',
                                glyph: 'xf073@FontAwesome',
                              },
                              showCaption: true,
                              id: 'static_image1',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                placeHolder: '开始时间',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'start_at',
                              },
                              valueFormat: 'YYYY年MM月DD日',
                              viewFieldName: 'START_AT',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              controlRenders: [
                                {
                                  layoutPanelModel:
                                    'data.start_at.startsWith(new Date().getFullYear()) ? data.start_at.slice(5, -9) : data.start_at.slice(0, -9)\r\n\r\n',
                                  renderType: 'LAYOUTPANEL_MODEL',
                                  id: 'logic',
                                },
                              ],
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'start_at',
                            },
                          ],
                          layout: {
                            align: 'center',
                            dir: 'row',
                            layout: 'FLEX',
                            valign: 'center',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['start_at'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'START_AT',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                              id: '面板成员[container7][面板显示]逻辑',
                            },
                          ],
                          sysCss: {
                            cssName: 'kanban-time',
                          },
                          id: 'container7',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container6',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              rawItem: {
                                sysImage: {
                                  cssClass: 'fa fa-calendar-o',
                                  glyph: 'xf133@FontAwesome',
                                },
                                contentType: 'IMAGE',
                                predefinedType: 'STATIC_IMAGE',
                                id: 'static_image',
                              },
                              caption: '图片',
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingRight: 'OUTERSMALL',
                              },
                              sysImage: {
                                cssClass: 'fa fa-calendar-o',
                                glyph: 'xf133@FontAwesome',
                              },
                              showCaption: true,
                              id: 'static_image',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                placeHolder: '结束时间',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'end_at',
                              },
                              valueFormat: 'YYYY年MM月DD日',
                              viewFieldName: 'END_AT',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              controlRenders: [
                                {
                                  layoutPanelModel:
                                    'data.end_at.startsWith(new Date().getFullYear()) ? data.end_at.slice(5, -9) : data.end_at.slice(0, -9)',
                                  renderType: 'LAYOUTPANEL_MODEL',
                                  id: 'logic2',
                                },
                              ],
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'end_at',
                            },
                          ],
                          layout: {
                            align: 'center',
                            dir: 'row',
                            layout: 'FLEX',
                            valign: 'center',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          dynaClass:
                            "{'kanban-delay': data.state !== '40' && data.state !== '50' && data.state !== '60' && data.end_at && new Date(data.end_at).getTime() < new Date().getTime()}",
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['end_at'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'END_AT',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                              id: '面板成员[container5][面板显示]逻辑',
                            },
                          ],
                          sysCss: {
                            cssName: 'kanban-time',
                          },
                          id: 'container5',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container8',
                    },
                  ],
                  layout: {
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'Usr1218033220',
          controlType: 'PANEL',
          logicName: '工作项看板视图_看板_卡片面板',
          appDataEntityId: 'plmweb.work_item',
          controlParam: {},
          modelId: 'a60cedf772f605104e6dc0dd8406060a',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'plmweb.work_item.usr1218033220',
        },
        minorSortDir: 'ASC',
        minorSortAppDEFieldId: 'entry_position',
        dedataViewDataItems: [
          {
            appDEFieldId: 'title',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'identifier',
            dataType: 25,
            id: 'identifier',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'title',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'state',
            dataType: 25,
            id: 'state',
          },
          {
            appDEFieldId: 'assignee_id',
            dataType: 25,
            id: 'assignee_id',
          },
          {
            appDEFieldId: 'project_id',
            dataType: 25,
            id: 'project_id',
          },
          {
            frontCodeListId: 'plmweb.projmgmt__work_item_type',
            appDEFieldId: 'work_item_type_id',
            dataType: 25,
            id: 'srfdatatype',
          },
          {
            frontCodeListId: 'plmweb.projmgmt__work_item_type',
            appDEFieldId: 'work_item_type_id',
            dataType: 25,
            id: 'work_item_type_id',
          },
          {
            appDEFieldId: 'pid',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'sprint_id',
            dataType: 25,
            id: 'sprint_id',
          },
          {
            appDEFieldId: 'board_id',
            dataType: 25,
            id: 'board_id',
          },
          {
            appDEFieldId: 'entry_id',
            dataType: 25,
            id: 'entry_id',
          },
          {
            appDEFieldId: 'swimlane_id',
            dataType: 25,
            id: 'swimlane_id',
          },
          {
            appDEFieldId: 'top_id',
            dataType: 25,
            id: 'top_id',
          },
          {
            appDEFieldId: 'release_id',
            dataType: 25,
            id: 'release_id',
          },
          {
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        dedataViewItems: [
          {
            caption: '标题',
            dataItemName: 'title',
            itemType: 'DATAITEM',
            appDEFieldId: 'title',
            enableSort: true,
            name: 'TITLE',
            id: 'title',
          },
          {
            caption: '编号',
            dataItemName: 'identifier',
            itemType: 'DATAITEM',
            appDEFieldId: 'identifier',
            enableSort: true,
            name: 'IDENTIFIER',
            id: 'identifier',
          },
          {
            dataItemName: 'operate',
            itemType: 'ACTIONITEM',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '复制编号',
                  detailType: 'DEUIACTION',
                  uiactionId: 'copy_identifier@work_item',
                  tooltip: '复制编号',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-copy',
                    glyph: 'xf0c5@FontAwesome',
                  },
                  id: 'u87cef31',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '复制链接',
                  detailType: 'DEUIACTION',
                  uiactionId: 'copy_link@work_item',
                  tooltip: '复制链接',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-link',
                    glyph: 'xf0c1@FontAwesome',
                  },
                  id: 'ua4e6f75',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '复制',
                  detailType: 'DEUIACTION',
                  uiactionId: 'copy@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-copy',
                    glyph: 'xf0c5@FontAwesome',
                  },
                  id: 'u84865b0',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '移动',
                  detailType: 'DEUIACTION',
                  uiactionId: 'move@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-arrows',
                    glyph: 'xf047@FontAwesome',
                  },
                  id: 'u8aea425',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '归档',
                  detailType: 'DEUIACTION',
                  uiactionId: 'archive@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-archive',
                    glyph: 'xf187@FontAwesome',
                  },
                  id: 'u81c69d9',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '激活',
                  detailType: 'DEUIACTION',
                  uiactionId: 'activate@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'key',
                  },
                  id: 'u0fe1155',
                },
                {
                  actionLevel: 250,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '删除',
                  detailType: 'DEUIACTION',
                  uiactionId: 'delete@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  id: 'ua8f52f2',
                },
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '更改状态',
                  detailType: 'DEUIACTION',
                  uiactionId: 'change_work_item_state@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-navicon',
                    glyph: 'xf0c9@FontAwesome',
                  },
                  id: 'uc17deb0',
                },
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '分配负责人',
                  detailType: 'DEUIACTION',
                  uiactionId: 'change_work_item_assignee@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-user-plus',
                    glyph: 'xf234@FontAwesome',
                  },
                  id: 'ua2be636',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '变更父工作项',
                  detailType: 'DEUIACTION',
                  uiactionId: 'change_parent@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'git-branch',
                  },
                  id: 'u5bd58de',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '关联工作项',
                  detailType: 'DEUIACTION',
                  uiactionId: 'relation_work_item@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-link',
                    glyph: 'xf0c1@FontAwesome',
                  },
                  id: 'uc39824f',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '移入看板',
                  detailType: 'DEUIACTION',
                  uiactionId: 'shift_in_kanban@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trello',
                    glyph: 'xf181@FontAwesome',
                  },
                  id: 'u433180f',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '移入发布',
                  detailType: 'DEUIACTION',
                  uiactionId: 'shift_in_version@work_item',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-send-o',
                    glyph: 'xf1d9@FontAwesome',
                  },
                  id: 'u683f35b',
                },
              ],
              appDataEntityId: 'plmweb.work_item',
              uniqueTag: 'Work_item__Usr0226224309',
              name: '看板快捷操作',
              id: 'usr0226224309',
            },
            name: 'OPERATE',
            id: 'operate',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        enableCardEdit: true,
        enableCardEditGroup: true,
        enableCardEditOrder: true,
        enableGroup: true,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.work_item',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'plmweb.work_item',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.work_item',
          id: 'load',
        },
        dedataImportId: 'import_work_item_waterfall',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.work_item',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.work_item',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Kanban_view_KanBan',
        controlStyle: 'STEPS_KANBAN',
        controlType: 'KANBAN',
        logicName: '工作项看板视图_看板',
        appDataEntityId: 'plmweb.work_item',
        controlLogics: [
          {
            eventNames: 'onLoadSuccess',
            logicTag: 'kanban',
            logicType: 'APPDEUILOGIC',
            appDEUILogicId: 'calc_kanban_item_action_state',
            appDataEntityId: 'plmweb.work_item',
            triggerType: 'CTRLEVENT',
            id: 'logic4',
          },
          {
            eventNames: 'onSelectionChange',
            logicTag: 'kanban',
            logicType: 'APPDEUILOGIC',
            appDEUILogicId: 'calc_kanban_item_action_state',
            appDataEntityId: 'plmweb.work_item',
            triggerType: 'CTRLEVENT',
            id: 'logic2',
          },
        ],
        controlParam: {
          id: 'kanban',
        },
        sysPFPluginId: 'steps_kanban',
        modelId: 'e507d09a0e478fc687ba29b078adaaa7',
        modelType: 'PSDEKANBAN',
        name: 'kanban',
        id: 'plmweb.work_item.kanban_view_kanban',
      },
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.projmgmt__work_item_state',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'state',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'state',
            id: 'state',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.projmgmt__work_item_priority',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'priority',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'priority',
            id: 'priority',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'plmweb.projmgmt__severity',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'severity',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            itemType: 'FILTER',
            appDEFieldId: 'severity',
            id: 'severity',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'assignee_id',
              editorParams: {
                ISADDSYMBOL: 'true',
                MULTIPLE: 'true',
                'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                AC: 'TRUE',
                TRIGGER: 'TRUE',
                URL: 'projects/${context.project}/project_members/fetchdefault',
                PICKUPVIEW: 'FALSE',
                USERMETHOD: 'post',
                USERMAP: '{"id":"user_id","name":"name"}',
                DEPTMAP: '{"id":"id","name":"display_name"}',
                DEPTMETHOD: 'get',
                DEPTURL: '/users/fetchdefault',
              },
              editorStyle: 'PERSONEL_SELECT_PROJECT',
              editorType: 'PICKEREX_TRIGGER',
              sysPFPluginId: 'person_select',
              valueType: 'SIMPLE',
              editable: true,
              navigateParams: [
                {
                  key: 'n_department_id_eq',
                  value: 'srforgsectorid',
                  id: 'n_department_id_eq',
                },
              ],
              id: 'assignee_id',
            },
            allowEmpty: true,
            caption: '负责人',
            itemType: 'FILTER',
            appDEFieldId: 'assignee_id',
            id: 'assignee_id',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              editorParams: {
                ISADDSYMBOL: 'true',
                MULTIPLE: 'true',
                'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                AC: 'TRUE',
                TRIGGER: 'TRUE',
                URL: 'projects/${context.project}/project_members/fetchdefault',
                PICKUPVIEW: 'FALSE',
                USERMETHOD: 'post',
                USERMAP: '{"id":"user_id","name":"name"}',
                DEPTMAP: '{"id":"id","name":"display_name"}',
                DEPTMETHOD: 'get',
                DEPTURL: '/users/fetchdefault',
              },
              editorStyle: 'PERSONEL_SELECT_PROJECT',
              editorType: 'PICKEREX_TRIGGER',
              sysPFPluginId: 'person_select',
              valueType: 'SIMPLE',
              editable: true,
              navigateParams: [
                {
                  key: 'n_department_id_eq',
                  value: 'srforgsectorid',
                  id: 'n_department_id_eq',
                },
              ],
              id: 'create_man',
            },
            allowEmpty: true,
            caption: '创建人',
            itemType: 'FILTER',
            appDEFieldId: 'create_man',
            id: 'create_man',
          },
          {
            dataType: 21,
            labelPos: 'NONE',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'description',
            },
            allowEmpty: true,
            itemType: 'FILTER',
            appDEFieldId: 'description',
            id: 'description',
          },
        ],
        quickSearchMode: 1,
        searchBarStyle: 'SEARCHBAR2',
        enableFilter: true,
        enableQuickSearch: true,
        codeName: 'project_no_section',
        controlType: 'SEARCHBAR',
        logicName: '无分组-搜索栏',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '32a4e0ad260e65751e6e749981f83842',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'plmweb.work_item.project_no_section',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORK_ITEM',
        },
        caption: '工作项看板',
        codeName: 'kanban_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {},
        name: 'captionbar',
        id: 'kanban_viewcaptionbar',
      },
    ],
    codeName: 'Usr1225597504',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'kanban_view实体看板视图布局面板',
    appDataEntityId: 'plmweb.work_item',
    controlParam: {},
    modelId: '033a684a324719285424819217d44505',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1225597504',
  },
  title: '工作项看板',
  viewStyle: 'DEFAULT',
  viewType: 'DEKANBANVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '49716114df796787a0c066c708626859',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemkanban_view',
  id: 'plmweb.work_itemkanban_view',
};
