export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'test_follow_edit_view',
  deviewId: '95f5ce765946b773d7a4d65d84a9c1f8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '工作项',
  codeName: 'work_item_test_follow_edit_view',
  height: 90,
  appDataEntityId: 'plmweb.work_item',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              appDEACModeId: 'aichat',
                              appDEDataSetId: 'fetch_default',
                              appDataEntityId: 'plmweb.work_item',
                              enableAC: true,
                              editorParams: {
                                USERINSCRIPT:
                                  'value.replaceAll(/\\@\\{\\"(user)?id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\"\\}/g,(x, user, id, name) => {return controller.getNodeInfo({ id, name })}).replaceAll(/\\@\\{userid=(.+?),name=(.+?)\\}/g,(x, id, name) => {return controller.getNodeInfo({ id, name })})',
                                QUOTECODELISTMAP:
                                  '{"type":"plmweb.base__recent_visite"}',
                                QUOTEFIELDMAP:
                                  '{"identifier":"show_identifier","name":"name","id":"id","type":"owner_subtype"}',
                                QUOTEPARAMS:
                                  '{"page":0,"size":20,"sort":"update_time,desc"}',
                                AC: 'TRUE',
                                QUOTEINSCRIPT:
                                  'value.replaceAll(/\\#\\{\\"id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\",\\"identifier\\":\\"(.+?)\\",\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\"\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })}).replaceAll(/\\#\\{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })})',
                                USERSCRIPT:
                                  '`@{"id":"${data.id}","name":"${data.name}"}`',
                                QUOTESCRIPT:
                                  '`#{"id":"${data.id}","name":"${data.name}","identifier":"${data.identifier}","icon":"${data.icon}"}`',
                                REPLYSCRIPT:
                                  'value?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/#{"id":"(.+?)","name":"(.+?)","identifier":"(.+?)","icon":"((.|[\\t\\r\\f\\n\\s])+?)"}/g, "<span class=\\\'comment-tag\\\'>$4 $3 $2</span>").replace(/#{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)}/g, "<span class=\\\'comment-tag\\\'>$4 $3 $2</span>")',
                                USERFIELDMAP: '{"id":"user_id","name":"name"}',
                                USERURL:
                                  '`projects/${context.project}/project_members/fetch_default`',
                                QUOTEURL: '`recents/fetch_recent_access`',
                              },
                              editorStyle: 'COMMENT_PROJECT',
                              editorType: 'HTMLEDITOR',
                              sysPFPluginId: 'comment',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'field_textbox',
                            },
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              grow: 10,
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'field_textbox',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'INFO',
                            buttonType: 'PANELBUTTON',
                            uiactionId: 'clear_comment@comment',
                            renderMode: 'BUTTON',
                            tooltip: '取消',
                            uiactionTarget: 'NONE',
                            caption: '取消',
                            dynaClass: "['ibiz-panel-button--comment__cancel']",
                            itemStyle: 'INFO',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 0,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedItemNames: ['field_textbox'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'ISNOTNULL',
                                    dstModelField: 'FIELD_TEXTBOX',
                                    logicType: 'SINGLE',
                                    id: '逻辑项',
                                  },
                                ],
                                logicType: 'GROUP',
                                id: '面板成员[comment_cancel][面板显示]逻辑',
                              },
                            ],
                            showCaption: true,
                            id: 'comment_cancel',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'DEFAULT',
                            buttonType: 'PANELBUTTON',
                            uiactionId: 'send_comment@comment',
                            renderMode: 'BUTTON',
                            tooltip: '发送',
                            uiactionTarget: 'NONE',
                            caption: '发送',
                            dynaClass: "['ibiz-panel-button--comment__send']",
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 0,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedItemNames: ['field_textbox'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'ISNOTNULL',
                                    dstModelField: 'FIELD_TEXTBOX',
                                    logicType: 'SINGLE',
                                    id: '逻辑项',
                                  },
                                ],
                                logicType: 'GROUP',
                                id: '面板成员[comment_send][面板显示]逻辑',
                              },
                            ],
                            showCaption: true,
                            id: 'comment_send',
                          },
                          {
                            rawItem: {
                              sysImage: {
                                cssClass: 'fa fa-arrow-circle-o-right',
                                glyph: 'xf18e@FontAwesome',
                              },
                              contentType: 'IMAGE',
                              dynaClass: "['ibiz-panel-button--comment__icon']",
                              sysCss: {
                                cssName: 'comment_icon',
                              },
                              predefinedType: 'STATIC_IMAGE',
                              rawItemHeight: 48,
                              id: 'comment_icon',
                            },
                            caption: '图片',
                            contentHeight: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            sysCss: {
                              cssName: 'comment_icon',
                            },
                            sysImage: {
                              cssClass: 'fa fa-arrow-circle-o-right',
                              glyph: 'xf18e@FontAwesome',
                            },
                            showCaption: true,
                            id: 'comment_icon',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'flex-start',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                          widthMode: 'FULL',
                        },
                        id: 'container_comment',
                      },
                    ],
                    layout: {
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      heightMode: 'FULL',
                      layout: 'TABLE_24COL',
                      widthMode: 'FULL',
                    },
                    id: 'page_container',
                  },
                ],
                predefinedType: 'PANELPART',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '引用布局面板',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'panelpart',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 8,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      singleSelect: true,
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        DEFAULTATNVALUE: '40',
                        CODELISTID: 'Base__Attention_type',
                        'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        SELFFILLMAP: '{"user_id":"user_id","user_name":"name"}',
                        URL: 'projects/${context.project}/project_members/fetchdefault',
                        PICKUPVIEW: 'FALSE',
                        USERMETHOD: 'post',
                        USERMAP: '{"id":"user_id","name":"name"}',
                        DEPTMAP: '{"id":"id","name":"display_name"}',
                        DEPTMETHOD: 'get',
                        DEPTURL: '/users/fetchdefault',
                        CODELISTMAP:
                          '{"FOLLOWED":[20,30,40],"NOTFOLLOWING":[10]}',
                      },
                      editorStyle: 'ATTENTION_PRODUCT',
                      editorType: 'PICKEREX_TRIGGER',
                      sysPFPluginId: 'attention',
                      predefinedType: 'FIELD_PICKER',
                      valueType: 'SIMPLE',
                      editable: true,
                      navigateParams: [
                        {
                          key: 'n_department_id_eq',
                          value: 'srforgsectorid',
                          id: 'n_department_id_eq',
                        },
                      ],
                      id: 'attentions',
                    },
                    viewFieldName: 'ATTENTIONS',
                    allowEmpty: true,
                    caption: '数据选择',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                      valignSelf: 'MIDDLE',
                    },
                    id: 'attentions',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'DEACTION',
                appDEMethodId: 'get',
                appDataEntityId: 'plmweb.work_item',
                caption: '关注容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                  spacingLeft: 'INNERSMALL',
                  spacingRight: 'INNERSMALL',
                  valignSelf: 'MIDDLE',
                },
                id: 'container_attention',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 4,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container1',
          },
        ],
        predefinedType: 'CONTAINER_GRID',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '栅格容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_view_bottom',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'save',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '表单保存',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '表单保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'change_password',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '修改密码',
            itemType: 'DEUIACTION',
            tooltip: '修改密码',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'test_follow_edit_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '测试关注编辑视图_工具栏',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'dc719c56e92d7dccab95449473109fd0',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'test_follow_edit_view_toolbar',
      },
      {
        autoSaveMode: 1,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.work_item',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'plmweb.work_item',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'plmweb.work_item',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.work_item',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.work_item',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.work_item',
          id: 'update',
        },
        enableAutoSave: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 5,
                    enableCond: 3,
                    itemWidth: 230,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'end_at',
                    editor: {
                      dateTimeFormat: 'YYYY-MM-DD',
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                      },
                      editorType: 'DATEPICKEREX_NOTIME',
                      editorWidth: 100,
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'end_at',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '结束时间',
                    codeName: 'end_at',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'end_at',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 21,
                        enableCond: 3,
                        itemHeight: 620,
                        labelPos: 'TOP',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'description',
                        editor: {
                          editorHeight: 600,
                          editorParams: {
                            SAVEINTERVAL: '500',
                            USERINSCRIPT:
                              'value.replaceAll(/\\@\\{\\"(user)?id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\"\\}/g,(x, user, id, name) => {return controller.getNodeInfo({ id, name })}).replaceAll(/\\@\\{userid=(.+?),name=(.+?)\\}/g,(x, id, name) => {return controller.getNodeInfo({ id, name })})',
                            MAXHEIGHT: '600',
                            QUOTECODELISTMAP:
                              '{"type":"plmweb.base__recent_visite"}',
                            QUOTEFIELDMAP:
                              '{"identifier":"show_identifier","name":"name","id":"id","type":"owner_subtype"}',
                            QUOTEPARAMS:
                              '{"page":0,"size":20,"sort":"update_time,desc"}',
                            enableFullScreen: 'true',
                            MODE: 'default',
                            QUOTEINSCRIPT:
                              'value.replaceAll(/\\#\\{\\"id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\",\\"identifier\\":\\"(.+?)\\",\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\"\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })}).replaceAll(/\\#\\{id=(.+?),name=(.+?),identifier=(.+?),icon=((.|[\\t\\r\\f\\n\\s])+?)\\}/g,(x, id, name, identifier, icon) => {return controller.getNodeInfo({ id, name, identifier, icon })})',
                            USERSCRIPT:
                              '`@{"id":"${data.id}","name":"${data.name}"}`',
                            QUOTESCRIPT:
                              '`#{"id":"${data.id}","name":"${data.name}","identifier":"${data.identifier}","icon":"${data.icon}"}`',
                            EMITMODE: 'AUTOMATIC',
                            RENDERMODE: 'JSON',
                            USERURL:
                              "`${context.library ? `libraries/${context.library}/library_members/fetch_default` : context.product ? `products/${context.product}/product_members/fetch_default` : context.project ? `projects/${context.project}/project_members/fetch_default` : ''}`",
                            USERFIELDMAP: '{"id":"user_id","name":"name"}',
                            INSERTKEYS:
                              '[{"index":66,"keys":["marker"]},{"index":5,"keys":["paintformat"]}]',
                            QUOTEURL: '`recents/fetch_recent_access`',
                          },
                          editorStyle: 'COLLAPSE',
                          editorType: 'HTMLEDITOR',
                          sysPFPluginId: 'comment',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'description',
                        },
                        allowEmpty: true,
                        emptyCaption: true,
                        codeName: 'description',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'description',
                      },
                    ],
                    caption: '描述',
                    codeName: 'description_contain',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'description_contain',
                  },
                ],
                codeName: 'left_grouppanel',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 16,
                  colMD: 16,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'left_grouppanel',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'title',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'title',
                        },
                        caption: '标题',
                        codeName: 'title',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'title',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        itemWidth: 230,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'start_at',
                        editor: {
                          dateTimeFormat: 'YYYY-MM-DD',
                          editorParams: {
                            TIMEFMT: 'YYYY-MM-DD',
                          },
                          editorType: 'DATEPICKEREX_NOTIME',
                          editorWidth: 100,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'start_at',
                        },
                        valueFormat: 'YYYY-MM-DD',
                        allowEmpty: true,
                        caption: '开始时间',
                        codeName: 'start_at',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'start_at',
                      },
                    ],
                    codeName: 'grouppanel8',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel8',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'attentions',
                    editor: {
                      singleSelect: true,
                      handlerType: 'PickupText',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        MULTIPLE: 'true',
                        DEFAULTATNVALUE: '40',
                        'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                        AC: 'TRUE',
                        DEFAULTSELCURUSER: 'true',
                        TRIGGER: 'TRUE',
                        SELFFILLMAP: '{"user_id":"user_id","user_name":"name"}',
                        URL: 'projects/${context.project}/project_members/fetch_default',
                        PICKUPVIEW: 'FALSE',
                        USERMETHOD: 'post',
                        USERMAP: '{"id":"user_id","name":"name"}',
                        DEPTMAP: '{"id":"id","name":"display_name"}',
                        DEPTMETHOD: 'get',
                        DEPTURL: '/users/fetch_default',
                      },
                      editorStyle: 'PERSONEL_SELECT_PROJECT',
                      editorType: 'PICKEREX_TRIGGER',
                      objectIdField: 'id',
                      objectNameField: 'name',
                      sysPFPluginId: 'person_select',
                      valueType: 'OBJECTS',
                      editable: true,
                      navigateParams: [
                        {
                          key: 'n_department_id_eq',
                          value: 'srforgsectorid',
                          id: 'n_department_id_eq',
                        },
                      ],
                      id: 'attentions',
                    },
                    allowEmpty: true,
                    caption: '关注',
                    codeName: 'attentions',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'attentions',
                  },
                ],
                caption: '工作项基本信息',
                codeName: 'right_grouppanel',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'right_grouppanel',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'update_man',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'plmweb.sysoperator',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'update_man',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.UPDATE_MAN',
                    },
                    caption: '更新人',
                    codeName: 'update_man',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'update_man',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'update_time',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'update_time',
                    },
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.UPDATE_TIME',
                    },
                    caption: '更新时间',
                    codeName: 'update_time',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'update_time',
                  },
                ],
                caption: '操作信息',
                codeName: 'group2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group2',
              },
            ],
            caption: '其它',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'test_follow',
        controlType: 'FORM',
        logicName: '测试关注编辑视图_表单',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'form',
        },
        modelId: '18c6c4465ebe2376d198b43c623b4695',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'plmweb.work_item.test_follow',
      },
      {
        codeName: 'test_follow_edit_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'test_follow_edit_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORK_ITEM',
        },
        caption: '工作项',
        codeName: 'test_follow_edit_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {},
        name: 'captionbar',
        id: 'test_follow_edit_view_captionbar',
      },
    ],
    codeName: 'usr0221831396',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'test_follow_editView编辑视图布局面板',
    appDataEntityId: 'plmweb.work_item',
    controlLogics: [
      {
        eventNames: 'onChange',
        itemName: 'ATTENTIONS',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'attention_personnel_update',
        appDataEntityId: 'plmweb.work_item',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onBlur',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_hidden',
        appDataEntityId: 'plmweb.comment',
        triggerType: 'CTRLEVENT',
        name: 'onBlur',
        id: 'onblur',
      },
      {
        eventNames: 'onFocus',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_show',
        appDataEntityId: 'plmweb.comment',
        triggerType: 'CTRLEVENT',
        name: 'onFocus',
        id: 'onfocus',
      },
    ],
    controlParam: {},
    modelId: '41168fad07ca8c875034c4fa29c3646e',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0221831396',
  },
  title: '测试关注编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: '0d6b2108828945ba149b7fc890721029',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemtest_follow_edit_view',
  id: 'plmweb.work_item_test_follow_edit_view',
};
