export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'run_list_view',
  deviewId: '9735bed5fc218ae1fb0ac8504ce3166e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORKLOAD',
  },
  caption: '工时',
  codeName: 'workloadrun_list_view',
  appDataEntityId: 'plmweb.workload',
  appViewNavParams: [
    {
      key: 'n_principal_id_eq',
      value: 'test_case',
      id: 'n_principal_id_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        panelItems: [
          {
            caption: '列表',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'list',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'ListView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.workloadeditview',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.workloadeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'plmweb.workloadeditview',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.workloadeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '工时编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORKLOAD.EDITVIEW',
        },
        refAppViewId: 'plmweb.workloadeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '工时编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORKLOAD.EDITVIEW',
        },
        refAppViewId: 'plmweb.workloadeditview',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        groupMode: 'NONE',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              panelItems: [
                {
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'field_text_dynamic',
                      },
                      viewFieldName: 'DURATION',
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        halignSelf: 'LEFT',
                        layout: 'FLEX',
                      },
                      id: 'field_text_dynamic',
                    },
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId: 'plmweb.sysoperator',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'field_text_dynamic1',
                      },
                      viewFieldName: 'CREATE_MAN',
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        halignSelf: 'RIGHT',
                        layout: 'FLEX',
                      },
                      id: 'field_text_dynamic1',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container1',
                },
                {
                  panelItems: [
                    {
                      editor: {
                        contentType: 'HTML',
                        editorParams: {
                          contenttype: 'HTML',
                        },
                        editorType: 'RAW',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'field_text_dynamic3',
                      },
                      viewFieldName: 'DESCRIPTION',
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        halignSelf: 'LEFT',
                        layout: 'FLEX',
                      },
                      id: 'field_text_dynamic3',
                    },
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'field_text_dynamic2',
                      },
                      viewFieldName: 'CREATE_TIME',
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        halignSelf: 'RIGHT',
                        layout: 'FLEX',
                        valignSelf: 'MIDDLE',
                      },
                      id: 'field_text_dynamic2',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container2',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'Usr0102394540',
          controlType: 'PANEL',
          logicName: 'list_列表项面板',
          appDataEntityId: 'plmweb.workload',
          controlParam: {},
          modelId: '300538ecd6718fe86cd8720a43e61f61',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list_itempanel',
          id: 'plmweb.workload.usr0102394540',
        },
        delistDataItems: [
          {
            appDEFieldId: 'description',
            dataType: 21,
            id: 'description',
          },
          {
            appDEFieldId: 'duration',
            dataType: 6,
            id: 'duration',
          },
          {
            appDEFieldId: 'create_time',
            dataType: 5,
            format: 'YYYY-MM-DD HH:mm:ss',
            id: 'create_time',
          },
          {
            appDEFieldId: 'create_man',
            frontCodeListId: 'plmweb.sysoperator',
            dataType: 25,
            id: 'create_man',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'type_id',
            dataType: 25,
            id: 'type_id',
          },
        ],
        pagingSize: 1000,
        showHeader: true,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.workload',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'plmweb.workload',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.workload',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.workload',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.workload',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'List',
        controlType: 'LIST',
        logicName: 'list',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'list',
        },
        modelId: '0a892dc89a098bda719d94c2f97b9d31',
        modelType: 'PSDELIST',
        name: 'list',
        id: 'plmweb.workload.list',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'back_run_main_view@workload',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '返回',
            itemType: 'DEUIACTION',
            tooltip: '返回',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'list',
        codeName: 'run_list_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '返回',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'acc6441e52498ec442bae9cf97896d07',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'run_list_viewtoolbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.workload',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORKLOAD',
        },
        caption: '工时',
        codeName: 'run_list_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.workload',
        controlParam: {},
        name: 'captionbar',
        id: 'run_list_viewcaptionbar',
      },
    ],
    codeName: 'Usr0318042361',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'run_list_view列表视图布局面板',
    appDataEntityId: 'plmweb.workload',
    controlParam: {},
    modelId: '071d1df25a7dd856701051617915e6c6',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318042361',
  },
  title: '工时明细列表视图（执行用例）',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '50f045bbecc91eade88c9412d0e0dd59',
  modelType: 'PSAPPDEVIEW',
  name: 'workloadrun_list_view',
  id: 'plmweb.workloadrun_list_view',
};
