export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'global_setting_view',
  deviewId: '708a64a7ae868f296248bcb3827775ab',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '工作项配置',
  codeName: 'work_item_global_setting_view',
  appDataEntityId: 'plmweb.work_item',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '工作项属性',
          appViewId: 'plmweb.psde_field_grid_view',
          navigateContexts: [
            {
              key: 'PSDATAENTITY',
              value: 'ProjMgmt.WORK_ITEM',
              rawValue: true,
              name: 'PSDATAENTITY',
              id: 'psdataentity',
            },
            {
              key: 'PSDENAME',
              value: 'WORK_ITEM',
              rawValue: true,
              name: 'PSDENAME',
              id: 'psdename',
            },
          ],
          id: 'dritem1',
        },
        {
          caption: '工作项状态',
          appViewId: 'plmweb.work_item_state_grid_view',
          id: 'dritem2',
        },
        {
          caption: '工作项类型',
          appViewId: 'plmweb.work_item_type_global_grid_view',
          id: 'dritem3',
        },
      ],
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.WORK_ITEM',
      },
      editItemCaption: '工作项',
      uniqueTag: 'work_item_global_setting_view__tabexppanel',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'global_setting_view_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'efc625391d64c5e4d884c239af84c7c8',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'global_setting_view_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WORK_ITEM',
      },
      caption: '工作项配置',
      codeName: 'global_setting_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {},
      name: 'captionbar',
      id: 'global_setting_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.work_item',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作项配置',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4fd3b4a237b221c98f14006c885034df',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemglobal_setting_view',
  id: 'plmweb.work_item_global_setting_view',
};
