export default {
  gridRowActiveMode: 1,
  enableRowEdit: true,
  rowEditDefault: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'milestone_grid_view',
  deviewId: '716caeec4dc47995b0cf11a690960644',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '里程碑',
  codeName: 'work_item_milestone_grid_view',
  appDataEntityId: 'plmweb.work_item',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.work_item_quick_create_view',
        },
        wizardAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'plmweb.work_item_quick_create_view',
        },
        enableWizardAdd: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.work_item_quick_create_view',
          },
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'plmweb.work_item_quick_create_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          refAppViewId: 'plmweb.work_item_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'plmweb.work_item_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '新建工作项',
      refAppViewId: 'plmweb.work_item_quick_create_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      openMode: 'INDEXVIEWTAB_POPUPMODAL',
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '工作项',
      refAppViewId: 'plmweb.work_item_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'new_waterfall_milestone@work_item',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '新建里程碑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建里程碑',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'seperator1',
        },
        {
          actionLevel: 100,
          buttonStyle: 'STYLE2',
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_exportaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.EXPORT',
              },
              caption: '导出里程碑',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-excel-o',
                glyph: 'xf1c3@FontAwesome',
              },
              tooltip: '导出里程碑',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.EXPORT',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-list-ul',
            glyph: 'xf0ca@FontAwesome',
          },
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'milestone_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '新建里程碑（waterfall）',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'ff41787db61e466a4721e50349805744',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'milestone_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'title',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state_text',
          excelCaption: '状态',
          appCodeListId: 'plmweb.projmgmt__scrum_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'assignee_name',
          excelCaption: '负责人',
          linkAppViewId: 'plmweb.user_redirect_view',
          linkValueItem: 'assignee_id',
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '负责人',
          codeName: 'assignee_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'assignee_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'ptitle',
          excelCaption: '父工作项',
          appDEFieldId: 'ptitle',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '父工作项',
          codeName: 'ptitle',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'ptitle',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'end_at',
          excelCaption: '截止时间',
          appDEFieldId: 'end_at',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '截止时间',
          codeName: 'end_at',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'end_at',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'create_man',
          excelCaption: '建立人',
          appCodeListId: 'plmweb.sysoperator',
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeName: 'create_man',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '建立时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'create_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          scriptCode:
            'var identifier = data.identifier;\r\nvar is_overtime = data.is_overtime;\r\nif(is_overtime == \'1\'){\r\n    var svgIcon = `<span title="超时提醒" style="display: flex;align-items: center;"><?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1729499164696" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="4536" width="16" height="16" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M561.593458 104.448a227.555556 227.555556 0 1 1 319.715555 319.715556 416.995556 416.995556 0 1 1-319.715555-319.715556z m-38.343111 70.087111a341.333333 341.333333 0 1 0 287.971555 287.971556 227.555556 227.555556 0 0 1-287.857778-287.971556z m-11.719111 375.466667l-173.738667 46.648889a37.888 37.888 0 1 1-19.683556-73.272889l117.646223-31.402667V360.448a37.888 37.888 0 1 1 75.776 0v189.553778zM736.58368 67.584a37.888 37.888 0 0 0-37.888 37.888V257.137778a37.888 37.888 0 0 0 75.776 0V105.358222a37.888 37.888 0 0 0-37.888-37.888z m0 256.796444a37.888 37.888 0 1 0 0 75.889778 37.888 37.888 0 0 0 0-75.889778z" fill="#DE5A55" p-id="4537"></path></svg></span>`;\r\n    return  `<span style="display: flex; align-items: center;">` + identifier + `&nbsp;` + svgIcon + `</span>`;\r\n} else {\r\n    return identifier;\r\n}',
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state_text',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_name',
        },
        {
          appDEFieldId: 'ptitle',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'ptitle',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'end_at',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'end_at',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'create_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'work_item_type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'work_item_type_id',
        },
        {
          appDEFieldId: 'assignee_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_id',
        },
        {
          appDEFieldId: 'is_overtime',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'is_overtime',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'project_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'project_id',
        },
        {
          appDEFieldId: 'work_item_type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'pid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'pid',
        },
        {
          appDEFieldId: 'sprint_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'sprint_id',
        },
        {
          appDEFieldId: 'board_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'board_id',
        },
        {
          appDEFieldId: 'entry_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'entry_id',
        },
        {
          appDEFieldId: 'swimlane_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'swimlane_id',
        },
        {
          appDEFieldId: 'top_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'top_id',
        },
        {
          appDEFieldId: 'release_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'release_id',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmstag',
        },
      ],
      degridEditItemUpdates: [
        {
          codeName: 'UpdateStateCodeList',
          degeiupdateDetails: [
            {
              id: 'state',
            },
          ],
          scriptCode:
            "const msg = {\r\n    messageid: 'updatestate',\r\n    messagename: 'command',\r\n    type: 'COMMAND',\r\n    subtype: 'OBJECTUPDATED',\r\n    triggerKey: ctrl.triggerKey,\r\n    data: data || {},\r\n    params: {\r\n        state: data?.state,\r\n        srfcustomtag: data?.srfkey\r\n    }\r\n};\r\nibiz.mc.command.update.next(msg);",
          customCode: true,
          showBusyIndicator: true,
          name: '更新状态代码表',
          id: 'updatestatecodelist',
        },
      ],
      degridEditItems: [
        {
          caption: '状态',
          codeName: 'state',
          enableCond: 3,
          appDEFieldId: 'state',
          degridEditItemUpdateId: 'updatestatecodelist',
          editor: {
            singleSelect: true,
            appCodeListId: 'plmweb.projmgmt__scrum_state',
            editorParams: {
              'srfnavparam.state': '%state%',
              'srfnavparam.project_id': '%project_id%',
              'srfnavparam.work_item_type_id': '%work_item_type_id%',
              type: 'round',
              alwaysLoad: 'true',
            },
            editorType: 'DROPDOWNLIST',
            editorItems: [
              {
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'plmweb.work_item_state',
                navigateParams: [
                  {
                    key: 'state',
                    value: 'state',
                    id: 'state',
                  },
                  {
                    key: 'project_id',
                    value: 'project_id',
                    id: 'project_id',
                  },
                  {
                    key: 'work_item_type_id',
                    value: 'work_item_type_id',
                    id: 'work_item_type_id',
                  },
                ],
                id: 'state',
              },
            ],
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'state',
                value: 'state',
                id: 'state',
              },
              {
                key: 'project_id',
                value: 'project_id',
                id: 'project_id',
              },
              {
                key: 'work_item_type_id',
                value: 'work_item_type_id',
                id: 'work_item_type_id',
              },
            ],
            id: 'state',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'state',
        },
        {
          caption: '负责人',
          codeName: 'assignee_name',
          enableCond: 3,
          appDEFieldId: 'assignee_name',
          editor: {
            singleSelect: true,
            handlerType: 'PickupText',
            appDEACModeId: 'member_select',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'plmweb.project_member',
            uiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '跳转至成员设置',
                  detailType: 'DEUIACTION',
                  uiactionId: 'jump_to_member_set@project_member',
                  tooltip: '跳转至成员设置',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-user-md',
                    glyph: 'xf0f0@FontAwesome',
                  },
                  id: 'uc5eeb4c',
                },
              ],
              appDataEntityId: 'plmweb.project_member',
              uniqueTag: 'project_member__Usr0104465165',
              name: '跳转至成员配置',
              id: 'usr0104465165',
            },
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'assignee_id',
            editorParams: {
              'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
              AC: 'TRUE',
              'SRFNAVPARAM.n_status_eq': '1',
              TRIGGER: 'TRUE',
              URL: 'projects/${context.project}/project_members/fetch_default',
              PICKUPVIEW: 'FALSE',
              USERMETHOD: 'post',
              USERMAP: '{"id":"user_id","name":"name"}',
              DEPTMAP: '{"id":"id","name":"display_name"}',
              DEPTMETHOD: 'get',
              DEPTURL: '/users/fetch_default',
            },
            editorStyle: 'PERSONEL_SELECT_PROJECT',
            editorType: 'PICKEREX_TRIGGER',
            editorItems: [{}],
            sysPFPluginId: 'person_select',
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_department_id_eq',
                value: 'srforgsectorid',
                id: 'n_department_id_eq',
              },
              {
                key: 'n_status_eq',
                value: '1',
                rawValue: true,
                id: 'n_status_eq',
              },
            ],
            id: 'assignee_name',
          },
          allowEmpty: true,
          id: 'assignee_name',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'assignee_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'assignee_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      singleSelect: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.work_item',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_milestone',
        appDataEntityId: 'plmweb.work_item',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.work_item',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.work_item',
        id: 'load',
      },
      dedataImportId: 'import_work_item_waterfall',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.work_item',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.work_item',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'milestone_grid',
      controlType: 'GRID',
      logicName: '工作项表格（里程碑）',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'grid',
      },
      modelId: 'a7732fa4853ef4fd9f3427fb5cbe15d6',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.work_item.milestone_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'identifier',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入查询编号',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_identifier_like',
              },
              allowEmpty: true,
              caption: '编号',
              codeName: 'n_identifier_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_identifier_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'title',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '标题',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_title_like',
              },
              allowEmpty: true,
              caption: '标题',
              codeName: 'n_title_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_title_like',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'ca044c4879a63d30121ff19610f25e6a',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.work_item.default',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WORK_ITEM',
      },
      caption: '里程碑',
      codeName: 'milestone_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {},
      name: 'captionbar',
      id: 'milestone_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.work_item',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作项表格视图（里程碑）',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'af2a6eb937c085677ff2bdf271b24902',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemmilestone_grid_view',
  id: 'plmweb.work_item_milestone_grid_view',
};
