export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'gantt_view',
  deviewId: '4124a4bed01e987edc78bef3c6db8224',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '工作项甘特图',
  codeName: 'work_itemgantt_view',
  appDataEntityId: 'plmweb.work_item',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '编号',
          codeName: 'sn',
          columnType: 'DEFGRIDCOLUMN',
          width: 150,
          widthUnit: 'PX',
          id: 'sn',
        },
        {
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          renderSysPFPluginId: 'column_action_edit',
          width: 200,
          widthUnit: 'px',
          id: 'name',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 180,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 180,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'top_node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 顶层节点',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'pid',
          parentDER1N: {
            masterRS: 48,
            pickupDEFName: 'PID',
            recursiveRS: true,
            codeName: 'Work_item',
            dertype: 'DER1N',
            logicName: '父工作项',
            minorCodeName: 'work_items',
            minorServiceCodeName: 'work_items',
            orderValue: 100,
            serviceCodeName: 'Work_item',
            name: 'DER1N_WORK_ITEM_WORK_ITEM_PID',
            id: 'projmgmt.work_item.der1n_work_item_work_item_pid',
          },
          parentDETreeNodeId: 'top_node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '顶层节点 - 节点',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'pid',
          parentDER1N: {
            masterRS: 48,
            pickupDEFName: 'PID',
            recursiveRS: true,
            codeName: 'Work_item',
            dertype: 'DER1N',
            logicName: '父工作项',
            minorCodeName: 'work_items',
            minorServiceCodeName: 'work_items',
            orderValue: 100,
            serviceCodeName: 'Work_item',
            name: 'DER1N_WORK_ITEM_WORK_ITEM_PID',
            id: 'projmgmt.work_item.der1n_work_item_work_item_pid',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '节点 - 节点',
        },
      ],
      detreeNodes: [
        {
          nodeValue: 'root',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetchdefault',
          textAppDEFieldId: 'title',
          nodeType: 'node',
          appDataEntityId: 'plmweb.work_item',
          decontextMenu: {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'new_waterfall_plan@work_item',
                uiactionTarget: 'SINGLEDATA',
                valid: true,
                caption: '新建计划',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'add',
                },
                tooltip: '新建计划',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove_waterfall_plan@work_item',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                caption: '删除计划',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                tooltip: '删除计划',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            codeName: 'gantt_viewnode_cm',
            controlType: 'CONTEXTMENU',
            logicName: '甘特图节点上下文菜单',
            appDataEntityId: 'plmweb.work_item',
            controlParam: {
              id: 'node_cm',
            },
            modelId: '0a34a6f6b626c24922b75f3d9f736eb8',
            modelType: 'PSDETOOLBAR',
            name: 'node_cm',
            id: 'gantt_viewnode_cm',
          },
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_at',
              appDEFieldId: 'end_at',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'end_at',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_at',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'identifier',
              appDEFieldId: 'identifier',
              valueType: 'SIMPLE',
              codeName: 'identifier',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'identifier',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_at',
              appDEFieldId: 'start_at',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'start_at',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_at',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'title',
              appDEFieldId: 'title',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'title',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'title',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_at',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'end_at',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'identifier',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'identifier',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_at',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'start_at',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'title',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'title',
            },
          ],
          detreeNodeEditItems: [
            {
              enableCond: 3,
              appDEFieldId: 'end_at',
              editor: {
                dateTimeFormat: 'YYYY-MM-DD',
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATEPICKEREX_NOTIME',
                valueType: 'SIMPLE',
                editable: true,
                id: 'end_at',
              },
              allowEmpty: true,
              id: 'end_at',
            },
            {
              enableCond: 3,
              appDEFieldId: 'start_at',
              editor: {
                dateTimeFormat: 'YYYY-MM-DD',
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATEPICKEREX_NOTIME',
                valueType: 'SIMPLE',
                editable: true,
                id: 'start_at',
              },
              allowEmpty: true,
              id: 'start_at',
            },
            {
              enableCond: 3,
              appDEFieldId: 'title',
              editor: {
                maxLength: 500,
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'title',
              },
              id: 'title',
            },
          ],
          detreeNodeRVs: [
            {
              refAppViewId: 'plmweb.work_itemmain_view',
              id: 'editdata',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          enableEditData: true,
          enableNewData: true,
          enableRemoveData: true,
          enableViewData: true,
          name: '节点',
          id: 'node',
        },
        {
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetchtop',
          textAppDEFieldId: 'title',
          nodeType: 'top_node',
          appDataEntityId: 'plmweb.work_item',
          decontextMenu: {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'new_waterfall_plan@work_item',
                uiactionTarget: 'SINGLEDATA',
                valid: true,
                caption: '新建计划',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'add',
                },
                tooltip: '新建计划',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove_waterfall_plan@work_item',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                caption: '删除计划',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                tooltip: '删除计划',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            codeName: 'gantt_viewtop_node_cm',
            controlType: 'CONTEXTMENU',
            logicName: '甘特图节点上下文菜单',
            appDataEntityId: 'plmweb.work_item',
            controlParam: {
              id: 'top_node_cm',
            },
            modelId: '0a34a6f6b626c24922b75f3d9f736eb8',
            modelType: 'PSDETOOLBAR',
            name: 'top_node_cm',
            id: 'gantt_viewtop_node_cm',
          },
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_at',
              appDEFieldId: 'end_at',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'end_at',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_at',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'identifier',
              appDEFieldId: 'identifier',
              valueType: 'SIMPLE',
              codeName: 'identifier',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'identifier',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_at',
              appDEFieldId: 'start_at',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'start_at',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_at',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'title',
              appDEFieldId: 'title',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'title',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'title',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_at',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'end_at',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'identifier',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'identifier',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_at',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'start_at',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'title',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'title',
            },
          ],
          detreeNodeEditItems: [
            {
              enableCond: 3,
              appDEFieldId: 'end_at',
              editor: {
                dateTimeFormat: 'YYYY-MM-DD',
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATEPICKEREX_NOTIME',
                valueType: 'SIMPLE',
                editable: true,
                id: 'end_at',
              },
              allowEmpty: true,
              id: 'end_at',
            },
            {
              enableCond: 3,
              appDEFieldId: 'start_at',
              editor: {
                dateTimeFormat: 'YYYY-MM-DD',
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                },
                editorType: 'DATEPICKEREX_NOTIME',
                valueType: 'SIMPLE',
                editable: true,
                id: 'start_at',
              },
              allowEmpty: true,
              id: 'start_at',
            },
            {
              enableCond: 3,
              appDEFieldId: 'title',
              editor: {
                maxLength: 500,
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'title',
              },
              id: 'title',
            },
          ],
          detreeNodeRVs: [
            {
              refAppViewId: 'plmweb.work_itemmain_view',
              id: 'editdata',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          enableEditData: true,
          enableNewData: true,
          enableRemoveData: true,
          enableViewData: true,
          name: '顶层节点',
          id: 'top_node',
        },
      ],
      treeGridMode: 2,
      enableEdit: true,
      outputIconDefault: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewLogics: [
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            actionAfterWizard: 'DEFAULT',
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_NEWDATA',
            id: '新建数据',
          },
          builtinLogic: true,
          id: 'node_newdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'INDEXVIEWTAB_POPUPMODAL',
              refAppViewId: 'plmweb.work_itemmain_view',
            },
            editMode: true,
            appUILogicRefViews: [
              {
                openMode: 'INDEXVIEWTAB_POPUPMODAL',
                refAppViewId: 'plmweb.work_itemmain_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '打开数据',
          },
          builtinLogic: true,
          id: 'node_opendata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            actionAfterWizard: 'DEFAULT',
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_NEWDATA',
            id: '新建数据',
          },
          builtinLogic: true,
          id: 'top_node_newdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'INDEXVIEWTAB_POPUPMODAL',
              refAppViewId: 'plmweb.work_itemmain_view',
            },
            editMode: true,
            appUILogicRefViews: [
              {
                openMode: 'INDEXVIEWTAB_POPUPMODAL',
                refAppViewId: 'plmweb.work_itemmain_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '打开数据',
          },
          builtinLogic: true,
          id: 'top_node_opendata',
        },
      ],
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'new_waterfall_plan@work_item',
              uiactionTarget: 'SINGLEDATA',
              valid: true,
              caption: '新建计划',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'add',
              },
              tooltip: '新建计划',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'remove_waterfall_plan@work_item',
              uiactionTarget: 'SINGLEKEY',
              valid: true,
              caption: '删除计划',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-trash-o',
                glyph: 'xf014@FontAwesome',
              },
              tooltip: '删除计划',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          codeName: 'gantt_viewnode_cm',
          controlType: 'CONTEXTMENU',
          logicName: '甘特图节点上下文菜单',
          appDataEntityId: 'plmweb.work_item',
          controlParam: {
            id: 'node_cm',
          },
          modelId: '0a34a6f6b626c24922b75f3d9f736eb8',
          modelType: 'PSDETOOLBAR',
          name: 'node_cm',
          id: 'gantt_viewnode_cm',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'new_waterfall_plan@work_item',
              uiactionTarget: 'SINGLEDATA',
              valid: true,
              caption: '新建计划',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'add',
              },
              tooltip: '新建计划',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'remove_waterfall_plan@work_item',
              uiactionTarget: 'SINGLEKEY',
              valid: true,
              caption: '删除计划',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-trash-o',
                glyph: 'xf014@FontAwesome',
              },
              tooltip: '删除计划',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          codeName: 'gantt_viewtop_node_cm',
          controlType: 'CONTEXTMENU',
          logicName: '甘特图节点上下文菜单',
          appDataEntityId: 'plmweb.work_item',
          controlParam: {
            id: 'top_node_cm',
          },
          modelId: '0a34a6f6b626c24922b75f3d9f736eb8',
          modelType: 'PSDETOOLBAR',
          name: 'top_node_cm',
          id: 'gantt_viewtop_node_cm',
        },
      ],
      codeName: 'Gantt_view_Gantt',
      controlType: 'GANTT',
      logicName: '工作项甘特视图_甘特部件',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'gantt',
      },
      modelId: '0ad5cc4f3355516ed48881487ad47ba5',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'plmweb.work_item.gantt_view_gantt',
    },
    {
      detoolbarItems: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'new_waterfall_stage@work_item',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '新建阶段',
              itemType: 'DEUIACTION',
              tooltip: '新建阶段',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'new_waterfall_milestone@work_item',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '新建里程碑',
              itemType: 'DEUIACTION',
              tooltip: '新建里程碑',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          caption: '新建计划',
          itemType: 'ITEMS',
          tooltip: '新建计划',
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'gantt',
      codeName: 'gantt_viewtoolbar',
      controlType: 'TOOLBAR',
      logicName: '工作项甘特视图_工具栏',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '126abf06c8d259bd01449ac73866c6dd',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'gantt_viewtoolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WORK_ITEM',
      },
      caption: '工作项甘特图',
      codeName: 'gantt_viewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.work_item',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_viewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'Layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.work_item',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作项甘特图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e5a049249fac2c0a2c8270b254df668e',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemgantt_view',
  id: 'plmweb.work_itemgantt_view',
};
