export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'ticket_re_work_item_gridview',
  deviewId: '4da9f94a4ee59fdc19afeb053b829c1b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM',
  },
  caption: '工作项',
  codeName: 'work_itemticket_re_work_item_gridview',
  appDataEntityId: 'plmweb.work_item',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        panelItems: [
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'total',
                    },
                    viewFieldName: 'total',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'INNERMEDIUM',
                    },
                    id: 'total',
                  },
                  {
                    rawItem: {
                      caption: '个工作项',
                      halign: 'LEFT',
                      renderMode: 'TEXT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_TEXT',
                      id: 'static_text',
                    },
                    caption: '文本',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_text',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            panelItems: [
              {
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        editor: {
          enablePickupView: true,
          singleSelect: true,
          pickupAppViewId: 'plmweb.work_itemothers_re_view',
          appDEACModeId: 'create_work_item',
          appDEDataSetId: 'fetchrecent_work_item',
          appDataEntityId: 'plmweb.recent',
          uiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                caption: '新建',
                detailType: 'DEUIACTION',
                uiactionId: 'create_new_work_item@recent',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-plus',
                  glyph: 'xf067@FontAwesome',
                },
                id: 'u5d97054',
              },
            ],
            uniqueTag: 'Recent__Usr0121381902',
            name: '关联新建（工作项）',
            id: 'usr0121381902',
          },
          enableAC: true,
          forceSelection: true,
          showTrigger: true,
          editorParams: {
            'srfnavparam.principal_id': '%principal_id%',
            'srfnavparam.size': '20',
            lastlabel: '更多工作项',
            AC: 'TRUE',
            toplabel: '最近浏览',
            PICKUPVIEW: 'TRUE',
          },
          editorStyle: 'MANAGE',
          editorType: 'PICKER',
          sysPFPluginId: 'manage',
          placeHolder: '添加关联工作项，点击确定按钮保存',
          predefinedType: 'FIELD_TEXT_DYNAMIC',
          valueType: 'SIMPLE',
          editable: true,
          navigateParams: [
            {
              key: 'principal_id',
              value: 'principal_id',
              id: 'principal_id',
            },
            {
              key: 'size',
              value: '20',
              rawValue: true,
              id: 'size',
            },
          ],
          id: 'choose_data',
        },
        allowEmpty: true,
        caption: '文本(动态)',
        itemStyle: 'DEFAULT',
        itemType: 'FIELD',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
          spacingBottom: 'INNERMEDIUM',
          spacingLeft: 'INNERMEDIUM',
          spacingRight: 'INNERMEDIUM',
          spacingTop: 'INNERMEDIUM',
        },
        id: 'choose_data',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.layoutPanel.panelItems.choose_data.state.visible = view.context.srfshowchoose || false;\n\n// 初始化默认隐藏表格\nview.layoutPanel.panelItems.grid.state.keepAlive = true;\nview.layoutPanel.panelItems.grid.state.visible = false;\nconst form = view.getController('form');\nconsole.log('项显示逻辑执行了');\nif (form) {\n    form.evt.on('onFormDetailEvent', event =>{\n        const panelItems = view.layoutPanel.panelItems;\n        if (!panelItems.comment) {\n            return;\n        }\n        if (event.formDetailName === 'tabpage1') {\n            panelItems.comment.state.visible = true;\n        } else {\n            panelItems.comment.state.visible = false;\n        }\n    });\n}\n\n// 初始化隐藏发送和清空按钮\nview.layoutPanel.panelItems.button_calluilogic1.state.visible = false\nview.layoutPanel.panelItems.button_calluilogic.state.visible = false",
        builtinLogic: true,
        id: 'viewmounted',
      },
      {
        eventNames: 'onLoadSuccess',
        logicTrigger: 'VIEWEVENT',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'get_idea_total',
        appDataEntityId: 'plmweb.idea',
        builtinLogic: true,
        id: 'onloadsuccess',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.work_itemeditview',
          },
          wizardAppView: {
            refAppViewId: 'plmweb.work_itemeditview',
          },
          enableWizardAdd: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.work_itemeditview',
            },
            {
              refAppViewId: 'plmweb.work_itemeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            navigateContexts: [
              {
                key: 'PROJECT',
                value: 'project_id',
                name: 'PROJECT',
                id: 'project',
              },
            ],
            refAppViewId: 'plmweb.work_itemmain_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              navigateContexts: [
                {
                  key: 'PROJECT',
                  value: 'project_id',
                  name: 'PROJECT',
                  id: 'project',
                },
              ],
              refAppViewId: 'plmweb.work_itemmain_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '工作项编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.WORK_ITEM.EDITVIEW',
        },
        refAppViewId: 'plmweb.work_itemeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        openMode: 'POPUPMODAL',
        navigateContexts: [
          {
            key: 'PROJECT',
            value: 'project_id',
            name: 'PROJECT',
            id: 'project',
          },
        ],
        realOpenMode: 'POPUPMODAL',
        realTitle: '工作项',
        refAppViewId: 'plmweb.work_itemmain_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'show_identifier',
            excelCaption: '编号',
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编号',
            codeName: 'identifier',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'identifier',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'title',
            excelCaption: '标题',
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '标题',
            codeName: 'title',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'title',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'state',
            excelCaption: '状态',
            appCodeListId: 'plmweb.projmgmt__work_item_state',
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'state',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'state',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'assignee_name',
            excelCaption: '负责人',
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '负责人',
            codeName: 'assignee_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'assignee_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'priority',
            excelCaption: '优先级',
            appCodeListId: 'plmweb.projmgmt__work_item_priority',
            appDEFieldId: 'priority',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  caption: '取消关联',
                  detailType: 'DEUIACTION',
                  uiactionId: 'del_relation@work_item',
                  tooltip: '取消关联',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-unlink',
                    glyph: 'xf127@FontAwesome',
                  },
                  id: 'u8fe5207',
                },
              ],
              uniqueTag: 'Work_item__Usr1227606619',
              name: '取消关联',
              id: 'usr1227606619',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '优先级',
            codeName: 'priority',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'priority',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'show_identifier',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'show_identifier',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'state',
          },
          {
            appDEFieldId: 'assignee_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_name',
          },
          {
            appDEFieldId: 'priority',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'priority',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'assignee_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'assignee_id',
          },
          {
            appDEFieldId: 'project_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'project_id',
          },
          {
            appDEFieldId: 'work_item_type_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdatatype',
          },
          {
            appDEFieldId: 'work_item_type_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'work_item_type_id',
          },
          {
            appDEFieldId: 'pid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'sprint_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'sprint_id',
          },
          {
            appDEFieldId: 'board_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'board_id',
          },
          {
            appDEFieldId: 'entry_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'entry_id',
          },
          {
            appDEFieldId: 'swimlane_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'swimlane_id',
          },
          {
            appDEFieldId: 'top_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'top_id',
          },
          {
            appDEFieldId: 'release_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'release_id',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        singleSelect: true,
        fetchControlAction: {
          appDEMethodId: 'fetchticket_relation_work_item',
          appDataEntityId: 'plmweb.work_item',
          id: 'fetch',
        },
        dedataImportId: 'import_work_item_waterfall',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.work_item',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Ticket_relation_work_item_grid',
        controlType: 'GRID',
        logicName: '工单关联工作项_表格',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'grid',
        },
        modelId: '1c31cc34d19bc12822ef9f9e79aaa908',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'plmweb.work_item.ticket_relation_work_item_grid',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'show_add_input@work_item',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '添加工作项',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '添加工作项',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'ticket_re_work_item_gridviewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '添加工作项',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '2233095e39cad0e4845ac97b5c28567b',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'ticket_re_work_item_gridviewtoolbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORK_ITEM',
        },
        caption: '工作项',
        codeName: 'ticket_re_work_item_gridviewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.work_item',
        controlParam: {},
        name: 'captionbar',
        id: 'ticket_re_work_item_gridviewcaptionbar',
      },
    ],
    codeName: 'Usr0112765952',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'ticket_re_work_item_gridview表格视图布局',
    appDataEntityId: 'plmweb.work_item',
    controlLogics: [
      {
        eventNames: 'onChange',
        itemName: 'CHOOSE_DATA',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'ticket_relation_work_item',
        appDataEntityId: 'plmweb.work_item',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: '20e23dd0a5f50b8156134e1073e04638',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0112765952',
  },
  title: '工单关联工作项表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '86474cd901ec38e7c72d21511c60c419',
  modelType: 'PSAPPDEVIEW',
  name: 'work_itemticket_re_work_item_gridview',
  id: 'plmweb.work_itemticket_re_work_item_gridview',
};
