export default {
  codeListTag: 'extension__enable_action',
  codeListType: 'STATIC',
  codeName: 'extension__enable_action',
  emptyText: '未定义',
  appDataEntityId: 'plmweb.psdelogic',
  codeItems: [
    {
      codeName: 'product',
      codeItems: [
        {
          codeName: 'prodmgmt_product_create_after',
          text: '创建产品',
          value: 'ProdMgmt.product.create:AFTER',
          id: 'prodmgmt_product_create_after',
        },
        {
          codeName: 'prodmgmt_product_archive_after',
          text: '归档产品',
          value: 'ProdMgmt.product.archive:AFTER',
          id: 'prodmgmt_product_archive_after',
        },
        {
          codeName: 'prodmgmt_product_delete_after',
          text: '删除产品',
          value: 'ProdMgmt.product.delete:AFTER',
          id: 'prodmgmt_product_delete_after',
        },
        {
          codeName: 'prodmgmt_idea_create_after',
          text: '创建产品需求',
          value: 'ProdMgmt.idea.create:AFTER',
          id: 'prodmgmt_idea_create_after',
        },
        {
          codeName: 'prodmgmt_idea_archive_after',
          text: '归档产品需求',
          value: 'ProdMgmt.idea.archive:AFTER',
          id: 'prodmgmt_idea_archive_after',
        },
        {
          codeName: 'prodmgmt_idea_delete_after',
          text: '删除产品需求',
          value: 'ProdMgmt.idea.delete:AFTER',
          id: 'prodmgmt_idea_delete_after',
        },
        {
          codeName: 'prodmgmt_ticket_create_after',
          text: '创建工单',
          value: 'ProdMgmt.ticket.create:AFTER',
          id: 'prodmgmt_ticket_create_after',
        },
        {
          codeName: 'prodmgmt_ticket_archive_after',
          text: '归档工单',
          value: 'ProdMgmt.ticket.archive:AFTER',
          id: 'prodmgmt_ticket_archive_after',
        },
        {
          codeName: 'prodmgmt_ticket_delete_after',
          text: '删除工单',
          value: 'ProdMgmt.ticket.delete:AFTER',
          id: 'prodmgmt_ticket_delete_after',
        },
      ],
      text: '产品',
      value: 'product',
      disableSelect: true,
      id: 'product',
    },
    {
      codeName: 'project',
      codeItems: [
        {
          codeName: 'projmgmt_project_create_after',
          text: '创建项目',
          value: 'ProjMgmt.project.create:AFTER',
          id: 'projmgmt_project_create_after',
        },
        {
          codeName: 'projmgmt_project_archive_after',
          text: '归档项目',
          value: 'ProjMgmt.project.archive:AFTER',
          id: 'projmgmt_project_archive_after',
        },
        {
          codeName: 'projmgmt_project_delete_after',
          text: '删除项目',
          value: 'ProjMgmt.project.delete:AFTER',
          id: 'projmgmt_project_delete_after',
        },
        {
          codeName: 'projmgmt_work_item_create_after',
          text: '创建工作项',
          value: 'ProjMgmt.work_item.create:AFTER',
          id: 'projmgmt_work_item_create_after',
        },
        {
          codeName: 'projmgmt_work_item_archive_after',
          text: '归档工作项',
          value: 'ProjMgmt.work_item.archive:AFTER',
          id: 'projmgmt_work_item_archive_after',
        },
        {
          codeName: 'projmgmt_work_item_delete_after',
          text: '删除工作项',
          value: 'ProjMgmt.work_item.delete:AFTER',
          id: 'projmgmt_work_item_delete_after',
        },
        {
          codeName: 'projmgmt_sprint_create_after',
          text: '创建迭代',
          value: 'ProjMgmt.sprint.create:AFTER',
          id: 'projmgmt_sprint_create_after',
        },
        {
          codeName: 'projmgmt_sprint_delete_after',
          text: '删除迭代',
          value: 'ProjMgmt.sprint.delete:AFTER',
          id: 'projmgmt_sprint_delete_after',
        },
        {
          codeName: 'projmgmt_release_create_after',
          text: '创建发布',
          value: 'ProjMgmt.release.create:AFTER',
          id: 'projmgmt_release_create_after',
        },
        {
          codeName: 'projmgmt_release_remove_after',
          text: '删除发布',
          value: 'ProjMgmt.release.remove:AFTER',
          id: 'projmgmt_release_remove_after',
        },
      ],
      text: '项目',
      value: 'project',
      disableSelect: true,
      id: 'project',
    },
    {
      codeName: 'library',
      codeItems: [
        {
          codeName: 'testmgmt_library_create_after',
          text: '创建测试库',
          value: 'TestMgmt.library.create:AFTER',
          id: 'testmgmt_library_create_after',
        },
        {
          codeName: 'testmgmt_library_archive_after',
          text: '归档测试库',
          value: 'TestMgmt.library.archive:AFTER',
          id: 'testmgmt_library_archive_after',
        },
        {
          codeName: 'testmgmt_library_delete_after',
          text: '删除测试库',
          value: 'TestMgmt.library.delete:AFTER',
          id: 'testmgmt_library_delete_after',
        },
        {
          codeName: 'testmgmt_test_case_create_after',
          text: '创建用例',
          value: 'TestMgmt.test_case.create:AFTER',
          id: 'testmgmt_test_case_create_after',
        },
        {
          codeName: 'testmgmt_test_case_delete_after',
          text: '删除用例',
          value: 'TestMgmt.test_case.delete:AFTER',
          id: 'testmgmt_test_case_delete_after',
        },
        {
          codeName: 'testmgmt_test_plan_create_after',
          text: '创建测试计划',
          value: 'TestMgmt.test_plan.create:AFTER',
          id: 'testmgmt_test_plan_create_after',
        },
        {
          codeName: 'testmgmt_test_plan_remove_after',
          text: '删除测试计划',
          value: 'TestMgmt.test_plan.remove:AFTER',
          id: 'testmgmt_test_plan_remove_after',
        },
        {
          codeName: 'testmgmt_review_create_after',
          text: '创建评审计划',
          value: 'TestMgmt.review.create:AFTER',
          id: 'testmgmt_review_create_after',
        },
        {
          codeName: 'testmgmt_review_remove_after',
          text: '删除评审计划',
          value: 'TestMgmt.review.remove:AFTER',
          id: 'testmgmt_review_remove_after',
        },
      ],
      text: '测试库',
      value: 'library',
      disableSelect: true,
      id: 'library',
    },
    {
      codeName: 'wiki',
      codeItems: [
        {
          codeName: 'wiki_space_create_after',
          text: '创建空间',
          value: 'Wiki.space.create:AFTER',
          id: 'wiki_space_create_after',
        },
        {
          codeName: 'wiki_space_archive_after',
          text: '归档空间',
          value: 'Wiki.space.archive:AFTER',
          id: 'wiki_space_archive_after',
        },
        {
          codeName: 'wiki_space_delete_after',
          text: '删除空间',
          value: 'Wiki.space.delete:AFTER',
          id: 'wiki_space_delete_after',
        },
        {
          codeName: 'wiki_article_page_publish_page_after',
          text: '发布页面',
          value: 'Wiki.article_page.publish_page:AFTER',
          id: 'wiki_article_page_publish_page_after',
        },
        {
          codeName: 'wiki_article_page_delete_after',
          text: '删除页面',
          value: 'Wiki.article_page.delete:AFTER',
          id: 'wiki_article_page_delete_after',
        },
      ],
      text: '空间',
      value: 'wiki',
      disableSelect: true,
      id: 'wiki',
    },
    {
      codeName: 'base',
      codeItems: [
        {
          codeName: 'base_member_create_after',
          text: '创建团队成员',
          value: 'Base.member.create:AFTER',
          id: 'base_member_create_after',
        },
        {
          codeName: 'base_member_remove_after',
          text: '删除团队成员',
          value: 'Base.member.remove:AFTER',
          id: 'base_member_remove_after',
        },
      ],
      text: '基础',
      value: 'base',
      disableSelect: true,
      id: 'base',
    },
  ],
  enableCache: true,
  name: '可供选择的触发器',
  id: 'plmweb.extension__enable_action',
};
