export default {
  codeListTag: 'extension__DELogicNodeType3',
  codeListType: 'STATIC',
  codeName: 'extension__DELogicNodeType3',
  emptyText: '无匹配节点',
  emptyTextLanguageRes: {
    lanResTag: 'CL.ITEM.LNAME.DELOGICNODETYPE3._EMTPY_',
  },
  appDataEntityId: 'plmweb.psdelogicnode',
  codeItems: [
    {
      codeName: 'baseevent',
      codeItems: [
        {
          codeName: 'begin',
          data: '{"logicnodetype": "BEGIN", "psdelogicnodename": "开始"}',
          iconCls: 'fa fa-arrow-circle-o-left',
          sysImage: {
            cssClass: 'fa fa-arrow-circle-o-left',
            glyph: 'xf190@FontAwesome',
          },
          text: '开始',
          value: 'BEGIN',
          id: 'begin',
        },
        {
          codeName: 'end',
          data: '{"logicnodetype": "END", "psdelogicnodename": "结束"}',
          iconCls: 'fa fa-arrow-circle-o-right',
          sysImage: {
            cssClass: 'fa fa-arrow-circle-o-right',
            glyph: 'xf18e@FontAwesome',
          },
          text: '结束',
          value: 'END',
          id: 'end',
        },
        {
          codeName: 'prepareparam',
          data: '{"logicnodetype": "PREPAREPARAM", "psdelogicnodename": "准备参数"}',
          iconCls: 'fa fa-at',
          sysImage: {
            cssClass: 'fa fa-at',
            glyph: 'xf1fa@FontAwesome',
          },
          text: '准备参数',
          value: 'PREPAREPARAM',
          id: 'prepareparam',
        },
      ],
      text: '基础事件',
      value: 'BaseEvent',
      id: 'baseevent',
    },
    {
      codeName: 'paramaction',
      data: '{\n        "hidden": "true"\n}',
      codeItems: [
        {
          codeName: 'resetparam',
          data: '{"logicnodetype": "RESETPARAM", "psdelogicnodename": "重置参数"}',
          iconCls: 'fa fa-cab',
          sysImage: {
            cssClass: 'fa fa-cab',
            glyph: 'xf1ba@FontAwesome',
          },
          text: '重置参数',
          value: 'RESETPARAM',
          id: 'resetparam',
        },
        {
          codeName: 'copyparam',
          data: '{"logicnodetype": "COPYPARAM", "psdelogicnodename": "拷贝参数"}',
          iconCls: 'fa fa-bus',
          sysImage: {
            cssClass: 'fa fa-bus',
            glyph: 'xf207@FontAwesome',
          },
          text: '拷贝参数',
          value: 'COPYPARAM',
          id: 'copyparam',
        },
        {
          codeName: 'bindparam',
          data: '{"logicnodetype": "BINDPARAM", "psdelogicnodename": "绑定参数"}',
          iconCls: 'fa fa-buysellads',
          sysImage: {
            cssClass: 'fa fa-buysellads',
            glyph: 'xf20d@FontAwesome',
          },
          text: '绑定参数',
          value: 'BINDPARAM',
          id: 'bindparam',
        },
        {
          codeName: 'appendparam',
          data: '{"logicnodetype": "APPENDPARAM", "psdelogicnodename": "附加到数组参数"}',
          iconCls: 'fa fa-calendar-o',
          sysImage: {
            cssClass: 'fa fa-calendar-o',
            glyph: 'xf133@FontAwesome',
          },
          text: '附加到数组参数',
          value: 'APPENDPARAM',
          id: 'appendparam',
        },
        {
          codeName: 'sortparam',
          data: '{"logicnodetype": "SORTPARAM", "psdelogicnodename": "排序数组参数"}',
          iconCls: 'fa fa-calendar',
          sysImage: {
            cssClass: 'fa fa-calendar',
            glyph: 'xf073@FontAwesome',
          },
          text: '排序数组参数',
          value: 'SORTPARAM',
          id: 'sortparam',
        },
        {
          codeName: 'filterparam',
          data: '{"logicnodetype": "FILTERPARAM", "psdelogicnodename": "过滤数组参数"}',
          iconCls: 'fa fa-bell-o',
          sysImage: {
            cssClass: 'fa fa-bell-o',
            glyph: 'xf0a2@FontAwesome',
          },
          text: '过滤数组参数',
          value: 'FILTERPARAM',
          id: 'filterparam',
        },
        {
          codeName: 'filterparam2',
          data: '{"logicnodetype": "FILTERPARAM2", "psdelogicnodename": "过滤数组参数2"}',
          iconCls: 'fa fa-arrow-circle-right',
          sysImage: {
            cssClass: 'fa fa-arrow-circle-right',
            glyph: 'xf0a9@FontAwesome',
          },
          text: '过滤数组参数2',
          value: 'FILTERPARAM2',
          id: 'filterparam2',
        },
        {
          codeName: 'mergeparam',
          data: '{"logicnodetype": "MERGEPARAM", "psdelogicnodename": "合并数组参数"}',
          iconCls: 'fa fa-database',
          sysImage: {
            cssClass: 'fa fa-database',
            glyph: 'xf1c0@FontAwesome',
          },
          text: '合并数组参数',
          value: 'MERGEPARAM',
          id: 'mergeparam',
        },
        {
          codeName: 'aggregateparam',
          data: '{"logicnodetype": "AGGREGATEPARAM", "psdelogicnodename": "聚合数组参数"}',
          iconCls: 'fa fa-dedent',
          sysImage: {
            cssClass: 'fa fa-dedent',
            glyph: 'xf03b@FontAwesome',
          },
          text: '聚合数组参数',
          value: 'AGGREGATEPARAM',
          id: 'aggregateparam',
        },
        {
          codeName: 'renewparam',
          data: '{"logicnodetype": "RENEWPARAM", "psdelogicnodename": "重新建立参数"}',
          iconCls: 'fa fa-bullseye',
          sysImage: {
            cssClass: 'fa fa-bullseye',
            glyph: 'xf140@FontAwesome',
          },
          text: '重新建立参数',
          value: 'RENEWPARAM',
          id: 'renewparam',
        },
      ],
      text: '参数操作',
      userData: 'contract',
      value: 'ParamAction',
      id: 'paramaction',
    },
    {
      codeName: 'generalprocess',
      codeItems: [
        {
          codeName: 'deaction',
          data: '{"logicnodetype": "DEACTION", "psdelogicnodename": "实体行为"}',
          iconCls: 'fa fa-arrow-circle-o-up',
          sysImage: {
            cssClass: 'fa fa-arrow-circle-o-up',
            glyph: 'xf01b@FontAwesome',
          },
          text: '实体行为',
          value: 'DEACTION',
          id: 'deaction',
        },
        {
          codeName: 'delogic',
          data: '{"logicnodetype": "DELOGIC", "psdelogicnodename": "实体处理逻辑"}',
          iconCls: 'fa fa-arrow-up',
          sysImage: {
            cssClass: 'fa fa-arrow-up',
            glyph: 'xf062@FontAwesome',
          },
          text: '实体处理逻辑',
          value: 'DELOGIC',
          id: 'delogic',
        },
        {
          codeName: 'dedataset',
          data: '{"logicnodetype": "DEDATASET", "psdelogicnodename": "实体数据集"}',
          iconCls: 'fa fa-arrow-circle-right',
          sysImage: {
            cssClass: 'fa fa-arrow-circle-right',
            glyph: 'xf0a9@FontAwesome',
          },
          text: '实体数据集',
          value: 'DEDATASET',
          id: 'dedataset',
        },
        {
          codeName: 'syslogic',
          data: '{"logicnodetype": "SYSLOGIC", "psdelogicnodename": "系统逻辑处理"}',
          iconCls: 'fa fa-arrow-down',
          sysImage: {
            cssClass: 'fa fa-arrow-down',
            glyph: 'xf063@FontAwesome',
          },
          text: '系统逻辑处理',
          value: 'SYSLOGIC',
          id: 'syslogic',
        },
        {
          codeName: 'throwexception',
          data: '{"logicnodetype": "THROWEXCEPTION", "psdelogicnodename": "抛出异常"}',
          iconCls: 'fa fa-arrow-left',
          sysImage: {
            cssClass: 'fa fa-arrow-left',
            glyph: 'xf060@FontAwesome',
          },
          text: '抛出异常',
          value: 'THROWEXCEPTION',
          id: 'throwexception',
        },
        {
          codeName: 'dedataquery',
          data: '{"logicnodetype": "DEDATAQUERY", "psdelogicnodename": "实体数据查询"}',
          iconCls: 'fa fa-bell-o',
          sysImage: {
            cssClass: 'fa fa-bell-o',
            glyph: 'xf0a2@FontAwesome',
          },
          text: '实体数据查询',
          value: 'DEDATAQUERY',
          id: 'dedataquery',
        },
        {
          codeName: 'subsyssamethod',
          data: '{"logicnodetype": "SUBSYSSAMETHOD", "psdelogicnodename": "外部接口调用"}',
          iconCls: 'fa fa-barcode',
          sysImage: {
            cssClass: 'fa fa-barcode',
            glyph: 'xf02a@FontAwesome',
          },
          text: '外部接口调用',
          value: 'SUBSYSSAMETHOD',
          id: 'subsyssamethod',
        },
        {
          codeName: 'rawwebcall',
          data: '{"logicnodetype": "RAWWEBCALL", "psdelogicnodename": "直接Web调用"}',
          iconCls: 'fa fa-camera',
          sysImage: {
            cssClass: 'fa fa-camera',
            glyph: 'xf030@FontAwesome',
          },
          text: '直接Web调用',
          value: 'RAWWEBCALL',
          id: 'rawwebcall',
        },
        {
          codeName: 'dedatasync',
          data: '{"logicnodetype": "DEDATASYNC", "psdelogicnodename": "实体数据同步"}',
          iconCls: 'fa fa-bug',
          sysImage: {
            cssClass: 'fa fa-bug',
            glyph: 'xf188@FontAwesome',
          },
          text: '实体数据同步',
          value: 'DEDATASYNC',
          id: 'dedatasync',
        },
        {
          codeName: 'dedataflow',
          data: '{"logicnodetype": "DEDATAFLOW", "psdelogicnodename": "实体数据流"}',
          iconCls: 'fa fa-arrow-right',
          sysImage: {
            cssClass: 'fa fa-arrow-right',
            glyph: 'xf061@FontAwesome',
          },
          text: '实体数据流',
          value: 'DEDATAFLOW',
          id: 'dedataflow',
        },
      ],
      text: '常规处理',
      value: 'GeneralProcess',
      id: 'generalprocess',
    },
    {
      codeName: 'dbprocess',
      codeItems: [
        {
          codeName: 'rawsqlcall',
          data: '{"logicnodetype": "RAWSQLCALL", "psdelogicnodename": "直接SQL调用"}',
          iconCls: 'fa fa-bar-chart',
          sysImage: {
            cssClass: 'fa fa-bar-chart',
            glyph: 'xf080@FontAwesome',
          },
          text: '直接SQL调用',
          value: 'RAWSQLCALL',
          id: 'rawsqlcall',
        },
        {
          codeName: 'rawsqlandloopcall',
          data: '{"logicnodetype": "RAWSQLANDLOOPCALL", "psdelogicnodename": "直接SQL并循环调用"}',
          iconCls: 'fa fa-bank',
          sysImage: {
            cssClass: 'fa fa-bank',
            glyph: 'xf19c@FontAwesome',
          },
          text: '直接SQL并循环调用',
          value: 'RAWSQLANDLOOPCALL',
          id: 'rawsqlandloopcall',
        },
      ],
      text: '数据库操作',
      value: 'DBProcess',
      id: 'dbprocess',
    },
    {
      codeName: 'wfprocess',
      codeItems: [
        {
          codeName: 'startwf',
          data: '{"logicnodetype": "STARTWF", "psdelogicnodename": "启动流程"}',
          iconCls: 'fa fa-arrows-h',
          sysImage: {
            cssClass: 'fa fa-arrows-h',
            glyph: 'xf07e@FontAwesome',
          },
          text: '启动流程',
          value: 'STARTWF',
          id: 'startwf',
        },
        {
          codeName: 'cancelwf',
          data: '{"logicnodetype": "CANCELWF", "psdelogicnodename": "取消流程"}',
          iconCls: 'fa fa-bar-chart-o',
          sysImage: {
            cssClass: 'fa fa-bar-chart-o',
            glyph: 'xf080@FontAwesome',
          },
          text: '取消流程',
          value: 'CANCELWF',
          id: 'cancelwf',
        },
      ],
      text: '工作流处理',
      value: 'WFProcess',
      id: 'wfprocess',
    },
    {
      codeName: 'advanced',
      codeItems: [
        {
          codeName: 'loopsubcall',
          data: '{"logicnodetype": "LOOPSUBCALL", "psdelogicnodename": "循环子调用"}',
          iconCls: 'fa fa-cutlery',
          sysImage: {
            cssClass: 'fa fa-cutlery',
            glyph: 'xf0f5@FontAwesome',
          },
          text: '循环子调用',
          value: 'LOOPSUBCALL',
          id: 'loopsubcall',
        },
        {
          codeName: 'sfplugin',
          data: '{"logicnodetype": "SFPLUGIN", "psdelogicnodename": "服务插件"}',
          iconCls: 'fa fa-arrow-right',
          sysImage: {
            cssClass: 'fa fa-arrow-right',
            glyph: 'xf061@FontAwesome',
          },
          text: '服务插件',
          value: 'SFPLUGIN',
          id: 'sfplugin',
        },
        {
          codeName: 'rawsfcode',
          data: '{"logicnodetype": "RAWSFCODE", "psdelogicnodename": "执行脚本代码"}',
          iconCls: 'fa fa-arrows-alt',
          sysImage: {
            cssClass: 'fa fa-arrows-alt',
            glyph: 'xf0b2@FontAwesome',
          },
          text: '执行脚本代码',
          value: 'RAWSFCODE',
          id: 'rawsfcode',
        },
        {
          codeName: 'denotify',
          data: '{"logicnodetype": "DENOTIFY", "psdelogicnodename": "实体通知"}',
          iconCls: 'fa fa-arrows',
          sysImage: {
            cssClass: 'fa fa-arrows',
            glyph: 'xf047@FontAwesome',
          },
          text: '实体通知',
          value: 'DENOTIFY',
          id: 'denotify',
        },
        {
          codeName: 'debugparam',
          data: '{"logicnodetype": "DEBUGPARAM", "psdelogicnodename": "调试逻辑参数"}',
          iconCls: 'fa fa-bullhorn',
          sysImage: {
            cssClass: 'fa fa-bullhorn',
            glyph: 'xf0a1@FontAwesome',
          },
          text: '调试逻辑参数',
          value: 'DEBUGPARAM',
          id: 'debugparam',
        },
        {
          codeName: 'sysdatasyncagentout',
          data: '{"logicnodetype": "SYSDATASYNCAGENTOUT", "psdelogicnodename": "数据同步代理输出"}',
          iconCls: 'fa fa-bug',
          sysImage: {
            cssClass: 'fa fa-bug',
            glyph: 'xf188@FontAwesome',
          },
          text: '数据同步代理输出',
          value: 'SYSDATASYNCAGENTOUT',
          id: 'sysdatasyncagentout',
        },
        {
          codeName: 'sysutil',
          data: '{"logicnodetype": "SYSUTIL", "psdelogicnodename": "系统功能组件调用"}',
          iconCls: 'fa fa-arrow-right',
          sysImage: {
            cssClass: 'fa fa-arrow-right',
            glyph: 'xf061@FontAwesome',
          },
          text: '系统功能组件调用',
          value: 'SYSUTIL',
          id: 'sysutil',
        },
        {
          codeName: 'I',
          data: '{"logicnodetype": "CREATE_WORK_ITEM", "psdelogicnodename": "建立工作项","paralleloutput ": 1}',
          text: '建立工作项',
          value: 'CREATE_WORK_ITEM',
          id: 'i',
        },
      ],
      text: '高级',
      value: 'Advanced',
      id: 'advanced',
    },
  ],
  enableCache: true,
  name: '实体逻辑处理节点类型(设计)3',
  id: 'plmweb.extension__delogicnodetype3',
};
