export default {
  codeListTag: 'Insight__report_group_bi',
  codeListType: 'STATIC',
  codeName: 'Insight__report_group_bi',
  emptyText: '未定义',
  appDataEntityId: 'plmweb.insight_report',
  codeItems: [
    {
      codeName: 'bischeme_work_item',
      text: '工作项',
      value: 'BIScheme.work_item',
      id: 'bischeme_work_item',
    },
    {
      codeName: 'bischeme_release',
      text: '发布',
      value: 'BIScheme.release',
      id: 'bischeme_release',
    },
    {
      codeName: 'bischeme_sprint',
      text: '迭代',
      value: 'BIScheme.sprint',
      id: 'bischeme_sprint',
    },
    {
      codeName: 'bischeme_project',
      text: '项目',
      value: 'BIScheme.project',
      id: 'bischeme_project',
    },
    {
      codeName: 'bischeme_test_case',
      text: '测试用例',
      value: 'BIScheme.test_case',
      id: 'bischeme_test_case',
    },
    {
      codeName: 'bischeme_run',
      text: '执行用例',
      value: 'BIScheme.run',
      id: 'bischeme_run',
    },
    {
      codeName: 'bischeme_test_plan',
      text: '测试计划',
      value: 'BIScheme.test_plan',
      id: 'bischeme_test_plan',
    },
    {
      codeName: 'bischeme_ticket',
      text: '工单',
      value: 'BIScheme.ticket',
      id: 'bischeme_ticket',
    },
    {
      codeName: 'bischeme_idea',
      text: '产品需求',
      value: 'BIScheme.idea',
      id: 'bischeme_idea',
    },
    {
      codeName: 'bischeme_workload',
      text: '工时',
      value: 'BIScheme.workload',
      id: 'bischeme_workload',
    },
    {
      codeName: 'bischeme_review',
      text: '测试评审',
      value: 'BIScheme.review',
      id: 'bischeme_review',
    },
  ],
  enableCache: true,
  name: '报表_数据集BI',
  id: 'plmweb.insight__report_group_bi',
};
