export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'Estimated_workload',
      logicName: '预估工时',
      stdDataType: 6,
      name: 'ESTIMATED_WORKLOAD',
      id: 'estimated_workload',
    },
    {
      codeName: 'Remaining_workload',
      logicName: '剩余工时',
      stdDataType: 6,
      name: 'REMAINING_WORKLOAD',
      id: 'remaining_workload',
    },
    {
      codeName: 'Story_points',
      logicName: '故事点',
      stdDataType: 6,
      name: 'STORY_POINTS',
      id: 'story_points',
    },
    {
      codeName: 'Work_item_count',
      logicName: '工作项数量',
      stdDataType: 6,
      name: 'WORK_ITEM_COUNT',
      id: 'work_item_count',
    },
    {
      codeName: 'Name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'Id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'Day_capacityDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'Estimated_workload',
          logicName: '预估工时',
          appDEFieldId: 'estimated_workload',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Estimated_workload',
          id: 'estimated_workload',
        },
        {
          codeName: 'Remaining_workload',
          logicName: '剩余工时',
          appDEFieldId: 'remaining_workload',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Remaining_workload',
          id: 'remaining_workload',
        },
        {
          codeName: 'Story_points',
          logicName: '故事点',
          appDEFieldId: 'story_points',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Story_points',
          id: 'story_points',
        },
        {
          codeName: 'Work_item_count',
          logicName: '工作项数量',
          appDEFieldId: 'work_item_count',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Work_item_count',
          id: 'work_item_count',
        },
        {
          codeName: 'Id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Id',
          id: 'id',
        },
        {
          codeName: 'Name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Name',
          id: 'name',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'Day_capacityDTO',
      id: 'day_capacitydto',
    },
    {
      codeName: 'Day_capacityFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_ID_EQ',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_ID_EQ',
          id: 'n_id_eq',
        },
        {
          codeName: 'N_NAME_LIKE',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_NAME_LIKE',
          id: 'n_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'Day_capacityFilterDTO',
      id: 'day_capacityfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'UNKNOWN',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'day_capacityfilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'day_capacitydto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'Day_capacity',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.DAY_CAPACITY',
  },
  logicName: '日容量',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  storageMode: 4,
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'DAY_CAPACITY',
  id: 'plmweb.day_capacity',
  codeName2: 'Day_capacities',
  requestPaths: [],
};
