export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'State',
      logicName: '状态',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'Start_at',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.START_AT',
      },
      logicName: '开始时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'START_AT',
      id: 'start_at',
    },
    {
      codeName: 'End_at',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.END_AT',
      },
      logicName: '结束时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'END_AT',
      id: 'end_at',
    },
    {
      codeName: 'Identifier',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IDENTIFIER',
      },
      logicName: '文件夹标识',
      stdDataType: 25,
      stringLength: 15,
      enableQuickSearch: true,
      name: 'IDENTIFIER',
      id: 'identifier',
    },
    {
      codeName: 'Description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DESCRIPTION',
      },
      logicName: '描述',
      stdDataType: 25,
      stringLength: 2000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'Is_deleted',
      logicName: '是否已删除',
      stdDataType: 9,
      name: 'IS_DELETED',
      id: 'is_deleted',
    },
    {
      codeName: 'Is_favorite',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IS_FAVORITE',
      },
      logicName: '是否星标',
      stdDataType: 25,
      stringLength: 200,
      name: 'IS_FAVORITE',
      id: 'is_favorite',
    },
    {
      codeName: 'Members',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PORTFOLIO.MEMBERS',
      },
      logicName: '项目集成员',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'MEMBERS',
      id: 'members',
    },
    {
      codeName: 'Assignee_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ASSIGNEE_NAME',
      },
      logicName: '负责人',
      stdDataType: 25,
      stringLength: 100,
      name: 'ASSIGNEE_NAME',
      id: 'assignee_name',
    },
    {
      codeName: 'Assignee_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ASSIGNEE_ID',
      },
      logicName: '负责人标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ASSIGNEE_ID',
      id: 'assignee_id',
    },
    {
      codeName: 'Create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'Id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'Name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'Create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'Update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'Update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PortfolioDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'State',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'State',
          id: 'state',
        },
        {
          codeName: 'Start_at',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '开始时间',
          appDEFieldId: 'start_at',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Start_at',
          id: 'start_at',
        },
        {
          codeName: 'End_at',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '结束时间',
          appDEFieldId: 'end_at',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'End_at',
          id: 'end_at',
        },
        {
          codeName: 'Identifier',
          logicName: '文件夹标识',
          appDEFieldId: 'identifier',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Identifier',
          id: 'identifier',
        },
        {
          codeName: 'Description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Description',
          id: 'description',
        },
        {
          codeName: 'Is_deleted',
          logicName: '是否已删除',
          appDEFieldId: 'is_deleted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Is_deleted',
          id: 'is_deleted',
        },
        {
          codeName: 'Is_favorite',
          logicName: '是否星标',
          appDEFieldId: 'is_favorite',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Is_favorite',
          id: 'is_favorite',
        },
        {
          codeName: 'Members',
          logicName: '项目集成员',
          appDEFieldId: 'members',
          refAppDEMethodDTOId: 'portfolio_memberdto',
          refAppDataEntityId: 'plmweb.portfolio_member',
          refPickupAppDEFieldId: 'portfolio_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          name: 'Members',
          id: 'members',
        },
        {
          codeName: 'Assignee_name',
          logicName: '负责人',
          appDEFieldId: 'assignee_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Assignee_name',
          id: 'assignee_name',
        },
        {
          codeName: 'Assignee_id',
          logicName: '负责人标识',
          appDEFieldId: 'assignee_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Assignee_id',
          id: 'assignee_id',
        },
        {
          codeName: 'Create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Create_man',
          id: 'create_man',
        },
        {
          codeName: 'Create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Create_time',
          id: 'create_time',
        },
        {
          codeName: 'Id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Id',
          id: 'id',
        },
        {
          codeName: 'Name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Name',
          id: 'name',
        },
        {
          codeName: 'Update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Update_man',
          id: 'update_man',
        },
        {
          codeName: 'Update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Update_time',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PortfolioDTO',
      id: 'portfoliodto',
    },
    {
      codeName: 'PortfolioFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_IDENTIFIER_LIKE',
          logicName: '文件夹标识',
          appDEFieldId: 'identifier',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_IDENTIFIER_LIKE',
          id: 'n_identifier_like',
        },
        {
          codeName: 'N_ID_EQ',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_ID_EQ',
          id: 'n_id_eq',
        },
        {
          codeName: 'N_IS_FAVORITE_EQ',
          logicName: '是否星标',
          appDEFieldId: 'is_favorite',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_IS_FAVORITE_EQ',
          id: 'n_is_favorite_eq',
        },
        {
          codeName: 'N_NAME_LIKE',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_NAME_LIKE',
          id: 'n_name_like',
        },
        {
          codeName: 'N_STATE_EQ',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_STATE_EQ',
          id: 'n_state_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PortfolioFilterDTO',
      id: 'portfoliofilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'Delete_project_set',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_project_set',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'delete_project_set',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Delete_project_set',
      id: 'delete_project_set',
    },
    {
      codeName: 'Favorite',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/favorite',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'favorite',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Favorite',
      id: 'favorite',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'Recover_project_set',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/recover_project_set',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'recover_project_set',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Recover_project_set',
      id: 'recover_project_set',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'Remove_from_project_set',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'POST',
      requestParamType: 'FIELD',
      requestPath: '/remove_from_project_set',
      actionMode: 'GETDRAFT',
      actionName: 'remove_from_project_set',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Remove_from_project_set',
      id: 'remove_from_project_set',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      needResourceKey: true,
      actionMode: 'UNKNOWN',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Un_favorite',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/un_favorite',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'un_favorite',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Un_favorite',
      id: 'un_favorite',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'FetchAdmin',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchadmin',
      actionType: 'REMOTE',
      dataSetName: 'admin',
      dataSetTag: 'Admin',
      dataSetType: 'REMOTE',
      name: 'FetchAdmin',
      id: 'fetchadmin',
    },
    {
      codeName: 'FetchChoose_project_portfolio',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchchoose_project_portfolio',
      actionType: 'REMOTE',
      dataSetName: 'choose_project_portfolio',
      dataSetTag: 'Choose_project_portfolio',
      dataSetType: 'REMOTE',
      name: 'FetchChoose_project_portfolio',
      id: 'fetchchoose_project_portfolio',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchFavorite',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchfavorite',
      actionType: 'REMOTE',
      dataSetName: 'favorite',
      dataSetTag: 'Favorite',
      dataSetType: 'REMOTE',
      name: 'FetchFavorite',
      id: 'fetchfavorite',
    },
    {
      codeName: 'FetchProject_set_deleted',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchproject_set_deleted',
      actionType: 'REMOTE',
      dataSetName: 'project_set_deleted',
      dataSetTag: 'Project_set_deleted',
      dataSetType: 'REMOTE',
      name: 'FetchProject_set_deleted',
      id: 'fetchproject_set_deleted',
    },
    {
      codeName: 'FetchProject_set_going',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchproject_set_going',
      actionType: 'REMOTE',
      dataSetName: 'project_set_going',
      dataSetTag: 'Project_set_going',
      dataSetType: 'REMOTE',
      name: 'FetchProject_set_going',
      id: 'fetchproject_set_going',
    },
    {
      codeName: 'FetchUser',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchuser',
      actionType: 'REMOTE',
      dataSetName: 'user',
      dataSetTag: 'User',
      dataSetType: 'REMOTE',
      name: 'FetchUser',
      id: 'fetchuser',
    },
    {
      codeName: 'FetchWork_project_portfolio',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchwork_project_portfolio',
      actionType: 'REMOTE',
      dataSetName: 'work_project_portfolio',
      dataSetTag: 'Work_project_portfolio',
      dataSetType: 'REMOTE',
      name: 'FetchWork_project_portfolio',
      id: 'fetchwork_project_portfolio',
    },
    {
      codeName: 'FetchTempAdmin',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'AdminInput',
        id: 'admininput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'AdminResult',
        id: 'adminresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Admin',
      dataSetType: 'DATAQUERY',
      name: 'admin',
      id: 'fetchtempadmin',
    },
    {
      codeName: 'FetchTempChoose_project_portfolio',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'Choose_project_portfolioInput',
        id: 'choose_project_portfolioinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'Choose_project_portfolioResult',
        id: 'choose_project_portfolioresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Choose_project_portfolio',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: '0',
              fieldName: 'IS_DELETED',
              condType: 'SINGLE',
              name: '(IS_DELETED) 等于(=) 0',
              id: '(is_deleted) 等于(=) 0',
            },
            {
              condition:
                'not exists(select 1 from `work` t2 where t2.id = t1.id and t2.portfolio_id = #{ctx.webcontext.portfolio})',
              condType: 'CUSTOM',
              id: '未曾加入',
            },
            {
              condition:
                "not exists(select 1 from `work` t2 where t1.id = t2.portfolio_id and t2.principal_type = 'project_portfolio')",
              condType: 'CUSTOM',
              id: '不包含子项目集',
            },
            {
              condOp: 'NOTEQ',
              condValue: 'portfolio',
              fieldName: 'ID',
              vartypeId: 'WEBCONTEXT',
              condType: 'SINGLE',
              name: '(ID) 不等于(<>) 网页请求上下文 portfolio',
              id: '(id) 不等于(<>) 网页请求上下文 portfolio',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'choose_project_portfolio',
      id: 'fetchtempchoose_project_portfolio',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FetchTempFavorite',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'FavoriteInput',
        id: 'favoriteinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'FavoriteResult',
        id: 'favoriteresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Favorite',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: '0',
              fieldName: 'IS_DELETED',
              condType: 'SINGLE',
              name: '(IS_DELETED) 等于(=) 0',
              id: '(is_deleted) 等于(=) 0',
            },
            {
              condOp: 'EQ',
              condValue: '1',
              fieldName: 'IS_FAVORITE',
              condType: 'SINGLE',
              name: '(IS_FAVORITE) 等于(=) 1',
              id: '(is_favorite) 等于(=) 1',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'favorite',
      id: 'fetchtempfavorite',
    },
    {
      codeName: 'FetchTempProject_set_deleted',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'Project_set_deletedInput',
        id: 'project_set_deletedinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'Project_set_deletedResult',
        id: 'project_set_deletedresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Project_set_deleted',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: '1',
              fieldName: 'IS_DELETED',
              condType: 'SINGLE',
              name: '(IS_DELETED) 等于(=) 1',
              id: '(is_deleted) 等于(=) 1',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'project_set_deleted',
      id: 'fetchtempproject_set_deleted',
    },
    {
      codeName: 'FetchTempProject_set_going',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'Project_set_goingInput',
        id: 'project_set_goinginput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'Project_set_goingResult',
        id: 'project_set_goingresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Project_set_going',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: '0',
              fieldName: 'IS_DELETED',
              condType: 'SINGLE',
              name: '(IS_DELETED) 等于(=) 0',
              id: '(is_deleted) 等于(=) 0',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'project_set_going',
      id: 'fetchtempproject_set_going',
    },
    {
      codeName: 'FetchTempUser',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'UserInput',
        id: 'userinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'UserResult',
        id: 'userresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'User',
      dataSetType: 'DATAQUERY',
      name: 'user',
      id: 'fetchtempuser',
    },
    {
      codeName: 'FetchTempWork_project_portfolio',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'portfoliofilterdto',
        type: 'DTO',
        name: 'Work_project_portfolioInput',
        id: 'work_project_portfolioinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'portfoliodto',
        type: 'PAGE',
        name: 'Work_project_portfolioResult',
        id: 'work_project_portfolioresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Work_project_portfolio',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condition:
                'exists(select 1 from `work` t2 where t2.principal_id= t1.id and t2.portfolio_id = #{ctx.webcontext.project_portfolio})',
              condType: 'CUSTOM',
              id: '所属项目集',
            },
            {
              condOp: 'EQ',
              condValue: '0',
              fieldName: 'IS_DELETED',
              condType: 'SINGLE',
              name: '(IS_DELETED) 等于(=) 0',
              id: '(is_deleted) 等于(=) 0',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'work_project_portfolio',
      id: 'fetchtempwork_project_portfolio',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '设置星标',
      codeName: 'add_favorite',
      dataAccessAction: 'ADD_FAVORITE',
      fullCodeName: 'Portfolio_add_favorite',
      appDEMethodId: 'favorite',
      deopprivId: 'add_favorite',
      navigateParams: [
        {
          key: 'owner_id',
          value: 'portfolio',
          id: 'owner_id',
        },
      ],
      sysImage: {
        rawContent:
          '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="design-iconfont" width="16" height="16">\n  <path d="M9.54013,6.48742551 L8,3.36677551 L6.45987,6.48742551 L3.01604,6.98784551 L5.50802,9.41692551 L4.91975,12.8468255 L8,11.2274255 L11.08025,12.8468255 L10.49195,9.41692551 L12.98395,6.98784551 L9.54013,6.48742551 Z M14.53135,6.20219551 C14.77745,6.23794551 14.87565,6.54033551 14.69765,6.71389551 L11.56645,9.76604551 L12.30565,14.0757255 C12.34765,14.3208255 12.09045,14.5077255 11.87035,14.3920255 L8,12.3572255 L4.12966,14.3920255 C3.90957,14.5077255 3.65234,14.3208255 3.69437,14.0757255 L4.43354,9.76604551 L1.30237,6.71389551 C1.12431,6.54033551 1.22256,6.23794551 1.46863,6.20219551 L5.79581,5.57341551 L7.73098,1.65232551 C7.84103,1.42934551 8.15898,1.42935551 8.26902,1.65232551 L10.20415,5.57341551 L14.53135,6.20219551 Z" fill-opacity=".9" fill="#557DA5" fill-rule="nonzero"></path>\n</svg>',
      },
      refreshMode: 2,
      timeout: 60000,
      tooltip: '星标',
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_favorite',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'refresh_current_grid',
      appDataEntityId: 'plmweb.portfolio',
      name: '设置星标',
      id: 'add_favorite@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '取消星标',
      codeName: 'cancel_favorite',
      dataAccessAction: 'CANCEL_FAVORITE',
      fullCodeName: 'Portfolio_cancel_favorite',
      appDEMethodId: 'un_favorite',
      deopprivId: 'cancel_favorite',
      navigateParams: [
        {
          key: 'owner_id',
          value: 'portfolio',
          id: 'owner_id',
        },
      ],
      sysImage: {
        rawContent:
          '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="design-iconfont" width="16" height="16">\n  <path d="M14.53135,6.20219551 C14.77745,6.23794551 14.87565,6.54033551 14.69765,6.71389551 L11.56645,9.76604551 L12.30565,14.0757255 C12.34765,14.3208255 12.09045,14.5077255 11.87035,14.3920255 L8,12.3572255 L4.12966,14.3920255 C3.90957,14.5077255 3.65234,14.3208255 3.69437,14.0757255 L4.43354,9.76604551 L1.30237,6.71389551 C1.12431,6.54033551 1.22256,6.23794551 1.46863,6.20219551 L5.79581,5.57341551 L7.73098,1.65232551 C7.84103,1.42934551 8.15898,1.42935551 8.26902,1.65232551 L10.20415,5.57341551 L14.53135,6.20219551 Z" fill-opacity=".9" fill="#FFB31A" fill-rule="nonzero"></path>\n</svg>',
      },
      refreshMode: 2,
      timeout: 60000,
      tooltip: '取消星标',
      uiactionMode: 'BACKEND',
      uiactionTag: 'cancel_favorite',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'refresh_current_grid',
      appDataEntityId: 'plmweb.portfolio',
      name: '取消星标',
      id: 'cancel_favorite@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '删除项目集',
      codeName: 'delete_project_set',
      confirmMsg: '确认删除该项目集？',
      fullCodeName: 'Portfolio_delete_project_set',
      appDEMethodId: 'delete_project_set',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_project_set',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '删除项目集',
      id: 'delete_project_set@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '新窗口打开',
      codeName: 'open_new_project',
      frontProcessType: 'OPENHTMLPAGE',
      fullCodeName: 'Portfolio_open_new_project',
      htmlPageUrl:
        './#/-/index/portfolio=${data.id}/portfolioproject_index_view/srfnav=drgroup/worktree_grid_ex_view/srfnavctx=%257B%2522srfdefaulttoroutedepth%2522%253A3%257D',
      timeout: 60000,
      tooltip: '新窗口打开',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_new_project',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '新开窗口（项目集）',
      id: 'open_new_project@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '编辑基本信息',
      codeName: 'open_project_edit_view',
      frontProcessType: 'OTHER',
      fullCodeName: 'Portfolio_open_project_edit_view',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      scriptCode:
        "const srfkey = context.portfolio ? context.portfolio : data[0].id;\r\nwindow.location.hash=`/-/index/portfolio=${srfkey}/portfolioproject_index_view/srfnav=drgroup/portfolioproject_setting_view/srfnav=${encodeURIComponent('root:setting:info')}/portfolioproject_edit_view/-`",
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_project_edit_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '编辑基本信息（项目集）',
      id: 'open_project_edit_view@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '项目集成员',
      codeName: 'open_project_member',
      frontAppViewId: 'plmweb.portfolioproject_setting_view',
      frontProcessType: 'OTHER',
      fullCodeName: 'Portfolio_open_project_member',
      sysImage: {
        cssClass: 'fa fa-users',
        glyph: 'xf0c0@FontAwesome',
      },
      scriptCode:
        "const srfkey = context.portfolio ? context.portfolio : data[0].id;\r\nwindow.location.hash=`/-/index/portfolio=${srfkey}/portfolioproject_index_view/srfnav=drgroup/portfolioproject_setting_view/srfnav=${encodeURIComponent('root:normal:member')}/portfolio_memberproject_member_grid_view/-`",
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_project_member',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '项目集成员',
      id: 'open_project_member@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '打开项目集主视图',
      codeName: 'open_project_set_index_view',
      frontAppViewId: 'plmweb.portfolioproject_index_view',
      frontProcessType: 'TOP',
      fullCodeName: 'Portfolio_open_project_set_index_view',
      sysImage: {},
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_project_set_index_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '打开项目集主视图',
      id: 'open_project_set_index_view@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '更多设置',
      codeName: 'open_project_setting',
      frontProcessType: 'OTHER',
      fullCodeName: 'Portfolio_open_project_setting',
      sysImage: {
        cssClass: 'fa fa-th-list',
        glyph: 'xf00b@FontAwesome',
      },
      scriptCode:
        "const srfkey = context.portfolio ? context.portfolio : data[0].id;\r\nwindow.location.hash=`/-/index/portfolio=${srfkey}/portfolioproject_index_view/srfnav=drgroup/portfolioproject_setting_view/srfnav=${encodeURIComponent('root:normal:member')}/portfolio_memberproject_member_grid_view/-`",
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_project_setting',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '更多设置（项目集）',
      id: 'open_project_setting@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '项目集信息',
      codeName: 'project_info',
      frontAppViewId: 'plmweb.portfolioproject_show_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Portfolio_project_info',
      sysImage: {
        cssClass: 'fa fa-info-circle',
        glyph: 'xf05a@FontAwesome',
      },
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'project_info',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '项目集信息',
      id: 'project_info@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '恢复',
      codeName: 'recover_project_set',
      fullCodeName: 'Portfolio_recover_project_set',
      appDEMethodId: 'recover_project_set',
      refreshMode: 1,
      successMsg: '恢复成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'recover_project_set',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '恢复项目集',
      id: 'recover_project_set@portfolio',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '移除',
      codeName: 'remove_from_project_set',
      confirmMsg: '确认从项目集中移除?',
      fullCodeName: 'Portfolio_remove_from_project_set',
      appDEMethodId: 'remove_from_project_set',
      navigateParams: [
        {
          key: 'portfolio_id',
          value: 'project_portfolio',
          id: 'portfolio_id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-trash-o',
        glyph: 'xf014@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '移除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove_from_project_set',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.portfolio',
      name: '从项目集中移除',
      id: 'remove_from_project_set@portfolio',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'refresh_current_grid',
      defaultParamName: 'Default',
      logicName: '刷新当前表格',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 40,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'default',
          leftPos: 270,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstLogicParamId: 'grid',
                    logicType: 'SINGLE',
                    name: 'grid 值不为空(NotNil)',
                    id: 'grid 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'rawjscode1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstLogicParamId: 'grid',
                    logicType: 'SINGLE',
                    name: 'grid 值为空(Nil)',
                    id: 'grid 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          invokeCtrlId: 'grid',
          invokeMethod: 'refresh',
          invokeParamId: 'default',
          codeName: 'VIEWCTRLINVOKE1',
          leftPos: 636,
          logicNodeType: 'VIEWCTRLINVOKE',
          topPos: 208,
          name: '视图部件调用',
          id: 'viewctrlinvoke1',
        },
        {
          code: "view.call('Refresh');\r\nsetTimeout(() => {\r\n    if (view.layoutPanel.panelItems.nav_pos && view.layoutPanel.panelItems.nav_pos.curNavViewMsg) {\r\n        // 找到当前的右侧视图\r\n        const viewId = view.layoutPanel.panelItems.nav_pos.curNavViewMsg.viewId;\r\n        if (viewId) {\r\n            const key = viewId.split('.').pop();\r\n            const viewPos = view.getController(key);\r\n            if (viewPos) {\r\n                viewPos.call('Refresh');\r\n            }\r\n        }\r\n    }\r\n}, 300)",
          codeName: 'RAWJSCODE1',
          leftPos: 636,
          logicNodeType: 'RAWJSCODE',
          topPos: 330,
          name: '刷新视图',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '当前表格',
          id: 'grid',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前工具栏',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '刷新当前表格',
      id: 'refresh_current_grid',
    },
    {
      codeName: 'remove_batch_temp',
      defaultParamName: 'Default',
      logicName: '批量删除项目集成员临时数据',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "return (async function() { \r\n    // 获取所有临时数据\r\n    const serviceUtil = ibiz.hub.getApp(context.srfappid).deService;\r\n    const service = await serviceUtil.getService(context, 'plmweb.portfolio_member');\r\n    const list = service.local.getList();\r\n    // 遍历临时数据删除\r\n    list.forEach(item => {\r\n        service.local.delete(context, item.id);\r\n    })\r\n    } \r\n)();\r\n",
          codeName: 'RAWJSCODE1',
          leftPos: 433,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '批量删除临时数据（临时）',
          id: 'rawjscode1',
        },
        {
          codeName: 'END1',
          leftPos: 700,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'list',
          entityListParam: true,
          name: '临时数据列表',
          id: 'list',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '批量删除项目集成员临时数据',
      id: 'remove_batch_temp',
    },
  ],
  demainStates: [
    {
      codeName: 'star',
      enterStateMode: 'ANY',
      logicName: '已星标',
      mstag: '1',
      orderValue: 99999,
      demainStateOPPrivs: [
        {
          deopprivId: 'add_favorite',
          name: 'ADD_FAVORITE',
          id: 'add_favorite',
        },
      ],
      stateValue: '1',
      name: '已星标',
      id: 'star',
    },
    {
      codeName: 'un_star',
      enterStateMode: 'ANY',
      logicName: '未星标',
      mstag: '0',
      orderValue: 99999,
      demainStateOPPrivs: [
        {
          deopprivId: 'cancel_favorite',
          name: 'CANCEL_FAVORITE',
          id: 'cancel_favorite',
        },
      ],
      stateValue: '0',
      name: '未星标',
      id: 'un_star',
    },
  ],
  deopprivs: [
    {
      logicName: '设置星标',
      name: 'ADD_FAVORITE',
      id: 'add_favorite',
    },
    {
      logicName: '取消星标',
      name: 'CANCEL_FAVORITE',
      id: 'cancel_favorite',
    },
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '子数据权限',
      name: 'SUBDATA',
      id: 'subdata',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'Portfolio',
  deapicodeName: 'portfolio',
  deapicodeName2: 'portfolios',
  deapitag: 'PORTFOLIO',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PORTFOLIO',
  },
  logicName: '文件夹',
  mainStateAppDEFieldIds: ['is_favorite'],
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['identifier', 'name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableDEMainState: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'PORTFOLIO',
  id: 'plmweb.portfolio',
  codeName2: 'Portfolios',
  requestPaths: [],
};
