export default {
  appDEFields: [
    {
      codeName: 'deploy_system_code',
      logicName: '部署应用名',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPLOY_SYSTEM_CODE',
      id: 'deploy_system_code',
    },
    {
      codeName: 'deploy_service_hub_id',
      logicName: '部署节点',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPLOY_SERVICE_HUB_ID',
      id: 'deploy_service_hub_id',
    },
    {
      codeName: 'deploy_data_source_id',
      logicName: '部署数据源',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPLOY_DATA_SOURCE_ID',
      id: 'deploy_data_source_id',
    },
    {
      codeName: 'deploy_prdver_id',
      logicName: '部署版本',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPLOY_PRDVER_ID',
      id: 'deploy_prdver_id',
    },
    {
      codeName: 'PSCorePrdId',
      logicName: '核心产品标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSCOREPRDID',
      id: 'pscoreprdid',
    },
    {
      codeName: 'PSCorePrdName',
      logicName: '产品名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSCOREPRDNAME',
      id: 'pscoreprdname',
    },
    {
      codeName: 'CreateMan',
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 60,
      name: 'CREATEMAN',
      id: 'createman',
    },
    {
      codeName: 'CreateDate',
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'createdate',
    },
    {
      codeName: 'UpdateMan',
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATEMAN',
      id: 'updateman',
    },
    {
      codeName: 'UpdateDate',
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'updatedate',
    },
    {
      codeName: 'PkgFolder',
      logicName: '安装包路径',
      stdDataType: 25,
      stringLength: 250,
      name: 'PKGFOLDER',
      id: 'pkgfolder',
    },
    {
      codeName: 'PrdTag2',
      logicName: '产品标记2',
      stdDataType: 25,
      stringLength: 200,
      name: 'PRDTAG2',
      id: 'prdtag2',
    },
    {
      codeName: 'PrdSN',
      logicName: '产品编号',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRDSN',
      id: 'prdsn',
    },
    {
      codeName: 'PrdTag',
      logicName: '产品标记',
      stdDataType: 25,
      stringLength: 200,
      name: 'PRDTAG',
      id: 'prdtag',
    },
    {
      codeName: 'PSCorePrdCatId',
      logicName: '产品分类',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSCOREPRDCATID',
      id: 'pscoreprdcatid',
    },
    {
      codeName: 'PSCorePrdCatName',
      logicName: '产品分类',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSCOREPRDCATNAME',
      id: 'pscoreprdcatname',
    },
    {
      codeName: 'PSCorePrdCatPath',
      logicName: '产品分类路径',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSCOREPRDCATPATH',
      id: 'pscoreprdcatpath',
    },
    {
      codeName: 'HttpUrlToRepo',
      logicName: 'Http仓库地址',
      stdDataType: 25,
      stringLength: 1000,
      name: 'HTTPURLTOREPO',
      id: 'httpurltorepo',
    },
    {
      codeName: 'Memo',
      logicName: '备注',
      stdDataType: 25,
      stringLength: 4000,
      name: 'MEMO',
      id: 'memo',
    },
    {
      codeName: 'FullPath',
      logicName: '完全路径',
      stdDataType: 25,
      stringLength: 1000,
      name: 'FULLPATH',
      id: 'fullpath',
    },
    {
      codeName: 'CurrentVersion',
      logicName: '当前版本',
      stdDataType: 25,
      stringLength: 100,
      name: 'CURRENTVERSION',
      id: 'currentversion',
    },
    {
      codeName: 'Path',
      logicName: '路径',
      stdDataType: 25,
      stringLength: 200,
      name: 'PATH',
      id: 'path',
    },
    {
      codeName: 'AvatarUrl',
      logicName: '图标路径',
      stdDataType: 25,
      stringLength: 500,
      name: 'AVATARURL',
      id: 'avatarurl',
    },
    {
      codeName: 'FullName',
      logicName: '完全名称',
      stdDataType: 25,
      stringLength: 1000,
      name: 'FULLNAME',
      id: 'fullname',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSCorePrdDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'deploy_system_code',
          logicName: '部署应用名',
          appDEFieldId: 'deploy_system_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'deploy_system_code',
        },
        {
          codeName: 'deploy_service_hub_id',
          logicName: '部署节点',
          appDEFieldId: 'deploy_service_hub_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'deploy_service_hub_id',
        },
        {
          codeName: 'deploy_data_source_id',
          logicName: '部署数据源',
          appDEFieldId: 'deploy_data_source_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'deploy_data_source_id',
        },
        {
          codeName: 'deploy_prdver_id',
          logicName: '部署版本',
          appDEFieldId: 'deploy_prdver_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'deploy_prdver_id',
        },
        {
          codeName: 'AvatarUrl',
          logicName: '图标路径',
          appDEFieldId: 'avatarurl',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'AvatarUrl',
          id: 'avatarurl',
        },
        {
          codeName: 'CreateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'createdate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'CreateDate',
          id: 'createdate',
        },
        {
          codeName: 'CreateMan',
          logicName: '建立人',
          appDEFieldId: 'createman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CreateMan',
          id: 'createman',
        },
        {
          codeName: 'CurrentVersion',
          logicName: '当前版本',
          appDEFieldId: 'currentversion',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'CurrentVersion',
          id: 'currentversion',
        },
        {
          codeName: 'FullName',
          logicName: '完全名称',
          appDEFieldId: 'fullname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FullName',
          id: 'fullname',
        },
        {
          codeName: 'FullPath',
          logicName: '完全路径',
          appDEFieldId: 'fullpath',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FullPath',
          id: 'fullpath',
        },
        {
          codeName: 'HttpUrlToRepo',
          logicName: 'Http仓库地址',
          appDEFieldId: 'httpurltorepo',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'HttpUrlToRepo',
          id: 'httpurltorepo',
        },
        {
          codeName: 'Memo',
          logicName: '备注',
          appDEFieldId: 'memo',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Memo',
          id: 'memo',
        },
        {
          codeName: 'PSCorePrdCatId',
          logicName: '产品分类',
          appDEFieldId: 'pscoreprdcatid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSCorePrdCatId',
          id: 'pscoreprdcatid',
        },
        {
          codeName: 'PSCorePrdCatName',
          logicName: '产品分类',
          appDEFieldId: 'pscoreprdcatname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSCorePrdCatName',
          id: 'pscoreprdcatname',
        },
        {
          codeName: 'PSCorePrdCatPath',
          logicName: '产品分类路径',
          appDEFieldId: 'pscoreprdcatpath',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSCorePrdCatPath',
          id: 'pscoreprdcatpath',
        },
        {
          codeName: 'PSCorePrdId',
          logicName: '核心产品标识',
          appDEFieldId: 'pscoreprdid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSCorePrdId',
          id: 'pscoreprdid',
        },
        {
          codeName: 'PSCorePrdName',
          logicName: '产品名称',
          appDEFieldId: 'pscoreprdname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSCorePrdName',
          id: 'pscoreprdname',
        },
        {
          codeName: 'Path',
          logicName: '路径',
          appDEFieldId: 'path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Path',
          id: 'path',
        },
        {
          codeName: 'PkgFolder',
          logicName: '安装包路径',
          appDEFieldId: 'pkgfolder',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PkgFolder',
          id: 'pkgfolder',
        },
        {
          codeName: 'PrdSN',
          logicName: '产品编号',
          appDEFieldId: 'prdsn',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PrdSN',
          id: 'prdsn',
        },
        {
          codeName: 'PrdTag',
          logicName: '产品标记',
          appDEFieldId: 'prdtag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PrdTag',
          id: 'prdtag',
        },
        {
          codeName: 'PrdTag2',
          logicName: '产品标记2',
          appDEFieldId: 'prdtag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PrdTag2',
          id: 'prdtag2',
        },
        {
          codeName: 'UpdateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'updatedate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'UpdateDate',
          id: 'updatedate',
        },
        {
          codeName: 'UpdateMan',
          logicName: '更新人',
          appDEFieldId: 'updateman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'UpdateMan',
          id: 'updateman',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSCorePrdDTO',
      id: 'pscoreprddto',
    },
    {
      codeName: 'PSCorePrdFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_PSCOREPRDCATID_EQ',
          logicName: '产品分类',
          appDEFieldId: 'pscoreprdcatid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSCOREPRDCATID_EQ',
          id: 'n_pscoreprdcatid_eq',
        },
        {
          codeName: 'N_PSCOREPRDCATID_IN',
          logicName: '产品分类',
          appDEFieldId: 'pscoreprdcatid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLES',
          allowEmpty: true,
          name: 'N_PSCOREPRDCATID_IN',
          id: 'n_pscoreprdcatid_in',
        },
        {
          codeName: 'N_PSCOREPRDID_EQ',
          logicName: '核心产品标识',
          appDEFieldId: 'pscoreprdid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSCOREPRDID_EQ',
          id: 'n_pscoreprdid_eq',
        },
        {
          codeName: 'N_PSCOREPRDNAME_LIKE',
          logicName: '产品名称',
          appDEFieldId: 'pscoreprdname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSCOREPRDNAME_LIKE',
          id: 'n_pscoreprdname_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSCorePrdFilterDTO',
      id: 'pscoreprdfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pscoreprdid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'PSCOREPRDID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pscoreprdid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'PSCOREPRDID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprdfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprddto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSCorePrd',
  deapicodeName: 'pscoreprd',
  deapicodeName2: 'pscoreprds',
  deapitag: 'PSCOREPRD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'pscoreprdid',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PSCOREPRD',
  },
  logicName: '核心产品',
  majorAppDEFieldId: 'pscoreprdname',
  quickSearchAppDEFieldIds: ['pscoreprdname'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSCOREPRD',
  id: 'plmweb.pscoreprd',
  codeName2: 'PSCorePrds',
  requestPaths: [],
};
