export default {
  appDEFields: [
    {
      codeName: 'DynaModelFlag',
      logicName: '扩展模型',
      stdDataType: 9,
      name: 'DYNAMODELFLAG',
      id: 'dynamodelflag',
    },
    {
      codeName: 'PSDEFieldId',
      logicName: '实体属性标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDEFIELDID',
      id: 'psdefieldid',
    },
    {
      codeName: 'PSDEFieldName',
      logicName: '实体属性名称',
      stdDataType: 25,
      stringLength: 200,
      name: 'PSDEFIELDNAME',
      id: 'psdefieldname',
    },
    {
      codeName: 'CreateMan',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATEMAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 60,
      name: 'CREATEMAN',
      id: 'createman',
    },
    {
      codeName: 'CreateDate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATEDATE',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'createdate',
    },
    {
      codeName: 'UpdateMan',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATEMAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATEMAN',
      id: 'updateman',
    },
    {
      codeName: 'UpdateDate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATEDATE',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'updatedate',
    },
    {
      codeName: 'PSDataTypeId',
      logicName: '数据类型',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDATATYPEID',
      id: 'psdatatypeid',
    },
    {
      codeName: 'PSDEId',
      logicName: '实体',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDEID',
      id: 'psdeid',
    },
    {
      codeName: 'PSDataTypeName',
      logicName: '数据类型',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDATATYPENAME',
      id: 'psdatatypename',
    },
    {
      codeName: 'DEFType',
      logicName: '属性类型',
      stdDataType: 9,
      name: 'DEFTYPE',
      id: 'deftype',
    },
    {
      codeName: 'PSDEName',
      logicName: '实体',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDENAME',
      id: 'psdename',
    },
    {
      codeName: 'AllowEmpty',
      logicName: '允许空值',
      stdDataType: 9,
      name: 'ALLOWEMPTY',
      id: 'allowempty',
    },
    {
      codeName: 'Length',
      logicName: '长度',
      stdDataType: 9,
      name: 'LENGTH',
      id: 'length',
    },
    {
      codeName: 'Precision2',
      logicName: '浮点精度',
      stdDataType: 9,
      name: 'PRECISION2',
      id: 'precision2',
    },
    {
      codeName: 'CodeName',
      logicName: '代码名称',
      stdDataType: 25,
      stringLength: 60,
      name: 'CODENAME',
      id: 'codename',
    },
    {
      codeName: 'LogicName',
      logicName: '中文名称',
      stdDataType: 25,
      stringLength: 60,
      enableQuickSearch: true,
      name: 'LOGICNAME',
      id: 'logicname',
    },
    {
      codeName: 'FieldTag2',
      logicName: '属性标记2',
      stdDataType: 25,
      stringLength: 100,
      name: 'FIELDTAG2',
      id: 'fieldtag2',
    },
    {
      codeName: 'FieldTag',
      logicName: '属性标记',
      stdDataType: 25,
      stringLength: 100,
      name: 'FIELDTAG',
      id: 'fieldtag',
    },
    {
      codeName: 'UserTag2',
      logicName: '用户标记2',
      stdDataType: 25,
      stringLength: 100,
      name: 'USERTAG2',
      id: 'usertag2',
    },
    {
      codeName: 'UserTag3',
      logicName: '用户标记3',
      stdDataType: 25,
      stringLength: 50,
      name: 'USERTAG3',
      id: 'usertag3',
    },
    {
      codeName: 'UserTag',
      logicName: '用户标记',
      stdDataType: 25,
      stringLength: 100,
      name: 'USERTAG',
      id: 'usertag',
    },
    {
      codeName: 'UserTag4',
      logicName: '用户标记4',
      stdDataType: 25,
      stringLength: 50,
      name: 'USERTAG4',
      id: 'usertag4',
    },
    {
      codeName: 'extension_tag',
      logicName: '扩展标记',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG',
      id: 'extension_tag',
    },
    {
      codeName: 'extension_tag2',
      logicName: '扩展标记2',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG2',
      id: 'extension_tag2',
    },
    {
      codeName: 'extension_tag3',
      logicName: '扩展标记3',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG3',
      id: 'extension_tag3',
    },
    {
      codeName: 'extension_tag4',
      logicName: '扩展标记4',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG4',
      id: 'extension_tag4',
    },
  ],
  appDELogics: [
    {
      codeName: 'GetDraft',
      defaultParamName: 'Default',
      logicName: 'GetDraft',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'plmweb.psdefield',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      valid: true,
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'nothing',
      defaultParamName: 'Default',
      logicName: '无操作',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'plmweb.psdefield',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      valid: true,
      name: '无操作',
      id: 'nothing',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSDEFieldDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'DynaModelFlag',
          logicName: '扩展模型',
          appDEFieldId: 'dynamodelflag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'DynaModelFlag',
          id: 'dynamodelflag',
        },
        {
          codeName: 'AllowEmpty',
          logicName: '允许空值',
          appDEFieldId: 'allowempty',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          name: 'AllowEmpty',
          id: 'allowempty',
        },
        {
          codeName: 'CodeName',
          logicName: '代码名称',
          appDEFieldId: 'codename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'CodeName',
          id: 'codename',
        },
        {
          codeName: 'CreateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'createdate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'CreateDate',
          id: 'createdate',
        },
        {
          codeName: 'CreateMan',
          logicName: '建立人',
          appDEFieldId: 'createman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CreateMan',
          id: 'createman',
        },
        {
          codeName: 'DEFType',
          logicName: '属性类型',
          appDEFieldId: 'deftype',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          name: 'DEFType',
          id: 'deftype',
        },
        {
          codeName: 'FieldTag',
          logicName: '属性标记',
          appDEFieldId: 'fieldtag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FieldTag',
          id: 'fieldtag',
        },
        {
          codeName: 'FieldTag2',
          logicName: '属性标记2',
          appDEFieldId: 'fieldtag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FieldTag2',
          id: 'fieldtag2',
        },
        {
          codeName: 'Length',
          logicName: '长度',
          appDEFieldId: 'length',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Length',
          id: 'length',
        },
        {
          codeName: 'LogicName',
          logicName: '中文名称',
          appDEFieldId: 'logicname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'LogicName',
          id: 'logicname',
        },
        {
          codeName: 'PSDEFieldId',
          logicName: '实体属性标识',
          appDEFieldId: 'psdefieldid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDEFieldId',
          id: 'psdefieldid',
        },
        {
          codeName: 'PSDEFieldName',
          logicName: '实体属性名称',
          appDEFieldId: 'psdefieldname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSDEFieldName',
          id: 'psdefieldname',
        },
        {
          codeName: 'PSDEId',
          logicName: '实体',
          appDEFieldId: 'psdeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDEId',
          id: 'psdeid',
        },
        {
          codeName: 'PSDEName',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDEName',
          id: 'psdename',
        },
        {
          codeName: 'PSDataTypeId',
          logicName: '数据类型',
          appDEFieldId: 'psdatatypeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDataTypeId',
          id: 'psdatatypeid',
        },
        {
          codeName: 'PSDataTypeName',
          logicName: '数据类型',
          appDEFieldId: 'psdatatypename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDataTypeName',
          id: 'psdatatypename',
        },
        {
          codeName: 'Precision2',
          logicName: '浮点精度',
          appDEFieldId: 'precision2',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Precision2',
          id: 'precision2',
        },
        {
          codeName: 'UpdateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'updatedate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'UpdateDate',
          id: 'updatedate',
        },
        {
          codeName: 'UpdateMan',
          logicName: '更新人',
          appDEFieldId: 'updateman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'UpdateMan',
          id: 'updateman',
        },
        {
          codeName: 'UserTag',
          logicName: '用户标记',
          appDEFieldId: 'usertag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'UserTag',
          id: 'usertag',
        },
        {
          codeName: 'UserTag2',
          logicName: '用户标记2',
          appDEFieldId: 'usertag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'UserTag2',
          id: 'usertag2',
        },
        {
          codeName: 'UserTag3',
          logicName: '用户标记3',
          appDEFieldId: 'usertag3',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'UserTag3',
          id: 'usertag3',
        },
        {
          codeName: 'UserTag4',
          logicName: '用户标记4',
          appDEFieldId: 'usertag4',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'UserTag4',
          id: 'usertag4',
        },
        {
          codeName: 'extension_tag',
          logicName: '扩展标记',
          appDEFieldId: 'extension_tag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag',
        },
        {
          codeName: 'extension_tag2',
          logicName: '扩展标记2',
          appDEFieldId: 'extension_tag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag2',
        },
        {
          codeName: 'extension_tag3',
          logicName: '扩展标记3',
          appDEFieldId: 'extension_tag3',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag3',
        },
        {
          codeName: 'extension_tag4',
          logicName: '扩展标记4',
          appDEFieldId: 'extension_tag4',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag4',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSDEFieldDTO',
      id: 'psdefielddto',
    },
    {
      codeName: 'PSDEFieldFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_DEFTYPE_EQ',
          logicName: '属性类型',
          appDEFieldId: 'deftype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_DEFTYPE_EQ',
          id: 'n_deftype_eq',
        },
        {
          codeName: 'N_FIELDTAG2_EQ',
          logicName: '属性标记2',
          appDEFieldId: 'fieldtag2',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_FIELDTAG2_EQ',
          id: 'n_fieldtag2_eq',
        },
        {
          codeName: 'N_FIELDTAG_EQ',
          logicName: '属性标记',
          appDEFieldId: 'fieldtag',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_FIELDTAG_EQ',
          id: 'n_fieldtag_eq',
        },
        {
          codeName: 'N_LOGICNAME_LIKE',
          logicName: '中文名称',
          appDEFieldId: 'logicname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_LOGICNAME_LIKE',
          id: 'n_logicname_like',
        },
        {
          codeName: 'N_PSDEFIELDID_EQ',
          logicName: '实体属性标识',
          appDEFieldId: 'psdefieldid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDEFIELDID_EQ',
          id: 'n_psdefieldid_eq',
        },
        {
          codeName: 'N_PSDEFIELDNAME_LIKE',
          logicName: '实体属性名称',
          appDEFieldId: 'psdefieldname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDEFIELDNAME_LIKE',
          id: 'n_psdefieldname_like',
        },
        {
          codeName: 'N_PSDEID_EQ',
          logicName: '实体',
          appDEFieldId: 'psdeid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDEID_EQ',
          id: 'n_psdeid_eq',
        },
        {
          codeName: 'N_PSDENAME_EQ',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDENAME_EQ',
          id: 'n_psdename_eq',
        },
        {
          codeName: 'N_PSDENAME_LIKE',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDENAME_LIKE',
          id: 'n_psdename_like',
        },
        {
          codeName: 'N_USERTAG2_EQ',
          logicName: '用户标记2',
          appDEFieldId: 'usertag2',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG2_EQ',
          id: 'n_usertag2_eq',
        },
        {
          codeName: 'N_USERTAG2_NOTEQ',
          logicName: '用户标记2',
          appDEFieldId: 'usertag2',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG2_NOTEQ',
          id: 'n_usertag2_noteq',
        },
        {
          codeName: 'N_USERTAG3_EQ',
          logicName: '用户标记3',
          appDEFieldId: 'usertag3',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG3_EQ',
          id: 'n_usertag3_eq',
        },
        {
          codeName: 'N_USERTAG3_NOTEQ',
          logicName: '用户标记3',
          appDEFieldId: 'usertag3',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG3_NOTEQ',
          id: 'n_usertag3_noteq',
        },
        {
          codeName: 'N_USERTAG4_EQ',
          logicName: '用户标记4',
          appDEFieldId: 'usertag4',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG4_EQ',
          id: 'n_usertag4_eq',
        },
        {
          codeName: 'N_USERTAG4_NOTEQ',
          logicName: '用户标记4',
          appDEFieldId: 'usertag4',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG4_NOTEQ',
          id: 'n_usertag4_noteq',
        },
        {
          codeName: 'N_USERTAG_EQ',
          logicName: '用户标记',
          appDEFieldId: 'usertag',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG_EQ',
          id: 'n_usertag_eq',
        },
        {
          codeName: 'N_USERTAG_NOTEQ',
          logicName: '用户标记',
          appDEFieldId: 'usertag',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_USERTAG_NOTEQ',
          id: 'n_usertag_noteq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSDEFieldFilterDTO',
      id: 'psdefieldfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdefieldid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'PSDEFIELDID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      actionMode: 'GETDRAFT',
      actionType: 'DELOGIC',
      appDELogicId: 'getdraft',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdefieldid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'PSDEFIELDID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'apply',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/apply',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'APPLY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'apply',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdefieldfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdefielddto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '编辑',
      codeName: 'edit_field',
      frontAppViewId: 'plmweb.psde_field_quick_cfg_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'PSDEField_edit_field',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      refreshMode: 1,
      tooltip: '编辑',
      uiactionMode: 'FRONT',
      uiactionTag: 'edit_field',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.psdefield',
      name: '编辑属性',
      id: 'edit_field@psdefield',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '删除',
      codeName: 'remove_field',
      confirmMsg: '确认删除该属性?',
      fullCodeName: 'PSDEField_remove_field',
      appDEMethodId: 'remove',
      sysImage: {
        cssClass: 'fa fa-trash-o',
        glyph: 'xf014@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      tooltip: '删除',
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove_field',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.psdefield',
      name: '删除属性',
      id: 'remove_field@psdefield',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'judge_column_state',
      defaultParamName: 'Default',
      logicName: '判断操作列是否禁用',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 200,
          logicNodeType: 'END',
          topPos: 484,
          name: '结束',
          id: 'end1',
        },
        {
          code: '\tconst rows = uiLogic.grid.state.rows;\r\n    console.log(rows);\r\n\tif (rows && rows.length > 0) {\r\n\t\trows.forEach(row => {\r\n\t\t\tconst dynamodelflag = row.data.dynamodelflag;\r\n            const psdeid = row.data.psdeid;\r\n\t\t\t\t\t if (dynamodelflag !== 1 || psdeid != context.psdataentity) {\r\n\t\t\t\t\t\t// 禁用\r\n                        row.uaColStates.uagridcolumn1.visible = false;\r\n                        Object.values(row.uaColStates.uagridcolumn1).forEach(item => {\r\n                            item.visible = false;\r\n                            item.disabled = true;\r\n                        })\r\n\t\t\t\t\t} \t\r\n\t\t})\r\n\t}\r\n',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 358,
          name: '判断操作列是否禁用',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'Grid',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '判断操作列是否禁用',
      id: 'judge_column_state',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSDEField',
  deapicodeName: 'psdefield',
  deapicodeName2: 'psdefields',
  deapitag: 'PSDEFIELD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'psdefieldid',
  logicName: '实体属性',
  majorAppDEFieldId: 'psdefieldname',
  quickSearchAppDEFieldIds: ['logicname'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSDEFIELD',
  id: 'plmweb.psdefield',
  codeName2: 'PSDEFields',
  requestPaths: [],
};
