export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'psdelogicid',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'psdelogicname',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'psdelogicname',
      valueAppDEFieldId: 'psdelogicid',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'DynaModelFlag',
      logicName: '扩展模型',
      stdDataType: 9,
      name: 'DYNAMODELFLAG',
      id: 'dynamodelflag',
    },
    {
      codeName: 'CreateMan',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATEMAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 60,
      name: 'CREATEMAN',
      id: 'createman',
    },
    {
      codeName: 'UpdateMan',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATEMAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATEMAN',
      id: 'updateman',
    },
    {
      codeName: 'CreateDate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATEDATE',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'createdate',
    },
    {
      codeName: 'UpdateDate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATEDATE',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'updatedate',
    },
    {
      codeName: 'PSDELogicName',
      logicName: '实体处理逻辑名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSDELOGICNAME',
      id: 'psdelogicname',
    },
    {
      codeName: 'PSDELogicId',
      logicName: '实体处理逻辑标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDELOGICID',
      id: 'psdelogicid',
    },
    {
      codeName: 'PSDEId',
      logicName: '实体',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDEID',
      id: 'psdeid',
    },
    {
      codeName: 'PSDEName',
      logicName: '实体',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDENAME',
      id: 'psdename',
    },
    {
      codeName: 'CodeName',
      logicName: '代码标识',
      stdDataType: 25,
      stringLength: 30,
      enableQuickSearch: true,
      name: 'CODENAME',
      id: 'codename',
    },
    {
      codeName: 'extension_tag',
      logicName: '扩展标记',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG',
      id: 'extension_tag',
    },
    {
      codeName: 'extension_tag2',
      logicName: '扩展标记2',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG2',
      id: 'extension_tag2',
    },
    {
      codeName: 'extension_tag3',
      logicName: '扩展标记3',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG3',
      id: 'extension_tag3',
    },
    {
      codeName: 'extension_tag4',
      logicName: '扩展标记4',
      stdDataType: 25,
      stringLength: 200,
      name: 'EXTENSION_TAG4',
      id: 'extension_tag4',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSDEMSLogicDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'DynaModelFlag',
          logicName: '扩展模型',
          appDEFieldId: 'dynamodelflag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'DynaModelFlag',
          id: 'dynamodelflag',
        },
        {
          codeName: 'CodeName',
          logicName: '代码标识',
          appDEFieldId: 'codename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CodeName',
          id: 'codename',
        },
        {
          codeName: 'CreateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'createdate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'CreateDate',
          id: 'createdate',
        },
        {
          codeName: 'CreateMan',
          logicName: '建立人',
          appDEFieldId: 'createman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CreateMan',
          id: 'createman',
        },
        {
          codeName: 'PSDEId',
          logicName: '实体',
          appDEFieldId: 'psdeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDEId',
          id: 'psdeid',
        },
        {
          codeName: 'PSDELogicId',
          logicName: '实体处理逻辑标识',
          appDEFieldId: 'psdelogicid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDELogicId',
          id: 'psdelogicid',
        },
        {
          codeName: 'PSDELogicName',
          logicName: '实体处理逻辑名称',
          appDEFieldId: 'psdelogicname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSDELogicName',
          id: 'psdelogicname',
        },
        {
          codeName: 'PSDEName',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDEName',
          id: 'psdename',
        },
        {
          codeName: 'UpdateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'updatedate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'UpdateDate',
          id: 'updatedate',
        },
        {
          codeName: 'UpdateMan',
          logicName: '更新人',
          appDEFieldId: 'updateman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'UpdateMan',
          id: 'updateman',
        },
        {
          codeName: 'extension_tag',
          logicName: '扩展标记',
          appDEFieldId: 'extension_tag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag',
        },
        {
          codeName: 'extension_tag2',
          logicName: '扩展标记2',
          appDEFieldId: 'extension_tag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag2',
        },
        {
          codeName: 'extension_tag3',
          logicName: '扩展标记3',
          appDEFieldId: 'extension_tag3',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag3',
        },
        {
          codeName: 'extension_tag4',
          logicName: '扩展标记4',
          appDEFieldId: 'extension_tag4',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'extension_tag4',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSDEMSLogicDTO',
      id: 'psdemslogicdto',
    },
    {
      codeName: 'PSDEMSLogicFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_PSDEID_EQ',
          logicName: '实体',
          appDEFieldId: 'psdeid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDEID_EQ',
          id: 'n_psdeid_eq',
        },
        {
          codeName: 'N_PSDELOGICID_EQ',
          logicName: '实体处理逻辑标识',
          appDEFieldId: 'psdelogicid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICID_EQ',
          id: 'n_psdelogicid_eq',
        },
        {
          codeName: 'N_PSDELOGICNAME_LIKE',
          logicName: '实体处理逻辑名称',
          appDEFieldId: 'psdelogicname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICNAME_LIKE',
          id: 'n_psdelogicname_like',
        },
        {
          codeName: 'N_PSDENAME_EQ',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDENAME_EQ',
          id: 'n_psdename_eq',
        },
        {
          codeName: 'N_PSDENAME_LIKE',
          logicName: '实体',
          appDEFieldId: 'psdename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDENAME_LIKE',
          id: 'n_psdename_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSDEMSLogicFilterDTO',
      id: 'psdemslogicfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'PSDELOGICID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'PSDELOGICID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'apply',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/apply',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'APPLY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'apply',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdemslogicfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdemslogicdto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSDEMSLogic',
  deapicodeName: 'psdemslogic',
  deapicodeName2: 'psdemslogics',
  deapitag: 'PSDEMSLOGIC',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'psdelogicid',
  logicName: '实体主状态迁移逻辑',
  majorAppDEFieldId: 'psdelogicname',
  quickSearchAppDEFieldIds: ['psdelogicname', 'codename'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSDEMSLOGIC',
  id: 'plmweb.psdemslogic',
  codeName2: 'PSDEMSLogics',
  requestPaths: [],
};
