export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'change_type',
      logicName: '变更类型',
      stdDataType: 25,
      stringLength: 100,
      name: 'CHANGE_TYPE',
      id: 'change_type',
    },
    {
      codeName: 'principal_id',
      logicName: '关联主体标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      codeName: 'change_version',
      logicName: '变更版本',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CHANGE_VERSION',
      id: 'change_version',
    },
    {
      codeName: 'owner_type',
      logicName: '所属数据对象',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      codeName: 'principal_type',
      logicName: '关联主体类型',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      codeName: 'stage_results',
      logicName: '评审结果',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'STAGE_RESULTS',
      id: 'stage_results',
    },
    {
      codeName: 'target_type',
      logicName: '关联目标类型',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TYPE',
      id: 'target_type',
    },
    {
      codeName: 'final_stage_results',
      logicName: '最终评审结果',
      stdDataType: 25,
      stringLength: 60,
      name: 'FINAL_STAGE_RESULTS',
      id: 'final_stage_results',
    },
    {
      codeName: 'target_id',
      logicName: '关联目标标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ID',
      id: 'target_id',
    },
    {
      codeName: 'target_version_id',
      logicName: '目标对象版本标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_VERSION_ID',
      id: 'target_version_id',
    },
    {
      codeName: 'parent_version_id',
      logicName: '父对象版本标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_VERSION_ID',
      id: 'parent_version_id',
    },
    {
      codeName: 'test_case',
      logicName: '测试用例',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TEST_CASE',
      id: 'test_case',
    },
    {
      codeName: 'cur_version_id',
      logicName: '当前版本标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'CUR_VERSION_ID',
      id: 'cur_version_id',
    },
    {
      codeName: 'target_identifier',
      logicName: '目标对象编号',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_IDENTIFIER',
      id: 'target_identifier',
    },
    {
      codeName: 'target_title',
      logicName: '目标对象标题',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TITLE',
      id: 'target_title',
    },
    {
      codeName: 'target_state',
      logicName: '目标对象状态',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_STATE',
      id: 'target_state',
    },
    {
      codeName: 'target_assignee',
      logicName: '目标对象负责人',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ASSIGNEE',
      id: 'target_assignee',
    },
    {
      codeName: 'target_version',
      logicName: '关联目标版本',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TARGET_VERSION',
      id: 'target_version',
    },
    {
      codeName: 'target_priority',
      logicName: '目标对象优先级',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PRIORITY',
      id: 'target_priority',
    },
    {
      codeName: 'target_parent_id',
      logicName: '目标对象父标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PARENT_ID',
      id: 'target_parent_id',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'review_content_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'change_type',
          logicName: '变更类型',
          appDEFieldId: 'change_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'change_type',
        },
        {
          codeName: 'principal_id',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_id',
        },
        {
          codeName: 'change_version',
          logicName: '变更版本',
          appDEFieldId: 'change_version',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          listMap: true,
          id: 'change_version',
        },
        {
          codeName: 'owner_type',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_type',
        },
        {
          codeName: 'principal_type',
          logicName: '关联主体类型',
          appDEFieldId: 'principal_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_type',
        },
        {
          codeName: 'stage_results',
          logicName: '评审结果',
          appDEFieldId: 'stage_results',
          refAppDEMethodDTOId: 'review_result_dto',
          refAppDataEntityId: 'plmweb.review_result',
          refPickupAppDEFieldId: 'content_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'stage_results',
        },
        {
          codeName: 'final_stage_results',
          logicName: '最终评审结果',
          appDEFieldId: 'final_stage_results',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'final_stage_results',
        },
        {
          codeName: 'target_type',
          logicName: '关联目标类型',
          appDEFieldId: 'target_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_type',
        },
        {
          codeName: 'target_id',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_id',
        },
        {
          codeName: 'parent_version_id',
          logicName: '父对象版本标识',
          appDEFieldId: 'parent_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_version_id',
        },
        {
          codeName: 'target_version_id',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_version_id',
        },
        {
          codeName: 'test_case',
          logicName: '测试用例',
          appDEFieldId: 'test_case',
          refAppDEMethodDTOId: 'test_case_dto',
          refAppDataEntityId: 'plmweb.test_case',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'test_case',
        },
        {
          codeName: 'cur_version_id',
          logicName: '当前版本标识',
          appDEFieldId: 'cur_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cur_version_id',
        },
        {
          codeName: 'target_identifier',
          logicName: '目标对象编号',
          appDEFieldId: 'target_identifier',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_identifier',
        },
        {
          codeName: 'target_title',
          logicName: '目标对象标题',
          appDEFieldId: 'target_title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_title',
        },
        {
          codeName: 'target_state',
          logicName: '目标对象状态',
          appDEFieldId: 'target_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_state',
        },
        {
          codeName: 'target_assignee',
          logicName: '目标对象负责人',
          appDEFieldId: 'target_assignee',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_assignee',
        },
        {
          codeName: 'target_version',
          logicName: '关联目标版本',
          appDEFieldId: 'target_version',
          refAppDEMethodDTOId: 'version_dto',
          refAppDataEntityId: 'plmweb.version',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'target_version',
        },
        {
          codeName: 'target_priority',
          logicName: '目标对象优先级',
          appDEFieldId: 'target_priority',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_priority',
        },
        {
          codeName: 'target_parent_id',
          logicName: '目标对象父标识',
          appDEFieldId: 'target_parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_parent_id',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'review_content_dto',
    },
    {
      codeName: 'review_content_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_principal_id_eq',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_principal_id_eq',
        },
        {
          codeName: 'n_target_id_eq',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_id_eq',
        },
        {
          codeName: 'n_target_version_id_eq',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_version_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'review_content_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'program_test_case',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/program_test_case',
      needResourceKey: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'program_test_case',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'review_content_total',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/review_content_total',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'review_content_total',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'set_review_result',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/set_review_result',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'set_review_result',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '设置评审结果',
      codeName: 'set_review_result',
      frontAppViewId: 'plmweb.review_content_result_option_view',
      fullCodeName: 'review_content_set_review_result',
      appDEMethodId: 'set_review_result',
      refreshMode: 1,
      successMsg: '评审结果已设置',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'set_review_result',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.review_content',
      name: '设置评审结果',
      id: 'set_review_result@review_content',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'get_review_content_total',
      defaultParamName: 'Default',
      logicName: '获取评审内容总条数',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 200,
          logicNodeType: 'END',
          topPos: 461,
          name: '结束',
          id: 'end1',
        },
        {
          code: 'const total = uiLogic.ctrl.state.total;\r\nconst rows = uiLogic.grid.state.rows;\r\nuiLogic.view.layoutPanel.state.data.total = rows.length;\r\nif (rows && rows.length > 0) {\r\n    let total_already = 0;\r\n    rows.forEach(row => {\r\n        const state = row.data.review_result;\r\n    if (state !== null && state !== undefined) {\r\n        total_already++;\r\n    }\r\n    });\r\n    uiLogic.view.layoutPanel.state.data.total_already = total_already;\r\n    const floatTotal = parseFloat(rows.length);\r\n    const floatTotalAlready = parseFloat(total_already);\r\n    const ratio = Math.round((floatTotalAlready / floatTotal) * 100); \r\n    uiLogic.view.layoutPanel.state.data.schedule = ratio;\r\n} \r\n',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 350,
          name: '设置总条数',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
        {
          codeName: 'VIEW',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'CTRL',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '当前部件对象',
          id: 'ctrl',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '获取评审内容总条数',
      id: 'get_review_content_total',
    },
    {
      codeName: 'review_content_before_save',
      defaultParamName: 'Default',
      logicName: '评审内容保存之前处理',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'default',
          leftPos: 324,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          codeName: 'END1',
          leftPos: 1069,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '评审内容保存之前处理',
      id: 'review_content_before_save',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'review_content',
  deapicodeName: 'review_content',
  deapicodeName2: 'review_contents',
  deapitag: 'REVIEW_CONTENT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.REVIEW_CONTENT',
  },
  logicName: '评审内容',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'review_contents',
      majorAppDataEntityId: 'plmweb.test_case',
      parentAppDEFieldId: 'target_id',
      rsmode: 2,
      name: '用例-评审内容',
      id: 'review_contents',
    },
    {
      actionRSMode: 1,
      codeName: 'review_contents',
      majorAppDataEntityId: 'plmweb.review',
      parentAppDEFieldId: 'principal_id',
      rsmode: 2,
      name: '评审-评审内容',
      id: 'review_contents',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['principal_id', 'target_id'],
  defaultMode: true,
  enableFilterActions: true,
  name: 'REVIEW_CONTENT',
  id: 'plmweb.review_content',
  codeName2: 'review_contents',
  requestPaths: [
    'test_cases/${test_case}/review_contents/${review_content}',
    'reviews/${review}/review_contents/${review_content}',
  ],
};
