export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'Description',
      logicName: '步骤描述',
      stdDataType: 25,
      stringLength: 2000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'Expected_value',
      logicName: '预期结果',
      stdDataType: 25,
      stringLength: 2000,
      name: 'EXPECTED_VALUE',
      id: 'expected_value',
    },
    {
      codeName: 'Group_id',
      logicName: '分组标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'GROUP_ID',
      id: 'group_id',
    },
    {
      codeName: 'Actual_value',
      logicName: '实际',
      stdDataType: 25,
      stringLength: 2000,
      name: 'ACTUAL_VALUE',
      id: 'actual_value',
    },
    {
      codeName: 'Is_group',
      logicName: '是否分组',
      stdDataType: 9,
      name: 'IS_GROUP',
      id: 'is_group',
    },
    {
      codeName: 'Status',
      logicName: '执行结果',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATUS',
      id: 'status',
    },
    {
      codeName: 'Id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'Name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'Update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'Create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'Create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'Update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'Case_id',
      logicName: '用例标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'CASE_ID',
      id: 'case_id',
    },
    {
      codeName: 'Run_id',
      logicName: '执行用例标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'RUN_ID',
      id: 'run_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'StepDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'Description',
          logicName: '步骤描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Description',
          id: 'description',
        },
        {
          codeName: 'Expected_value',
          logicName: '预期结果',
          appDEFieldId: 'expected_value',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Expected_value',
          id: 'expected_value',
        },
        {
          codeName: 'Group_id',
          logicName: '分组标识',
          appDEFieldId: 'group_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Group_id',
          id: 'group_id',
        },
        {
          codeName: 'Actual_value',
          logicName: '实际',
          appDEFieldId: 'actual_value',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Actual_value',
          id: 'actual_value',
        },
        {
          codeName: 'Is_group',
          logicName: '是否分组',
          appDEFieldId: 'is_group',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Is_group',
          id: 'is_group',
        },
        {
          codeName: 'Status',
          logicName: '执行结果',
          appDEFieldId: 'status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Status',
          id: 'status',
        },
        {
          codeName: 'Case_id',
          logicName: '用例标识',
          appDEFieldId: 'case_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Case_id',
          id: 'case_id',
        },
        {
          codeName: 'Create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Create_man',
          id: 'create_man',
        },
        {
          codeName: 'Create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Create_time',
          id: 'create_time',
        },
        {
          codeName: 'Id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Id',
          id: 'id',
        },
        {
          codeName: 'Name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Name',
          id: 'name',
        },
        {
          codeName: 'Run_id',
          logicName: '执行用例标识',
          appDEFieldId: 'run_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Run_id',
          id: 'run_id',
        },
        {
          codeName: 'Update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Update_man',
          id: 'update_man',
        },
        {
          codeName: 'Update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Update_time',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'StepDTO',
      id: 'stepdto',
    },
    {
      codeName: 'StepFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_CASE_ID_EQ',
          logicName: '用例标识',
          appDEFieldId: 'case_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_CASE_ID_EQ',
          id: 'n_case_id_eq',
        },
        {
          codeName: 'N_ID_EQ',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_ID_EQ',
          id: 'n_id_eq',
        },
        {
          codeName: 'N_NAME_LIKE',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_NAME_LIKE',
          id: 'n_name_like',
        },
        {
          codeName: 'N_RUN_ID_EQ',
          logicName: '执行用例标识',
          appDEFieldId: 'run_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_RUN_ID_EQ',
          id: 'n_run_id_eq',
        },
        {
          codeName: 'N_STATUS_EQ',
          logicName: '执行结果',
          appDEFieldId: 'status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_STATUS_EQ',
          id: 'n_status_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'StepFilterDTO',
      id: 'stepfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'UNKNOWN',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepdto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'stepfilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'stepdto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'Step',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.STEP',
  },
  logicName: '用例步骤',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'Run',
      majorAppDataEntityId: 'plmweb.run',
      parentAppDEFieldId: 'run_id',
      rsmode: 1,
      rstype: 'DER1N',
      name: 'DER1N_STEP_RUN_RUN_ID',
      id: 'run',
    },
    {
      actionRSMode: 1,
      codeName: 'Test_case',
      majorAppDataEntityId: 'plmweb.test_case',
      parentAppDEFieldId: 'case_id',
      rsmode: 1,
      rstype: 'DER1N',
      name: 'DER1N_STEP_TEST_CASE_CASE_ID',
      id: 'test_case',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  storageMode: 4,
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'STEP',
  id: 'plmweb.step',
  codeName2: 'Steps',
  requestPaths: [
    'runs/${run}/steps/${step}',
    'test_cases/${test_case}/steps/${step}',
  ],
};
