export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'title',
      logicName: '标题',
      stdDataType: 25,
      stringLength: 500,
      name: 'TITLE',
      id: 'title',
    },
    {
      codeName: 'level',
      logicName: '重要程度',
      stdDataType: 25,
      stringLength: 60,
      name: 'LEVEL',
      id: 'level',
    },
    {
      codeName: 'type',
      logicName: '用例类型',
      stdDataType: 25,
      stringLength: 60,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'test_type',
      logicName: '测试类型',
      stdDataType: 25,
      stringLength: 60,
      name: 'TEST_TYPE',
      id: 'test_type',
    },
    {
      codeName: 'description',
      logicName: '描述',
      stdDataType: 25,
      stringLength: 2000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'precondition',
      logicName: '前置条件',
      stdDataType: 25,
      stringLength: 2000,
      name: 'PRECONDITION',
      id: 'precondition',
    },
    {
      codeName: 'is_archived',
      logicName: '是否已归档',
      stdDataType: 9,
      name: 'IS_ARCHIVED',
      id: 'is_archived',
    },
    {
      codeName: 'is_deleted',
      logicName: '是否已删除',
      stdDataType: 9,
      name: 'IS_DELETED',
      id: 'is_deleted',
    },
    {
      codeName: 'state',
      logicName: '评审状态',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'suites',
      logicName: '模块路径',
      stdDataType: 25,
      stringLength: 500,
      name: 'SUITES',
      id: 'suites',
    },
    {
      codeName: 'steps',
      logicName: '步骤',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'STEPS',
      id: 'steps',
    },
    {
      codeName: 'test_plan_name',
      logicName: '测试计划名称',
      stdDataType: 25,
      stringLength: 100,
      name: 'TEST_PLAN_NAME',
      id: 'test_plan_name',
    },
    {
      codeName: 'executed_at',
      logicName: '执行时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'EXECUTED_AT',
      id: 'executed_at',
    },
    {
      codeName: 'executor_name',
      logicName: '执行人',
      stdDataType: 25,
      stringLength: 100,
      name: 'EXECUTOR_NAME',
      id: 'executor_name',
    },
    {
      codeName: 'run_status',
      logicName: '执行结果',
      stdDataType: 25,
      stringLength: 200,
      name: 'RUN_STATUS',
      id: 'run_status',
    },
    {
      codeName: 'target_library_id',
      logicName: '目标测试库',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_LIBRARY_ID',
      id: 'target_library_id',
    },
    {
      codeName: 'workload_schedule',
      logicName: '工时进度',
      precision: 1,
      stdDataType: 6,
      name: 'WORKLOAD_SCHEDULE',
      id: 'workload_schedule',
    },
    {
      codeName: 'estimated_workload',
      logicName: '预估工时',
      precision: 1,
      stdDataType: 6,
      name: 'ESTIMATED_WORKLOAD',
      id: 'estimated_workload',
    },
    {
      codeName: 'remaining_workload',
      logicName: '剩余工时',
      precision: 1,
      stdDataType: 6,
      name: 'REMAINING_WORKLOAD',
      id: 'remaining_workload',
    },
    {
      codeName: 'actual_workload',
      logicName: '实际工时',
      precision: 1,
      stdDataType: 6,
      name: 'ACTUAL_WORKLOAD',
      id: 'actual_workload',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'test_library_id',
      logicName: '测试库标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'TEST_LIBRARY_ID',
      id: 'test_library_id',
    },
    {
      codeName: 'test_library_name',
      logicName: '测试库名称',
      stdDataType: 25,
      stringLength: 200,
      name: 'TEST_LIBRARY_NAME',
      id: 'test_library_name',
    },
    {
      codeName: 'suite_id',
      logicName: '用例模块标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'SUITE_ID',
      id: 'suite_id',
    },
    {
      codeName: 'suite_name',
      logicName: '模块名称',
      stdDataType: 25,
      stringLength: 200,
      name: 'SUITE_NAME',
      id: 'suite_name',
    },
  ],
  appDELogics: [
    {
      codeName: 'nothing',
      defaultParamName: 'Default',
      logicName: '无操作',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'plmweb.test_case_template',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      valid: true,
      name: '无操作',
      id: 'nothing',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'test_case_template_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'title',
          logicName: '标题',
          appDEFieldId: 'title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'title',
        },
        {
          codeName: 'level',
          logicName: '重要程度',
          appDEFieldId: 'level',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'level',
        },
        {
          codeName: 'type',
          logicName: '用例类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type',
        },
        {
          codeName: 'test_type',
          logicName: '测试类型',
          appDEFieldId: 'test_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'test_type',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'precondition',
          logicName: '前置条件',
          appDEFieldId: 'precondition',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'precondition',
        },
        {
          codeName: 'is_archived',
          logicName: '是否已归档',
          appDEFieldId: 'is_archived',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_archived',
        },
        {
          codeName: 'is_deleted',
          logicName: '是否已删除',
          appDEFieldId: 'is_deleted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_deleted',
        },
        {
          codeName: 'state',
          logicName: '评审状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'suites',
          logicName: '模块路径',
          appDEFieldId: 'suites',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'suites',
        },
        {
          codeName: 'steps',
          logicName: '步骤',
          appDEFieldId: 'steps',
          refAppDEMethodDTOId: 'step_dto',
          refAppDataEntityId: 'plmweb.step',
          refPickupAppDEFieldId: 'case_template_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'steps',
        },
        {
          codeName: 'test_plan_name',
          logicName: '测试计划名称',
          appDEFieldId: 'test_plan_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'test_plan_name',
        },
        {
          codeName: 'executed_at',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '执行时间',
          appDEFieldId: 'executed_at',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'executed_at',
        },
        {
          codeName: 'executor_name',
          logicName: '执行人',
          appDEFieldId: 'executor_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'executor_name',
        },
        {
          codeName: 'run_status',
          logicName: '执行结果',
          appDEFieldId: 'run_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'run_status',
        },
        {
          codeName: 'target_library_id',
          logicName: '目标测试库',
          appDEFieldId: 'target_library_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_library_id',
        },
        {
          codeName: 'workload_schedule',
          logicName: '工时进度',
          appDEFieldId: 'workload_schedule',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'workload_schedule',
        },
        {
          codeName: 'estimated_workload',
          logicName: '预估工时',
          appDEFieldId: 'estimated_workload',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'estimated_workload',
        },
        {
          codeName: 'remaining_workload',
          logicName: '剩余工时',
          appDEFieldId: 'remaining_workload',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'remaining_workload',
        },
        {
          codeName: 'actual_workload',
          logicName: '实际工时',
          appDEFieldId: 'actual_workload',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'actual_workload',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'suite_id',
          logicName: '用例模块标识',
          appDEFieldId: 'suite_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'suite_id',
        },
        {
          codeName: 'suite_name',
          logicName: '模块名称',
          appDEFieldId: 'suite_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'suite_name',
        },
        {
          codeName: 'test_library_id',
          logicName: '测试库标识',
          appDEFieldId: 'test_library_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'test_library_id',
        },
        {
          codeName: 'test_library_name',
          logicName: '测试库名称',
          appDEFieldId: 'test_library_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'test_library_name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'test_case_template_dto',
    },
    {
      codeName: 'test_case_template_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_level_eq',
          logicName: '重要程度',
          appDEFieldId: 'level',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_level_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_run_status_eq',
          logicName: '执行结果',
          appDEFieldId: 'run_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_run_status_eq',
        },
        {
          codeName: 'n_state_eq',
          logicName: '评审状态',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
        {
          codeName: 'n_suite_id_eq',
          logicName: '用例模块标识',
          appDEFieldId: 'suite_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_suite_id_eq',
        },
        {
          codeName: 'n_suite_name_eq',
          logicName: '模块名称',
          appDEFieldId: 'suite_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_suite_name_eq',
        },
        {
          codeName: 'n_suite_name_like',
          logicName: '模块名称',
          appDEFieldId: 'suite_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_suite_name_like',
        },
        {
          codeName: 'n_test_library_id_eq',
          logicName: '测试库标识',
          appDEFieldId: 'test_library_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_test_library_id_eq',
        },
        {
          codeName: 'n_test_library_name_eq',
          logicName: '测试库名称',
          appDEFieldId: 'test_library_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_test_library_name_eq',
        },
        {
          codeName: 'n_test_library_name_like',
          logicName: '测试库名称',
          appDEFieldId: 'test_library_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_test_library_name_like',
        },
        {
          codeName: 'n_test_type_eq',
          logicName: '测试类型',
          appDEFieldId: 'test_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_test_type_eq',
        },
        {
          codeName: 'n_type_eq',
          logicName: '用例类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'test_case_template_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'nothing',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        name: 'NothingInput',
        id: 'nothinginput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'NothingResult',
        id: 'nothingresult',
      },
      actionMode: 'CUSTOM',
      actionType: 'DELOGIC',
      appDELogicId: 'nothing',
      dataSetType: 'REMOTE',
      id: 'nothing',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'test_case_template_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'test_case_template_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '删除',
      codeName: 'template_delete',
      confirmMsg: '确认删除选中模板吗？（无法恢复）',
      fullCodeName: 'test_case_template_template_delete',
      appDEMethodId: 'remove',
      sysImage: {
        cssClass: 'fa fa-trash-o',
        glyph: 'xf014@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      tooltip: '删除模板',
      uiactionMode: 'BACKEND',
      uiactionTag: 'template_delete',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.test_case_template',
      name: '删除模板',
      id: 'template_delete@test_case_template',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      caption: '编辑',
      codeName: 'template_edit',
      frontAppViewId: 'plmweb.stencil_model_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'test_case_template_template_edit',
      sysImage: {
        cssClass: 'fa fa-pencil',
        glyph: 'xf040@FontAwesome',
      },
      timeout: 60000,
      tooltip: '编辑模板',
      uiactionMode: 'FRONT',
      uiactionTag: 'template_edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.test_case_template',
      name: '编辑模板',
      id: 'template_edit@test_case_template',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '建立',
      mapDEName: 'LIBRARY',
      mapDEOPPrivName: 'UPDATE',
      name: 'CREATE',
      id: 'library__create',
    },
    {
      logicName: '删除',
      mapDEName: 'LIBRARY',
      mapDEOPPrivName: 'DELETE',
      name: 'DELETE',
      id: 'library__delete',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '读取',
      mapDEName: 'LIBRARY',
      mapDEOPPrivName: 'READ',
      name: 'READ',
      id: 'library__read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
    {
      logicName: '更新',
      mapDEName: 'LIBRARY',
      mapDEOPPrivName: 'UPDATE',
      name: 'UPDATE',
      id: 'library__update',
    },
  ],
  codeName: 'test_case_template',
  deapicodeName: 'test_case_template',
  deapicodeName2: 'test_case_templates',
  deapitag: 'TEST_CASE_TEMPLATE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.TEST_CASE_TEMPLATE',
  },
  logicName: '用例模板',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'test_case_templates',
      majorAppDataEntityId: 'plmweb.library',
      parentAppDEFieldId: 'test_library_id',
      rsmode: 2,
      name: 'DER1N_TEST_CASE_TEMPLATE_LIBRARY_TEST_LIBRARY_ID',
      id: 'test_case_templates',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  name: 'TEST_CASE_TEMPLATE',
  id: 'plmweb.test_case_template',
  codeName2: 'test_case_templates',
  requestPaths: [
    'libraries/${library}/test_case_templates/${test_case_template}',
  ],
};
