export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'Sequence',
      logicName: '序号',
      stdDataType: 6,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'Is_system',
      logicName: '是否系统类型',
      stdDataType: 9,
      name: 'IS_SYSTEM',
      id: 'is_system',
    },
    {
      codeName: 'Project_type',
      logicName: '项目类型',
      stdDataType: 25,
      stringLength: 60,
      name: 'PROJECT_TYPE',
      id: 'project_type',
    },
    {
      codeName: 'Group',
      logicName: '类型分组',
      stdDataType: 25,
      stringLength: 60,
      name: 'GROUP',
      id: 'group',
    },
    {
      codeName: 'Code',
      logicName: '编码',
      stdDataType: 25,
      stringLength: 100,
      name: 'CODE',
      id: 'code',
    },
    {
      codeName: 'Icon',
      logicName: '图标',
      stdDataType: 21,
      stringLength: 100,
      name: 'ICON',
      id: 'icon',
    },
    {
      codeName: 'Update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'Id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'Name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'Create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'Create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'Update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'Work_item_typeDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'Sequence',
          logicName: '序号',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          name: 'Sequence',
          id: 'sequence',
        },
        {
          codeName: 'Is_system',
          logicName: '是否系统类型',
          appDEFieldId: 'is_system',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Is_system',
          id: 'is_system',
        },
        {
          codeName: 'Project_type',
          logicName: '项目类型',
          appDEFieldId: 'project_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Project_type',
          id: 'project_type',
        },
        {
          codeName: 'Group',
          logicName: '类型分组',
          appDEFieldId: 'group',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Group',
          id: 'group',
        },
        {
          codeName: 'Code',
          logicName: '编码',
          appDEFieldId: 'code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Code',
          id: 'code',
        },
        {
          codeName: 'Icon',
          logicName: '图标',
          appDEFieldId: 'icon',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Icon',
          id: 'icon',
        },
        {
          codeName: 'Create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Create_man',
          id: 'create_man',
        },
        {
          codeName: 'Create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Create_time',
          id: 'create_time',
        },
        {
          codeName: 'Id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Id',
          id: 'id',
        },
        {
          codeName: 'Name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Name',
          id: 'name',
        },
        {
          codeName: 'Update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'Update_man',
          id: 'update_man',
        },
        {
          codeName: 'Update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'Update_time',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'Work_item_typeDTO',
      id: 'work_item_typedto',
    },
    {
      codeName: 'Work_item_typeFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_CODE_IN',
          logicName: '编码',
          appDEFieldId: 'code',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_CODE_IN',
          id: 'n_code_in',
        },
        {
          codeName: 'N_GROUP_EQ',
          logicName: '类型分组',
          appDEFieldId: 'group',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_GROUP_EQ',
          id: 'n_group_eq',
        },
        {
          codeName: 'N_ID_EQ',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_ID_EQ',
          id: 'n_id_eq',
        },
        {
          codeName: 'N_NAME_LIKE',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_NAME_LIKE',
          id: 'n_name_like',
        },
        {
          codeName: 'N_PROJECT_TYPE_EQ',
          logicName: '项目类型',
          appDEFieldId: 'project_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PROJECT_TYPE_EQ',
          id: 'n_project_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'Work_item_typeFilterDTO',
      id: 'work_item_typefilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      needResourceKey: true,
      actionMode: 'UNKNOWN',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typefilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchProject_work_item_type',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typefilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchproject_work_item_type',
      actionType: 'REMOTE',
      dataSetName: 'project_work_item_type',
      dataSetTag: 'Project_work_item_type',
      dataSetType: 'REMOTE',
      name: 'FetchProject_work_item_type',
      id: 'fetchproject_work_item_type',
    },
    {
      codeName: 'FetchProject_work_item_type_not_bug',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'work_item_typefilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'work_item_typedto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchproject_work_item_type_not_bug',
      actionType: 'REMOTE',
      dataSetName: 'project_work_item_type_not_bug',
      dataSetTag: 'Project_work_item_type_not_bug',
      dataSetType: 'REMOTE',
      name: 'FetchProject_work_item_type_not_bug',
      id: 'fetchproject_work_item_type_not_bug',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '通知配置',
      codeName: 'panel_Usr12299058218_button_link3_click',
      frontAppViewId: 'plmweb.psdenotifytab_exp_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr12299058218_button_link3_click',
      navigateContexts: [
        {
          key: 'PSDATAENTITY',
          value: '${project}@ProjMgmt.project',
          name: 'PSDATAENTITY',
          id: 'psdataentity',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr12299058218_button_link3_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr12299058218_button_link3_click@work_item_type',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '设计',
      codeName: 'panel_Usr12299058218_button_link_click',
      frontAppViewId: 'plmweb.psdelogicmslogicdesign',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr12299058218_button_link_click',
      navigateContexts: [
        {
          key: 'PSDEMSLOGIC',
          value: 'FIELD__PROJECT_ID__${project}@ProjMgmt.work_item.${id}',
          name: 'PSDEMSLOGIC',
          id: 'psdemslogic',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr12299058218_button_link_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr12299058218_button_link_click@work_item_type',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '表单设计',
      codeName: 'panel_Usr12299058218_form_cfg_click',
      frontAppViewId: 'plmweb.psdeformdesign_modal',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr12299058218_form_cfg_click',
      navigateContexts: [
        {
          key: 'PSDEFORM',
          value: 'FIELD__PROJECT_ID__${project}@ProjMgmt.work_item.${id}',
          name: 'PSDEFORM',
          id: 'psdeform',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr12299058218_form_cfg_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr12299058218_form_cfg_click@work_item_type',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '表单设计',
      codeName: 'panel_Usr1229905828_button_link1_click',
      frontAppViewId: 'plmweb.psdeformdesign',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr1229905828_button_link1_click',
      navigateContexts: [
        {
          key: 'PSDEFORM',
          value: 'ProjMgmt.work_item.${id}',
          name: 'PSDEFORM',
          id: 'psdeform',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr1229905828_button_link1_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr1229905828_button_link1_click@work_item_type',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '通知配置',
      codeName: 'panel_Usr1229905828_button_link3_click',
      frontAppViewId: 'plmweb.psdenotifytab_exp_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr1229905828_button_link3_click',
      navigateContexts: [
        {
          key: 'PSDATAENTITY',
          value: 'ProjMgmt.project',
          rawValue: true,
          name: 'PSDATAENTITY',
          id: 'psdataentity',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr1229905828_button_link3_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr1229905828_button_link3_click@work_item_type',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      caption: '设计',
      codeName: 'panel_Usr1229905828_button_link_click',
      frontAppViewId: 'plmweb.psdelogicmslogicdesign',
      frontProcessType: 'WIZARD',
      fullCodeName: 'Work_item_type_panel_Usr1229905828_button_link_click',
      navigateContexts: [
        {
          key: 'PSDEMSLOGIC',
          value: 'ProjMgmt.work_item.${id}',
          name: 'PSDEMSLOGIC',
          id: 'psdemslogic',
        },
      ],
      timeout: 60000,
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_Usr1229905828_button_link_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.work_item_type',
      name: '配置',
      id: 'panel_usr1229905828_button_link_click@work_item_type',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'Work_item_type',
  deapicodeName: 'work_item_type',
  deapicodeName2: 'work_item_types',
  deapitag: 'WORK_ITEM_TYPE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.WORK_ITEM_TYPE',
  },
  logicName: '工作项类型',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'WORK_ITEM_TYPE',
  id: 'plmweb.work_item_type',
  codeName2: 'Work_item_types',
  requestPaths: [],
};
